// Generated by sysml/tools/generate_abstract_syntax.py.
#pragma once
#include <sysml/model/Representation.h>
#include <sysml/model/Forward.h>
#include <sysml/model/KerMLTypes.h>
#include <sysml/occurrences/OccurrenceUsage.h>

namespace SysMLv2::Entities {
class SYSML_EXPORT ConstraintUsage : public virtual OccurrenceUsage, public virtual KerML::Entities::BooleanExpression, public virtual Representation {
public:
    ConstraintUsage();
    ~ConstraintUsage() override;
    std::string_view metaclassName() const noexcept override;
    std::vector<RepresentationIssue> validateRepresentation(bool includeDerived = false) const override;
    /// Derived snapshot; populated by a semantic evaluator or importer.
    std::shared_ptr<KerML::Entities::Predicate> constraintDefinition() const;
    void setConstraintDefinition(std::shared_ptr<KerML::Entities::Predicate> value);
private:
    std::shared_ptr<KerML::Entities::Predicate> constraintDefinition_ = {};
};
}
