// Generated by sysml/tools/generate_abstract_syntax.py.
#include <sysml/occurrences/EventOccurrenceUsage.h>
#include <sysml/occurrences/OccurrenceUsage.h>
#include <algorithm>
#include <stdexcept>

namespace SysMLv2::Entities {

std::shared_ptr<OccurrenceUsage> EventOccurrenceUsage::eventOccurrence() const {
    return eventOccurrence_;
}

void EventOccurrenceUsage::setEventOccurrence(std::shared_ptr<OccurrenceUsage> value) {
    eventOccurrence_ = std::move(value);
}

bool EventOccurrenceUsage::isReference() const {
    return isReference_;
}

void EventOccurrenceUsage::setIsReference(bool value) {
    isReference_ = std::move(value);
}

EventOccurrenceUsage::EventOccurrenceUsage() {
    _dType = "EventOccurrenceUsage";
}

EventOccurrenceUsage::~EventOccurrenceUsage() = default;

std::string_view EventOccurrenceUsage::metaclassName() const noexcept {
    return "EventOccurrenceUsage";
}

std::vector<RepresentationIssue> EventOccurrenceUsage::validateRepresentation(bool includeDerived) const {
    std::vector<RepresentationIssue> issues; (void)includeDerived;
    { auto optional = OccurrenceUsage::portionKind(); if (optional) { auto value = *optional; if (!(value == PortionKind::timeslice || value == PortionKind::snapshot)) issues.push_back({"OccurrenceUsage.portionKind", "invalid enumeration value"}); } }
    if (includeDerived) if (!EventOccurrenceUsage::eventOccurrence()) issues.push_back({"EventOccurrenceUsage.eventOccurrence", "required reference is missing"});
    return issues;
}

} // namespace SysMLv2::Entities
