// Generated by sysml/tools/generate_abstract_syntax.py.
#include <sysml/occurrences/OccurrenceDefinition.h>
#include <algorithm>
#include <stdexcept>

namespace SysMLv2::Entities {

bool OccurrenceDefinition::isIndividual() const {
    return isIndividual_;
}

void OccurrenceDefinition::setIsIndividual(bool value) {
    isIndividual_ = std::move(value);
}

OccurrenceDefinition::OccurrenceDefinition() {
    _dType = "OccurrenceDefinition";
}

OccurrenceDefinition::~OccurrenceDefinition() = default;

std::string_view OccurrenceDefinition::metaclassName() const noexcept {
    return "OccurrenceDefinition";
}

std::vector<RepresentationIssue> OccurrenceDefinition::validateRepresentation(bool includeDerived) const {
    std::vector<RepresentationIssue> issues; (void)includeDerived;
    return issues;
}

} // namespace SysMLv2::Entities
