// Generated by sysml/tools/generate_abstract_syntax.py.
#include <sysml/occurrences/OccurrenceUsage.h>
#include <sysml/occurrences/OccurrenceDefinition.h>
#include <sysml/occurrences/PortionKind.h>
#include <algorithm>
#include <stdexcept>

namespace SysMLv2::Entities {

std::vector<std::shared_ptr<KerML::Entities::Class>> OccurrenceUsage::occurrenceDefinition() const {
    return occurrenceDefinition_;
}

void OccurrenceUsage::setOccurrenceDefinition(std::vector<std::shared_ptr<KerML::Entities::Class>> value) {
    if (std::any_of(value.begin(), value.end(), [](const auto& item) { return !item; })) {
        throw std::invalid_argument("OccurrenceUsage.occurrenceDefinition: null entry");
    }
    for (std::size_t i = 0; i < value.size(); ++i) {
        if (std::find(value.begin(), value.begin() + i, value[i]) != value.begin() + i) {
            throw std::invalid_argument("OccurrenceUsage.occurrenceDefinition: duplicate entry");
        }
    }
    occurrenceDefinition_ = std::move(value);
}

void OccurrenceUsage::appendOccurrenceDefinition(std::shared_ptr<KerML::Entities::Class> value) {
    auto values = occurrenceDefinition();
    values.push_back(std::move(value));
    setOccurrenceDefinition(std::move(values));
}

std::shared_ptr<OccurrenceDefinition> OccurrenceUsage::individualDefinition() const {
    return individualDefinition_;
}

void OccurrenceUsage::setIndividualDefinition(std::shared_ptr<OccurrenceDefinition> value) {
    individualDefinition_ = std::move(value);
}

bool OccurrenceUsage::isIndividual() const {
    return isIndividual_;
}

void OccurrenceUsage::setIsIndividual(bool value) {
    isIndividual_ = std::move(value);
}

std::optional<PortionKind> OccurrenceUsage::portionKind() const {
    return portionKind_;
}

void OccurrenceUsage::setPortionKind(std::optional<PortionKind> value) {
    portionKind_ = std::move(value);
}

OccurrenceUsage::OccurrenceUsage() {
    _dType = "OccurrenceUsage";
}

OccurrenceUsage::~OccurrenceUsage() = default;

std::string_view OccurrenceUsage::metaclassName() const noexcept {
    return "OccurrenceUsage";
}

std::vector<RepresentationIssue> OccurrenceUsage::validateRepresentation(bool includeDerived) const {
    std::vector<RepresentationIssue> issues; (void)includeDerived;
    { auto optional = OccurrenceUsage::portionKind(); if (optional) { auto value = *optional; if (!(value == PortionKind::timeslice || value == PortionKind::snapshot)) issues.push_back({"OccurrenceUsage.portionKind", "invalid enumeration value"}); } }
    return issues;
}

} // namespace SysMLv2::Entities
