// Generated by kerml/tools/generate_abstract_syntax.py.
#pragma once
#include <kerml/core/features/Multiplicity.h>
#include <kerml/model/Forward.h>
#include <kerml/kerml_global.h>
#include <cstdint>
#include <memory>
#include <string>
#include <vector>

namespace KerML::Entities {
class KERML_EXPORT MultiplicityRange : public virtual Multiplicity {
public:
    MultiplicityRange();
    ~MultiplicityRange() override;
    /// Computed from the underlying representation.
    std::shared_ptr<Expression> lowerBound() const;
    /// Computed from the underlying representation.
    std::shared_ptr<Expression> upperBound() const;
    /// Derived snapshot populated by an importer or semantic evaluator.
    std::vector<std::shared_ptr<Expression>> bound() const;
    void setBound(std::vector<std::shared_ptr<Expression>> value);
    void appendBound(std::shared_ptr<Expression> value);
private:
    std::vector<std::shared_ptr<Expression>> bound_ = {};
};
}
