// Generated by sysml/tools/generate_abstract_syntax.py.
#include <sysml/enumerations/EnumerationDefinition.h>
#include <sysml/enumerations/EnumerationUsage.h>
#include <algorithm>
#include <stdexcept>

namespace SysMLv2::Entities {

std::vector<std::shared_ptr<EnumerationUsage>> EnumerationDefinition::enumeratedValue() const {
    return enumeratedValue_;
}

void EnumerationDefinition::setEnumeratedValue(std::vector<std::shared_ptr<EnumerationUsage>> value) {
    if (std::any_of(value.begin(), value.end(), [](const auto& item) { return !item; })) {
        throw std::invalid_argument("EnumerationDefinition.enumeratedValue: null entry");
    }
    for (std::size_t i = 0; i < value.size(); ++i) {
        if (std::find(value.begin(), value.begin() + i, value[i]) != value.begin() + i) {
            throw std::invalid_argument("EnumerationDefinition.enumeratedValue: duplicate entry");
        }
    }
    enumeratedValue_ = std::move(value);
}

void EnumerationDefinition::appendEnumeratedValue(std::shared_ptr<EnumerationUsage> value) {
    auto values = enumeratedValue();
    values.push_back(std::move(value));
    setEnumeratedValue(std::move(values));
}

bool EnumerationDefinition::isVariation() const {
    return isVariation_;
}

void EnumerationDefinition::setIsVariation(bool value) {
    isVariation_ = std::move(value);
}

EnumerationDefinition::EnumerationDefinition() {
    _dType = "EnumerationDefinition";
}

EnumerationDefinition::~EnumerationDefinition() = default;

std::string_view EnumerationDefinition::metaclassName() const noexcept {
    return "EnumerationDefinition";
}

std::vector<RepresentationIssue> EnumerationDefinition::validateRepresentation(bool includeDerived) const {
    std::vector<RepresentationIssue> issues; (void)includeDerived;
    return issues;
}

} // namespace SysMLv2::Entities
