// Generated by sysml/tools/generate_abstract_syntax.py.
#include <sysml/enumerations/EnumerationUsage.h>
#include <sysml/enumerations/EnumerationDefinition.h>
#include <algorithm>
#include <stdexcept>

namespace SysMLv2::Entities {

std::shared_ptr<EnumerationDefinition> EnumerationUsage::enumerationDefinition() const {
    return enumerationDefinition_;
}

void EnumerationUsage::setEnumerationDefinition(std::shared_ptr<EnumerationDefinition> value) {
    enumerationDefinition_ = std::move(value);
}

EnumerationUsage::EnumerationUsage() {
    _dType = "EnumerationUsage";
}

EnumerationUsage::~EnumerationUsage() = default;

std::string_view EnumerationUsage::metaclassName() const noexcept {
    return "EnumerationUsage";
}

std::vector<RepresentationIssue> EnumerationUsage::validateRepresentation(bool includeDerived) const {
    std::vector<RepresentationIssue> issues; (void)includeDerived;
    if (includeDerived) if (!EnumerationUsage::enumerationDefinition()) issues.push_back({"EnumerationUsage.enumerationDefinition", "required reference is missing"});
    return issues;
}

} // namespace SysMLv2::Entities
