
    #include <sysmlv2/sysmlv2file_global.h>


// Generated from ./KerML.g4 by ANTLR 4.13.2

#pragma once


#include "antlr4-runtime.h"




class SYSMLV2FILE_EXPORT KerMLLexer : public antlr4::Lexer {
public:
  enum {
    KEYWORD_ABOUT = 1, KEYWORD_ABSTRACT = 2, KEYWORD_ALIAS = 3, KEYWORD_ALL = 4, 
    KEYWORD_AND = 5, KEYWORD_AS = 6, KEYWORD_ASSOC = 7, KEYWORD_BEHAVIOR = 8, 
    KEYWORD_BINDING = 9, KEYWORD_BOOL = 10, KEYWORD_BY = 11, KEYWORD_CHAINS = 12, 
    KEYWORD_CLASS = 13, KEYWORD_CLASSIFIER = 14, KEYWORD_COMMENT = 15, KEYWORD_COMPOSITE = 16, 
    KEYWORD_CONJUGATE = 17, KEYWORD_CONJUGATES = 18, KEYWORD_CONJUGATION = 19, 
    KEYWORD_CONNECTOR = 20, KEYWORD_DATATYPE = 21, KEYWORD_DEFAULT = 22, 
    KEYWORD_DEPENDENCY = 23, KEYWORD_DERIVED = 24, KEYWORD_DIFFERENCES = 25, 
    KEYWORD_DISJOINING = 26, KEYWORD_DISJOINT = 27, KEYWORD_DOC = 28, KEYWORD_ELSE = 29, 
    KEYWORD_END = 30, KEYWORD_EXPR = 31, KEYWORD_FALSE = 32, KEYWORD_FEATURE = 33, 
    KEYWORD_FEATURED = 34, KEYWORD_FEATURING = 35, KEYWORD_FILTER = 36, 
    KEYWORD_FIRST = 37, KEYWORD_FLOW = 38, KEYWORD_FOR = 39, KEYWORD_FROM = 40, 
    KEYWORD_FUNCTION = 41, KEYWORD_HASTYPE = 42, KEYWORD_IF = 43, KEYWORD_INTERSECTS = 44, 
    KEYWORD_IMPLIES = 45, KEYWORD_IMPORT = 46, KEYWORD_IN = 47, KEYWORD_INOUT = 48, 
    KEYWORD_INTERACTION = 49, KEYWORD_INV = 50, KEYWORD_INVERSE = 51, KEYWORD_INVERTING = 52, 
    KEYWORD_ISTYPE = 53, KEYWORD_LANGUAGE = 54, KEYWORD_MEMBER = 55, KEYWORD_METACLASS = 56, 
    KEYWORD_METADATA = 57, KEYWORD_MULTIPLICITY = 58, KEYWORD_NAMESPACE = 59, 
    KEYWORD_NONUNIQUE = 60, KEYWORD_NOT = 61, KEYWORD_NULL = 62, KEYWORD_OF = 63, 
    KEYWORD_OR = 64, KEYWORD_ORDERED = 65, KEYWORD_OUT = 66, KEYWORD_PACKAGE = 67, 
    KEYWORD_PORTION = 68, KEYWORD_PREDICATE = 69, KEYWORD_PRIVATE = 70, 
    KEYWORD_PROTECTED = 71, KEYWORD_PUBLIC = 72, KEYWORD_READONLY = 73, 
    KEYWORD_REDEFINES = 74, KEYWORD_REDEFINITION = 75, KEYWORD_REFERENCES = 76, 
    KEYWORD_REP = 77, KEYWORD_RETURN = 78, KEYWORD_SPECIALIZATION = 79, 
    KEYWORD_SPECIALIZES = 80, KEYWORD_STEP = 81, KEYWORD_STRUCT = 82, KEYWORD_SUBCLASSIFIER = 83, 
    KEYWORD_SUBSET = 84, KEYWORD_SUBSETS = 85, KEYWORD_SUBTYPE = 86, KEYWORD_SUCCESSION = 87, 
    KEYWORD_THEN = 88, KEYWORD_TO = 89, KEYWORD_TRUE = 90, KEYWORD_TYPE = 91, 
    KEYWORD_TYPED = 92, KEYWORD_TYPING = 93, KEYWORD_UNIONS = 94, KEYWORD_XOR = 95, 
    KEYWORD_VAR = 96, KEYWORD_LOCALE = 97, KEYWORD_STANDARD = 98, KEYWORD_LIBRARY = 99, 
    KEYWORD_CONSTANT = 100, KEYWORD_CROSSES = 101, KEYWORD_META = 102, KEYWORD_NEW = 103, 
    SINGLE_LINE_NOTE = 104, MULTI_LINE_NOTE = 105, REGULAR_COMMENT = 106, 
    SYMBOL_COMMENT_BLOCK_START = 107, SYMBOL_NOTE_BLOCK_START = 108, SYMBOL_COMMENT_BLOCK_END = 109, 
    SYMBOL_STATEMENT_DELIMITER = 110, SYMBOL_STAR = 111, SYMBOL_NAMESPACE_SUBSET = 112, 
    SYMBOL_TYPED_BY = 113, SYMBOL_SPECIALIZES = 114, SYMBOL_REFERENCES = 115, 
    SYMBOL_REDEFINES = 116, SYMBOL_CONJUGATES = 117, SYMBOL_CROSSES = 118, 
    SYMBOL_ROUND_BRACKET_OPEN = 119, SYMBOL_ROUND_BRACKET_CLOSE = 120, SYMBOL_CURLY_BRACKET_OPEN = 121, 
    SYMBOL_CURLY_BRACKET_CLOSE = 122, SYMBOL_SQUARE_BRACKET_OPEN = 123, 
    SYMBOL_SQUARE_BRACKET_CLOSE = 124, SYMBOL_COMMA = 125, SYMBOL_AT = 126, 
    SYMBOL_HASHTAG = 127, SYMBOL_MOD = 128, SYMBOL_AND = 129, SYMBOL_UPPER = 130, 
    SYMBOL_VERTICAL_LINE = 131, SYMBOL_DOUBLE_STAR = 132, SYMBOL_PLUS = 133, 
    SYMBOL_MINUS = 134, SYMBOL_SLASH = 135, SYMBOL_ARROW = 136, SYMBOL_DOT = 137, 
    SYMBOL_DDOT = 138, SYMBOL_SMALLER = 139, SYMBOL_SMALLER_EQUAL = 140, 
    SYMBOL_ASSIGN = 141, SYMBOL_DEF_ASSIGN = 142, SYMBOL_EQUALS = 143, SYMBOL_IFF_EQUALS = 144, 
    SYMBOL_NOT_EQUALS = 145, SYMBOL_IFF_NOT_EQUALS = 146, SYMBOL_GREATER = 147, 
    SYMBOL_GREATER_EQUALS = 148, SYMBOL_QUESTION = 149, SYMBOL_DQUESTION = 150, 
    SYMBOL_DOT_QUESTION = 151, SYMBOL_ATAT = 152, NAME = 153, BASIC_NAME = 154, 
    UNRESTRICTED_NAME = 155, DECIMAL_VALUE = 156, EXPONENTIAL_VALUE = 157, 
    STRING_VALUE = 158, WS = 159
  };

  explicit KerMLLexer(antlr4::CharStream *input);

  ~KerMLLexer() override;


  std::string getGrammarFileName() const override;

  const std::vector<std::string>& getRuleNames() const override;

  const std::vector<std::string>& getChannelNames() const override;

  const std::vector<std::string>& getModeNames() const override;

  const antlr4::dfa::Vocabulary& getVocabulary() const override;

  antlr4::atn::SerializedATNView getSerializedATN() const override;

  const antlr4::atn::ATN& getATN() const override;

  // By default the static state used to implement the lexer is lazily initialized during the first
  // call to the constructor. You can call this function if you wish to initialize the static state
  // ahead of time.
  static void initialize();

private:

  // Individual action functions triggered by action() above.

  // Individual semantic predicate functions triggered by sempred() above.

};

