// Generated by sysml/tools/generate_abstract_syntax.py.
#pragma once
#include <sysml/model/Representation.h>
#include <sysml/model/Forward.h>
#include <sysml/model/KerMLTypes.h>
#include <sysml/usage/Usage.h>

namespace SysMLv2::Entities {
class SYSML_EXPORT AttributeUsage : public virtual Usage, public virtual Representation {
public:
    AttributeUsage();
    ~AttributeUsage() override;
    std::string_view metaclassName() const noexcept override;
    std::vector<RepresentationIssue> validateRepresentation(bool includeDerived = false) const override;
    /// Derived snapshot; populated by a semantic evaluator or importer.
    std::vector<std::shared_ptr<KerML::Entities::DataType>> attributeDefinition() const;
    void setAttributeDefinition(std::vector<std::shared_ptr<KerML::Entities::DataType>> value);
    void appendAttributeDefinition(std::shared_ptr<KerML::Entities::DataType> value);
    /// Derived snapshot; populated by a semantic evaluator or importer.
    bool isReference() const;
    void setIsReference(bool value);
private:
    std::vector<std::shared_ptr<KerML::Entities::DataType>> attributeDefinition_ = {};
    bool isReference_ = true;
};
}
