// Generated by sysml/tools/generate_abstract_syntax.py.
#pragma once
#include <sysml/model/Representation.h>
#include <sysml/model/Forward.h>
#include <sysml/model/KerMLTypes.h>
#include <sysml/usage/Definition.h>

namespace SysMLv2::Entities {
class SYSML_EXPORT AttributeDefinition : public virtual KerML::Entities::DataType, public virtual Definition, public virtual Representation {
public:
    AttributeDefinition();
    ~AttributeDefinition() override;
    std::string_view metaclassName() const noexcept override;
    std::vector<RepresentationIssue> validateRepresentation(bool includeDerived = false) const override;
private:
};
}
