// Generated by kerml/tools/generate_abstract_syntax.py.
#include <kerml/KerML.h>
#include <utility>
#include <stdexcept>
#include "../../model/RepresentationSupport.h"

namespace KerML::Entities {
std::vector<std::shared_ptr<Classifier>> Flow::payloadType() const {
    auto payload = payloadFeature(); return payload ? detail::select<Classifier>(payload->type()) : std::vector<std::shared_ptr<Classifier>>{};
}

std::shared_ptr<Feature> Flow::targetInputFeature() const {
    auto ends = connectorEnd(); if (ends.size() < 2 || !ends[1]) return nullptr; auto values = ends[1]->ownedFeature(); return values.empty() ? nullptr : values.front();
}

std::shared_ptr<Feature> Flow::sourceOutputFeature() const {
    auto ends = connectorEnd(); if (ends.empty() || !ends.front()) return nullptr; auto values = ends.front()->ownedFeature(); return values.empty() ? nullptr : values.front();
}

std::vector<std::shared_ptr<FlowEnd>> Flow::flowEnd() const {
    return detail::select<FlowEnd>(connectorEnd());
}

std::shared_ptr<PayloadFeature> Flow::payloadFeature() const {
    auto values = detail::select<PayloadFeature>(ownedFeature()); return values.empty() ? nullptr : values.front();
}

std::vector<std::shared_ptr<Interaction>> Flow::interaction() const {
    return detail::select<Interaction>(Feature::type());
}

Flow::Flow() {
    _dType = "Flow";
}

Flow::~Flow() = default;
}
