// Generated by kerml/tools/generate_abstract_syntax.py.
#include <kerml/KerML.h>
#include <utility>
#include <stdexcept>
#include "../../model/RepresentationSupport.h"

namespace KerML::Entities {
FlowEnd::FlowEnd() {
    _dType = "FlowEnd";
    setIsEnd(true);
}

FlowEnd::~FlowEnd() = default;
}
