// Generated by sysml/tools/generate_abstract_syntax.py.
#include <sysml/SysML.h>
#include <stdexcept>

namespace SysMLv2::Entities {

std::shared_ptr<Representation> createRepresentation(std::string_view name) {
    if (name == "FlowDefinition") return std::make_shared<FlowDefinition>();
    if (name == "FlowUsage") return std::make_shared<FlowUsage>();
    if (name == "SuccessionFlowUsage") return std::make_shared<SuccessionFlowUsage>();
    if (name == "EnumerationDefinition") return std::make_shared<EnumerationDefinition>();
    if (name == "EnumerationUsage") return std::make_shared<EnumerationUsage>();
    if (name == "RequirementUsage") return std::make_shared<RequirementUsage>();
    if (name == "ConcernUsage") return std::make_shared<ConcernUsage>();
    if (name == "FramedConcernMembership") return std::make_shared<FramedConcernMembership>();
    if (name == "ActorMembership") return std::make_shared<ActorMembership>();
    if (name == "StakeholderMembership") return std::make_shared<StakeholderMembership>();
    if (name == "SubjectMembership") return std::make_shared<SubjectMembership>();
    if (name == "ConcernDefinition") return std::make_shared<ConcernDefinition>();
    if (name == "RequirementDefinition") return std::make_shared<RequirementDefinition>();
    if (name == "RequirementConstraintMembership") return std::make_shared<RequirementConstraintMembership>();
    if (name == "SatisfyRequirementUsage") return std::make_shared<SatisfyRequirementUsage>();
    if (name == "CalculationDefinition") return std::make_shared<CalculationDefinition>();
    if (name == "CalculationUsage") return std::make_shared<CalculationUsage>();
    if (name == "MetadataDefinition") return std::make_shared<MetadataDefinition>();
    if (name == "MetadataUsage") return std::make_shared<MetadataUsage>();
    if (name == "AssertConstraintUsage") return std::make_shared<AssertConstraintUsage>();
    if (name == "ConstraintDefinition") return std::make_shared<ConstraintDefinition>();
    if (name == "ConstraintUsage") return std::make_shared<ConstraintUsage>();
    if (name == "CaseUsage") return std::make_shared<CaseUsage>();
    if (name == "CaseDefinition") return std::make_shared<CaseDefinition>();
    if (name == "ObjectiveMembership") return std::make_shared<ObjectiveMembership>();
    if (name == "TransitionFeatureMembership") return std::make_shared<TransitionFeatureMembership>();
    if (name == "ExhibitStateUsage") return std::make_shared<ExhibitStateUsage>();
    if (name == "StateSubactionMembership") return std::make_shared<StateSubactionMembership>();
    if (name == "StateUsage") return std::make_shared<StateUsage>();
    if (name == "StateDefinition") return std::make_shared<StateDefinition>();
    if (name == "TransitionUsage") return std::make_shared<TransitionUsage>();
    if (name == "UseCaseUsage") return std::make_shared<UseCaseUsage>();
    if (name == "IncludeUseCaseUsage") return std::make_shared<IncludeUseCaseUsage>();
    if (name == "UseCaseDefinition") return std::make_shared<UseCaseDefinition>();
    if (name == "PerformActionUsage") return std::make_shared<PerformActionUsage>();
    if (name == "ActionDefinition") return std::make_shared<ActionDefinition>();
    if (name == "ActionUsage") return std::make_shared<ActionUsage>();
    if (name == "AssignmentActionUsage") return std::make_shared<AssignmentActionUsage>();
    if (name == "ForLoopActionUsage") return std::make_shared<ForLoopActionUsage>();
    if (name == "TriggerInvocationExpression") return std::make_shared<TriggerInvocationExpression>();
    if (name == "DecisionNode") return std::make_shared<DecisionNode>();
    if (name == "ForkNode") return std::make_shared<ForkNode>();
    if (name == "JoinNode") return std::make_shared<JoinNode>();
    if (name == "MergeNode") return std::make_shared<MergeNode>();
    if (name == "TerminateActionUsage") return std::make_shared<TerminateActionUsage>();
    if (name == "AcceptActionUsage") return std::make_shared<AcceptActionUsage>();
    if (name == "WhileLoopActionUsage") return std::make_shared<WhileLoopActionUsage>();
    if (name == "SendActionUsage") return std::make_shared<SendActionUsage>();
    if (name == "IfActionUsage") return std::make_shared<IfActionUsage>();
    if (name == "ItemUsage") return std::make_shared<ItemUsage>();
    if (name == "ItemDefinition") return std::make_shared<ItemDefinition>();
    if (name == "EventOccurrenceUsage") return std::make_shared<EventOccurrenceUsage>();
    if (name == "OccurrenceUsage") return std::make_shared<OccurrenceUsage>();
    if (name == "OccurrenceDefinition") return std::make_shared<OccurrenceDefinition>();
    if (name == "Usage") return std::make_shared<Usage>();
    if (name == "ReferenceUsage") return std::make_shared<ReferenceUsage>();
    if (name == "VariantMembership") return std::make_shared<VariantMembership>();
    if (name == "Definition") return std::make_shared<Definition>();
    if (name == "AttributeDefinition") return std::make_shared<AttributeDefinition>();
    if (name == "AttributeUsage") return std::make_shared<AttributeUsage>();
    if (name == "PartDefinition") return std::make_shared<PartDefinition>();
    if (name == "PartUsage") return std::make_shared<PartUsage>();
    if (name == "AnalysisCaseUsage") return std::make_shared<AnalysisCaseUsage>();
    if (name == "AnalysisCaseDefinition") return std::make_shared<AnalysisCaseDefinition>();
    if (name == "PortConjugation") return std::make_shared<PortConjugation>();
    if (name == "ConjugatedPortDefinition") return std::make_shared<ConjugatedPortDefinition>();
    if (name == "PortDefinition") return std::make_shared<PortDefinition>();
    if (name == "ConjugatedPortTyping") return std::make_shared<ConjugatedPortTyping>();
    if (name == "PortUsage") return std::make_shared<PortUsage>();
    if (name == "ViewUsage") return std::make_shared<ViewUsage>();
    if (name == "ViewDefinition") return std::make_shared<ViewDefinition>();
    if (name == "RenderingUsage") return std::make_shared<RenderingUsage>();
    if (name == "ViewpointDefinition") return std::make_shared<ViewpointDefinition>();
    if (name == "RenderingDefinition") return std::make_shared<RenderingDefinition>();
    if (name == "MembershipExpose") return std::make_shared<MembershipExpose>();
    if (name == "NamespaceExpose") return std::make_shared<NamespaceExpose>();
    if (name == "ViewRenderingMembership") return std::make_shared<ViewRenderingMembership>();
    if (name == "ViewpointUsage") return std::make_shared<ViewpointUsage>();
    if (name == "ConnectionUsage") return std::make_shared<ConnectionUsage>();
    if (name == "SuccessionAsUsage") return std::make_shared<SuccessionAsUsage>();
    if (name == "ConnectionDefinition") return std::make_shared<ConnectionDefinition>();
    if (name == "BindingConnectorAsUsage") return std::make_shared<BindingConnectorAsUsage>();
    if (name == "InterfaceUsage") return std::make_shared<InterfaceUsage>();
    if (name == "InterfaceDefinition") return std::make_shared<InterfaceDefinition>();
    if (name == "AllocationDefinition") return std::make_shared<AllocationDefinition>();
    if (name == "AllocationUsage") return std::make_shared<AllocationUsage>();
    if (name == "RequirementVerificationMembership") return std::make_shared<RequirementVerificationMembership>();
    if (name == "VerificationCaseDefinition") return std::make_shared<VerificationCaseDefinition>();
    if (name == "VerificationCaseUsage") return std::make_shared<VerificationCaseUsage>();
    throw std::invalid_argument("Unknown or abstract SysML metaclass: " + std::string(name));
}
std::span<const MetaclassDescriptor> metaclasses() noexcept {
    static const MetaclassDescriptor values[] = {
        {"FlowDefinition", "flows", false, 1},
        {"FlowUsage", "flows", false, 1},
        {"SuccessionFlowUsage", "flows", false, 0},
        {"EnumerationDefinition", "enumerations", false, 2},
        {"EnumerationUsage", "enumerations", false, 1},
        {"RequirementUsage", "requirements", false, 9},
        {"ConcernUsage", "requirements", false, 1},
        {"FramedConcernMembership", "requirements", false, 3},
        {"ActorMembership", "requirements", false, 1},
        {"StakeholderMembership", "requirements", false, 1},
        {"SubjectMembership", "requirements", false, 1},
        {"ConcernDefinition", "requirements", false, 0},
        {"RequirementDefinition", "requirements", false, 8},
        {"RequirementConstraintMembership", "requirements", false, 3},
        {"SatisfyRequirementUsage", "requirements", false, 2},
        {"CalculationDefinition", "calculations", false, 1},
        {"CalculationUsage", "calculations", false, 1},
        {"MetadataDefinition", "metadata", false, 0},
        {"MetadataUsage", "metadata", false, 1},
        {"AssertConstraintUsage", "constraints", false, 1},
        {"ConstraintDefinition", "constraints", false, 0},
        {"ConstraintUsage", "constraints", false, 1},
        {"CaseUsage", "cases", false, 4},
        {"CaseDefinition", "cases", false, 3},
        {"ObjectiveMembership", "cases", false, 1},
        {"TransitionFeatureMembership", "states", false, 2},
        {"ExhibitStateUsage", "states", false, 1},
        {"StateSubactionMembership", "states", false, 2},
        {"StateUsage", "states", false, 5},
        {"StateDefinition", "states", false, 5},
        {"TransitionUsage", "states", false, 6},
        {"UseCaseUsage", "usecases", false, 2},
        {"IncludeUseCaseUsage", "usecases", false, 1},
        {"UseCaseDefinition", "usecases", false, 1},
        {"PerformActionUsage", "actions", false, 1},
        {"ActionDefinition", "actions", false, 1},
        {"ActionUsage", "actions", false, 1},
        {"AssignmentActionUsage", "actions", false, 3},
        {"ForLoopActionUsage", "actions", false, 2},
        {"TriggerInvocationExpression", "actions", false, 1},
        {"LoopActionUsage", "actions", true, 1},
        {"DecisionNode", "actions", false, 0},
        {"ForkNode", "actions", false, 0},
        {"JoinNode", "actions", false, 0},
        {"ControlNode", "actions", true, 0},
        {"MergeNode", "actions", false, 0},
        {"TerminateActionUsage", "actions", false, 1},
        {"AcceptActionUsage", "actions", false, 3},
        {"WhileLoopActionUsage", "actions", false, 2},
        {"SendActionUsage", "actions", false, 3},
        {"IfActionUsage", "actions", false, 3},
        {"ItemUsage", "items", false, 1},
        {"ItemDefinition", "items", false, 0},
        {"EventOccurrenceUsage", "occurrences", false, 2},
        {"OccurrenceUsage", "occurrences", false, 4},
        {"OccurrenceDefinition", "occurrences", false, 1},
        {"Usage", "usage", false, 37},
        {"ReferenceUsage", "usage", false, 1},
        {"VariantMembership", "usage", false, 1},
        {"Definition", "usage", false, 32},
        {"AttributeDefinition", "attributes", false, 0},
        {"AttributeUsage", "attributes", false, 2},
        {"PartDefinition", "parts", false, 0},
        {"PartUsage", "parts", false, 1},
        {"AnalysisCaseUsage", "analysiscases", false, 2},
        {"AnalysisCaseDefinition", "analysiscases", false, 1},
        {"PortConjugation", "ports", false, 2},
        {"ConjugatedPortDefinition", "ports", false, 2},
        {"PortDefinition", "ports", false, 1},
        {"ConjugatedPortTyping", "ports", false, 2},
        {"PortUsage", "ports", false, 1},
        {"ViewUsage", "views", false, 5},
        {"Expose", "views", true, 2},
        {"ViewDefinition", "views", false, 4},
        {"RenderingUsage", "views", false, 1},
        {"ViewpointDefinition", "views", false, 1},
        {"RenderingDefinition", "views", false, 1},
        {"MembershipExpose", "views", false, 0},
        {"NamespaceExpose", "views", false, 0},
        {"ViewRenderingMembership", "views", false, 2},
        {"ViewpointUsage", "views", false, 2},
        {"ConnectorAsUsage", "connections", true, 0},
        {"ConnectionUsage", "connections", false, 1},
        {"SuccessionAsUsage", "connections", false, 0},
        {"ConnectionDefinition", "connections", false, 2},
        {"BindingConnectorAsUsage", "connections", false, 0},
        {"InterfaceUsage", "interfaces", false, 1},
        {"InterfaceDefinition", "interfaces", false, 1},
        {"AllocationDefinition", "allocations", false, 1},
        {"AllocationUsage", "allocations", false, 1},
        {"RequirementVerificationMembership", "verificationcases", false, 3},
        {"VerificationCaseDefinition", "verificationcases", false, 1},
        {"VerificationCaseUsage", "verificationcases", false, 2},
    };
    return values;
}
}
