// Generated by kerml/tools/generate_abstract_syntax.py.
#include <kerml/KerML.h>
#include <utility>
#include <stdexcept>
#include "../../model/RepresentationSupport.h"

namespace KerML::Entities {
std::shared_ptr<Metaclass> MetadataFeature::metaclass() const {
    auto values = detail::select<Metaclass>(Feature::type()); return values.empty() ? nullptr : values.front();
}

MetadataFeature::MetadataFeature() {
    _dType = "MetadataFeature";
}

MetadataFeature::~MetadataFeature() = default;
}
