// Generated by kerml/tools/generate_abstract_syntax.py.
#pragma once
#include <kerml/kernel/classes/Class.h>
#include <kerml/model/Forward.h>
#include <kerml/kerml_global.h>
#include <cstdint>
#include <memory>
#include <string>
#include <vector>

namespace KerML::Entities {
class KERML_EXPORT Behavior : public virtual Class {
public:
    Behavior();
    ~Behavior() override;
    /// Computed from the underlying representation.
    std::vector<std::shared_ptr<Step>> step() const;
    /// Derived snapshot populated by an importer or semantic evaluator.
    std::vector<std::shared_ptr<Feature>> parameter() const;
    void setParameter(std::vector<std::shared_ptr<Feature>> value);
    void appendParameter(std::shared_ptr<Feature> value);
private:
    std::vector<std::shared_ptr<Feature>> parameter_ = {};
};
}
