// Generated by kerml/tools/generate_abstract_syntax.py.
#pragma once
#include <kerml/core/features/Feature.h>
#include <kerml/model/Forward.h>
#include <kerml/kerml_global.h>
#include <cstdint>
#include <memory>
#include <string>
#include <vector>

namespace KerML::Entities {
class KERML_EXPORT Step : public virtual Feature {
public:
    Step();
    ~Step() override;
    /// Derived snapshot populated by an importer or semantic evaluator.
    std::vector<std::shared_ptr<Behavior>> behavior() const;
    void setBehavior(std::vector<std::shared_ptr<Behavior>> value);
    void appendBehavior(std::shared_ptr<Behavior> value);
    /// Derived snapshot populated by an importer or semantic evaluator.
    std::vector<std::shared_ptr<Feature>> parameter() const;
    void setParameter(std::vector<std::shared_ptr<Feature>> value);
    void appendParameter(std::shared_ptr<Feature> value);
private:
    std::vector<std::shared_ptr<Behavior>> behavior_ = {};
    std::vector<std::shared_ptr<Feature>> parameter_ = {};
};
}
