// Generated by sysml/tools/generate_abstract_syntax.py.
#include <sysml/cases/CaseUsage.h>
#include <sysml/requirements/RequirementUsage.h>
#include <sysml/cases/CaseDefinition.h>
#include <sysml/usage/Usage.h>
#include <sysml/parts/PartUsage.h>
#include <algorithm>
#include <stdexcept>

namespace SysMLv2::Entities {

std::shared_ptr<RequirementUsage> CaseUsage::objectiveRequirement() const {
    return objectiveRequirement_;
}

void CaseUsage::setObjectiveRequirement(std::shared_ptr<RequirementUsage> value) {
    objectiveRequirement_ = std::move(value);
}

std::shared_ptr<CaseDefinition> CaseUsage::caseDefinition() const {
    return caseDefinition_;
}

void CaseUsage::setCaseDefinition(std::shared_ptr<CaseDefinition> value) {
    caseDefinition_ = std::move(value);
}

std::shared_ptr<Usage> CaseUsage::subjectParameter() const {
    return subjectParameter_;
}

void CaseUsage::setSubjectParameter(std::shared_ptr<Usage> value) {
    subjectParameter_ = std::move(value);
}

std::vector<std::shared_ptr<PartUsage>> CaseUsage::actorParameter() const {
    return actorParameter_;
}

void CaseUsage::setActorParameter(std::vector<std::shared_ptr<PartUsage>> value) {
    if (std::any_of(value.begin(), value.end(), [](const auto& item) { return !item; })) {
        throw std::invalid_argument("CaseUsage.actorParameter: null entry");
    }
    for (std::size_t i = 0; i < value.size(); ++i) {
        if (std::find(value.begin(), value.begin() + i, value[i]) != value.begin() + i) {
            throw std::invalid_argument("CaseUsage.actorParameter: duplicate entry");
        }
    }
    actorParameter_ = std::move(value);
}

void CaseUsage::appendActorParameter(std::shared_ptr<PartUsage> value) {
    auto values = actorParameter();
    values.push_back(std::move(value));
    setActorParameter(std::move(values));
}

CaseUsage::CaseUsage() {
    _dType = "CaseUsage";
}

CaseUsage::~CaseUsage() = default;

std::string_view CaseUsage::metaclassName() const noexcept {
    return "CaseUsage";
}

std::vector<RepresentationIssue> CaseUsage::validateRepresentation(bool includeDerived) const {
    std::vector<RepresentationIssue> issues; (void)includeDerived;
    { auto optional = OccurrenceUsage::portionKind(); if (optional) { auto value = *optional; if (!(value == PortionKind::timeslice || value == PortionKind::snapshot)) issues.push_back({"OccurrenceUsage.portionKind", "invalid enumeration value"}); } }
    if (includeDerived) if (!CaseUsage::subjectParameter()) issues.push_back({"CaseUsage.subjectParameter", "required reference is missing"});
    return issues;
}

} // namespace SysMLv2::Entities
