// Generated by sysml/tools/generate_abstract_syntax.py.
#include <sysml/cases/CaseDefinition.h>
#include <sysml/requirements/RequirementUsage.h>
#include <sysml/usage/Usage.h>
#include <sysml/parts/PartUsage.h>
#include <algorithm>
#include <stdexcept>

namespace SysMLv2::Entities {

std::shared_ptr<RequirementUsage> CaseDefinition::objectiveRequirement() const {
    return objectiveRequirement_;
}

void CaseDefinition::setObjectiveRequirement(std::shared_ptr<RequirementUsage> value) {
    objectiveRequirement_ = std::move(value);
}

std::shared_ptr<Usage> CaseDefinition::subjectParameter() const {
    return subjectParameter_;
}

void CaseDefinition::setSubjectParameter(std::shared_ptr<Usage> value) {
    subjectParameter_ = std::move(value);
}

std::vector<std::shared_ptr<PartUsage>> CaseDefinition::actorParameter() const {
    return actorParameter_;
}

void CaseDefinition::setActorParameter(std::vector<std::shared_ptr<PartUsage>> value) {
    if (std::any_of(value.begin(), value.end(), [](const auto& item) { return !item; })) {
        throw std::invalid_argument("CaseDefinition.actorParameter: null entry");
    }
    for (std::size_t i = 0; i < value.size(); ++i) {
        if (std::find(value.begin(), value.begin() + i, value[i]) != value.begin() + i) {
            throw std::invalid_argument("CaseDefinition.actorParameter: duplicate entry");
        }
    }
    actorParameter_ = std::move(value);
}

void CaseDefinition::appendActorParameter(std::shared_ptr<PartUsage> value) {
    auto values = actorParameter();
    values.push_back(std::move(value));
    setActorParameter(std::move(values));
}

CaseDefinition::CaseDefinition() {
    _dType = "CaseDefinition";
}

CaseDefinition::~CaseDefinition() = default;

std::string_view CaseDefinition::metaclassName() const noexcept {
    return "CaseDefinition";
}

std::vector<RepresentationIssue> CaseDefinition::validateRepresentation(bool includeDerived) const {
    std::vector<RepresentationIssue> issues; (void)includeDerived;
    if (includeDerived) if (!CaseDefinition::subjectParameter()) issues.push_back({"CaseDefinition.subjectParameter", "required reference is missing"});
    return issues;
}

} // namespace SysMLv2::Entities
