// Generated by sysml/tools/generate_abstract_syntax.py.
#pragma once
#include <sysml/model/Representation.h>
#include <sysml/model/Forward.h>
#include <sysml/model/KerMLTypes.h>

namespace SysMLv2::Entities {
class SYSML_EXPORT ActorMembership : public virtual KerML::Entities::ParameterMembership, public virtual Representation {
public:
    ActorMembership();
    ~ActorMembership() override;
    std::string_view metaclassName() const noexcept override;
    std::vector<RepresentationIssue> validateRepresentation(bool includeDerived = false) const override;
    /// Derived snapshot; populated by a semantic evaluator or importer.
    std::shared_ptr<PartUsage> ownedActorParameter() const;
    void setOwnedActorParameter(std::shared_ptr<PartUsage> value);
private:
    std::shared_ptr<PartUsage> ownedActorParameter_ = {};
};
}
