// Generated by sysml/tools/generate_abstract_syntax.py.
#pragma once
#include <sysml/model/Representation.h>
#include <sysml/model/Forward.h>
#include <sysml/model/KerMLTypes.h>
#include <sysml/requirements/RequirementUsage.h>

namespace SysMLv2::Entities {
class SYSML_EXPORT ConcernUsage : public virtual RequirementUsage, public virtual Representation {
public:
    ConcernUsage();
    ~ConcernUsage() override;
    std::string_view metaclassName() const noexcept override;
    std::vector<RepresentationIssue> validateRepresentation(bool includeDerived = false) const override;
    /// Derived snapshot; populated by a semantic evaluator or importer.
    std::shared_ptr<ConcernDefinition> concernDefinition() const;
    void setConcernDefinition(std::shared_ptr<ConcernDefinition> value);
private:
    std::shared_ptr<ConcernDefinition> concernDefinition_ = {};
};
}
