// Generated by sysml/tools/generate_abstract_syntax.py.
#pragma once
#include <sysml/model/Representation.h>
#include <sysml/model/Forward.h>
#include <sysml/model/KerMLTypes.h>
#include <sysml/requirements/RequirementConstraintMembership.h>
#include <sysml/requirements/RequirementConstraintKind.h>

namespace SysMLv2::Entities {
class SYSML_EXPORT FramedConcernMembership : public virtual RequirementConstraintMembership, public virtual Representation {
public:
    FramedConcernMembership();
    ~FramedConcernMembership() override;
    std::string_view metaclassName() const noexcept override;
    std::vector<RepresentationIssue> validateRepresentation(bool includeDerived = false) const override;
    /// Stored metamodel property.
    RequirementConstraintKind kind() const;
    void setKind(RequirementConstraintKind value);
    /// Derived snapshot; populated by a semantic evaluator or importer.
    std::shared_ptr<ConcernUsage> ownedConcern() const;
    void setOwnedConcern(std::shared_ptr<ConcernUsage> value);
    /// Derived snapshot; populated by a semantic evaluator or importer.
    std::shared_ptr<ConcernUsage> referencedConcern() const;
    void setReferencedConcern(std::shared_ptr<ConcernUsage> value);
private:
    RequirementConstraintKind kind_ = RequirementConstraintKind::requirement;
    std::shared_ptr<ConcernUsage> ownedConcern_ = {};
    std::shared_ptr<ConcernUsage> referencedConcern_ = {};
};
}
