// Generated by sysml/tools/generate_abstract_syntax.py.
#pragma once
#include <sysml/model/Representation.h>
#include <sysml/model/Forward.h>
#include <sysml/model/KerMLTypes.h>
#include <sysml/requirements/RequirementConstraintKind.h>

namespace SysMLv2::Entities {
class SYSML_EXPORT RequirementConstraintMembership : public virtual KerML::Entities::FeatureMembership, public virtual Representation {
public:
    RequirementConstraintMembership();
    ~RequirementConstraintMembership() override;
    std::string_view metaclassName() const noexcept override;
    std::vector<RepresentationIssue> validateRepresentation(bool includeDerived = false) const override;
    /// Stored metamodel property.
    RequirementConstraintKind kind() const;
    void setKind(RequirementConstraintKind value);
    /// Derived snapshot; populated by a semantic evaluator or importer.
    std::shared_ptr<ConstraintUsage> ownedConstraint() const;
    void setOwnedConstraint(std::shared_ptr<ConstraintUsage> value);
    /// Derived snapshot; populated by a semantic evaluator or importer.
    std::shared_ptr<ConstraintUsage> referencedConstraint() const;
    void setReferencedConstraint(std::shared_ptr<ConstraintUsage> value);
private:
    RequirementConstraintKind kind_ = {};
    std::shared_ptr<ConstraintUsage> ownedConstraint_ = {};
    std::shared_ptr<ConstraintUsage> referencedConstraint_ = {};
};
}
