// Generated by sysml/tools/generate_abstract_syntax.py.
#pragma once
#include <sysml/model/Representation.h>
#include <sysml/model/Forward.h>
#include <sysml/model/KerMLTypes.h>
#include <sysml/constraints/ConstraintDefinition.h>

namespace SysMLv2::Entities {
class SYSML_EXPORT RequirementDefinition : public virtual ConstraintDefinition, public virtual Representation {
public:
    RequirementDefinition();
    ~RequirementDefinition() override;
    std::string_view metaclassName() const noexcept override;
    std::vector<RepresentationIssue> validateRepresentation(bool includeDerived = false) const override;
    /// Stored metamodel property.
    std::optional<std::string> reqId() const;
    void setReqId(std::optional<std::string> value);
    /// Derived snapshot; populated by a semantic evaluator or importer.
    std::vector<std::string> text() const;
    void setText(std::vector<std::string> value);
    void appendText(std::string value);
    /// Derived snapshot; populated by a semantic evaluator or importer.
    std::shared_ptr<Usage> subjectParameter() const;
    void setSubjectParameter(std::shared_ptr<Usage> value);
    /// Derived snapshot; populated by a semantic evaluator or importer.
    std::vector<std::shared_ptr<PartUsage>> actorParameter() const;
    void setActorParameter(std::vector<std::shared_ptr<PartUsage>> value);
    void appendActorParameter(std::shared_ptr<PartUsage> value);
    /// Derived snapshot; populated by a semantic evaluator or importer.
    std::vector<std::shared_ptr<PartUsage>> stakeholderParameter() const;
    void setStakeholderParameter(std::vector<std::shared_ptr<PartUsage>> value);
    void appendStakeholderParameter(std::shared_ptr<PartUsage> value);
    /// Derived snapshot; populated by a semantic evaluator or importer.
    std::vector<std::shared_ptr<ConstraintUsage>> assumedConstraint() const;
    void setAssumedConstraint(std::vector<std::shared_ptr<ConstraintUsage>> value);
    void appendAssumedConstraint(std::shared_ptr<ConstraintUsage> value);
    /// Derived snapshot; populated by a semantic evaluator or importer.
    std::vector<std::shared_ptr<ConstraintUsage>> requiredConstraint() const;
    void setRequiredConstraint(std::vector<std::shared_ptr<ConstraintUsage>> value);
    void appendRequiredConstraint(std::shared_ptr<ConstraintUsage> value);
    /// Derived snapshot; populated by a semantic evaluator or importer.
    std::vector<std::shared_ptr<ConcernUsage>> framedConcern() const;
    void setFramedConcern(std::vector<std::shared_ptr<ConcernUsage>> value);
    void appendFramedConcern(std::shared_ptr<ConcernUsage> value);
private:
    std::optional<std::string> reqId_ = {};
    std::vector<std::string> text_ = {};
    std::shared_ptr<Usage> subjectParameter_ = {};
    std::vector<std::shared_ptr<PartUsage>> actorParameter_ = {};
    std::vector<std::shared_ptr<PartUsage>> stakeholderParameter_ = {};
    std::vector<std::shared_ptr<ConstraintUsage>> assumedConstraint_ = {};
    std::vector<std::shared_ptr<ConstraintUsage>> requiredConstraint_ = {};
    std::vector<std::shared_ptr<ConcernUsage>> framedConcern_ = {};
};
}
