// Generated by sysml/tools/generate_abstract_syntax.py.
#pragma once
#include <sysml/model/Representation.h>
#include <sysml/model/Forward.h>
#include <sysml/model/KerMLTypes.h>
#include <sysml/requirements/RequirementUsage.h>
#include <sysml/constraints/AssertConstraintUsage.h>

namespace SysMLv2::Entities {
class SYSML_EXPORT SatisfyRequirementUsage : public virtual RequirementUsage, public virtual AssertConstraintUsage, public virtual Representation {
public:
    SatisfyRequirementUsage();
    ~SatisfyRequirementUsage() override;
    std::string_view metaclassName() const noexcept override;
    std::vector<RepresentationIssue> validateRepresentation(bool includeDerived = false) const override;
    /// Derived snapshot; populated by a semantic evaluator or importer.
    std::shared_ptr<RequirementUsage> satisfiedRequirement() const;
    void setSatisfiedRequirement(std::shared_ptr<RequirementUsage> value);
    /// Derived snapshot; populated by a semantic evaluator or importer.
    std::shared_ptr<KerML::Entities::Feature> satisfyingFeature() const;
    void setSatisfyingFeature(std::shared_ptr<KerML::Entities::Feature> value);
private:
    std::shared_ptr<RequirementUsage> satisfiedRequirement_ = {};
    std::shared_ptr<KerML::Entities::Feature> satisfyingFeature_ = {};
};
}
