// Generated by sysml/tools/generate_abstract_syntax.py.
#pragma once
#include <sysml/model/Representation.h>
#include <sysml/model/Forward.h>
#include <sysml/model/KerMLTypes.h>

namespace SysMLv2::Entities {
class SYSML_EXPORT SubjectMembership : public virtual KerML::Entities::ParameterMembership, public virtual Representation {
public:
    SubjectMembership();
    ~SubjectMembership() override;
    std::string_view metaclassName() const noexcept override;
    std::vector<RepresentationIssue> validateRepresentation(bool includeDerived = false) const override;
    /// Derived snapshot; populated by a semantic evaluator or importer.
    std::shared_ptr<Usage> ownedSubjectParameter() const;
    void setOwnedSubjectParameter(std::shared_ptr<Usage> value);
private:
    std::shared_ptr<Usage> ownedSubjectParameter_ = {};
};
}
