// Generated by sysml/tools/generate_abstract_syntax.py.
#pragma once
#include <sysml/model/Representation.h>
#include <sysml/model/Forward.h>
#include <sysml/model/KerMLTypes.h>

namespace SysMLv2::Entities {
class SYSML_EXPORT Expose : public virtual KerML::Entities::Import, public virtual Representation {
public:
    Expose();
    ~Expose() override;
    std::string_view metaclassName() const noexcept override = 0;
    std::vector<RepresentationIssue> validateRepresentation(bool includeDerived = false) const override;
    /// Stored metamodel property.
    KerML::Entities::VisibilityKind visibility() const;
    void setVisibility(KerML::Entities::VisibilityKind value);
    /// Stored metamodel property.
    bool isImportAll() const;
    void setIsImportAll(bool value);
private:
};
}
