// Generated by sysml/tools/generate_abstract_syntax.py.
#pragma once
#include <sysml/model/Representation.h>
#include <sysml/model/Forward.h>
#include <sysml/model/KerMLTypes.h>
#include <sysml/views/Expose.h>

namespace SysMLv2::Entities {
class SYSML_EXPORT MembershipExpose : public virtual KerML::Entities::MembershipImport, public virtual Expose, public virtual Representation {
public:
    MembershipExpose();
    ~MembershipExpose() override;
    std::string_view metaclassName() const noexcept override;
    std::vector<RepresentationIssue> validateRepresentation(bool includeDerived = false) const override;
private:
};
}
