// Generated by sysml/tools/generate_abstract_syntax.py.
#pragma once
#include <sysml/model/Representation.h>
#include <sysml/model/Forward.h>
#include <sysml/model/KerMLTypes.h>
#include <sysml/views/Expose.h>

namespace SysMLv2::Entities {
class SYSML_EXPORT NamespaceExpose : public virtual Expose, public virtual KerML::Entities::NamespaceImport, public virtual Representation {
public:
    NamespaceExpose();
    ~NamespaceExpose() override;
    std::string_view metaclassName() const noexcept override;
    std::vector<RepresentationIssue> validateRepresentation(bool includeDerived = false) const override;
private:
};
}
