// Generated by sysml/tools/generate_abstract_syntax.py.
#pragma once
#include <sysml/model/Representation.h>
#include <sysml/model/Forward.h>
#include <sysml/model/KerMLTypes.h>
#include <sysml/parts/PartDefinition.h>

namespace SysMLv2::Entities {
class SYSML_EXPORT RenderingDefinition : public virtual PartDefinition, public virtual Representation {
public:
    RenderingDefinition();
    ~RenderingDefinition() override;
    std::string_view metaclassName() const noexcept override;
    std::vector<RepresentationIssue> validateRepresentation(bool includeDerived = false) const override;
    /// Derived snapshot; populated by a semantic evaluator or importer.
    std::vector<std::shared_ptr<RenderingUsage>> rendering() const;
    void setRendering(std::vector<std::shared_ptr<RenderingUsage>> value);
    void appendRendering(std::shared_ptr<RenderingUsage> value);
private:
    std::vector<std::shared_ptr<RenderingUsage>> rendering_ = {};
};
}
