// Generated by sysml/tools/generate_abstract_syntax.py.
#pragma once
#include <sysml/model/Representation.h>
#include <sysml/model/Forward.h>
#include <sysml/model/KerMLTypes.h>
#include <sysml/parts/PartUsage.h>

namespace SysMLv2::Entities {
class SYSML_EXPORT RenderingUsage : public virtual PartUsage, public virtual Representation {
public:
    RenderingUsage();
    ~RenderingUsage() override;
    std::string_view metaclassName() const noexcept override;
    std::vector<RepresentationIssue> validateRepresentation(bool includeDerived = false) const override;
    /// Derived snapshot; populated by a semantic evaluator or importer.
    std::shared_ptr<RenderingDefinition> renderingDefinition() const;
    void setRenderingDefinition(std::shared_ptr<RenderingDefinition> value);
private:
    std::shared_ptr<RenderingDefinition> renderingDefinition_ = {};
};
}
