// Generated by sysml/tools/generate_abstract_syntax.py.
#pragma once
#include <sysml/model/Representation.h>
#include <sysml/model/Forward.h>
#include <sysml/model/KerMLTypes.h>
#include <sysml/parts/PartDefinition.h>

namespace SysMLv2::Entities {
class SYSML_EXPORT ViewDefinition : public virtual PartDefinition, public virtual Representation {
public:
    ViewDefinition();
    ~ViewDefinition() override;
    std::string_view metaclassName() const noexcept override;
    std::vector<RepresentationIssue> validateRepresentation(bool includeDerived = false) const override;
    /// Derived snapshot; populated by a semantic evaluator or importer.
    std::vector<std::shared_ptr<ViewUsage>> view() const;
    void setView(std::vector<std::shared_ptr<ViewUsage>> value);
    void appendView(std::shared_ptr<ViewUsage> value);
    /// Derived snapshot; populated by a semantic evaluator or importer.
    std::vector<std::shared_ptr<ViewpointUsage>> satisfiedViewpoint() const;
    void setSatisfiedViewpoint(std::vector<std::shared_ptr<ViewpointUsage>> value);
    void appendSatisfiedViewpoint(std::shared_ptr<ViewpointUsage> value);
    /// Derived snapshot; populated by a semantic evaluator or importer.
    std::shared_ptr<RenderingUsage> viewRendering() const;
    void setViewRendering(std::shared_ptr<RenderingUsage> value);
    /// Derived snapshot; populated by a semantic evaluator or importer.
    std::vector<std::shared_ptr<KerML::Entities::Expression>> viewCondition() const;
    void setViewCondition(std::vector<std::shared_ptr<KerML::Entities::Expression>> value);
    void appendViewCondition(std::shared_ptr<KerML::Entities::Expression> value);
private:
    std::vector<std::shared_ptr<ViewUsage>> view_ = {};
    std::vector<std::shared_ptr<ViewpointUsage>> satisfiedViewpoint_ = {};
    std::shared_ptr<RenderingUsage> viewRendering_ = {};
    std::vector<std::shared_ptr<KerML::Entities::Expression>> viewCondition_ = {};
};
}
