// Generated by sysml/tools/generate_abstract_syntax.py.
#pragma once
#include <sysml/model/Representation.h>
#include <sysml/model/Forward.h>
#include <sysml/model/KerMLTypes.h>
#include <sysml/parts/PartUsage.h>

namespace SysMLv2::Entities {
class SYSML_EXPORT ViewUsage : public virtual PartUsage, public virtual Representation {
public:
    ViewUsage();
    ~ViewUsage() override;
    std::string_view metaclassName() const noexcept override;
    std::vector<RepresentationIssue> validateRepresentation(bool includeDerived = false) const override;
    /// Derived snapshot; populated by a semantic evaluator or importer.
    std::shared_ptr<ViewDefinition> viewDefinition() const;
    void setViewDefinition(std::shared_ptr<ViewDefinition> value);
    /// Derived snapshot; populated by a semantic evaluator or importer.
    std::vector<std::shared_ptr<ViewpointUsage>> satisfiedViewpoint() const;
    void setSatisfiedViewpoint(std::vector<std::shared_ptr<ViewpointUsage>> value);
    void appendSatisfiedViewpoint(std::shared_ptr<ViewpointUsage> value);
    /// Derived snapshot; populated by a semantic evaluator or importer.
    std::vector<std::shared_ptr<KerML::Entities::Element>> exposedElement() const;
    void setExposedElement(std::vector<std::shared_ptr<KerML::Entities::Element>> value);
    void appendExposedElement(std::shared_ptr<KerML::Entities::Element> value);
    /// Derived snapshot; populated by a semantic evaluator or importer.
    std::shared_ptr<RenderingUsage> viewRendering() const;
    void setViewRendering(std::shared_ptr<RenderingUsage> value);
    /// Derived snapshot; populated by a semantic evaluator or importer.
    std::vector<std::shared_ptr<KerML::Entities::Expression>> viewCondition() const;
    void setViewCondition(std::vector<std::shared_ptr<KerML::Entities::Expression>> value);
    void appendViewCondition(std::shared_ptr<KerML::Entities::Expression> value);
private:
    std::shared_ptr<ViewDefinition> viewDefinition_ = {};
    std::vector<std::shared_ptr<ViewpointUsage>> satisfiedViewpoint_ = {};
    std::vector<std::shared_ptr<KerML::Entities::Element>> exposedElement_ = {};
    std::shared_ptr<RenderingUsage> viewRendering_ = {};
    std::vector<std::shared_ptr<KerML::Entities::Expression>> viewCondition_ = {};
};
}
