// Generated by sysml/tools/generate_abstract_syntax.py.
#pragma once
#include <sysml/model/Representation.h>
#include <sysml/model/Forward.h>
#include <sysml/model/KerMLTypes.h>

namespace SysMLv2::Entities {
class SYSML_EXPORT ViewRenderingMembership : public virtual KerML::Entities::FeatureMembership, public virtual Representation {
public:
    ViewRenderingMembership();
    ~ViewRenderingMembership() override;
    std::string_view metaclassName() const noexcept override;
    std::vector<RepresentationIssue> validateRepresentation(bool includeDerived = false) const override;
    /// Derived snapshot; populated by a semantic evaluator or importer.
    std::shared_ptr<RenderingUsage> ownedRendering() const;
    void setOwnedRendering(std::shared_ptr<RenderingUsage> value);
    /// Derived snapshot; populated by a semantic evaluator or importer.
    std::shared_ptr<RenderingUsage> referencedRendering() const;
    void setReferencedRendering(std::shared_ptr<RenderingUsage> value);
private:
    std::shared_ptr<RenderingUsage> ownedRendering_ = {};
    std::shared_ptr<RenderingUsage> referencedRendering_ = {};
};
}
