// Generated by sysml/tools/generate_abstract_syntax.py.
#pragma once
#include <sysml/model/Representation.h>
#include <sysml/model/Forward.h>
#include <sysml/model/KerMLTypes.h>
#include <sysml/requirements/RequirementDefinition.h>

namespace SysMLv2::Entities {
class SYSML_EXPORT ViewpointDefinition : public virtual RequirementDefinition, public virtual Representation {
public:
    ViewpointDefinition();
    ~ViewpointDefinition() override;
    std::string_view metaclassName() const noexcept override;
    std::vector<RepresentationIssue> validateRepresentation(bool includeDerived = false) const override;
    /// Derived snapshot; populated by a semantic evaluator or importer.
    std::vector<std::shared_ptr<PartUsage>> viewpointStakeholder() const;
    void setViewpointStakeholder(std::vector<std::shared_ptr<PartUsage>> value);
    void appendViewpointStakeholder(std::shared_ptr<PartUsage> value);
private:
    std::vector<std::shared_ptr<PartUsage>> viewpointStakeholder_ = {};
};
}
