// Generated by kerml/tools/generate_abstract_syntax.py.
#include <kerml/KerML.h>
#include <utility>
#include <stdexcept>
#include "../../model/RepresentationSupport.h"

namespace KerML::Entities {
std::shared_ptr<Expression> ElementFilterMembership::condition() const {
    return std::dynamic_pointer_cast<Expression>(ownedMemberElement());
}

void ElementFilterMembership::setCondition(std::shared_ptr<Expression> value) {
    setOwnedMemberElement(std::move(value));
}

ElementFilterMembership::ElementFilterMembership() {
    _dType = "ElementFilterMembership";
}

ElementFilterMembership::~ElementFilterMembership() = default;
}
