// Generated by kerml/tools/generate_abstract_syntax.py.
#include <kerml/KerML.h>
#include <utility>
#include <stdexcept>
#include "../../model/RepresentationSupport.h"

namespace KerML::Entities {
bool LibraryPackage::isStandard() const {
    return isStandard_;
}

void LibraryPackage::setIsStandard(bool value) {
    isStandard_ = std::move(value);
}

LibraryPackage::LibraryPackage() {
    _dType = "LibraryPackage";
}

LibraryPackage::~LibraryPackage() = default;
}
