// Generated by kerml/tools/generate_abstract_syntax.py.
#include <kerml/KerML.h>
#include <utility>
#include <stdexcept>
#include "../../model/RepresentationSupport.h"

namespace KerML::Entities {
std::vector<std::shared_ptr<Expression>> Package::filterCondition() const {
    std::vector<std::shared_ptr<Expression>> result; for (const auto& m : ownedMembership()) { if (auto filter = std::dynamic_pointer_cast<ElementFilterMembership>(m)) { if (auto condition = filter->condition()) result.push_back(condition); } } return result;
}

Package::Package() {
    _dType = "Package";
}

Package::~Package() = default;
}
