// Generated by sysml/tools/generate_abstract_syntax.py.
#pragma once
#include <sysml/model/Representation.h>
#include <sysml/model/Forward.h>
#include <sysml/model/KerMLTypes.h>

namespace SysMLv2::Entities {
class SYSML_EXPORT Definition : public virtual KerML::Entities::Classifier, public virtual Representation {
public:
    Definition();
    ~Definition() override;
    std::string_view metaclassName() const noexcept override;
    std::vector<RepresentationIssue> validateRepresentation(bool includeDerived = false) const override;
    /// Stored metamodel property.
    bool isVariation() const;
    void setIsVariation(bool value);
    /// Derived view.
    std::vector<std::shared_ptr<Usage>> variant() const;
    /// Derived view.
    std::vector<std::shared_ptr<VariantMembership>> variantMembership() const;
    /// Derived view.
    std::vector<std::shared_ptr<Usage>> usage() const;
    /// Derived view.
    std::vector<std::shared_ptr<Usage>> directedUsage() const;
    /// Derived view.
    std::vector<std::shared_ptr<Usage>> ownedUsage() const;
    /// Derived view.
    std::vector<std::shared_ptr<ReferenceUsage>> ownedReference() const;
    /// Derived view.
    std::vector<std::shared_ptr<AttributeUsage>> ownedAttribute() const;
    /// Derived view.
    std::vector<std::shared_ptr<EnumerationUsage>> ownedEnumeration() const;
    /// Derived view.
    std::vector<std::shared_ptr<OccurrenceUsage>> ownedOccurrence() const;
    /// Derived view.
    std::vector<std::shared_ptr<ItemUsage>> ownedItem() const;
    /// Derived view.
    std::vector<std::shared_ptr<PartUsage>> ownedPart() const;
    /// Derived view.
    std::vector<std::shared_ptr<PortUsage>> ownedPort() const;
    /// Derived view.
    std::vector<std::shared_ptr<ConnectorAsUsage>> ownedConnection() const;
    /// Derived view.
    std::vector<std::shared_ptr<FlowUsage>> ownedFlow() const;
    /// Derived view.
    std::vector<std::shared_ptr<InterfaceUsage>> ownedInterface() const;
    /// Derived view.
    std::vector<std::shared_ptr<AllocationUsage>> ownedAllocation() const;
    /// Derived view.
    std::vector<std::shared_ptr<ActionUsage>> ownedAction() const;
    /// Derived view.
    std::vector<std::shared_ptr<StateUsage>> ownedState() const;
    /// Derived view.
    std::vector<std::shared_ptr<TransitionUsage>> ownedTransition() const;
    /// Derived view.
    std::vector<std::shared_ptr<CalculationUsage>> ownedCalculation() const;
    /// Derived view.
    std::vector<std::shared_ptr<ConstraintUsage>> ownedConstraint() const;
    /// Derived view.
    std::vector<std::shared_ptr<RequirementUsage>> ownedRequirement() const;
    /// Derived view.
    std::vector<std::shared_ptr<ConcernUsage>> ownedConcern() const;
    /// Derived view.
    std::vector<std::shared_ptr<CaseUsage>> ownedCase() const;
    /// Derived view.
    std::vector<std::shared_ptr<AnalysisCaseUsage>> ownedAnalysisCase() const;
    /// Derived view.
    std::vector<std::shared_ptr<VerificationCaseUsage>> ownedVerificationCase() const;
    /// Derived view.
    std::vector<std::shared_ptr<UseCaseUsage>> ownedUseCase() const;
    /// Derived view.
    std::vector<std::shared_ptr<ViewUsage>> ownedView() const;
    /// Derived view.
    std::vector<std::shared_ptr<ViewpointUsage>> ownedViewpoint() const;
    /// Derived view.
    std::vector<std::shared_ptr<RenderingUsage>> ownedRendering() const;
    /// Derived view.
    std::vector<std::shared_ptr<MetadataUsage>> ownedMetadata() const;
private:
    bool isVariation_ = {};
};
}
