// Generated by sysml/tools/generate_abstract_syntax.py.
#pragma once
#include <sysml/model/Representation.h>
#include <sysml/model/Forward.h>
#include <sysml/model/KerMLTypes.h>
#include <sysml/usage/Usage.h>

namespace SysMLv2::Entities {
class SYSML_EXPORT ReferenceUsage : public virtual Usage, public virtual Representation {
public:
    ReferenceUsage();
    ~ReferenceUsage() override;
    std::string_view metaclassName() const noexcept override;
    std::vector<RepresentationIssue> validateRepresentation(bool includeDerived = false) const override;
    /// Derived view.
    bool isReference() const;
private:
};
}
