// Generated by sysml/tools/generate_abstract_syntax.py.
#pragma once
#include <sysml/model/Representation.h>
#include <sysml/model/Forward.h>
#include <sysml/model/KerMLTypes.h>

namespace SysMLv2::Entities {
class SYSML_EXPORT Usage : public virtual KerML::Entities::Feature, public virtual Representation {
public:
    Usage();
    ~Usage() override;
    std::string_view metaclassName() const noexcept override;
    std::vector<RepresentationIssue> validateRepresentation(bool includeDerived = false) const override;
    /// Derived snapshot; populated by a semantic evaluator or importer.
    bool mayTimeVary() const;
    void setMayTimeVary(bool value);
    /// Derived view.
    bool isReference() const;
    /// Derived view.
    std::vector<std::shared_ptr<Usage>> variant() const;
    /// Derived view.
    std::vector<std::shared_ptr<VariantMembership>> variantMembership() const;
    /// Derived view.
    std::shared_ptr<Definition> owningDefinition() const;
    /// Derived view.
    std::shared_ptr<Usage> owningUsage() const;
    /// Derived view.
    std::vector<std::shared_ptr<KerML::Entities::Classifier>> definition() const;
    /// Derived view.
    std::vector<std::shared_ptr<Usage>> usage() const;
    /// Derived view.
    std::vector<std::shared_ptr<Usage>> directedUsage() const;
    /// Derived view.
    std::vector<std::shared_ptr<Usage>> nestedUsage() const;
    /// Derived view.
    std::vector<std::shared_ptr<ReferenceUsage>> nestedReference() const;
    /// Derived view.
    std::vector<std::shared_ptr<AttributeUsage>> nestedAttribute() const;
    /// Derived view.
    std::vector<std::shared_ptr<EnumerationUsage>> nestedEnumeration() const;
    /// Derived view.
    std::vector<std::shared_ptr<OccurrenceUsage>> nestedOccurrence() const;
    /// Derived view.
    std::vector<std::shared_ptr<ItemUsage>> nestedItem() const;
    /// Derived view.
    std::vector<std::shared_ptr<PartUsage>> nestedPart() const;
    /// Derived view.
    std::vector<std::shared_ptr<PortUsage>> nestedPort() const;
    /// Derived view.
    std::vector<std::shared_ptr<ConnectorAsUsage>> nestedConnection() const;
    /// Derived view.
    std::vector<std::shared_ptr<FlowUsage>> nestedFlow() const;
    /// Derived view.
    std::vector<std::shared_ptr<InterfaceUsage>> nestedInterface() const;
    /// Derived view.
    std::vector<std::shared_ptr<AllocationUsage>> nestedAllocation() const;
    /// Derived view.
    std::vector<std::shared_ptr<ActionUsage>> nestedAction() const;
    /// Derived view.
    std::vector<std::shared_ptr<StateUsage>> nestedState() const;
    /// Derived view.
    std::vector<std::shared_ptr<TransitionUsage>> nestedTransition() const;
    /// Derived view.
    std::vector<std::shared_ptr<CalculationUsage>> nestedCalculation() const;
    /// Derived view.
    std::vector<std::shared_ptr<ConstraintUsage>> nestedConstraint() const;
    /// Derived view.
    std::vector<std::shared_ptr<RequirementUsage>> nestedRequirement() const;
    /// Derived view.
    std::vector<std::shared_ptr<ConcernUsage>> nestedConcern() const;
    /// Derived view.
    std::vector<std::shared_ptr<CaseUsage>> nestedCase() const;
    /// Derived view.
    std::vector<std::shared_ptr<AnalysisCaseUsage>> nestedAnalysisCase() const;
    /// Derived view.
    std::vector<std::shared_ptr<VerificationCaseUsage>> nestedVerificationCase() const;
    /// Derived view.
    std::vector<std::shared_ptr<UseCaseUsage>> nestedUseCase() const;
    /// Derived view.
    std::vector<std::shared_ptr<ViewUsage>> nestedView() const;
    /// Derived view.
    std::vector<std::shared_ptr<ViewpointUsage>> nestedViewpoint() const;
    /// Derived view.
    std::vector<std::shared_ptr<RenderingUsage>> nestedRendering() const;
    /// Derived view.
    std::vector<std::shared_ptr<MetadataUsage>> nestedMetadata() const;
    /// Stored metamodel property.
    bool isVariation() const;
    void setIsVariation(bool value);
private:
    bool mayTimeVary_ = {};
    bool isVariation_ = {};
};
}
