// Generated by sysml/tools/generate_abstract_syntax.py.
#pragma once
#include <sysml/model/Representation.h>
#include <sysml/model/Forward.h>
#include <sysml/model/KerMLTypes.h>
#include <sysml/usecases/UseCaseUsage.h>
#include <sysml/actions/PerformActionUsage.h>

namespace SysMLv2::Entities {
class SYSML_EXPORT IncludeUseCaseUsage : public virtual UseCaseUsage, public virtual PerformActionUsage, public virtual Representation {
public:
    IncludeUseCaseUsage();
    ~IncludeUseCaseUsage() override;
    std::string_view metaclassName() const noexcept override;
    std::vector<RepresentationIssue> validateRepresentation(bool includeDerived = false) const override;
    /// Derived snapshot; populated by a semantic evaluator or importer.
    std::shared_ptr<UseCaseUsage> useCaseIncluded() const;
    void setUseCaseIncluded(std::shared_ptr<UseCaseUsage> value);
private:
    std::shared_ptr<UseCaseUsage> useCaseIncluded_ = {};
};
}
