// Generated by sysml/tools/generate_abstract_syntax.py.
#pragma once
#include <sysml/model/Representation.h>
#include <sysml/model/Forward.h>
#include <sysml/model/KerMLTypes.h>
#include <sysml/cases/CaseUsage.h>

namespace SysMLv2::Entities {
class SYSML_EXPORT UseCaseUsage : public virtual CaseUsage, public virtual Representation {
public:
    UseCaseUsage();
    ~UseCaseUsage() override;
    std::string_view metaclassName() const noexcept override;
    std::vector<RepresentationIssue> validateRepresentation(bool includeDerived = false) const override;
    /// Derived snapshot; populated by a semantic evaluator or importer.
    std::shared_ptr<UseCaseDefinition> useCaseDefinition() const;
    void setUseCaseDefinition(std::shared_ptr<UseCaseDefinition> value);
    /// Derived snapshot; populated by a semantic evaluator or importer.
    std::vector<std::shared_ptr<UseCaseUsage>> includedUseCase() const;
    void setIncludedUseCase(std::vector<std::shared_ptr<UseCaseUsage>> value);
    void appendIncludedUseCase(std::shared_ptr<UseCaseUsage> value);
private:
    std::shared_ptr<UseCaseDefinition> useCaseDefinition_ = {};
    std::vector<std::shared_ptr<UseCaseUsage>> includedUseCase_ = {};
};
}
