.TH "conanfile.CPPSysMLRecipe" 3 "Version 1.0 Beta 2" "SysMLv2 C++ Implementation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
conanfile.CPPSysMLRecipe
.SH SYNOPSIS
.br
.PP
.PP
Inherits ConanFile\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBrequirements\fP (self)"
.br
.ti -1c
.RI "\fBconfig_options\fP (self)"
.br
.ti -1c
.RI "\fBconfigure\fP (self)"
.br
.ti -1c
.RI "\fBlayout\fP (self)"
.br
.ti -1c
.RI "\fBgenerate\fP (self)"
.br
.ti -1c
.RI "\fBbuild\fP (self)"
.br
.ti -1c
.RI "\fBbuild_requirements\fP (self)"
.br
.ti -1c
.RI "\fBtest\fP (self)"
.br
.ti -1c
.RI "\fBpackage\fP (self)"
.br
.ti -1c
.RI "\fBpackage_info\fP (self)"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "str \fBname\fP = 'sysmllib'"
.br
.ti -1c
.RI "str \fBpackage_type\fP = 'library'"
.br
.ti -1c
.RI "str \fBlicense\fP = '<Put the package license here>'"
.br
.ti -1c
.RI "str \fBauthor\fP = 'Moritz Herzog'"
.br
.ti -1c
.RI "str \fBurl\fP = 'https://github\&.com/Protestator\-Research/CPP\-SysMLv2'"
.br
.ti -1c
.RI "tuple \fBdescription\fP = ('This library defines a SysMLv2 C++ Library allowing the usage of this for other projects\&.')"
.br
.ti -1c
.RI "tuple \fBtopics\fP = ('SysMLv2', 'modeling', 'library')"
.br
.ti -1c
.RI "str \fBsettings\fP = 'os', 'compiler', 'build_type', 'arch'"
.br
.ti -1c
.RI "dict \fBoptions\fP = {'shared': [True, False], 'fPIC': [True, False], 'with_rest': [True, False], 'with_services':[True, False], 'with_parsing':[True,False]}"
.br
.ti -1c
.RI "dict \fBdefault_options\fP = {'shared': True, 'fPIC': False, 'with_rest': True, 'with_services': True, 'with_parsing': True}"
.br
.ti -1c
.RI "str \fBexports_sources\fP = 'CMakeLists\&.txt', 'interfaces/*', 'conformance\-test/*', 'filehandling/*', 'kerml/*', 'rest\-api/*', 'services/*'"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for SysMLv2 C++ Implementation from the source code\&.
