.TH "HTTP_RETURN_CODES" 3 "Version 1.0 Beta 2" "SysMLv2 C++ Implementation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HTTP_RETURN_CODES
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <HttpReturnCodes\&.h>\fP
.SH "Detailed Description"
.PP 
This enum represents a human readable version of the HTTP return codes\&. HTTP Version 1\&.1

.PP
\fBAuthor\fP
.RS 4
Moritz Herzog herzogm@rptu.de 
.RE
.PP
\fBVersion\fP
.RS 4
1\&.0 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for SysMLv2 C++ Implementation from the source code\&.
