.TH "IExternalRelationShipService" 3 "Version 1.0 Beta 2" "SysMLv2 C++ Implementation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IExternalRelationShipService
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <IExternalReleationshipService\&.h>\fP
.SH "Detailed Description"
.PP 
This class represents an interface definition of the ExternalRelationshipService according to the \fBSysMLv2\fP Standard Version: 1\&.0 Beta 3\&. 
.PP
\fBVersion\fP
.RS 4
1\&.0 Beta 3 
.RE
.PP
\fBAuthor\fP
.RS 4
Moritz Herzog 
.RE
.PP
\fBSee also\fP
.RS 4
\fBSysMLv2::Entities::Project\fP 

.PP
\fBSysMLv2::Entities::Commit\fP 

.PP
\fBSysMLv2::Entities::Branch\fP 

.PP
\fBSysMLv2::Entities::ExternalRelationship\fP 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for SysMLv2 C++ Implementation from the source code\&.
