.TH "KerMLParser::Type_featuringContext" 3 "Version 1.0 Beta 2" "SysMLv2 C++ Implementation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KerMLParser::Type_featuringContext
.SH SYNOPSIS
.br
.PP
.PP
Inherits antlr4::ParserRuleContext\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBType_featuringContext\fP (antlr4::ParserRuleContext *parent, size_t invokingState)"
.br
.ti -1c
.RI "virtual size_t \fBgetRuleIndex\fP () const override"
.br
.ti -1c
.RI "antlr4::tree::TerminalNode * \fBKEYWORD_FEATURING\fP ()"
.br
.ti -1c
.RI "std::vector< \fBQualified_nameContext\fP * > \fBqualified_name\fP ()"
.br
.ti -1c
.RI "\fBQualified_nameContext\fP * \fBqualified_name\fP (size_t i)"
.br
.ti -1c
.RI "antlr4::tree::TerminalNode * \fBKEYWORD_BY\fP ()"
.br
.ti -1c
.RI "\fBRelationship_bodyContext\fP * \fBrelationship_body\fP ()"
.br
.ti -1c
.RI "\fBIdentificationContext\fP * \fBidentification\fP ()"
.br
.ti -1c
.RI "antlr4::tree::TerminalNode * \fBKEYWORD_OF\fP ()"
.br
.ti -1c
.RI "virtual void \fBenterRule\fP (antlr4::tree::ParseTreeListener *listener) override"
.br
.ti -1c
.RI "virtual void \fBexitRule\fP (antlr4::tree::ParseTreeListener *listener) override"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for SysMLv2 C++ Implementation from the source code\&.
