.TH "KerMLError" 3 "Version 1.0 Beta 2" "SysMLv2 C++ Implementation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KerMLError
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBKerMLError\fP (KerMLErrorType errorType, int line, int postionInLine, std::string message)"
.br
.ti -1c
.RI "std::string \fBmessage\fP ()"
.br
.ti -1c
.RI "int \fBline\fP ()"
.br
.ti -1c
.RI "int \fBpositionInLine\fP ()"
.br
.ti -1c
.RI "KerMLErrorType \fBerrorType\fP ()"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "KerMLErrorType \fBErrorType\fP"
.br
.ti -1c
.RI "std::string \fBErrorMessage\fP"
.br
.ti -1c
.RI "int \fBLine\fP"
.br
.ti -1c
.RI "int \fBPositionInLine\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for SysMLv2 C++ Implementation from the source code\&.
