.TH "KerML::Entities::FeatureMembership" 3 "Version 1.0 Beta 2" "SysMLv2 C++ Implementation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KerML::Entities::FeatureMembership
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBKerML::Entities::EndFeatureMembership\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SysMLv2 C++ Implementation from the source code\&.
