.TH "KerMLListener" 3 "Version 1.0 Beta 2" "SysMLv2 C++ Implementation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KerMLListener
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <KerMLListener\&.h>\fP
.PP
Inherits antlr4::tree::ParseTreeListener\&.
.PP
Inherited by \fBKerMLBaseListener\fP, and \fBKerMLListenerImplementation\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBenterStart\fP (\fBKerMLParser::StartContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBexitStart\fP (\fBKerMLParser::StartContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBenterStartRule\fP (\fBKerMLParser::StartRuleContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBexitStartRule\fP (\fBKerMLParser::StartRuleContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBenterElements\fP (\fBKerMLParser::ElementsContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBexitElements\fP (\fBKerMLParser::ElementsContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBenterIdentification\fP (\fBKerMLParser::IdentificationContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBexitIdentification\fP (\fBKerMLParser::IdentificationContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBenterRelationship_body\fP (\fBKerMLParser::Relationship_bodyContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBexitRelationship_body\fP (\fBKerMLParser::Relationship_bodyContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBenterRelationship_onwed_elements\fP (\fBKerMLParser::Relationship_onwed_elementsContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBexitRelationship_onwed_elements\fP (\fBKerMLParser::Relationship_onwed_elementsContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBenterRelationship_owned_element\fP (\fBKerMLParser::Relationship_owned_elementContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBexitRelationship_owned_element\fP (\fBKerMLParser::Relationship_owned_elementContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBenterOwned_related_element\fP (\fBKerMLParser::Owned_related_elementContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBexitOwned_related_element\fP (\fBKerMLParser::Owned_related_elementContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBenterDependency\fP (\fBKerMLParser::DependencyContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBexitDependency\fP (\fBKerMLParser::DependencyContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBenterAnnotation\fP (\fBKerMLParser::AnnotationContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBexitAnnotation\fP (\fBKerMLParser::AnnotationContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBenterOwned_annotation\fP (\fBKerMLParser::Owned_annotationContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBexitOwned_annotation\fP (\fBKerMLParser::Owned_annotationContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBenterAnnotating_element\fP (\fBKerMLParser::Annotating_elementContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBexitAnnotating_element\fP (\fBKerMLParser::Annotating_elementContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBenterComment\fP (\fBKerMLParser::CommentContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBexitComment\fP (\fBKerMLParser::CommentContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBenterDocumentation\fP (\fBKerMLParser::DocumentationContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBexitDocumentation\fP (\fBKerMLParser::DocumentationContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBenterTextual_representation\fP (\fBKerMLParser::Textual_representationContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBexitTextual_representation\fP (\fBKerMLParser::Textual_representationContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBenterRoot_namespace\fP (\fBKerMLParser::Root_namespaceContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBexitRoot_namespace\fP (\fBKerMLParser::Root_namespaceContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBenterNamespace\fP (\fBKerMLParser::NamespaceContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBexitNamespace\fP (\fBKerMLParser::NamespaceContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBenterNamespace_declaration\fP (\fBKerMLParser::Namespace_declarationContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBexitNamespace_declaration\fP (\fBKerMLParser::Namespace_declarationContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBenterNamespace_body\fP (\fBKerMLParser::Namespace_bodyContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBexitNamespace_body\fP (\fBKerMLParser::Namespace_bodyContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBenterNamespace_body_elements\fP (\fBKerMLParser::Namespace_body_elementsContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBexitNamespace_body_elements\fP (\fBKerMLParser::Namespace_body_elementsContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBenterNamespace_body_element\fP (\fBKerMLParser::Namespace_body_elementContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBexitNamespace_body_element\fP (\fBKerMLParser::Namespace_body_elementContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBenterMember_prefix\fP (\fBKerMLParser::Member_prefixContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBexitMember_prefix\fP (\fBKerMLParser::Member_prefixContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBenterVisibility_indicator\fP (\fBKerMLParser::Visibility_indicatorContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBexitVisibility_indicator\fP (\fBKerMLParser::Visibility_indicatorContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBenterNamespace_member\fP (\fBKerMLParser::Namespace_memberContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBexitNamespace_member\fP (\fBKerMLParser::Namespace_memberContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBenterNon_feature_member\fP (\fBKerMLParser::Non_feature_memberContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBexitNon_feature_member\fP (\fBKerMLParser::Non_feature_memberContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBenterNamespace_feature_member\fP (\fBKerMLParser::Namespace_feature_memberContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBexitNamespace_feature_member\fP (\fBKerMLParser::Namespace_feature_memberContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBenterAlias_member\fP (\fBKerMLParser::Alias_memberContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBexitAlias_member\fP (\fBKerMLParser::Alias_memberContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBenterQualified_name\fP (\fBKerMLParser::Qualified_nameContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBexitQualified_name\fP (\fBKerMLParser::Qualified_nameContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBenterNamespace_import\fP (\fBKerMLParser::Namespace_importContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBexitNamespace_import\fP (\fBKerMLParser::Namespace_importContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBenterImport_declaration\fP (\fBKerMLParser::Import_declarationContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBexitImport_declaration\fP (\fBKerMLParser::Import_declarationContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBenterMembership_import\fP (\fBKerMLParser::Membership_importContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBexitMembership_import\fP (\fBKerMLParser::Membership_importContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBenterFilter_package\fP (\fBKerMLParser::Filter_packageContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBexitFilter_package\fP (\fBKerMLParser::Filter_packageContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBenterFilter_package_member\fP (\fBKerMLParser::Filter_package_memberContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBexitFilter_package_member\fP (\fBKerMLParser::Filter_package_memberContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBenterElement\fP (\fBKerMLParser::ElementContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBexitElement\fP (\fBKerMLParser::ElementContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBenterNon_feature_element\fP (\fBKerMLParser::Non_feature_elementContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBexitNon_feature_element\fP (\fBKerMLParser::Non_feature_elementContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBenterFeature_element\fP (\fBKerMLParser::Feature_elementContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBexitFeature_element\fP (\fBKerMLParser::Feature_elementContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBenterAdditional_options\fP (\fBKerMLParser::Additional_optionsContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBexitAdditional_options\fP (\fBKerMLParser::Additional_optionsContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBenterType\fP (\fBKerMLParser::TypeContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBexitType\fP (\fBKerMLParser::TypeContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBenterType_prefix\fP (\fBKerMLParser::Type_prefixContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBexitType_prefix\fP (\fBKerMLParser::Type_prefixContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBenterType_declaration\fP (\fBKerMLParser::Type_declarationContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBexitType_declaration\fP (\fBKerMLParser::Type_declarationContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBenterSpecialization_part\fP (\fBKerMLParser::Specialization_partContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBexitSpecialization_part\fP (\fBKerMLParser::Specialization_partContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBenterConjugation_part\fP (\fBKerMLParser::Conjugation_partContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBexitConjugation_part\fP (\fBKerMLParser::Conjugation_partContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBenterType_relationship_part\fP (\fBKerMLParser::Type_relationship_partContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBexitType_relationship_part\fP (\fBKerMLParser::Type_relationship_partContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBenterDisjoining_part\fP (\fBKerMLParser::Disjoining_partContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBexitDisjoining_part\fP (\fBKerMLParser::Disjoining_partContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBenterUnioning_part\fP (\fBKerMLParser::Unioning_partContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBexitUnioning_part\fP (\fBKerMLParser::Unioning_partContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBenterIntersecting_part\fP (\fBKerMLParser::Intersecting_partContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBexitIntersecting_part\fP (\fBKerMLParser::Intersecting_partContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBenterDifferencing_part\fP (\fBKerMLParser::Differencing_partContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBexitDifferencing_part\fP (\fBKerMLParser::Differencing_partContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBenterType_body\fP (\fBKerMLParser::Type_bodyContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBexitType_body\fP (\fBKerMLParser::Type_bodyContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBenterType_body_elements\fP (\fBKerMLParser::Type_body_elementsContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBexitType_body_elements\fP (\fBKerMLParser::Type_body_elementsContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBenterType_body_element\fP (\fBKerMLParser::Type_body_elementContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBexitType_body_element\fP (\fBKerMLParser::Type_body_elementContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBenterSpecialization\fP (\fBKerMLParser::SpecializationContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBexitSpecialization\fP (\fBKerMLParser::SpecializationContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBenterOwned_specialization\fP (\fBKerMLParser::Owned_specializationContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBexitOwned_specialization\fP (\fBKerMLParser::Owned_specializationContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBenterSpecific_type\fP (\fBKerMLParser::Specific_typeContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBexitSpecific_type\fP (\fBKerMLParser::Specific_typeContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBenterGeneral_type\fP (\fBKerMLParser::General_typeContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBexitGeneral_type\fP (\fBKerMLParser::General_typeContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBenterConjunction\fP (\fBKerMLParser::ConjunctionContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBexitConjunction\fP (\fBKerMLParser::ConjunctionContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBenterOwned_conjugation\fP (\fBKerMLParser::Owned_conjugationContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBexitOwned_conjugation\fP (\fBKerMLParser::Owned_conjugationContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBenterDisjoining\fP (\fBKerMLParser::DisjoiningContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBexitDisjoining\fP (\fBKerMLParser::DisjoiningContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBenterOwned_disjoining\fP (\fBKerMLParser::Owned_disjoiningContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBexitOwned_disjoining\fP (\fBKerMLParser::Owned_disjoiningContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBenterUnioning\fP (\fBKerMLParser::UnioningContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBexitUnioning\fP (\fBKerMLParser::UnioningContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBenterIntersecting\fP (\fBKerMLParser::IntersectingContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBexitIntersecting\fP (\fBKerMLParser::IntersectingContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBenterDifferencing\fP (\fBKerMLParser::DifferencingContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBexitDifferencing\fP (\fBKerMLParser::DifferencingContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBenterFeature_member\fP (\fBKerMLParser::Feature_memberContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBexitFeature_member\fP (\fBKerMLParser::Feature_memberContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBenterType_feature_member\fP (\fBKerMLParser::Type_feature_memberContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBexitType_feature_member\fP (\fBKerMLParser::Type_feature_memberContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBenterOwned_feature_member\fP (\fBKerMLParser::Owned_feature_memberContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBexitOwned_feature_member\fP (\fBKerMLParser::Owned_feature_memberContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBenterClassifier\fP (\fBKerMLParser::ClassifierContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBexitClassifier\fP (\fBKerMLParser::ClassifierContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBenterClassifier_declaration\fP (\fBKerMLParser::Classifier_declarationContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBexitClassifier_declaration\fP (\fBKerMLParser::Classifier_declarationContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBenterSuperclassing_part\fP (\fBKerMLParser::Superclassing_partContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBexitSuperclassing_part\fP (\fBKerMLParser::Superclassing_partContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBenterSubclassification\fP (\fBKerMLParser::SubclassificationContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBexitSubclassification\fP (\fBKerMLParser::SubclassificationContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBenterOwned_subclassification\fP (\fBKerMLParser::Owned_subclassificationContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBexitOwned_subclassification\fP (\fBKerMLParser::Owned_subclassificationContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBenterFeature\fP (\fBKerMLParser::FeatureContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBexitFeature\fP (\fBKerMLParser::FeatureContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBenterFeature_prefix\fP (\fBKerMLParser::Feature_prefixContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBexitFeature_prefix\fP (\fBKerMLParser::Feature_prefixContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBenterFeature_direction\fP (\fBKerMLParser::Feature_directionContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBexitFeature_direction\fP (\fBKerMLParser::Feature_directionContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBenterFeature_declaration\fP (\fBKerMLParser::Feature_declarationContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBexitFeature_declaration\fP (\fBKerMLParser::Feature_declarationContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBenterFeature_identification\fP (\fBKerMLParser::Feature_identificationContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBexitFeature_identification\fP (\fBKerMLParser::Feature_identificationContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBenterFeature_relationship_part\fP (\fBKerMLParser::Feature_relationship_partContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBexitFeature_relationship_part\fP (\fBKerMLParser::Feature_relationship_partContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBenterChaining_part\fP (\fBKerMLParser::Chaining_partContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBexitChaining_part\fP (\fBKerMLParser::Chaining_partContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBenterInverting_part\fP (\fBKerMLParser::Inverting_partContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBexitInverting_part\fP (\fBKerMLParser::Inverting_partContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBenterType_featuring_part\fP (\fBKerMLParser::Type_featuring_partContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBexitType_featuring_part\fP (\fBKerMLParser::Type_featuring_partContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBenterFeature_specialization_part\fP (\fBKerMLParser::Feature_specialization_partContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBexitFeature_specialization_part\fP (\fBKerMLParser::Feature_specialization_partContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBenterMultiplicity_part\fP (\fBKerMLParser::Multiplicity_partContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBexitMultiplicity_part\fP (\fBKerMLParser::Multiplicity_partContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBenterFeature_specilization\fP (\fBKerMLParser::Feature_specilizationContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBexitFeature_specilization\fP (\fBKerMLParser::Feature_specilizationContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBenterTypings\fP (\fBKerMLParser::TypingsContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBexitTypings\fP (\fBKerMLParser::TypingsContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBenterTyped_by\fP (\fBKerMLParser::Typed_byContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBexitTyped_by\fP (\fBKerMLParser::Typed_byContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBenterSubsettings\fP (\fBKerMLParser::SubsettingsContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBexitSubsettings\fP (\fBKerMLParser::SubsettingsContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBenterSubsets\fP (\fBKerMLParser::SubsetsContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBexitSubsets\fP (\fBKerMLParser::SubsetsContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBenterReferences\fP (\fBKerMLParser::ReferencesContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBexitReferences\fP (\fBKerMLParser::ReferencesContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBenterRedefinitions\fP (\fBKerMLParser::RedefinitionsContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBexitRedefinitions\fP (\fBKerMLParser::RedefinitionsContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBenterRedefines\fP (\fBKerMLParser::RedefinesContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBexitRedefines\fP (\fBKerMLParser::RedefinesContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBenterFeature_typing\fP (\fBKerMLParser::Feature_typingContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBexitFeature_typing\fP (\fBKerMLParser::Feature_typingContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBenterOwned_feature_typing\fP (\fBKerMLParser::Owned_feature_typingContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBexitOwned_feature_typing\fP (\fBKerMLParser::Owned_feature_typingContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBenterSubsetting\fP (\fBKerMLParser::SubsettingContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBexitSubsetting\fP (\fBKerMLParser::SubsettingContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBenterOwned_subsetting\fP (\fBKerMLParser::Owned_subsettingContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBexitOwned_subsetting\fP (\fBKerMLParser::Owned_subsettingContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBenterOwned_reference_subsetting\fP (\fBKerMLParser::Owned_reference_subsettingContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBexitOwned_reference_subsetting\fP (\fBKerMLParser::Owned_reference_subsettingContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBenterRedefinition\fP (\fBKerMLParser::RedefinitionContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBexitRedefinition\fP (\fBKerMLParser::RedefinitionContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBenterOwned_redefinition\fP (\fBKerMLParser::Owned_redefinitionContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBexitOwned_redefinition\fP (\fBKerMLParser::Owned_redefinitionContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBenterOwned_feature_chain\fP (\fBKerMLParser::Owned_feature_chainContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBexitOwned_feature_chain\fP (\fBKerMLParser::Owned_feature_chainContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBenterFeature_chain\fP (\fBKerMLParser::Feature_chainContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBexitFeature_chain\fP (\fBKerMLParser::Feature_chainContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBenterOwned_feature_chaining\fP (\fBKerMLParser::Owned_feature_chainingContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBexitOwned_feature_chaining\fP (\fBKerMLParser::Owned_feature_chainingContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBenterFeature_inverting\fP (\fBKerMLParser::Feature_invertingContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBexitFeature_inverting\fP (\fBKerMLParser::Feature_invertingContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBenterOwned_feature_inverting\fP (\fBKerMLParser::Owned_feature_invertingContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBexitOwned_feature_inverting\fP (\fBKerMLParser::Owned_feature_invertingContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBenterType_featuring\fP (\fBKerMLParser::Type_featuringContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBexitType_featuring\fP (\fBKerMLParser::Type_featuringContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBenterOwned_type_featuring\fP (\fBKerMLParser::Owned_type_featuringContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBexitOwned_type_featuring\fP (\fBKerMLParser::Owned_type_featuringContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBenterData_type\fP (\fBKerMLParser::Data_typeContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBexitData_type\fP (\fBKerMLParser::Data_typeContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBenterClass\fP (\fBKerMLParser::ClassContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBexitClass\fP (\fBKerMLParser::ClassContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBenterStructure\fP (\fBKerMLParser::StructureContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBexitStructure\fP (\fBKerMLParser::StructureContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBenterAssociation\fP (\fBKerMLParser::AssociationContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBexitAssociation\fP (\fBKerMLParser::AssociationContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBenterAssociation_structure\fP (\fBKerMLParser::Association_structureContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBexitAssociation_structure\fP (\fBKerMLParser::Association_structureContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBenterConnector\fP (\fBKerMLParser::ConnectorContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBexitConnector\fP (\fBKerMLParser::ConnectorContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBenterConnector_declaration\fP (\fBKerMLParser::Connector_declarationContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBexitConnector_declaration\fP (\fBKerMLParser::Connector_declarationContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBenterBinary_connector_declaration\fP (\fBKerMLParser::Binary_connector_declarationContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBexitBinary_connector_declaration\fP (\fBKerMLParser::Binary_connector_declarationContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBenterNary_connector_declaration\fP (\fBKerMLParser::Nary_connector_declarationContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBexitNary_connector_declaration\fP (\fBKerMLParser::Nary_connector_declarationContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBenterConnector_end_member\fP (\fBKerMLParser::Connector_end_memberContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBexitConnector_end_member\fP (\fBKerMLParser::Connector_end_memberContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBenterConnector_end\fP (\fBKerMLParser::Connector_endContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBexitConnector_end\fP (\fBKerMLParser::Connector_endContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBenterBinding_connector\fP (\fBKerMLParser::Binding_connectorContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBexitBinding_connector\fP (\fBKerMLParser::Binding_connectorContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBenterBinding_connector_declaration\fP (\fBKerMLParser::Binding_connector_declarationContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBexitBinding_connector_declaration\fP (\fBKerMLParser::Binding_connector_declarationContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBenterSuccession\fP (\fBKerMLParser::SuccessionContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBexitSuccession\fP (\fBKerMLParser::SuccessionContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBenterSuccession_declaration\fP (\fBKerMLParser::Succession_declarationContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBexitSuccession_declaration\fP (\fBKerMLParser::Succession_declarationContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBenterBehavior\fP (\fBKerMLParser::BehaviorContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBexitBehavior\fP (\fBKerMLParser::BehaviorContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBenterStep\fP (\fBKerMLParser::StepContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBexitStep\fP (\fBKerMLParser::StepContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBenterFunction\fP (\fBKerMLParser::FunctionContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBexitFunction\fP (\fBKerMLParser::FunctionContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBenterFunction_body\fP (\fBKerMLParser::Function_bodyContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBexitFunction_body\fP (\fBKerMLParser::Function_bodyContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBenterFunction_body_part\fP (\fBKerMLParser::Function_body_partContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBexitFunction_body_part\fP (\fBKerMLParser::Function_body_partContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBenterReturn_feature_member\fP (\fBKerMLParser::Return_feature_memberContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBexitReturn_feature_member\fP (\fBKerMLParser::Return_feature_memberContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBenterResult_expression_member\fP (\fBKerMLParser::Result_expression_memberContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBexitResult_expression_member\fP (\fBKerMLParser::Result_expression_memberContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBenterExpression\fP (\fBKerMLParser::ExpressionContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBexitExpression\fP (\fBKerMLParser::ExpressionContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBenterPredicate\fP (\fBKerMLParser::PredicateContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBexitPredicate\fP (\fBKerMLParser::PredicateContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBenterBoolean_expression\fP (\fBKerMLParser::Boolean_expressionContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBexitBoolean_expression\fP (\fBKerMLParser::Boolean_expressionContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBenterInvariant\fP (\fBKerMLParser::InvariantContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBexitInvariant\fP (\fBKerMLParser::InvariantContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBenterOwned_expression_reference_member\fP (\fBKerMLParser::Owned_expression_reference_memberContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBexitOwned_expression_reference_member\fP (\fBKerMLParser::Owned_expression_reference_memberContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBenterOwned_expression_reference\fP (\fBKerMLParser::Owned_expression_referenceContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBexitOwned_expression_reference\fP (\fBKerMLParser::Owned_expression_referenceContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBenterOwned_expression_member\fP (\fBKerMLParser::Owned_expression_memberContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBexitOwned_expression_member\fP (\fBKerMLParser::Owned_expression_memberContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBenterOwned_expressions\fP (\fBKerMLParser::Owned_expressionsContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBexitOwned_expressions\fP (\fBKerMLParser::Owned_expressionsContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBenterOwned_expression\fP (\fBKerMLParser::Owned_expressionContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBexitOwned_expression\fP (\fBKerMLParser::Owned_expressionContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBenterEased_owned_expression\fP (\fBKerMLParser::Eased_owned_expressionContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBexitEased_owned_expression\fP (\fBKerMLParser::Eased_owned_expressionContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBenterConditional_expression\fP (\fBKerMLParser::Conditional_expressionContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBexitConditional_expression\fP (\fBKerMLParser::Conditional_expressionContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBenterConditional_binary_operator_expression\fP (\fBKerMLParser::Conditional_binary_operator_expressionContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBexitConditional_binary_operator_expression\fP (\fBKerMLParser::Conditional_binary_operator_expressionContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBenterConditional_binary_operator\fP (\fBKerMLParser::Conditional_binary_operatorContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBexitConditional_binary_operator\fP (\fBKerMLParser::Conditional_binary_operatorContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBenterBinary_operator_expression\fP (\fBKerMLParser::Binary_operator_expressionContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBexitBinary_operator_expression\fP (\fBKerMLParser::Binary_operator_expressionContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBenterBinary_operator\fP (\fBKerMLParser::Binary_operatorContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBexitBinary_operator\fP (\fBKerMLParser::Binary_operatorContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBenterUnary_operator_expression\fP (\fBKerMLParser::Unary_operator_expressionContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBexitUnary_operator_expression\fP (\fBKerMLParser::Unary_operator_expressionContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBenterUnary_operator\fP (\fBKerMLParser::Unary_operatorContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBexitUnary_operator\fP (\fBKerMLParser::Unary_operatorContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBenterClassification_expression\fP (\fBKerMLParser::Classification_expressionContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBexitClassification_expression\fP (\fBKerMLParser::Classification_expressionContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBenterClassification\fP (\fBKerMLParser::ClassificationContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBexitClassification\fP (\fBKerMLParser::ClassificationContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBenterClassification_test_operator\fP (\fBKerMLParser::Classification_test_operatorContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBexitClassification_test_operator\fP (\fBKerMLParser::Classification_test_operatorContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBenterCast_operator\fP (\fBKerMLParser::Cast_operatorContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBexitCast_operator\fP (\fBKerMLParser::Cast_operatorContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBenterMetaclassification_expression\fP (\fBKerMLParser::Metaclassification_expressionContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBexitMetaclassification_expression\fP (\fBKerMLParser::Metaclassification_expressionContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBenterArgument_member\fP (\fBKerMLParser::Argument_memberContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBexitArgument_member\fP (\fBKerMLParser::Argument_memberContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBenterArgument\fP (\fBKerMLParser::ArgumentContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBexitArgument\fP (\fBKerMLParser::ArgumentContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBenterArgument_value\fP (\fBKerMLParser::Argument_valueContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBexitArgument_value\fP (\fBKerMLParser::Argument_valueContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBenterArgument_expression_member\fP (\fBKerMLParser::Argument_expression_memberContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBexitArgument_expression_member\fP (\fBKerMLParser::Argument_expression_memberContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBenterArgument_expression\fP (\fBKerMLParser::Argument_expressionContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBexitArgument_expression\fP (\fBKerMLParser::Argument_expressionContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBenterArgument_expression_value\fP (\fBKerMLParser::Argument_expression_valueContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBexitArgument_expression_value\fP (\fBKerMLParser::Argument_expression_valueContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBenterMetadata_argument_member\fP (\fBKerMLParser::Metadata_argument_memberContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBexitMetadata_argument_member\fP (\fBKerMLParser::Metadata_argument_memberContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBenterMetadata_argument\fP (\fBKerMLParser::Metadata_argumentContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBexitMetadata_argument\fP (\fBKerMLParser::Metadata_argumentContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBenterMetadata_value\fP (\fBKerMLParser::Metadata_valueContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBexitMetadata_value\fP (\fBKerMLParser::Metadata_valueContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBenterMetadata_reference\fP (\fBKerMLParser::Metadata_referenceContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBexitMetadata_reference\fP (\fBKerMLParser::Metadata_referenceContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBenterMetadataclassification_test_operator\fP (\fBKerMLParser::Metadataclassification_test_operatorContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBexitMetadataclassification_test_operator\fP (\fBKerMLParser::Metadataclassification_test_operatorContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBenterMeta_cast_operator\fP (\fBKerMLParser::Meta_cast_operatorContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBexitMeta_cast_operator\fP (\fBKerMLParser::Meta_cast_operatorContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBenterExtend_expression\fP (\fBKerMLParser::Extend_expressionContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBexitExtend_expression\fP (\fBKerMLParser::Extend_expressionContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBenterType_reference_member\fP (\fBKerMLParser::Type_reference_memberContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBexitType_reference_member\fP (\fBKerMLParser::Type_reference_memberContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBenterType_result_member\fP (\fBKerMLParser::Type_result_memberContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBexitType_result_member\fP (\fBKerMLParser::Type_result_memberContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBenterType_reference\fP (\fBKerMLParser::Type_referenceContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBexitType_reference\fP (\fBKerMLParser::Type_referenceContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBenterReference_typing\fP (\fBKerMLParser::Reference_typingContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBexitReference_typing\fP (\fBKerMLParser::Reference_typingContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBenterPrimary_expressions\fP (\fBKerMLParser::Primary_expressionsContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBexitPrimary_expressions\fP (\fBKerMLParser::Primary_expressionsContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBenterPrimary_expression\fP (\fBKerMLParser::Primary_expressionContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBexitPrimary_expression\fP (\fBKerMLParser::Primary_expressionContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBenterPrimary_argument_value\fP (\fBKerMLParser::Primary_argument_valueContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBexitPrimary_argument_value\fP (\fBKerMLParser::Primary_argument_valueContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBenterPrimary_argument\fP (\fBKerMLParser::Primary_argumentContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBexitPrimary_argument\fP (\fBKerMLParser::Primary_argumentContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBenterPrimary_argument_member\fP (\fBKerMLParser::Primary_argument_memberContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBexitPrimary_argument_member\fP (\fBKerMLParser::Primary_argument_memberContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBenterNon_feature_chain_primary_expression\fP (\fBKerMLParser::Non_feature_chain_primary_expressionContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBexitNon_feature_chain_primary_expression\fP (\fBKerMLParser::Non_feature_chain_primary_expressionContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBenterNon_feature_chain_primary_argument_value\fP (\fBKerMLParser::Non_feature_chain_primary_argument_valueContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBexitNon_feature_chain_primary_argument_value\fP (\fBKerMLParser::Non_feature_chain_primary_argument_valueContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBenterNon_feature_chain_primary_argument\fP (\fBKerMLParser::Non_feature_chain_primary_argumentContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBexitNon_feature_chain_primary_argument\fP (\fBKerMLParser::Non_feature_chain_primary_argumentContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBenterNon_feature_chain_primary_argument_member\fP (\fBKerMLParser::Non_feature_chain_primary_argument_memberContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBexitNon_feature_chain_primary_argument_member\fP (\fBKerMLParser::Non_feature_chain_primary_argument_memberContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBenterBracket_expression\fP (\fBKerMLParser::Bracket_expressionContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBexitBracket_expression\fP (\fBKerMLParser::Bracket_expressionContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBenterIndex_expression\fP (\fBKerMLParser::Index_expressionContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBexitIndex_expression\fP (\fBKerMLParser::Index_expressionContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBenterSequence_expression\fP (\fBKerMLParser::Sequence_expressionContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBexitSequence_expression\fP (\fBKerMLParser::Sequence_expressionContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBenterSequence_expression_list\fP (\fBKerMLParser::Sequence_expression_listContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBexitSequence_expression_list\fP (\fBKerMLParser::Sequence_expression_listContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBenterSequence_operator_expression\fP (\fBKerMLParser::Sequence_operator_expressionContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBexitSequence_operator_expression\fP (\fBKerMLParser::Sequence_operator_expressionContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBenterSequence_expression_list_member\fP (\fBKerMLParser::Sequence_expression_list_memberContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBexitSequence_expression_list_member\fP (\fBKerMLParser::Sequence_expression_list_memberContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBenterFeature_chain_expression\fP (\fBKerMLParser::Feature_chain_expressionContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBexitFeature_chain_expression\fP (\fBKerMLParser::Feature_chain_expressionContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBenterCollect_expression\fP (\fBKerMLParser::Collect_expressionContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBexitCollect_expression\fP (\fBKerMLParser::Collect_expressionContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBenterSelect_expression\fP (\fBKerMLParser::Select_expressionContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBexitSelect_expression\fP (\fBKerMLParser::Select_expressionContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBenterFunction_operation_expression\fP (\fBKerMLParser::Function_operation_expressionContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBexitFunction_operation_expression\fP (\fBKerMLParser::Function_operation_expressionContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBenterBody_argument_member\fP (\fBKerMLParser::Body_argument_memberContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBexitBody_argument_member\fP (\fBKerMLParser::Body_argument_memberContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBenterBody_argument\fP (\fBKerMLParser::Body_argumentContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBexitBody_argument\fP (\fBKerMLParser::Body_argumentContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBenterBody_argument_value\fP (\fBKerMLParser::Body_argument_valueContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBexitBody_argument_value\fP (\fBKerMLParser::Body_argument_valueContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBenterBody_expression_member\fP (\fBKerMLParser::Body_expression_memberContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBexitBody_expression_member\fP (\fBKerMLParser::Body_expression_memberContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBenterFunction_reference_argument_member\fP (\fBKerMLParser::Function_reference_argument_memberContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBexitFunction_reference_argument_member\fP (\fBKerMLParser::Function_reference_argument_memberContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBenterFunction_reference_argument\fP (\fBKerMLParser::Function_reference_argumentContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBexitFunction_reference_argument\fP (\fBKerMLParser::Function_reference_argumentContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBenterFunction_reference_arugment_value\fP (\fBKerMLParser::Function_reference_arugment_valueContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBexitFunction_reference_arugment_value\fP (\fBKerMLParser::Function_reference_arugment_valueContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBenterFunction_reference_expression\fP (\fBKerMLParser::Function_reference_expressionContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBexitFunction_reference_expression\fP (\fBKerMLParser::Function_reference_expressionContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBenterFunction_reference_member\fP (\fBKerMLParser::Function_reference_memberContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBexitFunction_reference_member\fP (\fBKerMLParser::Function_reference_memberContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBenterFunction_reference\fP (\fBKerMLParser::Function_referenceContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBexitFunction_reference\fP (\fBKerMLParser::Function_referenceContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBenterFeature_chain_member\fP (\fBKerMLParser::Feature_chain_memberContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBexitFeature_chain_member\fP (\fBKerMLParser::Feature_chain_memberContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBenterOwned_feature_chain_member\fP (\fBKerMLParser::Owned_feature_chain_memberContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBexitOwned_feature_chain_member\fP (\fBKerMLParser::Owned_feature_chain_memberContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBenterBase_expression\fP (\fBKerMLParser::Base_expressionContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBexitBase_expression\fP (\fBKerMLParser::Base_expressionContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBenterNull_expression\fP (\fBKerMLParser::Null_expressionContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBexitNull_expression\fP (\fBKerMLParser::Null_expressionContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBenterFeature_reference_expression\fP (\fBKerMLParser::Feature_reference_expressionContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBexitFeature_reference_expression\fP (\fBKerMLParser::Feature_reference_expressionContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBenterFeature_reference_member\fP (\fBKerMLParser::Feature_reference_memberContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBexitFeature_reference_member\fP (\fBKerMLParser::Feature_reference_memberContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBenterFeature_reference\fP (\fBKerMLParser::Feature_referenceContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBexitFeature_reference\fP (\fBKerMLParser::Feature_referenceContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBenterMetadata_access_expression\fP (\fBKerMLParser::Metadata_access_expressionContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBexitMetadata_access_expression\fP (\fBKerMLParser::Metadata_access_expressionContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBenterInvocation_expression\fP (\fBKerMLParser::Invocation_expressionContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBexitInvocation_expression\fP (\fBKerMLParser::Invocation_expressionContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBenterInternal_invocation_expression\fP (\fBKerMLParser::Internal_invocation_expressionContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBexitInternal_invocation_expression\fP (\fBKerMLParser::Internal_invocation_expressionContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBenterArgument_list\fP (\fBKerMLParser::Argument_listContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBexitArgument_list\fP (\fBKerMLParser::Argument_listContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBenterPositional_argument_list\fP (\fBKerMLParser::Positional_argument_listContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBexitPositional_argument_list\fP (\fBKerMLParser::Positional_argument_listContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBenterNamed_argument_list\fP (\fBKerMLParser::Named_argument_listContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBexitNamed_argument_list\fP (\fBKerMLParser::Named_argument_listContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBenterNamed_argument_member\fP (\fBKerMLParser::Named_argument_memberContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBexitNamed_argument_member\fP (\fBKerMLParser::Named_argument_memberContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBenterNamed_argument\fP (\fBKerMLParser::Named_argumentContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBexitNamed_argument\fP (\fBKerMLParser::Named_argumentContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBenterParamenter_redefinition\fP (\fBKerMLParser::Paramenter_redefinitionContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBexitParamenter_redefinition\fP (\fBKerMLParser::Paramenter_redefinitionContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBenterBody_expression\fP (\fBKerMLParser::Body_expressionContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBexitBody_expression\fP (\fBKerMLParser::Body_expressionContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBenterExpression_body_member\fP (\fBKerMLParser::Expression_body_memberContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBexitExpression_body_member\fP (\fBKerMLParser::Expression_body_memberContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBenterExpression_body\fP (\fBKerMLParser::Expression_bodyContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBexitExpression_body\fP (\fBKerMLParser::Expression_bodyContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBenterLiteral_expression\fP (\fBKerMLParser::Literal_expressionContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBexitLiteral_expression\fP (\fBKerMLParser::Literal_expressionContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBenterLiteral_boolean\fP (\fBKerMLParser::Literal_booleanContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBexitLiteral_boolean\fP (\fBKerMLParser::Literal_booleanContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBenterBoolean_value\fP (\fBKerMLParser::Boolean_valueContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBexitBoolean_value\fP (\fBKerMLParser::Boolean_valueContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBenterLiteral_string\fP (\fBKerMLParser::Literal_stringContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBexitLiteral_string\fP (\fBKerMLParser::Literal_stringContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBenterLiteral_integer\fP (\fBKerMLParser::Literal_integerContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBexitLiteral_integer\fP (\fBKerMLParser::Literal_integerContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBenterLiteral_real\fP (\fBKerMLParser::Literal_realContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBexitLiteral_real\fP (\fBKerMLParser::Literal_realContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBenterReal_value\fP (\fBKerMLParser::Real_valueContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBexitReal_value\fP (\fBKerMLParser::Real_valueContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBenterLiteral_infinity\fP (\fBKerMLParser::Literal_infinityContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBexitLiteral_infinity\fP (\fBKerMLParser::Literal_infinityContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBenterInteraction\fP (\fBKerMLParser::InteractionContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBexitInteraction\fP (\fBKerMLParser::InteractionContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBenterItem_flow\fP (\fBKerMLParser::Item_flowContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBexitItem_flow\fP (\fBKerMLParser::Item_flowContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBenterSuccession_item_flow\fP (\fBKerMLParser::Succession_item_flowContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBexitSuccession_item_flow\fP (\fBKerMLParser::Succession_item_flowContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBenterItem_flow_declaration\fP (\fBKerMLParser::Item_flow_declarationContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBexitItem_flow_declaration\fP (\fBKerMLParser::Item_flow_declarationContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBenterItem_feature_member\fP (\fBKerMLParser::Item_feature_memberContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBexitItem_feature_member\fP (\fBKerMLParser::Item_feature_memberContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBenterItem_feature\fP (\fBKerMLParser::Item_featureContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBexitItem_feature\fP (\fBKerMLParser::Item_featureContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBenterItem_feature_specilization_part\fP (\fBKerMLParser::Item_feature_specilization_partContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBexitItem_feature_specilization_part\fP (\fBKerMLParser::Item_feature_specilization_partContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBenterItem_flow_end_member\fP (\fBKerMLParser::Item_flow_end_memberContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBexitItem_flow_end_member\fP (\fBKerMLParser::Item_flow_end_memberContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBenterItem_flow_end\fP (\fBKerMLParser::Item_flow_endContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBexitItem_flow_end\fP (\fBKerMLParser::Item_flow_endContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBenterItem_flow_feature_member\fP (\fBKerMLParser::Item_flow_feature_memberContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBexitItem_flow_feature_member\fP (\fBKerMLParser::Item_flow_feature_memberContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBenterItem_flow_feature\fP (\fBKerMLParser::Item_flow_featureContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBexitItem_flow_feature\fP (\fBKerMLParser::Item_flow_featureContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBenterItem_flow_redefinition\fP (\fBKerMLParser::Item_flow_redefinitionContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBexitItem_flow_redefinition\fP (\fBKerMLParser::Item_flow_redefinitionContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBenterValue_part\fP (\fBKerMLParser::Value_partContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBexitValue_part\fP (\fBKerMLParser::Value_partContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBenterFeature_value\fP (\fBKerMLParser::Feature_valueContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBexitFeature_value\fP (\fBKerMLParser::Feature_valueContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBenterFeature_assignment\fP (\fBKerMLParser::Feature_assignmentContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBexitFeature_assignment\fP (\fBKerMLParser::Feature_assignmentContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBenterMultiplicity\fP (\fBKerMLParser::MultiplicityContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBexitMultiplicity\fP (\fBKerMLParser::MultiplicityContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBenterMultiplicity_subset\fP (\fBKerMLParser::Multiplicity_subsetContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBexitMultiplicity_subset\fP (\fBKerMLParser::Multiplicity_subsetContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBenterMultiplicity_range\fP (\fBKerMLParser::Multiplicity_rangeContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBexitMultiplicity_range\fP (\fBKerMLParser::Multiplicity_rangeContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBenterOwned_multiplicity\fP (\fBKerMLParser::Owned_multiplicityContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBexitOwned_multiplicity\fP (\fBKerMLParser::Owned_multiplicityContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBenterOwned_multiplicity_range\fP (\fBKerMLParser::Owned_multiplicity_rangeContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBexitOwned_multiplicity_range\fP (\fBKerMLParser::Owned_multiplicity_rangeContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBenterMultiplicity_bounds\fP (\fBKerMLParser::Multiplicity_boundsContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBexitMultiplicity_bounds\fP (\fBKerMLParser::Multiplicity_boundsContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBenterMultiplicity_expression_member\fP (\fBKerMLParser::Multiplicity_expression_memberContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBexitMultiplicity_expression_member\fP (\fBKerMLParser::Multiplicity_expression_memberContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBenterInternal_multiplicity_expression_member\fP (\fBKerMLParser::Internal_multiplicity_expression_memberContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBexitInternal_multiplicity_expression_member\fP (\fBKerMLParser::Internal_multiplicity_expression_memberContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBenterMetaclass\fP (\fBKerMLParser::MetaclassContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBexitMetaclass\fP (\fBKerMLParser::MetaclassContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBenterPrefix_metadata_annotation\fP (\fBKerMLParser::Prefix_metadata_annotationContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBexitPrefix_metadata_annotation\fP (\fBKerMLParser::Prefix_metadata_annotationContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBenterPrefix_metadata_member\fP (\fBKerMLParser::Prefix_metadata_memberContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBexitPrefix_metadata_member\fP (\fBKerMLParser::Prefix_metadata_memberContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBenterPrefix_metadata_feature\fP (\fBKerMLParser::Prefix_metadata_featureContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBexitPrefix_metadata_feature\fP (\fBKerMLParser::Prefix_metadata_featureContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBenterMetadata_feature\fP (\fBKerMLParser::Metadata_featureContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBexitMetadata_feature\fP (\fBKerMLParser::Metadata_featureContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBenterMetadata_feature_declaration\fP (\fBKerMLParser::Metadata_feature_declarationContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBexitMetadata_feature_declaration\fP (\fBKerMLParser::Metadata_feature_declarationContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBenterMetadata_body\fP (\fBKerMLParser::Metadata_bodyContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBexitMetadata_body\fP (\fBKerMLParser::Metadata_bodyContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBenterMetadata_body_element\fP (\fBKerMLParser::Metadata_body_elementContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBexitMetadata_body_element\fP (\fBKerMLParser::Metadata_body_elementContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBenterMetadata_body_feature_member\fP (\fBKerMLParser::Metadata_body_feature_memberContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBexitMetadata_body_feature_member\fP (\fBKerMLParser::Metadata_body_feature_memberContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBenterMetadata_body_feature\fP (\fBKerMLParser::Metadata_body_featureContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBexitMetadata_body_feature\fP (\fBKerMLParser::Metadata_body_featureContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBenterPackage\fP (\fBKerMLParser::PackageContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBexitPackage\fP (\fBKerMLParser::PackageContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBenterLibrary_package\fP (\fBKerMLParser::Library_packageContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBexitLibrary_package\fP (\fBKerMLParser::Library_packageContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBenterPackage_declaration\fP (\fBKerMLParser::Package_declarationContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBexitPackage_declaration\fP (\fBKerMLParser::Package_declarationContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBenterPackage_body\fP (\fBKerMLParser::Package_bodyContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBexitPackage_body\fP (\fBKerMLParser::Package_bodyContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBenterElement_filter_member\fP (\fBKerMLParser::Element_filter_memberContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBexitElement_filter_member\fP (\fBKerMLParser::Element_filter_memberContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBenterMeta_assignment\fP (\fBKerMLParser::Meta_assignmentContext\fP *ctx)=0"
.br
.ti -1c
.RI "virtual void \fBexitMeta_assignment\fP (\fBKerMLParser::Meta_assignmentContext\fP *ctx)=0"
.br
.in -1c
.SH "Detailed Description"
.PP 
This interface defines an abstract listener for a parse tree produced by \fBKerMLParser\fP\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for SysMLv2 C++ Implementation from the source code\&.
