.TH "KerMLParser::Non_feature_elementContext" 3 "Version 1.0 Beta 2" "SysMLv2 C++ Implementation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KerMLParser::Non_feature_elementContext
.SH SYNOPSIS
.br
.PP
.PP
Inherits antlr4::ParserRuleContext\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBNon_feature_elementContext\fP (antlr4::ParserRuleContext *parent, size_t invokingState)"
.br
.ti -1c
.RI "virtual size_t \fBgetRuleIndex\fP () const override"
.br
.ti -1c
.RI "\fBDependencyContext\fP * \fBdependency\fP ()"
.br
.ti -1c
.RI "\fBTypeContext\fP * \fBtype\fP ()"
.br
.ti -1c
.RI "\fBClassifierContext\fP * \fBclassifier\fP ()"
.br
.ti -1c
.RI "\fBData_typeContext\fP * \fBdata_type\fP ()"
.br
.ti -1c
.RI "\fBNamespaceContext\fP * \fBnamespace_\fP ()"
.br
.ti -1c
.RI "\fBClassContext\fP * \fBclass_\fP ()"
.br
.ti -1c
.RI "\fBStructureContext\fP * \fBstructure\fP ()"
.br
.ti -1c
.RI "\fBMetaclassContext\fP * \fBmetaclass\fP ()"
.br
.ti -1c
.RI "\fBAssociationContext\fP * \fBassociation\fP ()"
.br
.ti -1c
.RI "\fBAssociation_structureContext\fP * \fBassociation_structure\fP ()"
.br
.ti -1c
.RI "\fBInteractionContext\fP * \fBinteraction\fP ()"
.br
.ti -1c
.RI "\fBBehaviorContext\fP * \fBbehavior\fP ()"
.br
.ti -1c
.RI "\fBFunctionContext\fP * \fBfunction\fP ()"
.br
.ti -1c
.RI "\fBPredicateContext\fP * \fBpredicate\fP ()"
.br
.ti -1c
.RI "\fBMultiplicityContext\fP * \fBmultiplicity\fP ()"
.br
.ti -1c
.RI "\fBPackageContext\fP * \fBpackage\fP ()"
.br
.ti -1c
.RI "\fBLibrary_packageContext\fP * \fBlibrary_package\fP ()"
.br
.ti -1c
.RI "\fBSpecializationContext\fP * \fBspecialization\fP ()"
.br
.ti -1c
.RI "\fBConjunctionContext\fP * \fBconjunction\fP ()"
.br
.ti -1c
.RI "\fBSubclassificationContext\fP * \fBsubclassification\fP ()"
.br
.ti -1c
.RI "\fBDisjoiningContext\fP * \fBdisjoining\fP ()"
.br
.ti -1c
.RI "\fBFeature_invertingContext\fP * \fBfeature_inverting\fP ()"
.br
.ti -1c
.RI "\fBFeature_typingContext\fP * \fBfeature_typing\fP ()"
.br
.ti -1c
.RI "\fBSubsettingContext\fP * \fBsubsetting\fP ()"
.br
.ti -1c
.RI "\fBRedefinitionContext\fP * \fBredefinition\fP ()"
.br
.ti -1c
.RI "\fBType_featuringContext\fP * \fBtype_featuring\fP ()"
.br
.ti -1c
.RI "\fBNamespace_importContext\fP * \fBnamespace_import\fP ()"
.br
.ti -1c
.RI "virtual void \fBenterRule\fP (antlr4::tree::ParseTreeListener *listener) override"
.br
.ti -1c
.RI "virtual void \fBexitRule\fP (antlr4::tree::ParseTreeListener *listener) override"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for SysMLv2 C++ Implementation from the source code\&.
