.TH "KerML::Entities::Classifier" 3 "Version 1.0 Beta 2" "SysMLv2 C++ Implementation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KerML::Entities::Classifier
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBKerML::Entities::Association\fP, \fBKerML::Entities::Class\fP, and \fBKerML::Entities::DataType\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SysMLv2 C++ Implementation from the source code\&.
