.TH "KerMLParser::Classification_expressionContext" 3 "Version 1.0 Beta 2" "SysMLv2 C++ Implementation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KerMLParser::Classification_expressionContext
.SH SYNOPSIS
.br
.PP
.PP
Inherits antlr4::ParserRuleContext\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBClassification_expressionContext\fP (antlr4::ParserRuleContext *parent, size_t invokingState)"
.br
.ti -1c
.RI "virtual size_t \fBgetRuleIndex\fP () const override"
.br
.ti -1c
.RI "\fBArgument_memberContext\fP * \fBargument_member\fP ()"
.br
.ti -1c
.RI "\fBClassification_test_operatorContext\fP * \fBclassification_test_operator\fP ()"
.br
.ti -1c
.RI "\fBType_reference_memberContext\fP * \fBtype_reference_member\fP ()"
.br
.ti -1c
.RI "\fBCast_operatorContext\fP * \fBcast_operator\fP ()"
.br
.ti -1c
.RI "\fBType_result_memberContext\fP * \fBtype_result_member\fP ()"
.br
.ti -1c
.RI "virtual void \fBenterRule\fP (antlr4::tree::ParseTreeListener *listener) override"
.br
.ti -1c
.RI "virtual void \fBexitRule\fP (antlr4::tree::ParseTreeListener *listener) override"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for SysMLv2 C++ Implementation from the source code\&.
