.TH "KerMLParser::Literal_expressionContext" 3 "Version 1.0 Beta 2" "SysMLv2 C++ Implementation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KerMLParser::Literal_expressionContext
.SH SYNOPSIS
.br
.PP
.PP
Inherits antlr4::ParserRuleContext\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBLiteral_expressionContext\fP (antlr4::ParserRuleContext *parent, size_t invokingState)"
.br
.ti -1c
.RI "virtual size_t \fBgetRuleIndex\fP () const override"
.br
.ti -1c
.RI "antlr4::tree::TerminalNode * \fBKEYWORD_TRUE\fP ()"
.br
.ti -1c
.RI "antlr4::tree::TerminalNode * \fBKEYWORD_FALSE\fP ()"
.br
.ti -1c
.RI "\fBLiteral_stringContext\fP * \fBliteral_string\fP ()"
.br
.ti -1c
.RI "\fBLiteral_integerContext\fP * \fBliteral_integer\fP ()"
.br
.ti -1c
.RI "\fBLiteral_realContext\fP * \fBliteral_real\fP ()"
.br
.ti -1c
.RI "\fBLiteral_infinityContext\fP * \fBliteral_infinity\fP ()"
.br
.ti -1c
.RI "virtual void \fBenterRule\fP (antlr4::tree::ParseTreeListener *listener) override"
.br
.ti -1c
.RI "virtual void \fBexitRule\fP (antlr4::tree::ParseTreeListener *listener) override"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for SysMLv2 C++ Implementation from the source code\&.
