.TH "md__r_e_a_d_m_e" 3 "Version 1.0 Beta 2" "SysMLv2 C++ Implementation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md__r_e_a_d_m_e \- C++ SysML v2 Implementation 
.PP


.PP
This library gives an implementation of the SysML v2 standard and \fBKerML\fP standard\&. This allows developers to implment own applications with this library\&. The existence of this library is the proof, that SysML v2 can be implemented in C++\&.
.SH "Table of Contents"
.PP
[toc]
.SH "Build Status"
.PP
The System and Tests: \fR\fP
.SH "Licensing"
.PP
This software is licensed under the GPL v3, allowing a free and open source editing of the code\&. We want to offer you the option to use this libary also for commercial project\&. This will be done in a later step, since we are currently developing this from the ground up\&.
.SH "Building and usage"
.PP
We offer the build work flow with conan and standalone\&.
.SS "Conan Build"
One of the Todos we have is to offer this library in the conan central repositories\&. But this can be done, if the implementation is done\&. You will be informed\&.

.PP
With this build the conan file is provided, allowing you to install the dependencies and then to build the files\&.

.PP
.PP
.nf
mkdir build && cd build
conan install \&.\&.
conan build \&.\&.
.fi
.PP
.SS "Standalone Build"
Please install the dependencies required for the build:
.SS "Dependencies"
Dependency   Version    antlr4-cppruntime   4\&.13\&.1    boost   Min 1\&.83\&.0    nlohmann_json   Min 3\&.11\&.2    date   3\&.0\&.1    gtest   1\&.14\&.0   

.PP
We are working on an option to only use a part of the dependencies\&. This will be depended on the modules that are used\&.
.SS "Build"
For the build we require you to have CMake installed\&. This allows to have one implementation for all operating systems\&.

.PP
To generate the build files for your system use the following command\&.

.PP
.PP
.nf
mkdir build && cd build
cmake \&.\&.
make
.fi
.PP

.PP
For the install option use the following command install\&.

.PP
.PP
.nf
make install 
.fi
.PP
 
