.TH "SysMLv2Parser::Feature_elementContext" 3 "Version 1.0 Beta 2" "SysMLv2 C++ Implementation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SysMLv2Parser::Feature_elementContext
.SH SYNOPSIS
.br
.PP
.PP
Inherits antlr4::ParserRuleContext\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBFeature_elementContext\fP (antlr4::ParserRuleContext *parent, size_t invokingState)"
.br
.ti -1c
.RI "virtual size_t \fBgetRuleIndex\fP () const override"
.br
.ti -1c
.RI "\fBFeatureContext\fP * \fBfeature\fP ()"
.br
.ti -1c
.RI "\fBStepContext\fP * \fBstep\fP ()"
.br
.ti -1c
.RI "\fBExpressionContext\fP * \fBexpression\fP ()"
.br
.ti -1c
.RI "\fBBoolean_expressionContext\fP * \fBboolean_expression\fP ()"
.br
.ti -1c
.RI "\fBInvariantContext\fP * \fBinvariant\fP ()"
.br
.ti -1c
.RI "\fBConnectorContext\fP * \fBconnector\fP ()"
.br
.ti -1c
.RI "\fBBinding_connectorContext\fP * \fBbinding_connector\fP ()"
.br
.ti -1c
.RI "\fBSuccessionContext\fP * \fBsuccession\fP ()"
.br
.ti -1c
.RI "\fBItem_flowContext\fP * \fBitem_flow\fP ()"
.br
.ti -1c
.RI "\fBSuccession_item_flowContext\fP * \fBsuccession_item_flow\fP ()"
.br
.ti -1c
.RI "virtual void \fBenterRule\fP (antlr4::tree::ParseTreeListener *listener) override"
.br
.ti -1c
.RI "virtual void \fBexitRule\fP (antlr4::tree::ParseTreeListener *listener) override"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for SysMLv2 C++ Implementation from the source code\&.
