.TH "SysMLv2Parser::Terminate_nodeContext" 3 "Version 1.0 Beta 2" "SysMLv2 C++ Implementation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SysMLv2Parser::Terminate_nodeContext
.SH SYNOPSIS
.br
.PP
.PP
Inherits antlr4::ParserRuleContext\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTerminate_nodeContext\fP (antlr4::ParserRuleContext *parent, size_t invokingState)"
.br
.ti -1c
.RI "virtual size_t \fBgetRuleIndex\fP () const override"
.br
.ti -1c
.RI "\fBOccurrence_usage_prefixContext\fP * \fBoccurrence_usage_prefix\fP ()"
.br
.ti -1c
.RI "antlr4::tree::TerminalNode * \fBKEYWORD_TERMINATE\fP ()"
.br
.ti -1c
.RI "\fBAction_bodyContext\fP * \fBaction_body\fP ()"
.br
.ti -1c
.RI "\fBAction_node_usage_declarationContext\fP * \fBaction_node_usage_declaration\fP ()"
.br
.ti -1c
.RI "\fBNode_parameter_memberContext\fP * \fBnode_parameter_member\fP ()"
.br
.ti -1c
.RI "virtual void \fBenterRule\fP (antlr4::tree::ParseTreeListener *listener) override"
.br
.ti -1c
.RI "virtual void \fBexitRule\fP (antlr4::tree::ParseTreeListener *listener) override"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for SysMLv2 C++ Implementation from the source code\&.
