.TH "SysMLv2::API::EXCEPTIONS::HTTPException" 3 "Version 1.0 Beta 2" "SysMLv2 C++ Implementation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SysMLv2::API::EXCEPTIONS::HTTPException
.SH SYNOPSIS
.br
.PP
.PP
Inherits std::exception\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBHTTPException\fP (long httpErrorCode)"
.br
.ti -1c
.RI "const char * \fBwhat\fP () const noexcept override"
.br
.ti -1c
.RI "long \fBhttpErrorCode\fP ()"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "long \fBHttpErrorCode\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for SysMLv2 C++ Implementation from the source code\&.
