.TH "SysMLv2::Entities::DataVersion" 3 "Version 1.0 Beta 2" "SysMLv2 C++ Implementation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SysMLv2::Entities::DataVersion
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <DataVersion\&.h>\fP
.PP
Inherits \fBSysMLv2::Entities::Record\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDataVersion\fP (std::shared_ptr< \fBDataIdentity\fP > identity, std::shared_ptr< \fBData\fP > payload=nullptr)"
.br
.ti -1c
.RI "std::shared_ptr< \fBDataIdentity\fP > \fBgetIdentity\fP ()"
.br
.ti -1c
.RI "void \fBsetPayload\fP (std::shared_ptr< \fBData\fP > payload)"
.br
.ti -1c
.RI "std::shared_ptr< \fBData\fP > \fBgetPayload\fP ()"
.br
.ti -1c
.RI "boost::uuids::uuid \fBgetId\fP ()"
.br
.ti -1c
.RI "std::string \fBserializeToJson\fP ()"
.br
.in -1c

Public Member Functions inherited from \fBSysMLv2::Entities::Record\fP
.in +1c
.ti -1c
.RI "\fBRecord\fP ()=delete"
.br
.ti -1c
.RI "\fBRecord\fP (boost::uuids::uuid id, std::string name='', std::string description='')"
.br
.ti -1c
.RI "\fBRecord\fP (std::string jsonStringOrName)"
.br
.ti -1c
.RI "virtual \fB~Record\fP ()"
.br
.ti -1c
.RI "bool \fBoperator==\fP (\fBRecord\fP const &other) const"
.br
.ti -1c
.RI "std::string \fBgetName\fP () const"
.br
.ti -1c
.RI "void \fBsetName\fP (std::string name)"
.br
.ti -1c
.RI "std::list< std::string > \fBgetAlias\fP () const"
.br
.ti -1c
.RI "void \fBappendAlias\fP (std::string &alias)"
.br
.ti -1c
.RI "std::string \fBgetDescription\fP () const"
.br
.ti -1c
.RI "void \fBsetDescription\fP (std::string &description)"
.br
.ti -1c
.RI "boost::uuids::uuid \fBgetId\fP () const"
.br
.ti -1c
.RI "std::string \fBgetType\fP () const"
.br
.ti -1c
.RI "std::string \fBserializeToJson\fP () override"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "std::shared_ptr< \fBDataIdentity\fP > \fBIdentity\fP"
.br
.ti -1c
.RI "std::shared_ptr< \fBData\fP > \fBPayload\fP"
.br
.in -1c
.SS "Additional Inherited Members"


Protected Attributes inherited from \fBSysMLv2::Entities::Record\fP
.in +1c
.ti -1c
.RI "std::string \fBType\fP"
.br
.ti -1c
.RI "std::string \fBName\fP"
.br
.ti -1c
.RI "std::list< std::string > \fBAlias\fP"
.br
.ti -1c
.RI "std::string \fBDescription\fP"
.br
.ti -1c
.RI "boost::uuids::uuid \fBId\fP"
.br
.ti -1c
.RI "bool \fBIsForCreation\fP = false"
.br
.in -1c

Protected Attributes inherited from \fBSysMLv2::Entities::IEntity\fP
.in +1c
.ti -1c
.RI "const int \fBJSON_INTENT\fP = 2"
.br
.in -1c
.SH "Detailed Description"
.PP 
The class \fBDataVersion\fP represents a specific version of the \fBData\fP in its lifecycle

.PP
\fBAuthor\fP
.RS 4
Moritz Herzog 
.RE
.PP
\fBVersion\fP
.RS 4
1\&.0 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "std::string SysMLv2::Entities::DataVersion::serializeToJson ()\fR [virtual]\fP"
Allows the serialization of the Object to a JSON String\&. 
.PP
\fBReturns\fP
.RS 4
JSON String of the Object 
.RE
.PP

.PP
Implements \fBSysMLv2::Entities::IEntity\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SysMLv2 C++ Implementation from the source code\&.
