.TH "SysMLv2::API" 3 "Version 1.0 Beta 2" "SysMLv2 C++ Implementation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SysMLv2::API
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBElementNavigationService\fP"
.br
.ti -1c
.RI "class \fBIElementNavigationService\fP"
.br
.ti -1c
.RI "class \fBIExternalRelationshipService\fP"
.br
.ti -1c
.RI "class \fBIProjectService\fP"
.br
.ti -1c
.RI "class \fBIProjectUsageService\fP"
.br
.ti -1c
.RI "class \fBIProjectVersioningService\fP"
.br
.ti -1c
.RI "class \fBIQueryService\fP"
.br
.ti -1c
.RI "class \fBProjectService\fP"
.br
.ti -1c
.RI "class \fBSysMLAPIImplementation\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBINTERNAL_STATUS_CODE\fP { \fBSUCCESS\fP = 0, \fBRE_DO\fP, \fBTHROW_ERROR\fP }"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for SysMLv2 C++ Implementation from the source code\&.
