.TH "SysMLv2Parser::Include_use_case_usageContext" 3 "Version 1.0 Beta 2" "SysMLv2 C++ Implementation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SysMLv2Parser::Include_use_case_usageContext
.SH SYNOPSIS
.br
.PP
.PP
Inherits antlr4::ParserRuleContext\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBInclude_use_case_usageContext\fP (antlr4::ParserRuleContext *parent, size_t invokingState)"
.br
.ti -1c
.RI "virtual size_t \fBgetRuleIndex\fP () const override"
.br
.ti -1c
.RI "\fBOccurrence_usage_prefixContext\fP * \fBoccurrence_usage_prefix\fP ()"
.br
.ti -1c
.RI "antlr4::tree::TerminalNode * \fBKEYWORD_INCLUDE\fP ()"
.br
.ti -1c
.RI "\fBCase_bodyContext\fP * \fBcase_body\fP ()"
.br
.ti -1c
.RI "\fBOwned_reference_subsettingContext\fP * \fBowned_reference_subsetting\fP ()"
.br
.ti -1c
.RI "antlr4::tree::TerminalNode * \fBKEYWORD_USE\fP ()"
.br
.ti -1c
.RI "antlr4::tree::TerminalNode * \fBKEYWORD_CASE\fP ()"
.br
.ti -1c
.RI "\fBUsage_declarationContext\fP * \fBusage_declaration\fP ()"
.br
.ti -1c
.RI "\fBValue_partContext\fP * \fBvalue_part\fP ()"
.br
.ti -1c
.RI "\fBFeature_specialization_partContext\fP * \fBfeature_specialization_part\fP ()"
.br
.ti -1c
.RI "virtual void \fBenterRule\fP (antlr4::tree::ParseTreeListener *listener) override"
.br
.ti -1c
.RI "virtual void \fBexitRule\fP (antlr4::tree::ParseTreeListener *listener) override"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for SysMLv2 C++ Implementation from the source code\&.
