.TH "SysMLv2Parser::Owned_expressionContext" 3 "Version 1.0 Beta 2" "SysMLv2 C++ Implementation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SysMLv2Parser::Owned_expressionContext
.SH SYNOPSIS
.br
.PP
.PP
Inherits antlr4::ParserRuleContext\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBOwned_expressionContext\fP (antlr4::ParserRuleContext *parent, size_t invokingState)"
.br
.ti -1c
.RI "virtual size_t \fBgetRuleIndex\fP () const override"
.br
.ti -1c
.RI "\fBConditional_expressionContext\fP * \fBconditional_expression\fP ()"
.br
.ti -1c
.RI "\fBConditional_binary_operator_expressionContext\fP * \fBconditional_binary_operator_expression\fP ()"
.br
.ti -1c
.RI "\fBBinary_operator_expressionContext\fP * \fBbinary_operator_expression\fP ()"
.br
.ti -1c
.RI "\fBUnary_operator_expressionContext\fP * \fBunary_operator_expression\fP ()"
.br
.ti -1c
.RI "\fBClassification_expressionContext\fP * \fBclassification_expression\fP ()"
.br
.ti -1c
.RI "\fBMetaclassification_expressionContext\fP * \fBmetaclassification_expression\fP ()"
.br
.ti -1c
.RI "\fBExtend_expressionContext\fP * \fBextend_expression\fP ()"
.br
.ti -1c
.RI "\fBPrimary_expressionContext\fP * \fBprimary_expression\fP ()"
.br
.ti -1c
.RI "virtual void \fBenterRule\fP (antlr4::tree::ParseTreeListener *listener) override"
.br
.ti -1c
.RI "virtual void \fBexitRule\fP (antlr4::tree::ParseTreeListener *listener) override"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for SysMLv2 C++ Implementation from the source code\&.
