.TH "SysMLv2::Files::Parser" 3 "Version 1.0 Beta 2" "SysMLv2 C++ Implementation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SysMLv2::Files::Parser
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static std::pair< std::vector< std::shared_ptr< \fBKerML::Entities::Element\fP > >, std::vector< std::shared_ptr< \fBParserError\fP > > > \fBparseKerML\fP (std::string text)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for SysMLv2 C++ Implementation from the source code\&.
