.TH "SysMLv2::Entities::MergeResult" 3 "Version 1.0 Beta 2" "SysMLv2 C++ Implementation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SysMLv2::Entities::MergeResult
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMergeResult\fP (std::shared_ptr< \fBCommit\fP > mergeCommit=nullptr, std::vector< std::shared_ptr< \fBDataIdentity\fP > > conflict=std::vector< std::shared_ptr< \fBDataIdentity\fP > >())"
.br
.ti -1c
.RI "std::vector< std::shared_ptr< \fBDataIdentity\fP > > \fBconflict\fP ()"
.br
.ti -1c
.RI "std::shared_ptr< \fBCommit\fP > \fBmergeCommit\fP ()"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "std::shared_ptr< \fBCommit\fP > \fBMergeCommit\fP = nullptr"
.br
.ti -1c
.RI "std::vector< std::shared_ptr< \fBDataIdentity\fP > > \fBConflict\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for SysMLv2 C++ Implementation from the source code\&.
