.TH "SysMLv2::API::EXCEPTIONS::ConnectionError" 3 "Version 1.0 Beta 2" "SysMLv2 C++ Implementation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SysMLv2::API::EXCEPTIONS::ConnectionError
.SH SYNOPSIS
.br
.PP
.PP
Inherits std::runtime_error\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBConnectionError\fP (SysMLv2::API::EXCEPTIONS::CONNECTION_ERROR_TYPE errorType)"
.br
.ti -1c
.RI "const char * \fBwhat\fP () const noexcept override"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "CONNECTION_ERROR_TYPE \fBErrorType\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for SysMLv2 C++ Implementation from the source code\&.
