.TH "VisibilityKind" 3 "Version 1.0 Beta 2" "SysMLv2 C++ Implementation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
VisibilityKind
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <VisibilityKind\&.h>\fP
.SH "Detailed Description"
.PP 

.PP
\fBAuthor\fP
.RS 4
Moritz Herzog 
.RE
.PP
\fBVersion\fP
.RS 4
1\&.0 Beta 2 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for SysMLv2 C++ Implementation from the source code\&.
