// Generated by kerml/tools/generate_abstract_syntax.py.
#include <kerml/KerML.h>
#include <utility>
#include <stdexcept>
#include "../../model/RepresentationSupport.h"

namespace KerML::Entities {
std::shared_ptr<Predicate> BooleanExpression::predicate() const {
    return std::dynamic_pointer_cast<Predicate>(function());
}

void BooleanExpression::setPredicate(std::shared_ptr<Predicate> value) {
    setFunction(std::move(value));
}

BooleanExpression::BooleanExpression() {
    _dType = "BooleanExpression";
}

BooleanExpression::~BooleanExpression() = default;
}
