// Generated by kerml/tools/generate_abstract_syntax.py.
#include <kerml/KerML.h>
#include <utility>
#include <stdexcept>
#include "../../model/RepresentationSupport.h"

namespace KerML::Entities {
std::shared_ptr<Function> Expression::function() const {
    return function_;
}

void Expression::setFunction(std::shared_ptr<Function> value) {
    function_ = std::move(value);
}

std::shared_ptr<Feature> Expression::result() const {
    return result_;
}

void Expression::setResult(std::shared_ptr<Feature> value) {
    result_ = std::move(value);
}

bool Expression::isModelLevelEvaluable() const {
    return isModelLevelEvaluable_;
}

void Expression::setIsModelLevelEvaluable(bool value) {
    isModelLevelEvaluable_ = std::move(value);
}

Expression::Expression() {
    _dType = "Expression";
}

Expression::~Expression() = default;
}
