// Generated by kerml/tools/generate_abstract_syntax.py.
#include <kerml/KerML.h>
#include <utility>
#include <stdexcept>
#include "../../model/RepresentationSupport.h"

namespace KerML::Entities {
std::vector<std::shared_ptr<Expression>> Function::expression() const {
    return detail::select<Expression>(step());
}

std::shared_ptr<Feature> Function::result() const {
    return result_;
}

void Function::setResult(std::shared_ptr<Feature> value) {
    result_ = std::move(value);
}

bool Function::isModelLevelEvaluable() const {
    return isModelLevelEvaluable_;
}

void Function::setIsModelLevelEvaluable(bool value) {
    isModelLevelEvaluable_ = std::move(value);
}

Function::Function() {
    _dType = "Function";
}

Function::~Function() = default;
}
