// Generated by kerml/tools/generate_abstract_syntax.py.
#include <kerml/KerML.h>
#include <utility>
#include <stdexcept>
#include "../../model/RepresentationSupport.h"

namespace KerML::Entities {
bool Invariant::isNegated() const {
    return isNegated_;
}

void Invariant::setIsNegated(bool value) {
    isNegated_ = std::move(value);
}

Invariant::Invariant() {
    _dType = "Invariant";
}

Invariant::~Invariant() = default;
}
