// Generated by kerml/tools/generate_abstract_syntax.py.
#include <kerml/KerML.h>
#include <utility>
#include <stdexcept>
#include "../../model/RepresentationSupport.h"

namespace KerML::Entities {
std::shared_ptr<Feature> ParameterMembership::ownedMemberParameter() const {
    return FeatureMembership::ownedMemberFeature();
}

void ParameterMembership::setOwnedMemberParameter(std::shared_ptr<Feature> value) {
    FeatureMembership::setOwnedMemberFeature(std::move(value));
}

ParameterMembership::ParameterMembership() {
    _dType = "ParameterMembership";
}

ParameterMembership::~ParameterMembership() = default;
}
