// Generated by kerml/tools/generate_abstract_syntax.py.
#include <kerml/KerML.h>
#include <utility>
#include <stdexcept>
#include "../../model/RepresentationSupport.h"

namespace KerML::Entities {
ResultExpressionMembership::ResultExpressionMembership(std::shared_ptr<Expression> expression, std::shared_ptr<Type> owner) : ResultExpressionMembership() {
    setOwnedResultExpression(std::move(expression));
    setOwningType(std::move(owner));
}

void ResultExpressionMembership::setOwningType(std::shared_ptr<Type> owner) {
    if (!std::dynamic_pointer_cast<Function>(owner) && !std::dynamic_pointer_cast<Expression>(owner)) throw std::invalid_argument("Result expression owner must be a Function or Expression");
    FeatureMembership::setOwningType(std::move(owner));
}

std::shared_ptr<Expression> ResultExpressionMembership::ownedResultExpression() const {
    return std::dynamic_pointer_cast<Expression>(FeatureMembership::ownedMemberFeature());
}

void ResultExpressionMembership::setOwnedResultExpression(std::shared_ptr<Expression> value) {
    if (!value) throw std::invalid_argument("Result expression is required");
    FeatureMembership::setOwnedMemberFeature(std::move(value));
}

ResultExpressionMembership::ResultExpressionMembership() {
    _dType = "ResultExpressionMembership";
}

ResultExpressionMembership::~ResultExpressionMembership() = default;
}
