#pragma once
#include <sysml/flows/FlowDefinition.h>
#include <sysml/flows/FlowUsage.h>
#include <sysml/flows/SuccessionFlowUsage.h>
#include <sysml/enumerations/EnumerationDefinition.h>
#include <sysml/enumerations/EnumerationUsage.h>
#include <sysml/requirements/RequirementUsage.h>
#include <sysml/requirements/ConcernUsage.h>
#include <sysml/requirements/FramedConcernMembership.h>
#include <sysml/requirements/ActorMembership.h>
#include <sysml/requirements/StakeholderMembership.h>
#include <sysml/requirements/SubjectMembership.h>
#include <sysml/requirements/ConcernDefinition.h>
#include <sysml/requirements/RequirementDefinition.h>
#include <sysml/requirements/RequirementConstraintMembership.h>
#include <sysml/requirements/RequirementConstraintKind.h>
#include <sysml/requirements/SatisfyRequirementUsage.h>
#include <sysml/calculations/CalculationDefinition.h>
#include <sysml/calculations/CalculationUsage.h>
#include <sysml/metadata/MetadataDefinition.h>
#include <sysml/metadata/MetadataUsage.h>
#include <sysml/constraints/AssertConstraintUsage.h>
#include <sysml/constraints/ConstraintDefinition.h>
#include <sysml/constraints/ConstraintUsage.h>
#include <sysml/cases/CaseUsage.h>
#include <sysml/cases/CaseDefinition.h>
#include <sysml/cases/ObjectiveMembership.h>
#include <sysml/states/TransitionFeatureMembership.h>
#include <sysml/states/StateSubactionKind.h>
#include <sysml/states/ExhibitStateUsage.h>
#include <sysml/states/StateSubactionMembership.h>
#include <sysml/states/StateUsage.h>
#include <sysml/states/StateDefinition.h>
#include <sysml/states/TransitionFeatureKind.h>
#include <sysml/states/TransitionUsage.h>
#include <sysml/usecases/UseCaseUsage.h>
#include <sysml/usecases/IncludeUseCaseUsage.h>
#include <sysml/usecases/UseCaseDefinition.h>
#include <sysml/actions/PerformActionUsage.h>
#include <sysml/actions/ActionDefinition.h>
#include <sysml/actions/ActionUsage.h>
#include <sysml/actions/AssignmentActionUsage.h>
#include <sysml/actions/ForLoopActionUsage.h>
#include <sysml/actions/TriggerInvocationExpression.h>
#include <sysml/actions/LoopActionUsage.h>
#include <sysml/actions/DecisionNode.h>
#include <sysml/actions/ForkNode.h>
#include <sysml/actions/JoinNode.h>
#include <sysml/actions/ControlNode.h>
#include <sysml/actions/MergeNode.h>
#include <sysml/actions/TerminateActionUsage.h>
#include <sysml/actions/AcceptActionUsage.h>
#include <sysml/actions/WhileLoopActionUsage.h>
#include <sysml/actions/SendActionUsage.h>
#include <sysml/actions/IfActionUsage.h>
#include <sysml/actions/TriggerKind.h>
#include <sysml/items/ItemUsage.h>
#include <sysml/items/ItemDefinition.h>
#include <sysml/occurrences/EventOccurrenceUsage.h>
#include <sysml/occurrences/PortionKind.h>
#include <sysml/occurrences/OccurrenceUsage.h>
#include <sysml/occurrences/OccurrenceDefinition.h>
#include <sysml/usage/Usage.h>
#include <sysml/usage/ReferenceUsage.h>
#include <sysml/usage/VariantMembership.h>
#include <sysml/usage/Definition.h>
#include <sysml/attributes/AttributeDefinition.h>
#include <sysml/attributes/AttributeUsage.h>
#include <sysml/parts/PartDefinition.h>
#include <sysml/parts/PartUsage.h>
#include <sysml/analysiscases/AnalysisCaseUsage.h>
#include <sysml/analysiscases/AnalysisCaseDefinition.h>
#include <sysml/ports/PortConjugation.h>
#include <sysml/ports/ConjugatedPortDefinition.h>
#include <sysml/ports/PortDefinition.h>
#include <sysml/ports/ConjugatedPortTyping.h>
#include <sysml/ports/PortUsage.h>
#include <sysml/views/ViewUsage.h>
#include <sysml/views/Expose.h>
#include <sysml/views/ViewDefinition.h>
#include <sysml/views/RenderingUsage.h>
#include <sysml/views/ViewpointDefinition.h>
#include <sysml/views/RenderingDefinition.h>
#include <sysml/views/MembershipExpose.h>
#include <sysml/views/NamespaceExpose.h>
#include <sysml/views/ViewRenderingMembership.h>
#include <sysml/views/ViewpointUsage.h>
#include <sysml/connections/ConnectorAsUsage.h>
#include <sysml/connections/ConnectionUsage.h>
#include <sysml/connections/SuccessionAsUsage.h>
#include <sysml/connections/ConnectionDefinition.h>
#include <sysml/connections/BindingConnectorAsUsage.h>
#include <sysml/interfaces/InterfaceUsage.h>
#include <sysml/interfaces/InterfaceDefinition.h>
#include <sysml/allocations/AllocationDefinition.h>
#include <sysml/allocations/AllocationUsage.h>
#include <sysml/verificationcases/RequirementVerificationMembership.h>
#include <sysml/verificationcases/VerificationCaseDefinition.h>
#include <sysml/verificationcases/VerificationCaseUsage.h>
