// Generated by sysml/tools/generate_abstract_syntax.py.
#include <sysml/states/ExhibitStateUsage.h>
#include <sysml/states/StateUsage.h>
#include <algorithm>
#include <stdexcept>

namespace SysMLv2::Entities {

std::shared_ptr<StateUsage> ExhibitStateUsage::exhibitedState() const {
    return exhibitedState_;
}

void ExhibitStateUsage::setExhibitedState(std::shared_ptr<StateUsage> value) {
    exhibitedState_ = std::move(value);
}

ExhibitStateUsage::ExhibitStateUsage() {
    _dType = "ExhibitStateUsage";
}

ExhibitStateUsage::~ExhibitStateUsage() = default;

std::string_view ExhibitStateUsage::metaclassName() const noexcept {
    return "ExhibitStateUsage";
}

std::vector<RepresentationIssue> ExhibitStateUsage::validateRepresentation(bool includeDerived) const {
    std::vector<RepresentationIssue> issues; (void)includeDerived;
    { auto optional = OccurrenceUsage::portionKind(); if (optional) { auto value = *optional; if (!(value == PortionKind::timeslice || value == PortionKind::snapshot)) issues.push_back({"OccurrenceUsage.portionKind", "invalid enumeration value"}); } }
    if (includeDerived) if (!EventOccurrenceUsage::eventOccurrence()) issues.push_back({"EventOccurrenceUsage.eventOccurrence", "required reference is missing"});
    if (includeDerived) if (!PerformActionUsage::performedAction()) issues.push_back({"PerformActionUsage.performedAction", "required reference is missing"});
    if (includeDerived) if (!ExhibitStateUsage::exhibitedState()) issues.push_back({"ExhibitStateUsage.exhibitedState", "required reference is missing"});
    return issues;
}

} // namespace SysMLv2::Entities
