// Generated by sysml/tools/generate_abstract_syntax.py.
#include <sysml/states/StateUsage.h>
#include <sysml/actions/ActionUsage.h>
#include <algorithm>
#include <stdexcept>

namespace SysMLv2::Entities {

std::vector<std::shared_ptr<KerML::Entities::Behavior>> StateUsage::stateDefinition() const {
    return stateDefinition_;
}

void StateUsage::setStateDefinition(std::vector<std::shared_ptr<KerML::Entities::Behavior>> value) {
    if (std::any_of(value.begin(), value.end(), [](const auto& item) { return !item; })) {
        throw std::invalid_argument("StateUsage.stateDefinition: null entry");
    }
    for (std::size_t i = 0; i < value.size(); ++i) {
        if (std::find(value.begin(), value.begin() + i, value[i]) != value.begin() + i) {
            throw std::invalid_argument("StateUsage.stateDefinition: duplicate entry");
        }
    }
    stateDefinition_ = std::move(value);
}

void StateUsage::appendStateDefinition(std::shared_ptr<KerML::Entities::Behavior> value) {
    auto values = stateDefinition();
    values.push_back(std::move(value));
    setStateDefinition(std::move(values));
}

std::shared_ptr<ActionUsage> StateUsage::entryAction() const {
    return entryAction_;
}

void StateUsage::setEntryAction(std::shared_ptr<ActionUsage> value) {
    entryAction_ = std::move(value);
}

std::shared_ptr<ActionUsage> StateUsage::doAction() const {
    return doAction_;
}

void StateUsage::setDoAction(std::shared_ptr<ActionUsage> value) {
    doAction_ = std::move(value);
}

std::shared_ptr<ActionUsage> StateUsage::exitAction() const {
    return exitAction_;
}

void StateUsage::setExitAction(std::shared_ptr<ActionUsage> value) {
    exitAction_ = std::move(value);
}

bool StateUsage::isParallel() const {
    return isParallel_;
}

void StateUsage::setIsParallel(bool value) {
    isParallel_ = std::move(value);
}

StateUsage::StateUsage() {
    _dType = "StateUsage";
}

StateUsage::~StateUsage() = default;

std::string_view StateUsage::metaclassName() const noexcept {
    return "StateUsage";
}

std::vector<RepresentationIssue> StateUsage::validateRepresentation(bool includeDerived) const {
    std::vector<RepresentationIssue> issues; (void)includeDerived;
    { auto optional = OccurrenceUsage::portionKind(); if (optional) { auto value = *optional; if (!(value == PortionKind::timeslice || value == PortionKind::snapshot)) issues.push_back({"OccurrenceUsage.portionKind", "invalid enumeration value"}); } }
    return issues;
}

} // namespace SysMLv2::Entities
