// Generated by sysml/tools/generate_abstract_syntax.py.
#include <sysml/states/StateSubactionMembership.h>
#include <sysml/states/StateSubactionKind.h>
#include <sysml/actions/ActionUsage.h>
#include <algorithm>
#include <stdexcept>

namespace SysMLv2::Entities {

StateSubactionKind StateSubactionMembership::kind() const {
    return kind_;
}

void StateSubactionMembership::setKind(StateSubactionKind value) {
    kind_ = std::move(value);
}

std::shared_ptr<ActionUsage> StateSubactionMembership::action() const {
    return action_;
}

void StateSubactionMembership::setAction(std::shared_ptr<ActionUsage> value) {
    action_ = std::move(value);
}

StateSubactionMembership::StateSubactionMembership() {
    _dType = "StateSubactionMembership";
}

StateSubactionMembership::~StateSubactionMembership() = default;

std::string_view StateSubactionMembership::metaclassName() const noexcept {
    return "StateSubactionMembership";
}

std::vector<RepresentationIssue> StateSubactionMembership::validateRepresentation(bool includeDerived) const {
    std::vector<RepresentationIssue> issues; (void)includeDerived;
    { auto value = StateSubactionMembership::kind(); if (!(value == StateSubactionKind::entry || value == StateSubactionKind::do_ || value == StateSubactionKind::exit)) issues.push_back({"StateSubactionMembership.kind", "invalid enumeration value"}); }
    if (includeDerived) if (!StateSubactionMembership::action()) issues.push_back({"StateSubactionMembership.action", "required reference is missing"});
    return issues;
}

} // namespace SysMLv2::Entities
