// Generated by sysml/tools/generate_abstract_syntax.py.
#include <sysml/states/StateDefinition.h>
#include <sysml/states/StateUsage.h>
#include <sysml/actions/ActionUsage.h>
#include <algorithm>
#include <stdexcept>

namespace SysMLv2::Entities {

std::vector<std::shared_ptr<StateUsage>> StateDefinition::state() const {
    return state_;
}

void StateDefinition::setState(std::vector<std::shared_ptr<StateUsage>> value) {
    if (std::any_of(value.begin(), value.end(), [](const auto& item) { return !item; })) {
        throw std::invalid_argument("StateDefinition.state: null entry");
    }
    for (std::size_t i = 0; i < value.size(); ++i) {
        if (std::find(value.begin(), value.begin() + i, value[i]) != value.begin() + i) {
            throw std::invalid_argument("StateDefinition.state: duplicate entry");
        }
    }
    state_ = std::move(value);
}

void StateDefinition::appendState(std::shared_ptr<StateUsage> value) {
    auto values = state();
    values.push_back(std::move(value));
    setState(std::move(values));
}

std::shared_ptr<ActionUsage> StateDefinition::entryAction() const {
    return entryAction_;
}

void StateDefinition::setEntryAction(std::shared_ptr<ActionUsage> value) {
    entryAction_ = std::move(value);
}

std::shared_ptr<ActionUsage> StateDefinition::doAction() const {
    return doAction_;
}

void StateDefinition::setDoAction(std::shared_ptr<ActionUsage> value) {
    doAction_ = std::move(value);
}

std::shared_ptr<ActionUsage> StateDefinition::exitAction() const {
    return exitAction_;
}

void StateDefinition::setExitAction(std::shared_ptr<ActionUsage> value) {
    exitAction_ = std::move(value);
}

bool StateDefinition::isParallel() const {
    return isParallel_;
}

void StateDefinition::setIsParallel(bool value) {
    isParallel_ = std::move(value);
}

StateDefinition::StateDefinition() {
    _dType = "StateDefinition";
}

StateDefinition::~StateDefinition() = default;

std::string_view StateDefinition::metaclassName() const noexcept {
    return "StateDefinition";
}

std::vector<RepresentationIssue> StateDefinition::validateRepresentation(bool includeDerived) const {
    std::vector<RepresentationIssue> issues; (void)includeDerived;
    return issues;
}

} // namespace SysMLv2::Entities
