// Generated by sysml/tools/generate_abstract_syntax.py.
#include <sysml/states/TransitionFeatureMembership.h>
#include <sysml/states/TransitionFeatureKind.h>
#include <algorithm>
#include <stdexcept>

namespace SysMLv2::Entities {

TransitionFeatureKind TransitionFeatureMembership::kind() const {
    return kind_;
}

void TransitionFeatureMembership::setKind(TransitionFeatureKind value) {
    kind_ = std::move(value);
}

std::shared_ptr<KerML::Entities::Step> TransitionFeatureMembership::transitionFeature() const {
    return transitionFeature_;
}

void TransitionFeatureMembership::setTransitionFeature(std::shared_ptr<KerML::Entities::Step> value) {
    transitionFeature_ = std::move(value);
}

TransitionFeatureMembership::TransitionFeatureMembership() {
    _dType = "TransitionFeatureMembership";
}

TransitionFeatureMembership::~TransitionFeatureMembership() = default;

std::string_view TransitionFeatureMembership::metaclassName() const noexcept {
    return "TransitionFeatureMembership";
}

std::vector<RepresentationIssue> TransitionFeatureMembership::validateRepresentation(bool includeDerived) const {
    std::vector<RepresentationIssue> issues; (void)includeDerived;
    { auto value = TransitionFeatureMembership::kind(); if (!(value == TransitionFeatureKind::trigger || value == TransitionFeatureKind::guard || value == TransitionFeatureKind::effect)) issues.push_back({"TransitionFeatureMembership.kind", "invalid enumeration value"}); }
    if (includeDerived) if (!TransitionFeatureMembership::transitionFeature()) issues.push_back({"TransitionFeatureMembership.transitionFeature", "required reference is missing"});
    return issues;
}

} // namespace SysMLv2::Entities
