// Generated by sysml/tools/generate_abstract_syntax.py.
#include <sysml/states/TransitionUsage.h>
#include <sysml/actions/ActionUsage.h>
#include <sysml/actions/AcceptActionUsage.h>
#include <algorithm>
#include <stdexcept>

namespace SysMLv2::Entities {

std::shared_ptr<ActionUsage> TransitionUsage::source() const {
    return source_;
}

void TransitionUsage::setSource(std::shared_ptr<ActionUsage> value) {
    source_ = std::move(value);
}

std::shared_ptr<ActionUsage> TransitionUsage::target() const {
    return target_;
}

void TransitionUsage::setTarget(std::shared_ptr<ActionUsage> value) {
    target_ = std::move(value);
}

std::vector<std::shared_ptr<AcceptActionUsage>> TransitionUsage::triggerAction() const {
    return triggerAction_;
}

void TransitionUsage::setTriggerAction(std::vector<std::shared_ptr<AcceptActionUsage>> value) {
    if (std::any_of(value.begin(), value.end(), [](const auto& item) { return !item; })) {
        throw std::invalid_argument("TransitionUsage.triggerAction: null entry");
    }
    for (std::size_t i = 0; i < value.size(); ++i) {
        if (std::find(value.begin(), value.begin() + i, value[i]) != value.begin() + i) {
            throw std::invalid_argument("TransitionUsage.triggerAction: duplicate entry");
        }
    }
    triggerAction_ = std::move(value);
}

void TransitionUsage::appendTriggerAction(std::shared_ptr<AcceptActionUsage> value) {
    auto values = triggerAction();
    values.push_back(std::move(value));
    setTriggerAction(std::move(values));
}

std::vector<std::shared_ptr<KerML::Entities::Expression>> TransitionUsage::guardExpression() const {
    return guardExpression_;
}

void TransitionUsage::setGuardExpression(std::vector<std::shared_ptr<KerML::Entities::Expression>> value) {
    if (std::any_of(value.begin(), value.end(), [](const auto& item) { return !item; })) {
        throw std::invalid_argument("TransitionUsage.guardExpression: null entry");
    }
    for (std::size_t i = 0; i < value.size(); ++i) {
        if (std::find(value.begin(), value.begin() + i, value[i]) != value.begin() + i) {
            throw std::invalid_argument("TransitionUsage.guardExpression: duplicate entry");
        }
    }
    guardExpression_ = std::move(value);
}

void TransitionUsage::appendGuardExpression(std::shared_ptr<KerML::Entities::Expression> value) {
    auto values = guardExpression();
    values.push_back(std::move(value));
    setGuardExpression(std::move(values));
}

std::vector<std::shared_ptr<ActionUsage>> TransitionUsage::effectAction() const {
    return effectAction_;
}

void TransitionUsage::setEffectAction(std::vector<std::shared_ptr<ActionUsage>> value) {
    if (std::any_of(value.begin(), value.end(), [](const auto& item) { return !item; })) {
        throw std::invalid_argument("TransitionUsage.effectAction: null entry");
    }
    for (std::size_t i = 0; i < value.size(); ++i) {
        if (std::find(value.begin(), value.begin() + i, value[i]) != value.begin() + i) {
            throw std::invalid_argument("TransitionUsage.effectAction: duplicate entry");
        }
    }
    effectAction_ = std::move(value);
}

void TransitionUsage::appendEffectAction(std::shared_ptr<ActionUsage> value) {
    auto values = effectAction();
    values.push_back(std::move(value));
    setEffectAction(std::move(values));
}

std::shared_ptr<KerML::Entities::Succession> TransitionUsage::succession() const {
    return succession_;
}

void TransitionUsage::setSuccession(std::shared_ptr<KerML::Entities::Succession> value) {
    succession_ = std::move(value);
}

TransitionUsage::TransitionUsage() {
    _dType = "TransitionUsage";
}

TransitionUsage::~TransitionUsage() = default;

std::string_view TransitionUsage::metaclassName() const noexcept {
    return "TransitionUsage";
}

std::vector<RepresentationIssue> TransitionUsage::validateRepresentation(bool includeDerived) const {
    std::vector<RepresentationIssue> issues; (void)includeDerived;
    { auto optional = OccurrenceUsage::portionKind(); if (optional) { auto value = *optional; if (!(value == PortionKind::timeslice || value == PortionKind::snapshot)) issues.push_back({"OccurrenceUsage.portionKind", "invalid enumeration value"}); } }
    if (includeDerived) if (!TransitionUsage::source()) issues.push_back({"TransitionUsage.source", "required reference is missing"});
    if (includeDerived) if (!TransitionUsage::target()) issues.push_back({"TransitionUsage.target", "required reference is missing"});
    if (includeDerived) if (!TransitionUsage::succession()) issues.push_back({"TransitionUsage.succession", "required reference is missing"});
    return issues;
}

} // namespace SysMLv2::Entities
