// Generated by sysml/tools/generate_abstract_syntax.py.
#include <sysml/actions/AcceptActionUsage.h>
#include <sysml/usage/ReferenceUsage.h>
#include <algorithm>
#include <stdexcept>

namespace SysMLv2::Entities {

std::shared_ptr<KerML::Entities::Expression> AcceptActionUsage::receiverArgument() const {
    return receiverArgument_;
}

void AcceptActionUsage::setReceiverArgument(std::shared_ptr<KerML::Entities::Expression> value) {
    receiverArgument_ = std::move(value);
}

std::shared_ptr<ReferenceUsage> AcceptActionUsage::payloadParameter() const {
    return payloadParameter_;
}

void AcceptActionUsage::setPayloadParameter(std::shared_ptr<ReferenceUsage> value) {
    payloadParameter_ = std::move(value);
}

std::shared_ptr<KerML::Entities::Expression> AcceptActionUsage::payloadArgument() const {
    return payloadArgument_;
}

void AcceptActionUsage::setPayloadArgument(std::shared_ptr<KerML::Entities::Expression> value) {
    payloadArgument_ = std::move(value);
}

AcceptActionUsage::AcceptActionUsage() {
    _dType = "AcceptActionUsage";
}

AcceptActionUsage::~AcceptActionUsage() = default;

std::string_view AcceptActionUsage::metaclassName() const noexcept {
    return "AcceptActionUsage";
}

std::vector<RepresentationIssue> AcceptActionUsage::validateRepresentation(bool includeDerived) const {
    std::vector<RepresentationIssue> issues; (void)includeDerived;
    { auto optional = OccurrenceUsage::portionKind(); if (optional) { auto value = *optional; if (!(value == PortionKind::timeslice || value == PortionKind::snapshot)) issues.push_back({"OccurrenceUsage.portionKind", "invalid enumeration value"}); } }
    if (includeDerived) if (!AcceptActionUsage::payloadParameter()) issues.push_back({"AcceptActionUsage.payloadParameter", "required reference is missing"});
    return issues;
}

} // namespace SysMLv2::Entities
