// Generated by sysml/tools/generate_abstract_syntax.py.
#include <sysml/actions/ActionDefinition.h>
#include <sysml/actions/ActionUsage.h>
#include <algorithm>
#include <stdexcept>

namespace SysMLv2::Entities {

std::vector<std::shared_ptr<ActionUsage>> ActionDefinition::action() const {
    return action_;
}

void ActionDefinition::setAction(std::vector<std::shared_ptr<ActionUsage>> value) {
    if (std::any_of(value.begin(), value.end(), [](const auto& item) { return !item; })) {
        throw std::invalid_argument("ActionDefinition.action: null entry");
    }
    for (std::size_t i = 0; i < value.size(); ++i) {
        if (std::find(value.begin(), value.begin() + i, value[i]) != value.begin() + i) {
            throw std::invalid_argument("ActionDefinition.action: duplicate entry");
        }
    }
    action_ = std::move(value);
}

void ActionDefinition::appendAction(std::shared_ptr<ActionUsage> value) {
    auto values = action();
    values.push_back(std::move(value));
    setAction(std::move(values));
}

ActionDefinition::ActionDefinition() {
    _dType = "ActionDefinition";
}

ActionDefinition::~ActionDefinition() = default;

std::string_view ActionDefinition::metaclassName() const noexcept {
    return "ActionDefinition";
}

std::vector<RepresentationIssue> ActionDefinition::validateRepresentation(bool includeDerived) const {
    std::vector<RepresentationIssue> issues; (void)includeDerived;
    return issues;
}

} // namespace SysMLv2::Entities
