// Generated by sysml/tools/generate_abstract_syntax.py.
#include <sysml/actions/AssignmentActionUsage.h>
#include <algorithm>
#include <stdexcept>

namespace SysMLv2::Entities {

std::shared_ptr<KerML::Entities::Expression> AssignmentActionUsage::targetArgument() const {
    return targetArgument_;
}

void AssignmentActionUsage::setTargetArgument(std::shared_ptr<KerML::Entities::Expression> value) {
    targetArgument_ = std::move(value);
}

std::shared_ptr<KerML::Entities::Expression> AssignmentActionUsage::valueExpression() const {
    return valueExpression_;
}

void AssignmentActionUsage::setValueExpression(std::shared_ptr<KerML::Entities::Expression> value) {
    valueExpression_ = std::move(value);
}

std::shared_ptr<KerML::Entities::Feature> AssignmentActionUsage::referent() const {
    return referent_;
}

void AssignmentActionUsage::setReferent(std::shared_ptr<KerML::Entities::Feature> value) {
    referent_ = std::move(value);
}

AssignmentActionUsage::AssignmentActionUsage() {
    _dType = "AssignmentActionUsage";
}

AssignmentActionUsage::~AssignmentActionUsage() = default;

std::string_view AssignmentActionUsage::metaclassName() const noexcept {
    return "AssignmentActionUsage";
}

std::vector<RepresentationIssue> AssignmentActionUsage::validateRepresentation(bool includeDerived) const {
    std::vector<RepresentationIssue> issues; (void)includeDerived;
    { auto optional = OccurrenceUsage::portionKind(); if (optional) { auto value = *optional; if (!(value == PortionKind::timeslice || value == PortionKind::snapshot)) issues.push_back({"OccurrenceUsage.portionKind", "invalid enumeration value"}); } }
    if (includeDerived) if (!AssignmentActionUsage::referent()) issues.push_back({"AssignmentActionUsage.referent", "required reference is missing"});
    return issues;
}

} // namespace SysMLv2::Entities
