// Generated by sysml/tools/generate_abstract_syntax.py.
#include <sysml/actions/ControlNode.h>
#include <algorithm>
#include <stdexcept>

namespace SysMLv2::Entities {

ControlNode::ControlNode() {
    _dType = "ControlNode";
}

ControlNode::~ControlNode() = default;

std::vector<RepresentationIssue> ControlNode::validateRepresentation(bool includeDerived) const {
    std::vector<RepresentationIssue> issues; (void)includeDerived;
    { auto optional = OccurrenceUsage::portionKind(); if (optional) { auto value = *optional; if (!(value == PortionKind::timeslice || value == PortionKind::snapshot)) issues.push_back({"OccurrenceUsage.portionKind", "invalid enumeration value"}); } }
    return issues;
}

} // namespace SysMLv2::Entities
