// Generated by sysml/tools/generate_abstract_syntax.py.
#include <sysml/actions/DecisionNode.h>
#include <algorithm>
#include <stdexcept>

namespace SysMLv2::Entities {

DecisionNode::DecisionNode() {
    _dType = "DecisionNode";
}

DecisionNode::~DecisionNode() = default;

std::string_view DecisionNode::metaclassName() const noexcept {
    return "DecisionNode";
}

std::vector<RepresentationIssue> DecisionNode::validateRepresentation(bool includeDerived) const {
    std::vector<RepresentationIssue> issues; (void)includeDerived;
    { auto optional = OccurrenceUsage::portionKind(); if (optional) { auto value = *optional; if (!(value == PortionKind::timeslice || value == PortionKind::snapshot)) issues.push_back({"OccurrenceUsage.portionKind", "invalid enumeration value"}); } }
    return issues;
}

} // namespace SysMLv2::Entities
