// Generated by sysml/tools/generate_abstract_syntax.py.
#include <sysml/actions/ForkNode.h>
#include <algorithm>
#include <stdexcept>

namespace SysMLv2::Entities {

ForkNode::ForkNode() {
    _dType = "ForkNode";
}

ForkNode::~ForkNode() = default;

std::string_view ForkNode::metaclassName() const noexcept {
    return "ForkNode";
}

std::vector<RepresentationIssue> ForkNode::validateRepresentation(bool includeDerived) const {
    std::vector<RepresentationIssue> issues; (void)includeDerived;
    { auto optional = OccurrenceUsage::portionKind(); if (optional) { auto value = *optional; if (!(value == PortionKind::timeslice || value == PortionKind::snapshot)) issues.push_back({"OccurrenceUsage.portionKind", "invalid enumeration value"}); } }
    return issues;
}

} // namespace SysMLv2::Entities
