// Generated by sysml/tools/generate_abstract_syntax.py.
#include <sysml/actions/ForLoopActionUsage.h>
#include <sysml/usage/ReferenceUsage.h>
#include <algorithm>
#include <stdexcept>

namespace SysMLv2::Entities {

std::shared_ptr<KerML::Entities::Expression> ForLoopActionUsage::seqArgument() const {
    return seqArgument_;
}

void ForLoopActionUsage::setSeqArgument(std::shared_ptr<KerML::Entities::Expression> value) {
    seqArgument_ = std::move(value);
}

std::shared_ptr<ReferenceUsage> ForLoopActionUsage::loopVariable() const {
    return loopVariable_;
}

void ForLoopActionUsage::setLoopVariable(std::shared_ptr<ReferenceUsage> value) {
    loopVariable_ = std::move(value);
}

ForLoopActionUsage::ForLoopActionUsage() {
    _dType = "ForLoopActionUsage";
}

ForLoopActionUsage::~ForLoopActionUsage() = default;

std::string_view ForLoopActionUsage::metaclassName() const noexcept {
    return "ForLoopActionUsage";
}

std::vector<RepresentationIssue> ForLoopActionUsage::validateRepresentation(bool includeDerived) const {
    std::vector<RepresentationIssue> issues; (void)includeDerived;
    { auto optional = OccurrenceUsage::portionKind(); if (optional) { auto value = *optional; if (!(value == PortionKind::timeslice || value == PortionKind::snapshot)) issues.push_back({"OccurrenceUsage.portionKind", "invalid enumeration value"}); } }
    if (includeDerived) if (!LoopActionUsage::bodyAction()) issues.push_back({"LoopActionUsage.bodyAction", "required reference is missing"});
    if (includeDerived) if (!ForLoopActionUsage::seqArgument()) issues.push_back({"ForLoopActionUsage.seqArgument", "required reference is missing"});
    if (includeDerived) if (!ForLoopActionUsage::loopVariable()) issues.push_back({"ForLoopActionUsage.loopVariable", "required reference is missing"});
    return issues;
}

} // namespace SysMLv2::Entities
