// Generated by sysml/tools/generate_abstract_syntax.py.
#include <sysml/actions/IfActionUsage.h>
#include <sysml/actions/ActionUsage.h>
#include <algorithm>
#include <stdexcept>

namespace SysMLv2::Entities {

std::shared_ptr<ActionUsage> IfActionUsage::elseAction() const {
    return elseAction_;
}

void IfActionUsage::setElseAction(std::shared_ptr<ActionUsage> value) {
    elseAction_ = std::move(value);
}

std::shared_ptr<ActionUsage> IfActionUsage::thenAction() const {
    return thenAction_;
}

void IfActionUsage::setThenAction(std::shared_ptr<ActionUsage> value) {
    thenAction_ = std::move(value);
}

std::shared_ptr<KerML::Entities::Expression> IfActionUsage::ifArgument() const {
    return ifArgument_;
}

void IfActionUsage::setIfArgument(std::shared_ptr<KerML::Entities::Expression> value) {
    ifArgument_ = std::move(value);
}

IfActionUsage::IfActionUsage() {
    _dType = "IfActionUsage";
}

IfActionUsage::~IfActionUsage() = default;

std::string_view IfActionUsage::metaclassName() const noexcept {
    return "IfActionUsage";
}

std::vector<RepresentationIssue> IfActionUsage::validateRepresentation(bool includeDerived) const {
    std::vector<RepresentationIssue> issues; (void)includeDerived;
    { auto optional = OccurrenceUsage::portionKind(); if (optional) { auto value = *optional; if (!(value == PortionKind::timeslice || value == PortionKind::snapshot)) issues.push_back({"OccurrenceUsage.portionKind", "invalid enumeration value"}); } }
    if (includeDerived) if (!IfActionUsage::thenAction()) issues.push_back({"IfActionUsage.thenAction", "required reference is missing"});
    if (includeDerived) if (!IfActionUsage::ifArgument()) issues.push_back({"IfActionUsage.ifArgument", "required reference is missing"});
    return issues;
}

} // namespace SysMLv2::Entities
