// Generated by sysml/tools/generate_abstract_syntax.py.
#include <sysml/actions/JoinNode.h>
#include <algorithm>
#include <stdexcept>

namespace SysMLv2::Entities {

JoinNode::JoinNode() {
    _dType = "JoinNode";
}

JoinNode::~JoinNode() = default;

std::string_view JoinNode::metaclassName() const noexcept {
    return "JoinNode";
}

std::vector<RepresentationIssue> JoinNode::validateRepresentation(bool includeDerived) const {
    std::vector<RepresentationIssue> issues; (void)includeDerived;
    { auto optional = OccurrenceUsage::portionKind(); if (optional) { auto value = *optional; if (!(value == PortionKind::timeslice || value == PortionKind::snapshot)) issues.push_back({"OccurrenceUsage.portionKind", "invalid enumeration value"}); } }
    return issues;
}

} // namespace SysMLv2::Entities
