// Generated by sysml/tools/generate_abstract_syntax.py.
#include <sysml/actions/LoopActionUsage.h>
#include <sysml/actions/ActionUsage.h>
#include <algorithm>
#include <stdexcept>

namespace SysMLv2::Entities {

std::shared_ptr<ActionUsage> LoopActionUsage::bodyAction() const {
    return bodyAction_;
}

void LoopActionUsage::setBodyAction(std::shared_ptr<ActionUsage> value) {
    bodyAction_ = std::move(value);
}

LoopActionUsage::LoopActionUsage() {
    _dType = "LoopActionUsage";
}

LoopActionUsage::~LoopActionUsage() = default;

std::vector<RepresentationIssue> LoopActionUsage::validateRepresentation(bool includeDerived) const {
    std::vector<RepresentationIssue> issues; (void)includeDerived;
    { auto optional = OccurrenceUsage::portionKind(); if (optional) { auto value = *optional; if (!(value == PortionKind::timeslice || value == PortionKind::snapshot)) issues.push_back({"OccurrenceUsage.portionKind", "invalid enumeration value"}); } }
    if (includeDerived) if (!LoopActionUsage::bodyAction()) issues.push_back({"LoopActionUsage.bodyAction", "required reference is missing"});
    return issues;
}

} // namespace SysMLv2::Entities
