// Generated by sysml/tools/generate_abstract_syntax.py.
#include <sysml/actions/MergeNode.h>
#include <algorithm>
#include <stdexcept>

namespace SysMLv2::Entities {

MergeNode::MergeNode() {
    _dType = "MergeNode";
}

MergeNode::~MergeNode() = default;

std::string_view MergeNode::metaclassName() const noexcept {
    return "MergeNode";
}

std::vector<RepresentationIssue> MergeNode::validateRepresentation(bool includeDerived) const {
    std::vector<RepresentationIssue> issues; (void)includeDerived;
    { auto optional = OccurrenceUsage::portionKind(); if (optional) { auto value = *optional; if (!(value == PortionKind::timeslice || value == PortionKind::snapshot)) issues.push_back({"OccurrenceUsage.portionKind", "invalid enumeration value"}); } }
    return issues;
}

} // namespace SysMLv2::Entities
