// Generated by sysml/tools/generate_abstract_syntax.py.
#include <sysml/actions/PerformActionUsage.h>
#include <sysml/actions/ActionUsage.h>
#include <algorithm>
#include <stdexcept>

namespace SysMLv2::Entities {

std::shared_ptr<ActionUsage> PerformActionUsage::performedAction() const {
    return performedAction_;
}

void PerformActionUsage::setPerformedAction(std::shared_ptr<ActionUsage> value) {
    performedAction_ = std::move(value);
}

PerformActionUsage::PerformActionUsage() {
    _dType = "PerformActionUsage";
}

PerformActionUsage::~PerformActionUsage() = default;

std::string_view PerformActionUsage::metaclassName() const noexcept {
    return "PerformActionUsage";
}

std::vector<RepresentationIssue> PerformActionUsage::validateRepresentation(bool includeDerived) const {
    std::vector<RepresentationIssue> issues; (void)includeDerived;
    { auto optional = OccurrenceUsage::portionKind(); if (optional) { auto value = *optional; if (!(value == PortionKind::timeslice || value == PortionKind::snapshot)) issues.push_back({"OccurrenceUsage.portionKind", "invalid enumeration value"}); } }
    if (includeDerived) if (!EventOccurrenceUsage::eventOccurrence()) issues.push_back({"EventOccurrenceUsage.eventOccurrence", "required reference is missing"});
    if (includeDerived) if (!PerformActionUsage::performedAction()) issues.push_back({"PerformActionUsage.performedAction", "required reference is missing"});
    return issues;
}

} // namespace SysMLv2::Entities
