// Generated by sysml/tools/generate_abstract_syntax.py.
#include <sysml/actions/SendActionUsage.h>
#include <algorithm>
#include <stdexcept>

namespace SysMLv2::Entities {

std::shared_ptr<KerML::Entities::Expression> SendActionUsage::receiverArgument() const {
    return receiverArgument_;
}

void SendActionUsage::setReceiverArgument(std::shared_ptr<KerML::Entities::Expression> value) {
    receiverArgument_ = std::move(value);
}

std::shared_ptr<KerML::Entities::Expression> SendActionUsage::payloadArgument() const {
    return payloadArgument_;
}

void SendActionUsage::setPayloadArgument(std::shared_ptr<KerML::Entities::Expression> value) {
    payloadArgument_ = std::move(value);
}

std::shared_ptr<KerML::Entities::Expression> SendActionUsage::senderArgument() const {
    return senderArgument_;
}

void SendActionUsage::setSenderArgument(std::shared_ptr<KerML::Entities::Expression> value) {
    senderArgument_ = std::move(value);
}

SendActionUsage::SendActionUsage() {
    _dType = "SendActionUsage";
}

SendActionUsage::~SendActionUsage() = default;

std::string_view SendActionUsage::metaclassName() const noexcept {
    return "SendActionUsage";
}

std::vector<RepresentationIssue> SendActionUsage::validateRepresentation(bool includeDerived) const {
    std::vector<RepresentationIssue> issues; (void)includeDerived;
    { auto optional = OccurrenceUsage::portionKind(); if (optional) { auto value = *optional; if (!(value == PortionKind::timeslice || value == PortionKind::snapshot)) issues.push_back({"OccurrenceUsage.portionKind", "invalid enumeration value"}); } }
    if (includeDerived) if (!SendActionUsage::payloadArgument()) issues.push_back({"SendActionUsage.payloadArgument", "required reference is missing"});
    return issues;
}

} // namespace SysMLv2::Entities
