// Generated by sysml/tools/generate_abstract_syntax.py.
#include <sysml/actions/TerminateActionUsage.h>
#include <algorithm>
#include <stdexcept>

namespace SysMLv2::Entities {

std::shared_ptr<KerML::Entities::Expression> TerminateActionUsage::terminatedOccurrenceArgument() const {
    return terminatedOccurrenceArgument_;
}

void TerminateActionUsage::setTerminatedOccurrenceArgument(std::shared_ptr<KerML::Entities::Expression> value) {
    terminatedOccurrenceArgument_ = std::move(value);
}

TerminateActionUsage::TerminateActionUsage() {
    _dType = "TerminateActionUsage";
}

TerminateActionUsage::~TerminateActionUsage() = default;

std::string_view TerminateActionUsage::metaclassName() const noexcept {
    return "TerminateActionUsage";
}

std::vector<RepresentationIssue> TerminateActionUsage::validateRepresentation(bool includeDerived) const {
    std::vector<RepresentationIssue> issues; (void)includeDerived;
    { auto optional = OccurrenceUsage::portionKind(); if (optional) { auto value = *optional; if (!(value == PortionKind::timeslice || value == PortionKind::snapshot)) issues.push_back({"OccurrenceUsage.portionKind", "invalid enumeration value"}); } }
    return issues;
}

} // namespace SysMLv2::Entities
