// Generated by sysml/tools/generate_abstract_syntax.py.
#include <sysml/actions/TriggerInvocationExpression.h>
#include <sysml/actions/TriggerKind.h>
#include <algorithm>
#include <stdexcept>

namespace SysMLv2::Entities {

TriggerKind TriggerInvocationExpression::kind() const {
    return kind_;
}

void TriggerInvocationExpression::setKind(TriggerKind value) {
    kind_ = std::move(value);
}

TriggerInvocationExpression::TriggerInvocationExpression() {
    _dType = "TriggerInvocationExpression";
}

TriggerInvocationExpression::~TriggerInvocationExpression() = default;

std::string_view TriggerInvocationExpression::metaclassName() const noexcept {
    return "TriggerInvocationExpression";
}

std::vector<RepresentationIssue> TriggerInvocationExpression::validateRepresentation(bool includeDerived) const {
    std::vector<RepresentationIssue> issues; (void)includeDerived;
    { auto value = TriggerInvocationExpression::kind(); if (!(value == TriggerKind::when || value == TriggerKind::at || value == TriggerKind::after)) issues.push_back({"TriggerInvocationExpression.kind", "invalid enumeration value"}); }
    return issues;
}

} // namespace SysMLv2::Entities
