// Generated by sysml/tools/generate_abstract_syntax.py.
#include <sysml/actions/WhileLoopActionUsage.h>
#include <algorithm>
#include <stdexcept>

namespace SysMLv2::Entities {

std::shared_ptr<KerML::Entities::Expression> WhileLoopActionUsage::whileArgument() const {
    return whileArgument_;
}

void WhileLoopActionUsage::setWhileArgument(std::shared_ptr<KerML::Entities::Expression> value) {
    whileArgument_ = std::move(value);
}

std::shared_ptr<KerML::Entities::Expression> WhileLoopActionUsage::untilArgument() const {
    return untilArgument_;
}

void WhileLoopActionUsage::setUntilArgument(std::shared_ptr<KerML::Entities::Expression> value) {
    untilArgument_ = std::move(value);
}

WhileLoopActionUsage::WhileLoopActionUsage() {
    _dType = "WhileLoopActionUsage";
}

WhileLoopActionUsage::~WhileLoopActionUsage() = default;

std::string_view WhileLoopActionUsage::metaclassName() const noexcept {
    return "WhileLoopActionUsage";
}

std::vector<RepresentationIssue> WhileLoopActionUsage::validateRepresentation(bool includeDerived) const {
    std::vector<RepresentationIssue> issues; (void)includeDerived;
    { auto optional = OccurrenceUsage::portionKind(); if (optional) { auto value = *optional; if (!(value == PortionKind::timeslice || value == PortionKind::snapshot)) issues.push_back({"OccurrenceUsage.portionKind", "invalid enumeration value"}); } }
    if (includeDerived) if (!LoopActionUsage::bodyAction()) issues.push_back({"LoopActionUsage.bodyAction", "required reference is missing"});
    if (includeDerived) if (!WhileLoopActionUsage::whileArgument()) issues.push_back({"WhileLoopActionUsage.whileArgument", "required reference is missing"});
    return issues;
}

} // namespace SysMLv2::Entities
