// Generated by conformance-test/tools/generate_metaclass_name_test.py from the model headers. Do not edit by hand.
// Every concrete class is instantiated with each of its public constructors; getType() must be the exact metaclass name.
#include <gtest/gtest.h>
#include <iostream>
#include <exception>
#include <memory>
#include <vector>
#include <string>
#include <type_traits>
#include <boost/uuid/uuid.hpp>
#include <kerml/core/classifiers/Classifier.h>
#include <kerml/core/classifiers/Subclassification.h>
#include <kerml/core/features/CrossSubsetting.h>
#include <kerml/core/features/EndFeatureMembership.h>
#include <kerml/core/features/Feature.h>
#include <kerml/core/features/FeatureChaining.h>
#include <kerml/core/features/FeatureInverting.h>
#include <kerml/core/features/FeatureMembership.h>
#include <kerml/core/features/FeatureTyping.h>
#include <kerml/core/features/Multiplicity.h>
#include <kerml/core/features/Redefinition.h>
#include <kerml/core/features/ReferenceSubsetting.h>
#include <kerml/core/features/Subsetting.h>
#include <kerml/core/features/TypeFeaturing.h>
#include <kerml/core/types/Conjugation.h>
#include <kerml/core/types/Differencing.h>
#include <kerml/core/types/Disjoining.h>
#include <kerml/core/types/Intersecting.h>
#include <kerml/core/types/Specialization.h>
#include <kerml/core/types/Type.h>
#include <kerml/core/types/Unioning.h>
#include <kerml/kernel/assiciations/Association.h>
#include <kerml/kernel/assiciations/AssociationStructure.h>
#include <kerml/kernel/behaviors/Behavior.h>
#include <kerml/kernel/behaviors/Step.h>
#include <kerml/kernel/classes/Class.h>
#include <kerml/kernel/connectors/BindingConnector.h>
#include <kerml/kernel/connectors/Connector.h>
#include <kerml/kernel/connectors/Succession.h>
#include <kerml/kernel/datatypes/DataType.h>
#include <kerml/kernel/expressions/CollectExpression.h>
#include <kerml/kernel/expressions/ConstructorExpression.h>
#include <kerml/kernel/expressions/FeatureChainExpression.h>
#include <kerml/kernel/expressions/FeatureReferenceExpression.h>
#include <kerml/kernel/expressions/IndexExpression.h>
#include <kerml/kernel/expressions/InstantiationExpression.h>
#include <kerml/kernel/expressions/InvocationExpression.h>
#include <kerml/kernel/expressions/LiteralBoolean.h>
#include <kerml/kernel/expressions/LiteralExpression.h>
#include <kerml/kernel/expressions/LiteralInfinity.h>
#include <kerml/kernel/expressions/LiteralInteger.h>
#include <kerml/kernel/expressions/LiteralRational.h>
#include <kerml/kernel/expressions/LiteralString.h>
#include <kerml/kernel/expressions/MetadataAccessExpression.h>
#include <kerml/kernel/expressions/NullExpression.h>
#include <kerml/kernel/expressions/OperatorExpression.h>
#include <kerml/kernel/expressions/SelectExpression.h>
#include <kerml/kernel/featurevalues/FeatureValue.h>
#include <kerml/kernel/functions/BooleanExpression.h>
#include <kerml/kernel/functions/Expression.h>
#include <kerml/kernel/functions/Function.h>
#include <kerml/kernel/functions/Invariant.h>
#include <kerml/kernel/functions/ParameterMembership.h>
#include <kerml/kernel/functions/Predicate.h>
#include <kerml/kernel/functions/ResultExpressionMembership.h>
#include <kerml/kernel/functions/ReturnParameterMembership.h>
#include <kerml/kernel/interactions/Flow.h>
#include <kerml/kernel/interactions/FlowEnd.h>
#include <kerml/kernel/interactions/Interaction.h>
#include <kerml/kernel/interactions/PayloadFeature.h>
#include <kerml/kernel/interactions/SuccessionFlow.h>
#include <kerml/kernel/metadata/Metaclass.h>
#include <kerml/kernel/metadata/MetadataFeature.h>
#include <kerml/kernel/multiplicities/MultiplicityRange.h>
#include <kerml/kernel/packages/ElementFilterMembership.h>
#include <kerml/kernel/packages/LibraryPackage.h>
#include <kerml/kernel/packages/Package.h>
#include <kerml/kernel/structures/Structure.h>
#include <kerml/root/annotations/AnnotatingElement.h>
#include <kerml/root/annotations/Annotation.h>
#include <kerml/root/annotations/Comment.h>
#include <kerml/root/annotations/Documentation.h>
#include <kerml/root/annotations/TextualRepresentation.h>
#include <kerml/root/dependencies/Dependency.h>
#include <kerml/root/elements/Element.h>
#include <kerml/root/elements/Relationship.h>
#include <kerml/root/namespaces/Import.h>
#include <kerml/root/namespaces/Membership.h>
#include <kerml/root/namespaces/MembershipImport.h>
#include <kerml/root/namespaces/Namespace.h>
#include <kerml/root/namespaces/NamespaceImport.h>
#include <kerml/root/namespaces/OwningMembership.h>
#include <sysml/actions/AcceptActionUsage.h>
#include <sysml/actions/ActionDefinition.h>
#include <sysml/actions/ActionUsage.h>
#include <sysml/actions/AssignmentActionUsage.h>
#include <sysml/actions/ControlNode.h>
#include <sysml/actions/DecisionNode.h>
#include <sysml/actions/ForLoopActionUsage.h>
#include <sysml/actions/ForkNode.h>
#include <sysml/actions/IfActionUsage.h>
#include <sysml/actions/JoinNode.h>
#include <sysml/actions/LoopActionUsage.h>
#include <sysml/actions/MergeNode.h>
#include <sysml/actions/PerformActionUsage.h>
#include <sysml/actions/SendActionUsage.h>
#include <sysml/actions/TerminateActionUsage.h>
#include <sysml/actions/TriggerInvocationExpression.h>
#include <sysml/actions/WhileLoopActionUsage.h>
#include <sysml/allocations/AllocationDefinition.h>
#include <sysml/allocations/AllocationUsage.h>
#include <sysml/analysiscases/AnalysisCaseDefinition.h>
#include <sysml/analysiscases/AnalysisCaseUsage.h>
#include <sysml/attributes/AttributeDefinition.h>
#include <sysml/attributes/AttributeUsage.h>
#include <sysml/calculations/CalculationDefinition.h>
#include <sysml/calculations/CalculationUsage.h>
#include <sysml/cases/CaseDefinition.h>
#include <sysml/cases/CaseUsage.h>
#include <sysml/cases/ObjectiveMembership.h>
#include <sysml/connections/BindingConnectorAsUsage.h>
#include <sysml/connections/ConnectionDefinition.h>
#include <sysml/connections/ConnectionUsage.h>
#include <sysml/connections/ConnectorAsUsage.h>
#include <sysml/connections/SuccessionAsUsage.h>
#include <sysml/constraints/AssertConstraintUsage.h>
#include <sysml/constraints/ConstraintDefinition.h>
#include <sysml/constraints/ConstraintUsage.h>
#include <sysml/enumerations/EnumerationDefinition.h>
#include <sysml/enumerations/EnumerationUsage.h>
#include <sysml/flows/FlowDefinition.h>
#include <sysml/flows/FlowUsage.h>
#include <sysml/flows/SuccessionFlowUsage.h>
#include <sysml/interfaces/InterfaceDefinition.h>
#include <sysml/interfaces/InterfaceUsage.h>
#include <sysml/items/ItemDefinition.h>
#include <sysml/items/ItemUsage.h>
#include <sysml/metadata/MetadataDefinition.h>
#include <sysml/metadata/MetadataUsage.h>
#include <sysml/model/Representation.h>
#include <sysml/occurrences/EventOccurrenceUsage.h>
#include <sysml/occurrences/OccurrenceDefinition.h>
#include <sysml/occurrences/OccurrenceUsage.h>
#include <sysml/parts/PartDefinition.h>
#include <sysml/parts/PartUsage.h>
#include <sysml/ports/ConjugatedPortDefinition.h>
#include <sysml/ports/ConjugatedPortTyping.h>
#include <sysml/ports/PortConjugation.h>
#include <sysml/ports/PortDefinition.h>
#include <sysml/ports/PortUsage.h>
#include <sysml/requirements/ActorMembership.h>
#include <sysml/requirements/ConcernDefinition.h>
#include <sysml/requirements/ConcernUsage.h>
#include <sysml/requirements/FramedConcernMembership.h>
#include <sysml/requirements/RequirementConstraintMembership.h>
#include <sysml/requirements/RequirementDefinition.h>
#include <sysml/requirements/RequirementUsage.h>
#include <sysml/requirements/SatisfyRequirementUsage.h>
#include <sysml/requirements/StakeholderMembership.h>
#include <sysml/requirements/SubjectMembership.h>
#include <sysml/states/ExhibitStateUsage.h>
#include <sysml/states/StateDefinition.h>
#include <sysml/states/StateSubactionMembership.h>
#include <sysml/states/StateUsage.h>
#include <sysml/states/TransitionFeatureMembership.h>
#include <sysml/states/TransitionUsage.h>
#include <sysml/usage/Definition.h>
#include <sysml/usage/ReferenceUsage.h>
#include <sysml/usage/Usage.h>
#include <sysml/usage/VariantMembership.h>
#include <sysml/usecases/IncludeUseCaseUsage.h>
#include <sysml/usecases/UseCaseDefinition.h>
#include <sysml/usecases/UseCaseUsage.h>
#include <sysml/verificationcases/RequirementVerificationMembership.h>
#include <sysml/verificationcases/VerificationCaseDefinition.h>
#include <sysml/verificationcases/VerificationCaseUsage.h>
#include <sysml/views/Expose.h>
#include <sysml/views/MembershipExpose.h>
#include <sysml/views/NamespaceExpose.h>
#include <sysml/views/RenderingDefinition.h>
#include <sysml/views/RenderingUsage.h>
#include <sysml/views/ViewDefinition.h>
#include <sysml/views/ViewRenderingMembership.h>
#include <sysml/views/ViewUsage.h>
#include <sysml/views/ViewpointDefinition.h>
#include <sysml/views/ViewpointUsage.h>

namespace {
struct Failure { std::string cls; std::string what; };
template <class A, bool Sample> struct Arg { static A make() { return A{}; } };
template <class U> struct Arg<std::shared_ptr<U>, true> {
    static std::shared_ptr<U> make() { if constexpr (std::is_default_constructible_v<U> && !std::is_abstract_v<U>) return std::make_shared<U>(); else return nullptr; }
};
template <bool Sample> struct Arg<std::string, Sample> { static std::string make() { return Sample ? "00000000-0000-0000-0000-000000000001" : std::string(); } };
template <class T, bool Sample, class... Args>
void attempt(std::vector<Failure>& failures, const char* expected, unsigned& instantiated, const char* signature) {
    T object{Arg<Args, Sample>::make()...};
    ++instantiated;
    const std::string actual = object.getType();
    if (actual != expected) failures.push_back({expected, std::string(signature) + " reports getType() == \"" + actual + "\""});
    if constexpr (requires { object.metaclassName(); }) {
        if (std::string(object.metaclassName()) != expected) failures.push_back({expected, std::string(signature) + " reports metaclassName() == \"" + std::string(object.metaclassName()) + "\""});
    }
}
template <class T, class... Args>
void check(std::vector<Failure>& failures, const char* expected, unsigned& instantiated, const char* signature, std::vector<std::string>& skipped) {
    if constexpr (std::is_abstract_v<T> || !std::is_constructible_v<T, Args...>) { (void)failures; (void)expected; (void)instantiated; (void)signature; (void)skipped; }
    else {
        try { attempt<T, false, Args...>(failures, expected, instantiated, signature); return; } catch (const std::exception&) {}
        try { attempt<T, true, Args...>(failures, expected, instantiated, signature); }
        catch (const std::exception& e) { skipped.push_back(std::string(expected) + ": " + signature + " rejects the sample arguments (" + e.what() + ")"); }
    }
}

void check_kerml(std::vector<Failure>& failures, unsigned& instantiated, unsigned& classes, std::vector<std::string>& skipped) {
    using namespace KerML::Entities;
    if constexpr (!std::is_abstract_v<Classifier>) { ++classes;
        check<Classifier, boost::uuids::uuid, std::shared_ptr<Element>>(failures, "Classifier", instantiated, "Classifier(boost::uuids::uuid, std::shared_ptr<Element>)", skipped);
        check<Classifier, std::string, boost::uuids::uuid, std::shared_ptr<Element>>(failures, "Classifier", instantiated, "Classifier(std::string, boost::uuids::uuid, std::shared_ptr<Element>)", skipped);
    }
    if constexpr (!std::is_abstract_v<Subclassification>) { ++classes;
        check<Subclassification, std::shared_ptr<Classifier>, std::shared_ptr<Classifier>>(failures, "Subclassification", instantiated, "Subclassification(std::shared_ptr<Classifier>, std::shared_ptr<Classifier>)", skipped);
    }
    if constexpr (!std::is_abstract_v<CrossSubsetting>) { ++classes;
        check<CrossSubsetting, std::shared_ptr<Feature>, std::shared_ptr<Feature>>(failures, "CrossSubsetting", instantiated, "CrossSubsetting(std::shared_ptr<Feature>, std::shared_ptr<Feature>)", skipped);
    }
    if constexpr (!std::is_abstract_v<EndFeatureMembership>) { ++classes;
        check<EndFeatureMembership, std::shared_ptr<Feature>, std::shared_ptr<Type>, std::vector<std::shared_ptr<Type>>>(failures, "EndFeatureMembership", instantiated, "EndFeatureMembership(std::shared_ptr<Feature>, std::shared_ptr<Type>, std::vector<std::shared_ptr<Type>>)", skipped);
    }
    if constexpr (!std::is_abstract_v<Feature>) { ++classes;
        check<Feature>(failures, "Feature", instantiated, "Feature()", skipped);
    }
    if constexpr (!std::is_abstract_v<FeatureChaining>) { ++classes;
        check<FeatureChaining, std::shared_ptr<Feature>, std::shared_ptr<Feature>, boost::uuids::uuid, std::shared_ptr<Element>>(failures, "FeatureChaining", instantiated, "FeatureChaining(std::shared_ptr<Feature>, std::shared_ptr<Feature>, boost::uuids::uuid, std::shared_ptr<Element>)", skipped);
    }
    if constexpr (!std::is_abstract_v<FeatureInverting>) { ++classes;
        check<FeatureInverting, std::shared_ptr<Feature>, std::shared_ptr<Feature>, boost::uuids::uuid, std::shared_ptr<Element>>(failures, "FeatureInverting", instantiated, "FeatureInverting(std::shared_ptr<Feature>, std::shared_ptr<Feature>, boost::uuids::uuid, std::shared_ptr<Element>)", skipped);
    }
    if constexpr (!std::is_abstract_v<FeatureMembership>) { ++classes;
        check<FeatureMembership>(failures, "FeatureMembership", instantiated, "FeatureMembership()", skipped);
        check<FeatureMembership, std::shared_ptr<Feature>, std::shared_ptr<Type>, std::vector<std::shared_ptr<Type>>>(failures, "FeatureMembership", instantiated, "FeatureMembership(std::shared_ptr<Feature>, std::shared_ptr<Type>, std::vector<std::shared_ptr<Type>>)", skipped);
    }
    if constexpr (!std::is_abstract_v<FeatureTyping>) { ++classes;
        check<FeatureTyping>(failures, "FeatureTyping", instantiated, "FeatureTyping()", skipped);
        check<FeatureTyping, std::shared_ptr<KerML::Entities::Type>, std::shared_ptr<KerML::Entities::Feature>>(failures, "FeatureTyping", instantiated, "FeatureTyping(std::shared_ptr<KerML::Entities::Type>, std::shared_ptr<KerML::Entities::Feature>)", skipped);
    }
    if constexpr (!std::is_abstract_v<Multiplicity>) { ++classes;
        check<Multiplicity>(failures, "Multiplicity", instantiated, "Multiplicity()", skipped);
        check<Multiplicity, unsigned>(failures, "Multiplicity", instantiated, "Multiplicity(unsigned)", skipped);
        check<Multiplicity, unsigned, unsigned>(failures, "Multiplicity", instantiated, "Multiplicity(unsigned, unsigned)", skipped);
        check<Multiplicity, unsigned, bool>(failures, "Multiplicity", instantiated, "Multiplicity(unsigned, bool)", skipped);
    }
    if constexpr (!std::is_abstract_v<Redefinition>) { ++classes;
        check<Redefinition, std::shared_ptr<Feature>, std::shared_ptr<Feature>>(failures, "Redefinition", instantiated, "Redefinition(std::shared_ptr<Feature>, std::shared_ptr<Feature>)", skipped);
    }
    if constexpr (!std::is_abstract_v<ReferenceSubsetting>) { ++classes;
        check<ReferenceSubsetting, std::shared_ptr<Feature>, std::shared_ptr<Feature>>(failures, "ReferenceSubsetting", instantiated, "ReferenceSubsetting(std::shared_ptr<Feature>, std::shared_ptr<Feature>)", skipped);
    }
    if constexpr (!std::is_abstract_v<Subsetting>) { ++classes;
        check<Subsetting, std::shared_ptr<Feature>, std::shared_ptr<Feature>>(failures, "Subsetting", instantiated, "Subsetting(std::shared_ptr<Feature>, std::shared_ptr<Feature>)", skipped);
    }
    if constexpr (!std::is_abstract_v<TypeFeaturing>) { ++classes;
        check<TypeFeaturing, std::shared_ptr<Type>, std::shared_ptr<Feature>, std::shared_ptr<Feature>>(failures, "TypeFeaturing", instantiated, "TypeFeaturing(std::shared_ptr<Type>, std::shared_ptr<Feature>, std::shared_ptr<Feature>)", skipped);
    }
    if constexpr (!std::is_abstract_v<Conjugation>) { ++classes;
        check<Conjugation>(failures, "Conjugation", instantiated, "Conjugation()", skipped);
        check<Conjugation, std::shared_ptr<Type>, std::shared_ptr<Type>>(failures, "Conjugation", instantiated, "Conjugation(std::shared_ptr<Type>, std::shared_ptr<Type>)", skipped);
    }
    if constexpr (!std::is_abstract_v<Differencing>) { ++classes;
        check<Differencing, std::shared_ptr<Type>, std::shared_ptr<Type>>(failures, "Differencing", instantiated, "Differencing(std::shared_ptr<Type>, std::shared_ptr<Type>)", skipped);
    }
    if constexpr (!std::is_abstract_v<Disjoining>) { ++classes;
        check<Disjoining, std::shared_ptr<Type>, std::shared_ptr<Type>>(failures, "Disjoining", instantiated, "Disjoining(std::shared_ptr<Type>, std::shared_ptr<Type>)", skipped);
    }
    if constexpr (!std::is_abstract_v<Intersecting>) { ++classes;
        check<Intersecting, std::shared_ptr<Type>, std::shared_ptr<Type>>(failures, "Intersecting", instantiated, "Intersecting(std::shared_ptr<Type>, std::shared_ptr<Type>)", skipped);
    }
    if constexpr (!std::is_abstract_v<Specialization>) { ++classes;
        check<Specialization>(failures, "Specialization", instantiated, "Specialization()", skipped);
        check<Specialization, std::shared_ptr<Type>, std::shared_ptr<Type>>(failures, "Specialization", instantiated, "Specialization(std::shared_ptr<Type>, std::shared_ptr<Type>)", skipped);
    }
    if constexpr (!std::is_abstract_v<Type>) { ++classes;
        check<Type, boost::uuids::uuid, std::shared_ptr<Element>>(failures, "Type", instantiated, "Type(boost::uuids::uuid, std::shared_ptr<Element>)", skipped);
        check<Type, std::string, boost::uuids::uuid, std::shared_ptr<Element>>(failures, "Type", instantiated, "Type(std::string, boost::uuids::uuid, std::shared_ptr<Element>)", skipped);
    }
    if constexpr (!std::is_abstract_v<Unioning>) { ++classes;
        check<Unioning, std::shared_ptr<Type>, std::shared_ptr<Type>>(failures, "Unioning", instantiated, "Unioning(std::shared_ptr<Type>, std::shared_ptr<Type>)", skipped);
    }
    if constexpr (!std::is_abstract_v<Association>) { ++classes;
        check<Association>(failures, "Association", instantiated, "Association()", skipped);
    }
    if constexpr (!std::is_abstract_v<AssociationStructure>) { ++classes;
        check<AssociationStructure>(failures, "AssociationStructure", instantiated, "AssociationStructure()", skipped);
    }
    if constexpr (!std::is_abstract_v<Behavior>) { ++classes;
        check<Behavior>(failures, "Behavior", instantiated, "Behavior()", skipped);
    }
    if constexpr (!std::is_abstract_v<Step>) { ++classes;
        check<Step>(failures, "Step", instantiated, "Step()", skipped);
    }
    if constexpr (!std::is_abstract_v<Class>) { ++classes;
        check<Class>(failures, "Class", instantiated, "Class()", skipped);
    }
    if constexpr (!std::is_abstract_v<BindingConnector>) { ++classes;
        check<BindingConnector>(failures, "BindingConnector", instantiated, "BindingConnector()", skipped);
    }
    if constexpr (!std::is_abstract_v<Connector>) { ++classes;
        check<Connector>(failures, "Connector", instantiated, "Connector()", skipped);
    }
    if constexpr (!std::is_abstract_v<Succession>) { ++classes;
        check<Succession>(failures, "Succession", instantiated, "Succession()", skipped);
    }
    if constexpr (!std::is_abstract_v<DataType>) { ++classes;
        check<DataType>(failures, "DataType", instantiated, "DataType()", skipped);
    }
    if constexpr (!std::is_abstract_v<CollectExpression>) { ++classes;
        check<CollectExpression>(failures, "CollectExpression", instantiated, "CollectExpression()", skipped);
    }
    if constexpr (!std::is_abstract_v<ConstructorExpression>) { ++classes;
        check<ConstructorExpression>(failures, "ConstructorExpression", instantiated, "ConstructorExpression()", skipped);
    }
    if constexpr (!std::is_abstract_v<FeatureChainExpression>) { ++classes;
        check<FeatureChainExpression>(failures, "FeatureChainExpression", instantiated, "FeatureChainExpression()", skipped);
    }
    if constexpr (!std::is_abstract_v<FeatureReferenceExpression>) { ++classes;
        check<FeatureReferenceExpression>(failures, "FeatureReferenceExpression", instantiated, "FeatureReferenceExpression()", skipped);
    }
    if constexpr (!std::is_abstract_v<IndexExpression>) { ++classes;
        check<IndexExpression>(failures, "IndexExpression", instantiated, "IndexExpression()", skipped);
    }
    if constexpr (!std::is_abstract_v<InstantiationExpression>) { ++classes;
        check<InstantiationExpression>(failures, "InstantiationExpression", instantiated, "InstantiationExpression()", skipped);
    }
    if constexpr (!std::is_abstract_v<InvocationExpression>) { ++classes;
        check<InvocationExpression>(failures, "InvocationExpression", instantiated, "InvocationExpression()", skipped);
    }
    if constexpr (!std::is_abstract_v<LiteralBoolean>) { ++classes;
        check<LiteralBoolean>(failures, "LiteralBoolean", instantiated, "LiteralBoolean()", skipped);
    }
    if constexpr (!std::is_abstract_v<LiteralExpression>) { ++classes;
        check<LiteralExpression>(failures, "LiteralExpression", instantiated, "LiteralExpression()", skipped);
    }
    if constexpr (!std::is_abstract_v<LiteralInfinity>) { ++classes;
        check<LiteralInfinity>(failures, "LiteralInfinity", instantiated, "LiteralInfinity()", skipped);
    }
    if constexpr (!std::is_abstract_v<LiteralInteger>) { ++classes;
        check<LiteralInteger>(failures, "LiteralInteger", instantiated, "LiteralInteger()", skipped);
    }
    if constexpr (!std::is_abstract_v<LiteralRational>) { ++classes;
        check<LiteralRational>(failures, "LiteralRational", instantiated, "LiteralRational()", skipped);
    }
    if constexpr (!std::is_abstract_v<LiteralString>) { ++classes;
        check<LiteralString>(failures, "LiteralString", instantiated, "LiteralString()", skipped);
    }
    if constexpr (!std::is_abstract_v<MetadataAccessExpression>) { ++classes;
        check<MetadataAccessExpression>(failures, "MetadataAccessExpression", instantiated, "MetadataAccessExpression()", skipped);
    }
    if constexpr (!std::is_abstract_v<NullExpression>) { ++classes;
        check<NullExpression>(failures, "NullExpression", instantiated, "NullExpression()", skipped);
    }
    if constexpr (!std::is_abstract_v<OperatorExpression>) { ++classes;
        check<OperatorExpression>(failures, "OperatorExpression", instantiated, "OperatorExpression()", skipped);
    }
    if constexpr (!std::is_abstract_v<SelectExpression>) { ++classes;
        check<SelectExpression>(failures, "SelectExpression", instantiated, "SelectExpression()", skipped);
    }
    if constexpr (!std::is_abstract_v<FeatureValue>) { ++classes;
        check<FeatureValue>(failures, "FeatureValue", instantiated, "FeatureValue()", skipped);
    }
    if constexpr (!std::is_abstract_v<BooleanExpression>) { ++classes;
        check<BooleanExpression>(failures, "BooleanExpression", instantiated, "BooleanExpression()", skipped);
    }
    if constexpr (!std::is_abstract_v<Expression>) { ++classes;
        check<Expression>(failures, "Expression", instantiated, "Expression()", skipped);
    }
    if constexpr (!std::is_abstract_v<Function>) { ++classes;
        check<Function>(failures, "Function", instantiated, "Function()", skipped);
    }
    if constexpr (!std::is_abstract_v<Invariant>) { ++classes;
        check<Invariant>(failures, "Invariant", instantiated, "Invariant()", skipped);
    }
    if constexpr (!std::is_abstract_v<ParameterMembership>) { ++classes;
        check<ParameterMembership>(failures, "ParameterMembership", instantiated, "ParameterMembership()", skipped);
    }
    if constexpr (!std::is_abstract_v<Predicate>) { ++classes;
        check<Predicate>(failures, "Predicate", instantiated, "Predicate()", skipped);
    }
    if constexpr (!std::is_abstract_v<ResultExpressionMembership>) { ++classes;
        check<ResultExpressionMembership>(failures, "ResultExpressionMembership", instantiated, "ResultExpressionMembership()", skipped);
        check<ResultExpressionMembership, std::shared_ptr<Expression>, std::shared_ptr<Type>>(failures, "ResultExpressionMembership", instantiated, "ResultExpressionMembership(std::shared_ptr<Expression>, std::shared_ptr<Type>)", skipped);
    }
    if constexpr (!std::is_abstract_v<ReturnParameterMembership>) { ++classes;
        check<ReturnParameterMembership>(failures, "ReturnParameterMembership", instantiated, "ReturnParameterMembership()", skipped);
    }
    if constexpr (!std::is_abstract_v<Flow>) { ++classes;
        check<Flow>(failures, "Flow", instantiated, "Flow()", skipped);
    }
    if constexpr (!std::is_abstract_v<FlowEnd>) { ++classes;
        check<FlowEnd>(failures, "FlowEnd", instantiated, "FlowEnd()", skipped);
    }
    if constexpr (!std::is_abstract_v<Interaction>) { ++classes;
        check<Interaction>(failures, "Interaction", instantiated, "Interaction()", skipped);
    }
    if constexpr (!std::is_abstract_v<PayloadFeature>) { ++classes;
        check<PayloadFeature>(failures, "PayloadFeature", instantiated, "PayloadFeature()", skipped);
    }
    if constexpr (!std::is_abstract_v<SuccessionFlow>) { ++classes;
        check<SuccessionFlow>(failures, "SuccessionFlow", instantiated, "SuccessionFlow()", skipped);
    }
    if constexpr (!std::is_abstract_v<Metaclass>) { ++classes;
        check<Metaclass>(failures, "Metaclass", instantiated, "Metaclass()", skipped);
    }
    if constexpr (!std::is_abstract_v<MetadataFeature>) { ++classes;
        check<MetadataFeature>(failures, "MetadataFeature", instantiated, "MetadataFeature()", skipped);
    }
    if constexpr (!std::is_abstract_v<MultiplicityRange>) { ++classes;
        check<MultiplicityRange>(failures, "MultiplicityRange", instantiated, "MultiplicityRange()", skipped);
    }
    if constexpr (!std::is_abstract_v<ElementFilterMembership>) { ++classes;
        check<ElementFilterMembership>(failures, "ElementFilterMembership", instantiated, "ElementFilterMembership()", skipped);
    }
    if constexpr (!std::is_abstract_v<LibraryPackage>) { ++classes;
        check<LibraryPackage>(failures, "LibraryPackage", instantiated, "LibraryPackage()", skipped);
    }
    if constexpr (!std::is_abstract_v<Package>) { ++classes;
        check<Package>(failures, "Package", instantiated, "Package()", skipped);
    }
    if constexpr (!std::is_abstract_v<Structure>) { ++classes;
        check<Structure>(failures, "Structure", instantiated, "Structure()", skipped);
    }
    if constexpr (!std::is_abstract_v<AnnotatingElement>) { ++classes;
        check<AnnotatingElement>(failures, "AnnotatingElement", instantiated, "AnnotatingElement()", skipped);
    }
    if constexpr (!std::is_abstract_v<Annotation>) { ++classes;
        check<Annotation, boost::uuids::uuid, std::shared_ptr<Element>>(failures, "Annotation", instantiated, "Annotation(boost::uuids::uuid, std::shared_ptr<Element>)", skipped);
        check<Annotation, std::string, std::shared_ptr<Element>>(failures, "Annotation", instantiated, "Annotation(std::string, std::shared_ptr<Element>)", skipped);
    }
    if constexpr (!std::is_abstract_v<Comment>) { ++classes;
        check<Comment>(failures, "Comment", instantiated, "Comment()", skipped);
        check<Comment, std::string, std::string>(failures, "Comment", instantiated, "Comment(std::string, std::string)", skipped);
    }
    if constexpr (!std::is_abstract_v<Documentation>) { ++classes;
        check<Documentation, std::shared_ptr<Element>, std::string, std::string>(failures, "Documentation", instantiated, "Documentation(std::shared_ptr<Element>, std::string, std::string)", skipped);
    }
    if constexpr (!std::is_abstract_v<TextualRepresentation>) { ++classes;
        check<TextualRepresentation>(failures, "TextualRepresentation", instantiated, "TextualRepresentation()", skipped);
        check<TextualRepresentation, std::string, std::string>(failures, "TextualRepresentation", instantiated, "TextualRepresentation(std::string, std::string)", skipped);
        check<TextualRepresentation, std::string>(failures, "TextualRepresentation", instantiated, "TextualRepresentation(std::string)", skipped);
    }
    if constexpr (!std::is_abstract_v<Dependency>) { ++classes;
        check<Dependency, boost::uuids::uuid, std::shared_ptr<Element>>(failures, "Dependency", instantiated, "Dependency(boost::uuids::uuid, std::shared_ptr<Element>)", skipped);
        check<Dependency, std::string, std::shared_ptr<Element>>(failures, "Dependency", instantiated, "Dependency(std::string, std::shared_ptr<Element>)", skipped);
    }
    if constexpr (!std::is_abstract_v<Element>) { ++classes;
        check<Element, boost::uuids::uuid, std::shared_ptr<Element>>(failures, "Element", instantiated, "Element(boost::uuids::uuid, std::shared_ptr<Element>)", skipped);
        check<Element, std::string, std::shared_ptr<Element>>(failures, "Element", instantiated, "Element(std::string, std::shared_ptr<Element>)", skipped);
    }
    if constexpr (!std::is_abstract_v<Relationship>) { ++classes;
        check<Relationship, boost::uuids::uuid, std::shared_ptr<Element>>(failures, "Relationship", instantiated, "Relationship(boost::uuids::uuid, std::shared_ptr<Element>)", skipped);
        check<Relationship, std::string, std::shared_ptr<Element>>(failures, "Relationship", instantiated, "Relationship(std::string, std::shared_ptr<Element>)", skipped);
    }
    if constexpr (!std::is_abstract_v<Membership>) { ++classes;
        check<Membership>(failures, "Membership", instantiated, "Membership()", skipped);
    }
    if constexpr (!std::is_abstract_v<MembershipImport>) { ++classes;
        check<MembershipImport>(failures, "MembershipImport", instantiated, "MembershipImport()", skipped);
    }
    if constexpr (!std::is_abstract_v<Namespace>) { ++classes;
        check<Namespace, boost::uuids::uuid, std::shared_ptr<Element>>(failures, "Namespace", instantiated, "Namespace(boost::uuids::uuid, std::shared_ptr<Element>)", skipped);
        check<Namespace, std::string, boost::uuids::uuid, std::shared_ptr<Element>>(failures, "Namespace", instantiated, "Namespace(std::string, boost::uuids::uuid, std::shared_ptr<Element>)", skipped);
        check<Namespace, std::string, bool, boost::uuids::uuid, std::shared_ptr<Element>>(failures, "Namespace", instantiated, "Namespace(std::string, bool, boost::uuids::uuid, std::shared_ptr<Element>)", skipped);
    }
    if constexpr (!std::is_abstract_v<NamespaceImport>) { ++classes;
        check<NamespaceImport, boost::uuids::uuid, std::shared_ptr<Element>>(failures, "NamespaceImport", instantiated, "NamespaceImport(boost::uuids::uuid, std::shared_ptr<Element>)", skipped);
        check<NamespaceImport, std::string, std::shared_ptr<Element>>(failures, "NamespaceImport", instantiated, "NamespaceImport(std::string, std::shared_ptr<Element>)", skipped);
        check<NamespaceImport, VisibilityKind, bool, bool, std::shared_ptr<Namespace>, std::shared_ptr<Namespace>, boost::uuids::uuid, std::shared_ptr<Element>>(failures, "NamespaceImport", instantiated, "NamespaceImport(VisibilityKind, bool, bool, std::shared_ptr<Namespace>, std::shared_ptr<Namespace>, boost::uuids::uuid, std::shared_ptr<Element>)", skipped);
    }
    if constexpr (!std::is_abstract_v<OwningMembership>) { ++classes;
        check<OwningMembership>(failures, "OwningMembership", instantiated, "OwningMembership()", skipped);
    }
}

void check_sysml(std::vector<Failure>& failures, unsigned& instantiated, unsigned& classes, std::vector<std::string>& skipped) {
    using namespace SysMLv2::Entities;
    if constexpr (!std::is_abstract_v<AcceptActionUsage>) { ++classes;
        check<AcceptActionUsage>(failures, "AcceptActionUsage", instantiated, "AcceptActionUsage()", skipped);
    }
    if constexpr (!std::is_abstract_v<ActionDefinition>) { ++classes;
        check<ActionDefinition>(failures, "ActionDefinition", instantiated, "ActionDefinition()", skipped);
    }
    if constexpr (!std::is_abstract_v<ActionUsage>) { ++classes;
        check<ActionUsage>(failures, "ActionUsage", instantiated, "ActionUsage()", skipped);
    }
    if constexpr (!std::is_abstract_v<AssignmentActionUsage>) { ++classes;
        check<AssignmentActionUsage>(failures, "AssignmentActionUsage", instantiated, "AssignmentActionUsage()", skipped);
    }
    if constexpr (!std::is_abstract_v<DecisionNode>) { ++classes;
        check<DecisionNode>(failures, "DecisionNode", instantiated, "DecisionNode()", skipped);
    }
    if constexpr (!std::is_abstract_v<ForLoopActionUsage>) { ++classes;
        check<ForLoopActionUsage>(failures, "ForLoopActionUsage", instantiated, "ForLoopActionUsage()", skipped);
    }
    if constexpr (!std::is_abstract_v<ForkNode>) { ++classes;
        check<ForkNode>(failures, "ForkNode", instantiated, "ForkNode()", skipped);
    }
    if constexpr (!std::is_abstract_v<IfActionUsage>) { ++classes;
        check<IfActionUsage>(failures, "IfActionUsage", instantiated, "IfActionUsage()", skipped);
    }
    if constexpr (!std::is_abstract_v<JoinNode>) { ++classes;
        check<JoinNode>(failures, "JoinNode", instantiated, "JoinNode()", skipped);
    }
    if constexpr (!std::is_abstract_v<MergeNode>) { ++classes;
        check<MergeNode>(failures, "MergeNode", instantiated, "MergeNode()", skipped);
    }
    if constexpr (!std::is_abstract_v<PerformActionUsage>) { ++classes;
        check<PerformActionUsage>(failures, "PerformActionUsage", instantiated, "PerformActionUsage()", skipped);
    }
    if constexpr (!std::is_abstract_v<SendActionUsage>) { ++classes;
        check<SendActionUsage>(failures, "SendActionUsage", instantiated, "SendActionUsage()", skipped);
    }
    if constexpr (!std::is_abstract_v<TerminateActionUsage>) { ++classes;
        check<TerminateActionUsage>(failures, "TerminateActionUsage", instantiated, "TerminateActionUsage()", skipped);
    }
    if constexpr (!std::is_abstract_v<TriggerInvocationExpression>) { ++classes;
        check<TriggerInvocationExpression>(failures, "TriggerInvocationExpression", instantiated, "TriggerInvocationExpression()", skipped);
    }
    if constexpr (!std::is_abstract_v<WhileLoopActionUsage>) { ++classes;
        check<WhileLoopActionUsage>(failures, "WhileLoopActionUsage", instantiated, "WhileLoopActionUsage()", skipped);
    }
    if constexpr (!std::is_abstract_v<AllocationDefinition>) { ++classes;
        check<AllocationDefinition>(failures, "AllocationDefinition", instantiated, "AllocationDefinition()", skipped);
    }
    if constexpr (!std::is_abstract_v<AllocationUsage>) { ++classes;
        check<AllocationUsage>(failures, "AllocationUsage", instantiated, "AllocationUsage()", skipped);
    }
    if constexpr (!std::is_abstract_v<AnalysisCaseDefinition>) { ++classes;
        check<AnalysisCaseDefinition>(failures, "AnalysisCaseDefinition", instantiated, "AnalysisCaseDefinition()", skipped);
    }
    if constexpr (!std::is_abstract_v<AnalysisCaseUsage>) { ++classes;
        check<AnalysisCaseUsage>(failures, "AnalysisCaseUsage", instantiated, "AnalysisCaseUsage()", skipped);
    }
    if constexpr (!std::is_abstract_v<AttributeDefinition>) { ++classes;
        check<AttributeDefinition>(failures, "AttributeDefinition", instantiated, "AttributeDefinition()", skipped);
    }
    if constexpr (!std::is_abstract_v<AttributeUsage>) { ++classes;
        check<AttributeUsage>(failures, "AttributeUsage", instantiated, "AttributeUsage()", skipped);
    }
    if constexpr (!std::is_abstract_v<CalculationDefinition>) { ++classes;
        check<CalculationDefinition>(failures, "CalculationDefinition", instantiated, "CalculationDefinition()", skipped);
    }
    if constexpr (!std::is_abstract_v<CalculationUsage>) { ++classes;
        check<CalculationUsage>(failures, "CalculationUsage", instantiated, "CalculationUsage()", skipped);
    }
    if constexpr (!std::is_abstract_v<CaseDefinition>) { ++classes;
        check<CaseDefinition>(failures, "CaseDefinition", instantiated, "CaseDefinition()", skipped);
    }
    if constexpr (!std::is_abstract_v<CaseUsage>) { ++classes;
        check<CaseUsage>(failures, "CaseUsage", instantiated, "CaseUsage()", skipped);
    }
    if constexpr (!std::is_abstract_v<ObjectiveMembership>) { ++classes;
        check<ObjectiveMembership>(failures, "ObjectiveMembership", instantiated, "ObjectiveMembership()", skipped);
    }
    if constexpr (!std::is_abstract_v<BindingConnectorAsUsage>) { ++classes;
        check<BindingConnectorAsUsage>(failures, "BindingConnectorAsUsage", instantiated, "BindingConnectorAsUsage()", skipped);
    }
    if constexpr (!std::is_abstract_v<ConnectionDefinition>) { ++classes;
        check<ConnectionDefinition>(failures, "ConnectionDefinition", instantiated, "ConnectionDefinition()", skipped);
    }
    if constexpr (!std::is_abstract_v<ConnectionUsage>) { ++classes;
        check<ConnectionUsage>(failures, "ConnectionUsage", instantiated, "ConnectionUsage()", skipped);
    }
    if constexpr (!std::is_abstract_v<SuccessionAsUsage>) { ++classes;
        check<SuccessionAsUsage>(failures, "SuccessionAsUsage", instantiated, "SuccessionAsUsage()", skipped);
    }
    if constexpr (!std::is_abstract_v<AssertConstraintUsage>) { ++classes;
        check<AssertConstraintUsage>(failures, "AssertConstraintUsage", instantiated, "AssertConstraintUsage()", skipped);
    }
    if constexpr (!std::is_abstract_v<ConstraintDefinition>) { ++classes;
        check<ConstraintDefinition>(failures, "ConstraintDefinition", instantiated, "ConstraintDefinition()", skipped);
    }
    if constexpr (!std::is_abstract_v<ConstraintUsage>) { ++classes;
        check<ConstraintUsage>(failures, "ConstraintUsage", instantiated, "ConstraintUsage()", skipped);
    }
    if constexpr (!std::is_abstract_v<EnumerationDefinition>) { ++classes;
        check<EnumerationDefinition>(failures, "EnumerationDefinition", instantiated, "EnumerationDefinition()", skipped);
    }
    if constexpr (!std::is_abstract_v<EnumerationUsage>) { ++classes;
        check<EnumerationUsage>(failures, "EnumerationUsage", instantiated, "EnumerationUsage()", skipped);
    }
    if constexpr (!std::is_abstract_v<FlowDefinition>) { ++classes;
        check<FlowDefinition>(failures, "FlowDefinition", instantiated, "FlowDefinition()", skipped);
    }
    if constexpr (!std::is_abstract_v<FlowUsage>) { ++classes;
        check<FlowUsage>(failures, "FlowUsage", instantiated, "FlowUsage()", skipped);
    }
    if constexpr (!std::is_abstract_v<SuccessionFlowUsage>) { ++classes;
        check<SuccessionFlowUsage>(failures, "SuccessionFlowUsage", instantiated, "SuccessionFlowUsage()", skipped);
    }
    if constexpr (!std::is_abstract_v<InterfaceDefinition>) { ++classes;
        check<InterfaceDefinition>(failures, "InterfaceDefinition", instantiated, "InterfaceDefinition()", skipped);
    }
    if constexpr (!std::is_abstract_v<InterfaceUsage>) { ++classes;
        check<InterfaceUsage>(failures, "InterfaceUsage", instantiated, "InterfaceUsage()", skipped);
    }
    if constexpr (!std::is_abstract_v<ItemDefinition>) { ++classes;
        check<ItemDefinition>(failures, "ItemDefinition", instantiated, "ItemDefinition()", skipped);
    }
    if constexpr (!std::is_abstract_v<ItemUsage>) { ++classes;
        check<ItemUsage>(failures, "ItemUsage", instantiated, "ItemUsage()", skipped);
    }
    if constexpr (!std::is_abstract_v<MetadataDefinition>) { ++classes;
        check<MetadataDefinition>(failures, "MetadataDefinition", instantiated, "MetadataDefinition()", skipped);
    }
    if constexpr (!std::is_abstract_v<MetadataUsage>) { ++classes;
        check<MetadataUsage>(failures, "MetadataUsage", instantiated, "MetadataUsage()", skipped);
    }
    if constexpr (!std::is_abstract_v<EventOccurrenceUsage>) { ++classes;
        check<EventOccurrenceUsage>(failures, "EventOccurrenceUsage", instantiated, "EventOccurrenceUsage()", skipped);
    }
    if constexpr (!std::is_abstract_v<OccurrenceDefinition>) { ++classes;
        check<OccurrenceDefinition>(failures, "OccurrenceDefinition", instantiated, "OccurrenceDefinition()", skipped);
    }
    if constexpr (!std::is_abstract_v<OccurrenceUsage>) { ++classes;
        check<OccurrenceUsage>(failures, "OccurrenceUsage", instantiated, "OccurrenceUsage()", skipped);
    }
    if constexpr (!std::is_abstract_v<PartDefinition>) { ++classes;
        check<PartDefinition>(failures, "PartDefinition", instantiated, "PartDefinition()", skipped);
    }
    if constexpr (!std::is_abstract_v<PartUsage>) { ++classes;
        check<PartUsage>(failures, "PartUsage", instantiated, "PartUsage()", skipped);
    }
    if constexpr (!std::is_abstract_v<ConjugatedPortDefinition>) { ++classes;
        check<ConjugatedPortDefinition>(failures, "ConjugatedPortDefinition", instantiated, "ConjugatedPortDefinition()", skipped);
    }
    if constexpr (!std::is_abstract_v<ConjugatedPortTyping>) { ++classes;
        check<ConjugatedPortTyping>(failures, "ConjugatedPortTyping", instantiated, "ConjugatedPortTyping()", skipped);
    }
    if constexpr (!std::is_abstract_v<PortConjugation>) { ++classes;
        check<PortConjugation>(failures, "PortConjugation", instantiated, "PortConjugation()", skipped);
    }
    if constexpr (!std::is_abstract_v<PortDefinition>) { ++classes;
        check<PortDefinition>(failures, "PortDefinition", instantiated, "PortDefinition()", skipped);
    }
    if constexpr (!std::is_abstract_v<PortUsage>) { ++classes;
        check<PortUsage>(failures, "PortUsage", instantiated, "PortUsage()", skipped);
    }
    if constexpr (!std::is_abstract_v<ActorMembership>) { ++classes;
        check<ActorMembership>(failures, "ActorMembership", instantiated, "ActorMembership()", skipped);
    }
    if constexpr (!std::is_abstract_v<ConcernDefinition>) { ++classes;
        check<ConcernDefinition>(failures, "ConcernDefinition", instantiated, "ConcernDefinition()", skipped);
    }
    if constexpr (!std::is_abstract_v<ConcernUsage>) { ++classes;
        check<ConcernUsage>(failures, "ConcernUsage", instantiated, "ConcernUsage()", skipped);
    }
    if constexpr (!std::is_abstract_v<FramedConcernMembership>) { ++classes;
        check<FramedConcernMembership>(failures, "FramedConcernMembership", instantiated, "FramedConcernMembership()", skipped);
    }
    if constexpr (!std::is_abstract_v<RequirementConstraintMembership>) { ++classes;
        check<RequirementConstraintMembership>(failures, "RequirementConstraintMembership", instantiated, "RequirementConstraintMembership()", skipped);
    }
    if constexpr (!std::is_abstract_v<RequirementDefinition>) { ++classes;
        check<RequirementDefinition>(failures, "RequirementDefinition", instantiated, "RequirementDefinition()", skipped);
    }
    if constexpr (!std::is_abstract_v<RequirementUsage>) { ++classes;
        check<RequirementUsage>(failures, "RequirementUsage", instantiated, "RequirementUsage()", skipped);
    }
    if constexpr (!std::is_abstract_v<SatisfyRequirementUsage>) { ++classes;
        check<SatisfyRequirementUsage>(failures, "SatisfyRequirementUsage", instantiated, "SatisfyRequirementUsage()", skipped);
    }
    if constexpr (!std::is_abstract_v<StakeholderMembership>) { ++classes;
        check<StakeholderMembership>(failures, "StakeholderMembership", instantiated, "StakeholderMembership()", skipped);
    }
    if constexpr (!std::is_abstract_v<SubjectMembership>) { ++classes;
        check<SubjectMembership>(failures, "SubjectMembership", instantiated, "SubjectMembership()", skipped);
    }
    if constexpr (!std::is_abstract_v<ExhibitStateUsage>) { ++classes;
        check<ExhibitStateUsage>(failures, "ExhibitStateUsage", instantiated, "ExhibitStateUsage()", skipped);
    }
    if constexpr (!std::is_abstract_v<StateDefinition>) { ++classes;
        check<StateDefinition>(failures, "StateDefinition", instantiated, "StateDefinition()", skipped);
    }
    if constexpr (!std::is_abstract_v<StateSubactionMembership>) { ++classes;
        check<StateSubactionMembership>(failures, "StateSubactionMembership", instantiated, "StateSubactionMembership()", skipped);
    }
    if constexpr (!std::is_abstract_v<StateUsage>) { ++classes;
        check<StateUsage>(failures, "StateUsage", instantiated, "StateUsage()", skipped);
    }
    if constexpr (!std::is_abstract_v<TransitionFeatureMembership>) { ++classes;
        check<TransitionFeatureMembership>(failures, "TransitionFeatureMembership", instantiated, "TransitionFeatureMembership()", skipped);
    }
    if constexpr (!std::is_abstract_v<TransitionUsage>) { ++classes;
        check<TransitionUsage>(failures, "TransitionUsage", instantiated, "TransitionUsage()", skipped);
    }
    if constexpr (!std::is_abstract_v<Definition>) { ++classes;
        check<Definition>(failures, "Definition", instantiated, "Definition()", skipped);
    }
    if constexpr (!std::is_abstract_v<ReferenceUsage>) { ++classes;
        check<ReferenceUsage>(failures, "ReferenceUsage", instantiated, "ReferenceUsage()", skipped);
    }
    if constexpr (!std::is_abstract_v<Usage>) { ++classes;
        check<Usage>(failures, "Usage", instantiated, "Usage()", skipped);
    }
    if constexpr (!std::is_abstract_v<VariantMembership>) { ++classes;
        check<VariantMembership>(failures, "VariantMembership", instantiated, "VariantMembership()", skipped);
    }
    if constexpr (!std::is_abstract_v<IncludeUseCaseUsage>) { ++classes;
        check<IncludeUseCaseUsage>(failures, "IncludeUseCaseUsage", instantiated, "IncludeUseCaseUsage()", skipped);
    }
    if constexpr (!std::is_abstract_v<UseCaseDefinition>) { ++classes;
        check<UseCaseDefinition>(failures, "UseCaseDefinition", instantiated, "UseCaseDefinition()", skipped);
    }
    if constexpr (!std::is_abstract_v<UseCaseUsage>) { ++classes;
        check<UseCaseUsage>(failures, "UseCaseUsage", instantiated, "UseCaseUsage()", skipped);
    }
    if constexpr (!std::is_abstract_v<RequirementVerificationMembership>) { ++classes;
        check<RequirementVerificationMembership>(failures, "RequirementVerificationMembership", instantiated, "RequirementVerificationMembership()", skipped);
    }
    if constexpr (!std::is_abstract_v<VerificationCaseDefinition>) { ++classes;
        check<VerificationCaseDefinition>(failures, "VerificationCaseDefinition", instantiated, "VerificationCaseDefinition()", skipped);
    }
    if constexpr (!std::is_abstract_v<VerificationCaseUsage>) { ++classes;
        check<VerificationCaseUsage>(failures, "VerificationCaseUsage", instantiated, "VerificationCaseUsage()", skipped);
    }
    if constexpr (!std::is_abstract_v<MembershipExpose>) { ++classes;
        check<MembershipExpose>(failures, "MembershipExpose", instantiated, "MembershipExpose()", skipped);
    }
    if constexpr (!std::is_abstract_v<NamespaceExpose>) { ++classes;
        check<NamespaceExpose>(failures, "NamespaceExpose", instantiated, "NamespaceExpose()", skipped);
    }
    if constexpr (!std::is_abstract_v<RenderingDefinition>) { ++classes;
        check<RenderingDefinition>(failures, "RenderingDefinition", instantiated, "RenderingDefinition()", skipped);
    }
    if constexpr (!std::is_abstract_v<RenderingUsage>) { ++classes;
        check<RenderingUsage>(failures, "RenderingUsage", instantiated, "RenderingUsage()", skipped);
    }
    if constexpr (!std::is_abstract_v<ViewDefinition>) { ++classes;
        check<ViewDefinition>(failures, "ViewDefinition", instantiated, "ViewDefinition()", skipped);
    }
    if constexpr (!std::is_abstract_v<ViewRenderingMembership>) { ++classes;
        check<ViewRenderingMembership>(failures, "ViewRenderingMembership", instantiated, "ViewRenderingMembership()", skipped);
    }
    if constexpr (!std::is_abstract_v<ViewUsage>) { ++classes;
        check<ViewUsage>(failures, "ViewUsage", instantiated, "ViewUsage()", skipped);
    }
    if constexpr (!std::is_abstract_v<ViewpointDefinition>) { ++classes;
        check<ViewpointDefinition>(failures, "ViewpointDefinition", instantiated, "ViewpointDefinition()", skipped);
    }
    if constexpr (!std::is_abstract_v<ViewpointUsage>) { ++classes;
        check<ViewpointUsage>(failures, "ViewpointUsage", instantiated, "ViewpointUsage()", skipped);
    }
}

}  // namespace

TEST(MetaclassNames, EveryConcreteClassReportsItsExactMetaclassName) {
    std::vector<Failure> failures;
    unsigned instantiated = 0, classes = 0;
    std::vector<std::string> skipped;
    check_kerml(failures, instantiated, classes, skipped);
    check_sysml(failures, instantiated, classes, skipped);
    for (const auto& failure : failures) ADD_FAILURE() << failure.cls << ": " << failure.what;
    std::cout << "[  NAMES  ] " << classes << " concrete classes, " << instantiated << " constructors instantiated" << std::endl;
    for (const auto& line : skipped) std::cout << "[  NAMES  ] skipped: " << line << std::endl;
    EXPECT_GT(classes, 150u);
}
