// Generated by sysml/tools/generate_abstract_syntax.py.
#include <sysml/connections/BindingConnectorAsUsage.h>
#include <algorithm>
#include <stdexcept>

namespace SysMLv2::Entities {

BindingConnectorAsUsage::BindingConnectorAsUsage() {
    _dType = "BindingConnectorAsUsage";
}

BindingConnectorAsUsage::~BindingConnectorAsUsage() = default;

std::string_view BindingConnectorAsUsage::metaclassName() const noexcept {
    return "BindingConnectorAsUsage";
}

std::vector<RepresentationIssue> BindingConnectorAsUsage::validateRepresentation(bool includeDerived) const {
    std::vector<RepresentationIssue> issues; (void)includeDerived;
    return issues;
}

} // namespace SysMLv2::Entities
