// Generated by sysml/tools/generate_abstract_syntax.py.
#include <sysml/connections/ConnectionDefinition.h>
#include <sysml/usage/Usage.h>
#include <algorithm>
#include <stdexcept>

namespace SysMLv2::Entities {

std::vector<std::shared_ptr<Usage>> ConnectionDefinition::connectionEnd() const {
    return connectionEnd_;
}

void ConnectionDefinition::setConnectionEnd(std::vector<std::shared_ptr<Usage>> value) {
    if (std::any_of(value.begin(), value.end(), [](const auto& item) { return !item; })) {
        throw std::invalid_argument("ConnectionDefinition.connectionEnd: null entry");
    }
    for (std::size_t i = 0; i < value.size(); ++i) {
        if (std::find(value.begin(), value.begin() + i, value[i]) != value.begin() + i) {
            throw std::invalid_argument("ConnectionDefinition.connectionEnd: duplicate entry");
        }
    }
    connectionEnd_ = std::move(value);
}

void ConnectionDefinition::appendConnectionEnd(std::shared_ptr<Usage> value) {
    auto values = connectionEnd();
    values.push_back(std::move(value));
    setConnectionEnd(std::move(values));
}

bool ConnectionDefinition::isSufficient() const {
    return isSufficient_;
}

void ConnectionDefinition::setIsSufficient(bool value) {
    isSufficient_ = std::move(value);
}

ConnectionDefinition::ConnectionDefinition() {
    _dType = "ConnectionDefinition";
}

ConnectionDefinition::~ConnectionDefinition() = default;

std::string_view ConnectionDefinition::metaclassName() const noexcept {
    return "ConnectionDefinition";
}

std::vector<RepresentationIssue> ConnectionDefinition::validateRepresentation(bool includeDerived) const {
    std::vector<RepresentationIssue> issues; (void)includeDerived;
    return issues;
}

} // namespace SysMLv2::Entities
