// Generated by sysml/tools/generate_abstract_syntax.py.
#include <sysml/connections/ConnectionUsage.h>
#include <algorithm>
#include <stdexcept>

namespace SysMLv2::Entities {

std::vector<std::shared_ptr<KerML::Entities::AssociationStructure>> ConnectionUsage::connectionDefinition() const {
    return connectionDefinition_;
}

void ConnectionUsage::setConnectionDefinition(std::vector<std::shared_ptr<KerML::Entities::AssociationStructure>> value) {
    if (std::any_of(value.begin(), value.end(), [](const auto& item) { return !item; })) {
        throw std::invalid_argument("ConnectionUsage.connectionDefinition: null entry");
    }
    for (std::size_t i = 0; i < value.size(); ++i) {
        if (std::find(value.begin(), value.begin() + i, value[i]) != value.begin() + i) {
            throw std::invalid_argument("ConnectionUsage.connectionDefinition: duplicate entry");
        }
    }
    connectionDefinition_ = std::move(value);
}

void ConnectionUsage::appendConnectionDefinition(std::shared_ptr<KerML::Entities::AssociationStructure> value) {
    auto values = connectionDefinition();
    values.push_back(std::move(value));
    setConnectionDefinition(std::move(values));
}

ConnectionUsage::ConnectionUsage() {
    _dType = "ConnectionUsage";
}

ConnectionUsage::~ConnectionUsage() = default;

std::string_view ConnectionUsage::metaclassName() const noexcept {
    return "ConnectionUsage";
}

std::vector<RepresentationIssue> ConnectionUsage::validateRepresentation(bool includeDerived) const {
    std::vector<RepresentationIssue> issues; (void)includeDerived;
    { auto optional = OccurrenceUsage::portionKind(); if (optional) { auto value = *optional; if (!(value == PortionKind::timeslice || value == PortionKind::snapshot)) issues.push_back({"OccurrenceUsage.portionKind", "invalid enumeration value"}); } }
    return issues;
}

} // namespace SysMLv2::Entities
