// Generated by sysml/tools/generate_abstract_syntax.py.
#include <sysml/connections/SuccessionAsUsage.h>
#include <algorithm>
#include <stdexcept>

namespace SysMLv2::Entities {

SuccessionAsUsage::SuccessionAsUsage() {
    _dType = "SuccessionAsUsage";
}

SuccessionAsUsage::~SuccessionAsUsage() = default;

std::string_view SuccessionAsUsage::metaclassName() const noexcept {
    return "SuccessionAsUsage";
}

std::vector<RepresentationIssue> SuccessionAsUsage::validateRepresentation(bool includeDerived) const {
    std::vector<RepresentationIssue> issues; (void)includeDerived;
    return issues;
}

} // namespace SysMLv2::Entities
