// Generated by sysml/tools/generate_abstract_syntax.py.
#pragma once

#include <memory>
#include <utility>
#include <vector>

namespace SysMLv2::Entities::detail {
template<class T, class U>
std::vector<std::shared_ptr<T>> select(const std::vector<std::shared_ptr<U>>& values) {
    std::vector<std::shared_ptr<T>> result;
    for (const auto& value : values) {
        if (auto typed = std::dynamic_pointer_cast<T>(value)) {
            result.push_back(std::move(typed));
        }
    }
    return result;
}
} // namespace SysMLv2::Entities::detail
