// Generated by kerml/tools/generate_abstract_syntax.py.
#include <kerml/KerML.h>
#include <utility>
#include <stdexcept>
#include "../../model/RepresentationSupport.h"

namespace KerML::Entities {
void CollectExpression::setOperatorName(const std::string& name) {
    if (name != "collect") throw std::invalid_argument("Invalid fixed operator for CollectExpression");
    OperatorExpression::setOperatorName(name);
}

CollectExpression::CollectExpression() {
    _dType = "CollectExpression";
    OperatorExpression::setOperatorName("collect");
}

CollectExpression::~CollectExpression() = default;
}
