// Generated by kerml/tools/generate_abstract_syntax.py.
#include <kerml/KerML.h>
#include <utility>
#include <stdexcept>
#include "../../model/RepresentationSupport.h"

namespace KerML::Entities {
void FeatureChainExpression::setOperatorName(const std::string& name) {
    if (name != ".") throw std::invalid_argument("Invalid fixed operator for FeatureChainExpression");
    OperatorExpression::setOperatorName(name);
}

std::shared_ptr<Feature> FeatureChainExpression::targetFeature() const {
    return targetFeature_;
}

void FeatureChainExpression::setTargetFeature(std::shared_ptr<Feature> value) {
    targetFeature_ = std::move(value);
}

FeatureChainExpression::FeatureChainExpression() {
    _dType = "FeatureChainExpression";
    OperatorExpression::setOperatorName(".");
}

FeatureChainExpression::~FeatureChainExpression() = default;
}
