// Generated by kerml/tools/generate_abstract_syntax.py.
#include <kerml/KerML.h>
#include <utility>
#include <stdexcept>
#include "../../model/RepresentationSupport.h"

namespace KerML::Entities {
std::shared_ptr<Feature> FeatureReferenceExpression::referent() const {
    return referent_;
}

void FeatureReferenceExpression::setReferent(std::shared_ptr<Feature> value) {
    referent_ = std::move(value);
}

FeatureReferenceExpression::FeatureReferenceExpression() {
    _dType = "FeatureReferenceExpression";
}

FeatureReferenceExpression::~FeatureReferenceExpression() = default;
}
