// Generated by kerml/tools/generate_abstract_syntax.py.
#include <kerml/KerML.h>
#include <utility>
#include <stdexcept>
#include "../../model/RepresentationSupport.h"

namespace KerML::Entities {
void IndexExpression::setOperatorName(const std::string& name) {
    if (name != "#") throw std::invalid_argument("Invalid fixed operator for IndexExpression");
    OperatorExpression::setOperatorName(name);
}

IndexExpression::IndexExpression() {
    _dType = "IndexExpression";
    OperatorExpression::setOperatorName("#");
}

IndexExpression::~IndexExpression() = default;
}
