// Generated by kerml/tools/generate_abstract_syntax.py.
#include <kerml/KerML.h>
#include <utility>
#include <stdexcept>
#include "../../model/RepresentationSupport.h"

namespace KerML::Entities {
std::vector<std::shared_ptr<Expression>> InstantiationExpression::argument() const {
    return argument_;
}

void InstantiationExpression::setArgument(std::vector<std::shared_ptr<Expression>> value) {
    detail::checkCollection(value, true, -1);
    argument_ = std::move(value);
}

void InstantiationExpression::appendArgument(std::shared_ptr<Expression> value) {
    auto values = argument(); values.push_back(std::move(value)); setArgument(std::move(values));
}

std::shared_ptr<Type> InstantiationExpression::instantiatedType() const {
    return instantiatedType_;
}

void InstantiationExpression::setInstantiatedType(std::shared_ptr<Type> value) {
    instantiatedType_ = std::move(value);
}

InstantiationExpression::InstantiationExpression() {
    _dType = "InstantiationExpression";
}

InstantiationExpression::~InstantiationExpression() = default;
}
