// Generated by kerml/tools/generate_abstract_syntax.py.
#include <kerml/KerML.h>
#include <utility>
#include <stdexcept>
#include "../../model/RepresentationSupport.h"

namespace KerML::Entities {
InvocationExpression::InvocationExpression() {
    _dType = "InvocationExpression";
}

InvocationExpression::~InvocationExpression() = default;
}
