// Generated by kerml/tools/generate_abstract_syntax.py.
#include <kerml/KerML.h>
#include <utility>
#include <stdexcept>
#include "../../model/RepresentationSupport.h"

namespace KerML::Entities {
std::string LiteralString::value() const {
    return value_;
}

void LiteralString::setValue(std::string value) {
    value_ = std::move(value);
}

LiteralString::LiteralString() {
    _dType = "LiteralString";
}

LiteralString::~LiteralString() = default;
}
