// Generated by kerml/tools/generate_abstract_syntax.py.
#include <kerml/KerML.h>
#include <utility>
#include <stdexcept>
#include "../../model/RepresentationSupport.h"

namespace KerML::Entities {
std::int64_t LiteralInteger::value() const {
    return value_;
}

void LiteralInteger::setValue(std::int64_t value) {
    value_ = std::move(value);
}

LiteralInteger::LiteralInteger() {
    _dType = "LiteralInteger";
}

LiteralInteger::~LiteralInteger() = default;
}
