// Generated by kerml/tools/generate_abstract_syntax.py.
#include <kerml/KerML.h>
#include <utility>
#include <stdexcept>
#include "../../model/RepresentationSupport.h"

namespace KerML::Entities {
bool LiteralBoolean::value() const {
    return value_;
}

void LiteralBoolean::setValue(bool value) {
    value_ = std::move(value);
}

LiteralBoolean::LiteralBoolean() {
    _dType = "LiteralBoolean";
}

LiteralBoolean::~LiteralBoolean() = default;
}
