// Generated by kerml/tools/generate_abstract_syntax.py.
#include <kerml/KerML.h>
#include <utility>
#include <stdexcept>
#include "../../model/RepresentationSupport.h"

namespace KerML::Entities {
double LiteralRational::value() const {
    return value_;
}

void LiteralRational::setValue(double value) {
    value_ = std::move(value);
}

LiteralRational::LiteralRational() {
    _dType = "LiteralRational";
}

LiteralRational::~LiteralRational() = default;
}
