// Generated by kerml/tools/generate_abstract_syntax.py.
#include <kerml/KerML.h>
#include <utility>
#include <stdexcept>
#include "../../model/RepresentationSupport.h"

namespace KerML::Entities {
std::shared_ptr<Element> MetadataAccessExpression::referencedElement() const {
    return referencedElement_;
}

void MetadataAccessExpression::setReferencedElement(std::shared_ptr<Element> value) {
    referencedElement_ = std::move(value);
}

MetadataAccessExpression::MetadataAccessExpression() {
    _dType = "MetadataAccessExpression";
}

MetadataAccessExpression::~MetadataAccessExpression() = default;
}
