// Generated by kerml/tools/generate_abstract_syntax.py.
#include <kerml/KerML.h>
#include <utility>
#include <stdexcept>
#include "../../model/RepresentationSupport.h"

namespace KerML::Entities {
const std::string& OperatorExpression::operatorName() const {
    return operatorName_;
}

void OperatorExpression::setOperatorName(const std::string& value) {
    operatorName_ = std::move(value);
}

OperatorExpression::OperatorExpression() {
    _dType = "OperatorExpression";
}

OperatorExpression::~OperatorExpression() = default;
}
