// Generated by kerml/tools/generate_abstract_syntax.py.
#include <kerml/KerML.h>
#include <utility>
#include <stdexcept>
#include "../../model/RepresentationSupport.h"

namespace KerML::Entities {
void SelectExpression::setOperatorName(const std::string& name) {
    if (name != "select") throw std::invalid_argument("Invalid fixed operator for SelectExpression");
    OperatorExpression::setOperatorName(name);
}

SelectExpression::SelectExpression() {
    _dType = "SelectExpression";
    OperatorExpression::setOperatorName("select");
}

SelectExpression::~SelectExpression() = default;
}
