// Generated by sysml/tools/generate_abstract_syntax.py.
#include <sysml/analysiscases/AnalysisCaseUsage.h>
#include <sysml/analysiscases/AnalysisCaseDefinition.h>
#include <algorithm>
#include <stdexcept>

namespace SysMLv2::Entities {

std::shared_ptr<AnalysisCaseDefinition> AnalysisCaseUsage::analysisCaseDefinition() const {
    return analysisCaseDefinition_;
}

void AnalysisCaseUsage::setAnalysisCaseDefinition(std::shared_ptr<AnalysisCaseDefinition> value) {
    analysisCaseDefinition_ = std::move(value);
}

std::shared_ptr<KerML::Entities::Expression> AnalysisCaseUsage::resultExpression() const {
    return resultExpression_;
}

void AnalysisCaseUsage::setResultExpression(std::shared_ptr<KerML::Entities::Expression> value) {
    resultExpression_ = std::move(value);
}

AnalysisCaseUsage::AnalysisCaseUsage() {
    _dType = "AnalysisCaseUsage";
}

AnalysisCaseUsage::~AnalysisCaseUsage() = default;

std::string_view AnalysisCaseUsage::metaclassName() const noexcept {
    return "AnalysisCaseUsage";
}

std::vector<RepresentationIssue> AnalysisCaseUsage::validateRepresentation(bool includeDerived) const {
    std::vector<RepresentationIssue> issues; (void)includeDerived;
    { auto optional = OccurrenceUsage::portionKind(); if (optional) { auto value = *optional; if (!(value == PortionKind::timeslice || value == PortionKind::snapshot)) issues.push_back({"OccurrenceUsage.portionKind", "invalid enumeration value"}); } }
    if (includeDerived) if (!CaseUsage::subjectParameter()) issues.push_back({"CaseUsage.subjectParameter", "required reference is missing"});
    return issues;
}

} // namespace SysMLv2::Entities
