// Generated by sysml/tools/generate_abstract_syntax.py.
#include <sysml/analysiscases/AnalysisCaseDefinition.h>
#include <algorithm>
#include <stdexcept>

namespace SysMLv2::Entities {

std::shared_ptr<KerML::Entities::Expression> AnalysisCaseDefinition::resultExpression() const {
    return resultExpression_;
}

void AnalysisCaseDefinition::setResultExpression(std::shared_ptr<KerML::Entities::Expression> value) {
    resultExpression_ = std::move(value);
}

AnalysisCaseDefinition::AnalysisCaseDefinition() {
    _dType = "AnalysisCaseDefinition";
}

AnalysisCaseDefinition::~AnalysisCaseDefinition() = default;

std::string_view AnalysisCaseDefinition::metaclassName() const noexcept {
    return "AnalysisCaseDefinition";
}

std::vector<RepresentationIssue> AnalysisCaseDefinition::validateRepresentation(bool includeDerived) const {
    std::vector<RepresentationIssue> issues; (void)includeDerived;
    if (includeDerived) if (!CaseDefinition::subjectParameter()) issues.push_back({"CaseDefinition.subjectParameter", "required reference is missing"});
    return issues;
}

} // namespace SysMLv2::Entities
