// Generated by sysml/tools/generate_abstract_syntax.py.
#include <sysml/requirements/ActorMembership.h>
#include <sysml/parts/PartUsage.h>
#include <algorithm>
#include <stdexcept>

namespace SysMLv2::Entities {

std::shared_ptr<PartUsage> ActorMembership::ownedActorParameter() const {
    return ownedActorParameter_;
}

void ActorMembership::setOwnedActorParameter(std::shared_ptr<PartUsage> value) {
    ownedActorParameter_ = std::move(value);
}

ActorMembership::ActorMembership() {
    _dType = "ActorMembership";
}

ActorMembership::~ActorMembership() = default;

std::string_view ActorMembership::metaclassName() const noexcept {
    return "ActorMembership";
}

std::vector<RepresentationIssue> ActorMembership::validateRepresentation(bool includeDerived) const {
    std::vector<RepresentationIssue> issues; (void)includeDerived;
    if (includeDerived) if (!ActorMembership::ownedActorParameter()) issues.push_back({"ActorMembership.ownedActorParameter", "required reference is missing"});
    return issues;
}

} // namespace SysMLv2::Entities
