// Generated by sysml/tools/generate_abstract_syntax.py.
#include <sysml/requirements/ConcernUsage.h>
#include <sysml/requirements/ConcernDefinition.h>
#include <algorithm>
#include <stdexcept>

namespace SysMLv2::Entities {

std::shared_ptr<ConcernDefinition> ConcernUsage::concernDefinition() const {
    return concernDefinition_;
}

void ConcernUsage::setConcernDefinition(std::shared_ptr<ConcernDefinition> value) {
    concernDefinition_ = std::move(value);
}

ConcernUsage::ConcernUsage() {
    _dType = "ConcernUsage";
}

ConcernUsage::~ConcernUsage() = default;

std::string_view ConcernUsage::metaclassName() const noexcept {
    return "ConcernUsage";
}

std::vector<RepresentationIssue> ConcernUsage::validateRepresentation(bool includeDerived) const {
    std::vector<RepresentationIssue> issues; (void)includeDerived;
    { auto optional = OccurrenceUsage::portionKind(); if (optional) { auto value = *optional; if (!(value == PortionKind::timeslice || value == PortionKind::snapshot)) issues.push_back({"OccurrenceUsage.portionKind", "invalid enumeration value"}); } }
    if (includeDerived) if (!RequirementUsage::subjectParameter()) issues.push_back({"RequirementUsage.subjectParameter", "required reference is missing"});
    return issues;
}

} // namespace SysMLv2::Entities
