// Generated by sysml/tools/generate_abstract_syntax.py.
#include <sysml/requirements/ConcernDefinition.h>
#include <algorithm>
#include <stdexcept>

namespace SysMLv2::Entities {

ConcernDefinition::ConcernDefinition() {
    _dType = "ConcernDefinition";
}

ConcernDefinition::~ConcernDefinition() = default;

std::string_view ConcernDefinition::metaclassName() const noexcept {
    return "ConcernDefinition";
}

std::vector<RepresentationIssue> ConcernDefinition::validateRepresentation(bool includeDerived) const {
    std::vector<RepresentationIssue> issues; (void)includeDerived;
    if (includeDerived) if (!RequirementDefinition::subjectParameter()) issues.push_back({"RequirementDefinition.subjectParameter", "required reference is missing"});
    return issues;
}

} // namespace SysMLv2::Entities
