// Generated by sysml/tools/generate_abstract_syntax.py.
#include <sysml/requirements/FramedConcernMembership.h>
#include <sysml/requirements/RequirementConstraintKind.h>
#include <sysml/requirements/ConcernUsage.h>
#include <algorithm>
#include <stdexcept>

namespace SysMLv2::Entities {

RequirementConstraintKind FramedConcernMembership::kind() const {
    return kind_;
}

void FramedConcernMembership::setKind(RequirementConstraintKind value) {
    kind_ = std::move(value);
}

std::shared_ptr<ConcernUsage> FramedConcernMembership::ownedConcern() const {
    return ownedConcern_;
}

void FramedConcernMembership::setOwnedConcern(std::shared_ptr<ConcernUsage> value) {
    ownedConcern_ = std::move(value);
}

std::shared_ptr<ConcernUsage> FramedConcernMembership::referencedConcern() const {
    return referencedConcern_;
}

void FramedConcernMembership::setReferencedConcern(std::shared_ptr<ConcernUsage> value) {
    referencedConcern_ = std::move(value);
}

FramedConcernMembership::FramedConcernMembership() {
    _dType = "FramedConcernMembership";
}

FramedConcernMembership::~FramedConcernMembership() = default;

std::string_view FramedConcernMembership::metaclassName() const noexcept {
    return "FramedConcernMembership";
}

std::vector<RepresentationIssue> FramedConcernMembership::validateRepresentation(bool includeDerived) const {
    std::vector<RepresentationIssue> issues; (void)includeDerived;
    { auto value = RequirementConstraintMembership::kind(); if (!(value == RequirementConstraintKind::assumption || value == RequirementConstraintKind::requirement)) issues.push_back({"RequirementConstraintMembership.kind", "invalid enumeration value"}); }
    if (includeDerived) if (!RequirementConstraintMembership::ownedConstraint()) issues.push_back({"RequirementConstraintMembership.ownedConstraint", "required reference is missing"});
    if (includeDerived) if (!RequirementConstraintMembership::referencedConstraint()) issues.push_back({"RequirementConstraintMembership.referencedConstraint", "required reference is missing"});
    { auto value = FramedConcernMembership::kind(); if (!(value == RequirementConstraintKind::assumption || value == RequirementConstraintKind::requirement)) issues.push_back({"FramedConcernMembership.kind", "invalid enumeration value"}); }
    if (includeDerived) if (!FramedConcernMembership::ownedConcern()) issues.push_back({"FramedConcernMembership.ownedConcern", "required reference is missing"});
    if (includeDerived) if (!FramedConcernMembership::referencedConcern()) issues.push_back({"FramedConcernMembership.referencedConcern", "required reference is missing"});
    return issues;
}

} // namespace SysMLv2::Entities
