// Generated by sysml/tools/generate_abstract_syntax.py.
#include <sysml/requirements/RequirementDefinition.h>
#include <sysml/usage/Usage.h>
#include <sysml/parts/PartUsage.h>
#include <sysml/constraints/ConstraintUsage.h>
#include <sysml/requirements/ConcernUsage.h>
#include <algorithm>
#include <stdexcept>

namespace SysMLv2::Entities {

std::optional<std::string> RequirementDefinition::reqId() const {
    return reqId_;
}

void RequirementDefinition::setReqId(std::optional<std::string> value) {
    reqId_ = std::move(value);
}

std::vector<std::string> RequirementDefinition::text() const {
    return text_;
}

void RequirementDefinition::setText(std::vector<std::string> value) {
    for (std::size_t i = 0; i < value.size(); ++i) {
        if (std::find(value.begin(), value.begin() + i, value[i]) != value.begin() + i) {
            throw std::invalid_argument("RequirementDefinition.text: duplicate entry");
        }
    }
    text_ = std::move(value);
}

void RequirementDefinition::appendText(std::string value) {
    auto values = text();
    values.push_back(std::move(value));
    setText(std::move(values));
}

std::shared_ptr<Usage> RequirementDefinition::subjectParameter() const {
    return subjectParameter_;
}

void RequirementDefinition::setSubjectParameter(std::shared_ptr<Usage> value) {
    subjectParameter_ = std::move(value);
}

std::vector<std::shared_ptr<PartUsage>> RequirementDefinition::actorParameter() const {
    return actorParameter_;
}

void RequirementDefinition::setActorParameter(std::vector<std::shared_ptr<PartUsage>> value) {
    if (std::any_of(value.begin(), value.end(), [](const auto& item) { return !item; })) {
        throw std::invalid_argument("RequirementDefinition.actorParameter: null entry");
    }
    for (std::size_t i = 0; i < value.size(); ++i) {
        if (std::find(value.begin(), value.begin() + i, value[i]) != value.begin() + i) {
            throw std::invalid_argument("RequirementDefinition.actorParameter: duplicate entry");
        }
    }
    actorParameter_ = std::move(value);
}

void RequirementDefinition::appendActorParameter(std::shared_ptr<PartUsage> value) {
    auto values = actorParameter();
    values.push_back(std::move(value));
    setActorParameter(std::move(values));
}

std::vector<std::shared_ptr<PartUsage>> RequirementDefinition::stakeholderParameter() const {
    return stakeholderParameter_;
}

void RequirementDefinition::setStakeholderParameter(std::vector<std::shared_ptr<PartUsage>> value) {
    if (std::any_of(value.begin(), value.end(), [](const auto& item) { return !item; })) {
        throw std::invalid_argument("RequirementDefinition.stakeholderParameter: null entry");
    }
    for (std::size_t i = 0; i < value.size(); ++i) {
        if (std::find(value.begin(), value.begin() + i, value[i]) != value.begin() + i) {
            throw std::invalid_argument("RequirementDefinition.stakeholderParameter: duplicate entry");
        }
    }
    stakeholderParameter_ = std::move(value);
}

void RequirementDefinition::appendStakeholderParameter(std::shared_ptr<PartUsage> value) {
    auto values = stakeholderParameter();
    values.push_back(std::move(value));
    setStakeholderParameter(std::move(values));
}

std::vector<std::shared_ptr<ConstraintUsage>> RequirementDefinition::assumedConstraint() const {
    return assumedConstraint_;
}

void RequirementDefinition::setAssumedConstraint(std::vector<std::shared_ptr<ConstraintUsage>> value) {
    if (std::any_of(value.begin(), value.end(), [](const auto& item) { return !item; })) {
        throw std::invalid_argument("RequirementDefinition.assumedConstraint: null entry");
    }
    for (std::size_t i = 0; i < value.size(); ++i) {
        if (std::find(value.begin(), value.begin() + i, value[i]) != value.begin() + i) {
            throw std::invalid_argument("RequirementDefinition.assumedConstraint: duplicate entry");
        }
    }
    assumedConstraint_ = std::move(value);
}

void RequirementDefinition::appendAssumedConstraint(std::shared_ptr<ConstraintUsage> value) {
    auto values = assumedConstraint();
    values.push_back(std::move(value));
    setAssumedConstraint(std::move(values));
}

std::vector<std::shared_ptr<ConstraintUsage>> RequirementDefinition::requiredConstraint() const {
    return requiredConstraint_;
}

void RequirementDefinition::setRequiredConstraint(std::vector<std::shared_ptr<ConstraintUsage>> value) {
    if (std::any_of(value.begin(), value.end(), [](const auto& item) { return !item; })) {
        throw std::invalid_argument("RequirementDefinition.requiredConstraint: null entry");
    }
    for (std::size_t i = 0; i < value.size(); ++i) {
        if (std::find(value.begin(), value.begin() + i, value[i]) != value.begin() + i) {
            throw std::invalid_argument("RequirementDefinition.requiredConstraint: duplicate entry");
        }
    }
    requiredConstraint_ = std::move(value);
}

void RequirementDefinition::appendRequiredConstraint(std::shared_ptr<ConstraintUsage> value) {
    auto values = requiredConstraint();
    values.push_back(std::move(value));
    setRequiredConstraint(std::move(values));
}

std::vector<std::shared_ptr<ConcernUsage>> RequirementDefinition::framedConcern() const {
    return framedConcern_;
}

void RequirementDefinition::setFramedConcern(std::vector<std::shared_ptr<ConcernUsage>> value) {
    if (std::any_of(value.begin(), value.end(), [](const auto& item) { return !item; })) {
        throw std::invalid_argument("RequirementDefinition.framedConcern: null entry");
    }
    for (std::size_t i = 0; i < value.size(); ++i) {
        if (std::find(value.begin(), value.begin() + i, value[i]) != value.begin() + i) {
            throw std::invalid_argument("RequirementDefinition.framedConcern: duplicate entry");
        }
    }
    framedConcern_ = std::move(value);
}

void RequirementDefinition::appendFramedConcern(std::shared_ptr<ConcernUsage> value) {
    auto values = framedConcern();
    values.push_back(std::move(value));
    setFramedConcern(std::move(values));
}

RequirementDefinition::RequirementDefinition() {
    _dType = "RequirementDefinition";
}

RequirementDefinition::~RequirementDefinition() = default;

std::string_view RequirementDefinition::metaclassName() const noexcept {
    return "RequirementDefinition";
}

std::vector<RepresentationIssue> RequirementDefinition::validateRepresentation(bool includeDerived) const {
    std::vector<RepresentationIssue> issues; (void)includeDerived;
    if (includeDerived) if (!RequirementDefinition::subjectParameter()) issues.push_back({"RequirementDefinition.subjectParameter", "required reference is missing"});
    return issues;
}

} // namespace SysMLv2::Entities
