// Generated by sysml/tools/generate_abstract_syntax.py.
#include <sysml/requirements/RequirementUsage.h>
#include <sysml/requirements/RequirementDefinition.h>
#include <sysml/constraints/ConstraintUsage.h>
#include <sysml/usage/Usage.h>
#include <sysml/requirements/ConcernUsage.h>
#include <sysml/parts/PartUsage.h>
#include <algorithm>
#include <stdexcept>

namespace SysMLv2::Entities {

std::shared_ptr<RequirementDefinition> RequirementUsage::requirementDefinition() const {
    return requirementDefinition_;
}

void RequirementUsage::setRequirementDefinition(std::shared_ptr<RequirementDefinition> value) {
    requirementDefinition_ = std::move(value);
}

std::optional<std::string> RequirementUsage::reqId() const {
    return reqId_;
}

void RequirementUsage::setReqId(std::optional<std::string> value) {
    reqId_ = std::move(value);
}

std::vector<std::string> RequirementUsage::text() const {
    return text_;
}

void RequirementUsage::setText(std::vector<std::string> value) {
    for (std::size_t i = 0; i < value.size(); ++i) {
        if (std::find(value.begin(), value.begin() + i, value[i]) != value.begin() + i) {
            throw std::invalid_argument("RequirementUsage.text: duplicate entry");
        }
    }
    text_ = std::move(value);
}

void RequirementUsage::appendText(std::string value) {
    auto values = text();
    values.push_back(std::move(value));
    setText(std::move(values));
}

std::vector<std::shared_ptr<ConstraintUsage>> RequirementUsage::requiredConstraint() const {
    return requiredConstraint_;
}

void RequirementUsage::setRequiredConstraint(std::vector<std::shared_ptr<ConstraintUsage>> value) {
    if (std::any_of(value.begin(), value.end(), [](const auto& item) { return !item; })) {
        throw std::invalid_argument("RequirementUsage.requiredConstraint: null entry");
    }
    for (std::size_t i = 0; i < value.size(); ++i) {
        if (std::find(value.begin(), value.begin() + i, value[i]) != value.begin() + i) {
            throw std::invalid_argument("RequirementUsage.requiredConstraint: duplicate entry");
        }
    }
    requiredConstraint_ = std::move(value);
}

void RequirementUsage::appendRequiredConstraint(std::shared_ptr<ConstraintUsage> value) {
    auto values = requiredConstraint();
    values.push_back(std::move(value));
    setRequiredConstraint(std::move(values));
}

std::vector<std::shared_ptr<ConstraintUsage>> RequirementUsage::assumedConstraint() const {
    return assumedConstraint_;
}

void RequirementUsage::setAssumedConstraint(std::vector<std::shared_ptr<ConstraintUsage>> value) {
    if (std::any_of(value.begin(), value.end(), [](const auto& item) { return !item; })) {
        throw std::invalid_argument("RequirementUsage.assumedConstraint: null entry");
    }
    for (std::size_t i = 0; i < value.size(); ++i) {
        if (std::find(value.begin(), value.begin() + i, value[i]) != value.begin() + i) {
            throw std::invalid_argument("RequirementUsage.assumedConstraint: duplicate entry");
        }
    }
    assumedConstraint_ = std::move(value);
}

void RequirementUsage::appendAssumedConstraint(std::shared_ptr<ConstraintUsage> value) {
    auto values = assumedConstraint();
    values.push_back(std::move(value));
    setAssumedConstraint(std::move(values));
}

std::shared_ptr<Usage> RequirementUsage::subjectParameter() const {
    return subjectParameter_;
}

void RequirementUsage::setSubjectParameter(std::shared_ptr<Usage> value) {
    subjectParameter_ = std::move(value);
}

std::vector<std::shared_ptr<ConcernUsage>> RequirementUsage::framedConcern() const {
    return framedConcern_;
}

void RequirementUsage::setFramedConcern(std::vector<std::shared_ptr<ConcernUsage>> value) {
    if (std::any_of(value.begin(), value.end(), [](const auto& item) { return !item; })) {
        throw std::invalid_argument("RequirementUsage.framedConcern: null entry");
    }
    for (std::size_t i = 0; i < value.size(); ++i) {
        if (std::find(value.begin(), value.begin() + i, value[i]) != value.begin() + i) {
            throw std::invalid_argument("RequirementUsage.framedConcern: duplicate entry");
        }
    }
    framedConcern_ = std::move(value);
}

void RequirementUsage::appendFramedConcern(std::shared_ptr<ConcernUsage> value) {
    auto values = framedConcern();
    values.push_back(std::move(value));
    setFramedConcern(std::move(values));
}

std::vector<std::shared_ptr<PartUsage>> RequirementUsage::actorParameter() const {
    return actorParameter_;
}

void RequirementUsage::setActorParameter(std::vector<std::shared_ptr<PartUsage>> value) {
    if (std::any_of(value.begin(), value.end(), [](const auto& item) { return !item; })) {
        throw std::invalid_argument("RequirementUsage.actorParameter: null entry");
    }
    for (std::size_t i = 0; i < value.size(); ++i) {
        if (std::find(value.begin(), value.begin() + i, value[i]) != value.begin() + i) {
            throw std::invalid_argument("RequirementUsage.actorParameter: duplicate entry");
        }
    }
    actorParameter_ = std::move(value);
}

void RequirementUsage::appendActorParameter(std::shared_ptr<PartUsage> value) {
    auto values = actorParameter();
    values.push_back(std::move(value));
    setActorParameter(std::move(values));
}

std::vector<std::shared_ptr<PartUsage>> RequirementUsage::stakeholderParameter() const {
    return stakeholderParameter_;
}

void RequirementUsage::setStakeholderParameter(std::vector<std::shared_ptr<PartUsage>> value) {
    if (std::any_of(value.begin(), value.end(), [](const auto& item) { return !item; })) {
        throw std::invalid_argument("RequirementUsage.stakeholderParameter: null entry");
    }
    for (std::size_t i = 0; i < value.size(); ++i) {
        if (std::find(value.begin(), value.begin() + i, value[i]) != value.begin() + i) {
            throw std::invalid_argument("RequirementUsage.stakeholderParameter: duplicate entry");
        }
    }
    stakeholderParameter_ = std::move(value);
}

void RequirementUsage::appendStakeholderParameter(std::shared_ptr<PartUsage> value) {
    auto values = stakeholderParameter();
    values.push_back(std::move(value));
    setStakeholderParameter(std::move(values));
}

RequirementUsage::RequirementUsage() {
    _dType = "RequirementUsage";
}

RequirementUsage::~RequirementUsage() = default;

std::string_view RequirementUsage::metaclassName() const noexcept {
    return "RequirementUsage";
}

std::vector<RepresentationIssue> RequirementUsage::validateRepresentation(bool includeDerived) const {
    std::vector<RepresentationIssue> issues; (void)includeDerived;
    { auto optional = OccurrenceUsage::portionKind(); if (optional) { auto value = *optional; if (!(value == PortionKind::timeslice || value == PortionKind::snapshot)) issues.push_back({"OccurrenceUsage.portionKind", "invalid enumeration value"}); } }
    if (includeDerived) if (!RequirementUsage::subjectParameter()) issues.push_back({"RequirementUsage.subjectParameter", "required reference is missing"});
    return issues;
}

} // namespace SysMLv2::Entities
