// Generated by sysml/tools/generate_abstract_syntax.py.
#include <sysml/requirements/SatisfyRequirementUsage.h>
#include <sysml/requirements/RequirementUsage.h>
#include <algorithm>
#include <stdexcept>

namespace SysMLv2::Entities {

std::shared_ptr<RequirementUsage> SatisfyRequirementUsage::satisfiedRequirement() const {
    return satisfiedRequirement_;
}

void SatisfyRequirementUsage::setSatisfiedRequirement(std::shared_ptr<RequirementUsage> value) {
    satisfiedRequirement_ = std::move(value);
}

std::shared_ptr<KerML::Entities::Feature> SatisfyRequirementUsage::satisfyingFeature() const {
    return satisfyingFeature_;
}

void SatisfyRequirementUsage::setSatisfyingFeature(std::shared_ptr<KerML::Entities::Feature> value) {
    satisfyingFeature_ = std::move(value);
}

SatisfyRequirementUsage::SatisfyRequirementUsage() {
    _dType = "SatisfyRequirementUsage";
}

SatisfyRequirementUsage::~SatisfyRequirementUsage() = default;

std::string_view SatisfyRequirementUsage::metaclassName() const noexcept {
    return "SatisfyRequirementUsage";
}

std::vector<RepresentationIssue> SatisfyRequirementUsage::validateRepresentation(bool includeDerived) const {
    std::vector<RepresentationIssue> issues; (void)includeDerived;
    { auto optional = OccurrenceUsage::portionKind(); if (optional) { auto value = *optional; if (!(value == PortionKind::timeslice || value == PortionKind::snapshot)) issues.push_back({"OccurrenceUsage.portionKind", "invalid enumeration value"}); } }
    if (includeDerived) if (!RequirementUsage::subjectParameter()) issues.push_back({"RequirementUsage.subjectParameter", "required reference is missing"});
    if (includeDerived) if (!AssertConstraintUsage::assertedConstraint()) issues.push_back({"AssertConstraintUsage.assertedConstraint", "required reference is missing"});
    if (includeDerived) if (!SatisfyRequirementUsage::satisfiedRequirement()) issues.push_back({"SatisfyRequirementUsage.satisfiedRequirement", "required reference is missing"});
    if (includeDerived) if (!SatisfyRequirementUsage::satisfyingFeature()) issues.push_back({"SatisfyRequirementUsage.satisfyingFeature", "required reference is missing"});
    return issues;
}

} // namespace SysMLv2::Entities
