// Generated by sysml/tools/generate_abstract_syntax.py.
#include <sysml/requirements/StakeholderMembership.h>
#include <sysml/parts/PartUsage.h>
#include <algorithm>
#include <stdexcept>

namespace SysMLv2::Entities {

std::shared_ptr<PartUsage> StakeholderMembership::ownedStakeholderParameter() const {
    return ownedStakeholderParameter_;
}

void StakeholderMembership::setOwnedStakeholderParameter(std::shared_ptr<PartUsage> value) {
    ownedStakeholderParameter_ = std::move(value);
}

StakeholderMembership::StakeholderMembership() {
    _dType = "StakeholderMembership";
}

StakeholderMembership::~StakeholderMembership() = default;

std::string_view StakeholderMembership::metaclassName() const noexcept {
    return "StakeholderMembership";
}

std::vector<RepresentationIssue> StakeholderMembership::validateRepresentation(bool includeDerived) const {
    std::vector<RepresentationIssue> issues; (void)includeDerived;
    if (includeDerived) if (!StakeholderMembership::ownedStakeholderParameter()) issues.push_back({"StakeholderMembership.ownedStakeholderParameter", "required reference is missing"});
    return issues;
}

} // namespace SysMLv2::Entities
