// Generated by sysml/tools/generate_abstract_syntax.py.
#include <sysml/requirements/SubjectMembership.h>
#include <sysml/usage/Usage.h>
#include <algorithm>
#include <stdexcept>

namespace SysMLv2::Entities {

std::shared_ptr<Usage> SubjectMembership::ownedSubjectParameter() const {
    return ownedSubjectParameter_;
}

void SubjectMembership::setOwnedSubjectParameter(std::shared_ptr<Usage> value) {
    ownedSubjectParameter_ = std::move(value);
}

SubjectMembership::SubjectMembership() {
    _dType = "SubjectMembership";
}

SubjectMembership::~SubjectMembership() = default;

std::string_view SubjectMembership::metaclassName() const noexcept {
    return "SubjectMembership";
}

std::vector<RepresentationIssue> SubjectMembership::validateRepresentation(bool includeDerived) const {
    std::vector<RepresentationIssue> issues; (void)includeDerived;
    if (includeDerived) if (!SubjectMembership::ownedSubjectParameter()) issues.push_back({"SubjectMembership.ownedSubjectParameter", "required reference is missing"});
    return issues;
}

} // namespace SysMLv2::Entities
