// Generated by kerml/tools/generate_abstract_syntax.py.
#pragma once
#include <kerml/core/classifiers/Classifier.h>
#include <kerml/model/Forward.h>
#include <kerml/kerml_global.h>
#include <cstdint>
#include <memory>
#include <string>
#include <vector>

namespace KerML::Entities {
class KERML_EXPORT DataType : public virtual Classifier {
public:
    DataType();
    ~DataType() override;
private:
};
}
