// Generated by sysml/tools/generate_abstract_syntax.py.
#pragma once
#include <sysml/model/Representation.h>
#include <sysml/model/Forward.h>
#include <sysml/model/KerMLTypes.h>
#include <sysml/connections/ConnectionDefinition.h>

namespace SysMLv2::Entities {
class SYSML_EXPORT InterfaceDefinition : public virtual ConnectionDefinition, public virtual Representation {
public:
    InterfaceDefinition();
    ~InterfaceDefinition() override;
    std::string_view metaclassName() const noexcept override;
    std::vector<RepresentationIssue> validateRepresentation(bool includeDerived = false) const override;
    /// Derived snapshot; populated by a semantic evaluator or importer.
    std::vector<std::shared_ptr<PortUsage>> interfaceEnd() const;
    void setInterfaceEnd(std::vector<std::shared_ptr<PortUsage>> value);
    void appendInterfaceEnd(std::shared_ptr<PortUsage> value);
private:
    std::vector<std::shared_ptr<PortUsage>> interfaceEnd_ = {};
};
}
