// Generated by sysml/tools/generate_abstract_syntax.py.
#pragma once
#include <sysml/model/Representation.h>
#include <sysml/model/Forward.h>
#include <sysml/model/KerMLTypes.h>
#include <sysml/connections/ConnectionUsage.h>

namespace SysMLv2::Entities {
class SYSML_EXPORT InterfaceUsage : public virtual ConnectionUsage, public virtual Representation {
public:
    InterfaceUsage();
    ~InterfaceUsage() override;
    std::string_view metaclassName() const noexcept override;
    std::vector<RepresentationIssue> validateRepresentation(bool includeDerived = false) const override;
    /// Derived snapshot; populated by a semantic evaluator or importer.
    std::vector<std::shared_ptr<InterfaceDefinition>> interfaceDefinition() const;
    void setInterfaceDefinition(std::vector<std::shared_ptr<InterfaceDefinition>> value);
    void appendInterfaceDefinition(std::shared_ptr<InterfaceDefinition> value);
private:
    std::vector<std::shared_ptr<InterfaceDefinition>> interfaceDefinition_ = {};
};
}
