// Generated by sysml/tools/generate_abstract_syntax.py.
#include <sysml/usage/Definition.h>
#include <sysml/usage/Usage.h>
#include <sysml/usage/VariantMembership.h>
#include <sysml/usage/ReferenceUsage.h>
#include <sysml/attributes/AttributeUsage.h>
#include <sysml/enumerations/EnumerationUsage.h>
#include <sysml/occurrences/OccurrenceUsage.h>
#include <sysml/items/ItemUsage.h>
#include <sysml/parts/PartUsage.h>
#include <sysml/ports/PortUsage.h>
#include <sysml/connections/ConnectorAsUsage.h>
#include <sysml/flows/FlowUsage.h>
#include <sysml/interfaces/InterfaceUsage.h>
#include <sysml/allocations/AllocationUsage.h>
#include <sysml/actions/ActionUsage.h>
#include <sysml/states/StateUsage.h>
#include <sysml/states/TransitionUsage.h>
#include <sysml/calculations/CalculationUsage.h>
#include <sysml/constraints/ConstraintUsage.h>
#include <sysml/requirements/RequirementUsage.h>
#include <sysml/requirements/ConcernUsage.h>
#include <sysml/cases/CaseUsage.h>
#include <sysml/analysiscases/AnalysisCaseUsage.h>
#include <sysml/verificationcases/VerificationCaseUsage.h>
#include <sysml/usecases/UseCaseUsage.h>
#include <sysml/views/ViewUsage.h>
#include <sysml/views/ViewpointUsage.h>
#include <sysml/views/RenderingUsage.h>
#include <sysml/metadata/MetadataUsage.h>
#include "../model/RepresentationSupport.h"
#include <algorithm>
#include <stdexcept>

namespace SysMLv2::Entities {

bool Definition::isVariation() const {
    return isVariation_;
}

void Definition::setIsVariation(bool value) {
    isVariation_ = std::move(value);
}

std::vector<std::shared_ptr<Usage>> Definition::variant() const {
    std::vector<std::shared_ptr<Usage>> result; for (const auto& membership : variantMembership()) { if (auto value = membership->ownedVariantUsage()) result.push_back(value); } return result;
}

std::vector<std::shared_ptr<VariantMembership>> Definition::variantMembership() const {
    return detail::select<VariantMembership>(KerML::Entities::Namespace::ownedMembership());
}

std::vector<std::shared_ptr<Usage>> Definition::usage() const {
    return detail::select<Usage>(KerML::Entities::Type::features());
}

std::vector<std::shared_ptr<Usage>> Definition::directedUsage() const {
    return detail::select<Usage>(KerML::Entities::Type::directedFeature());
}

std::vector<std::shared_ptr<Usage>> Definition::ownedUsage() const {
    return detail::select<Usage>(KerML::Entities::Type::ownedFeature());
}

std::vector<std::shared_ptr<ReferenceUsage>> Definition::ownedReference() const {
    return detail::select<ReferenceUsage>(KerML::Entities::Type::ownedFeature());
}

std::vector<std::shared_ptr<AttributeUsage>> Definition::ownedAttribute() const {
    return detail::select<AttributeUsage>(KerML::Entities::Type::ownedFeature());
}

std::vector<std::shared_ptr<EnumerationUsage>> Definition::ownedEnumeration() const {
    return detail::select<EnumerationUsage>(KerML::Entities::Type::ownedFeature());
}

std::vector<std::shared_ptr<OccurrenceUsage>> Definition::ownedOccurrence() const {
    return detail::select<OccurrenceUsage>(KerML::Entities::Type::ownedFeature());
}

std::vector<std::shared_ptr<ItemUsage>> Definition::ownedItem() const {
    return detail::select<ItemUsage>(KerML::Entities::Type::ownedFeature());
}

std::vector<std::shared_ptr<PartUsage>> Definition::ownedPart() const {
    return detail::select<PartUsage>(KerML::Entities::Type::ownedFeature());
}

std::vector<std::shared_ptr<PortUsage>> Definition::ownedPort() const {
    return detail::select<PortUsage>(KerML::Entities::Type::ownedFeature());
}

std::vector<std::shared_ptr<ConnectorAsUsage>> Definition::ownedConnection() const {
    return detail::select<ConnectorAsUsage>(KerML::Entities::Type::ownedFeature());
}

std::vector<std::shared_ptr<FlowUsage>> Definition::ownedFlow() const {
    return detail::select<FlowUsage>(KerML::Entities::Type::ownedFeature());
}

std::vector<std::shared_ptr<InterfaceUsage>> Definition::ownedInterface() const {
    return detail::select<InterfaceUsage>(KerML::Entities::Type::ownedFeature());
}

std::vector<std::shared_ptr<AllocationUsage>> Definition::ownedAllocation() const {
    return detail::select<AllocationUsage>(KerML::Entities::Type::ownedFeature());
}

std::vector<std::shared_ptr<ActionUsage>> Definition::ownedAction() const {
    return detail::select<ActionUsage>(KerML::Entities::Type::ownedFeature());
}

std::vector<std::shared_ptr<StateUsage>> Definition::ownedState() const {
    return detail::select<StateUsage>(KerML::Entities::Type::ownedFeature());
}

std::vector<std::shared_ptr<TransitionUsage>> Definition::ownedTransition() const {
    return detail::select<TransitionUsage>(KerML::Entities::Type::ownedFeature());
}

std::vector<std::shared_ptr<CalculationUsage>> Definition::ownedCalculation() const {
    return detail::select<CalculationUsage>(KerML::Entities::Type::ownedFeature());
}

std::vector<std::shared_ptr<ConstraintUsage>> Definition::ownedConstraint() const {
    return detail::select<ConstraintUsage>(KerML::Entities::Type::ownedFeature());
}

std::vector<std::shared_ptr<RequirementUsage>> Definition::ownedRequirement() const {
    return detail::select<RequirementUsage>(KerML::Entities::Type::ownedFeature());
}

std::vector<std::shared_ptr<ConcernUsage>> Definition::ownedConcern() const {
    return detail::select<ConcernUsage>(KerML::Entities::Type::ownedFeature());
}

std::vector<std::shared_ptr<CaseUsage>> Definition::ownedCase() const {
    return detail::select<CaseUsage>(KerML::Entities::Type::ownedFeature());
}

std::vector<std::shared_ptr<AnalysisCaseUsage>> Definition::ownedAnalysisCase() const {
    return detail::select<AnalysisCaseUsage>(KerML::Entities::Type::ownedFeature());
}

std::vector<std::shared_ptr<VerificationCaseUsage>> Definition::ownedVerificationCase() const {
    return detail::select<VerificationCaseUsage>(KerML::Entities::Type::ownedFeature());
}

std::vector<std::shared_ptr<UseCaseUsage>> Definition::ownedUseCase() const {
    return detail::select<UseCaseUsage>(KerML::Entities::Type::ownedFeature());
}

std::vector<std::shared_ptr<ViewUsage>> Definition::ownedView() const {
    return detail::select<ViewUsage>(KerML::Entities::Type::ownedFeature());
}

std::vector<std::shared_ptr<ViewpointUsage>> Definition::ownedViewpoint() const {
    return detail::select<ViewpointUsage>(KerML::Entities::Type::ownedFeature());
}

std::vector<std::shared_ptr<RenderingUsage>> Definition::ownedRendering() const {
    return detail::select<RenderingUsage>(KerML::Entities::Type::ownedFeature());
}

std::vector<std::shared_ptr<MetadataUsage>> Definition::ownedMetadata() const {
    return detail::select<MetadataUsage>(KerML::Entities::Type::ownedFeature());
}

Definition::Definition() {
    _dType = "Definition";
}

Definition::~Definition() = default;

std::string_view Definition::metaclassName() const noexcept {
    return "Definition";
}

std::vector<RepresentationIssue> Definition::validateRepresentation(bool includeDerived) const {
    std::vector<RepresentationIssue> issues; (void)includeDerived;
    return issues;
}

} // namespace SysMLv2::Entities
