// Generated by sysml/tools/generate_abstract_syntax.py.
#include <sysml/usage/ReferenceUsage.h>
#include <algorithm>
#include <stdexcept>

namespace SysMLv2::Entities {

bool ReferenceUsage::isReference() const {
    return !const_cast<ReferenceUsage*>(this)->KerML::Entities::Feature::isComposite();
}

ReferenceUsage::ReferenceUsage() {
    _dType = "ReferenceUsage";
}

ReferenceUsage::~ReferenceUsage() = default;

std::string_view ReferenceUsage::metaclassName() const noexcept {
    return "ReferenceUsage";
}

std::vector<RepresentationIssue> ReferenceUsage::validateRepresentation(bool includeDerived) const {
    std::vector<RepresentationIssue> issues; (void)includeDerived;
    return issues;
}

} // namespace SysMLv2::Entities
