// Generated by sysml/tools/generate_abstract_syntax.py.
#include <sysml/usage/Usage.h>
#include <sysml/usage/VariantMembership.h>
#include <sysml/usage/Definition.h>
#include <sysml/usage/ReferenceUsage.h>
#include <sysml/attributes/AttributeUsage.h>
#include <sysml/enumerations/EnumerationUsage.h>
#include <sysml/occurrences/OccurrenceUsage.h>
#include <sysml/items/ItemUsage.h>
#include <sysml/parts/PartUsage.h>
#include <sysml/ports/PortUsage.h>
#include <sysml/connections/ConnectorAsUsage.h>
#include <sysml/flows/FlowUsage.h>
#include <sysml/interfaces/InterfaceUsage.h>
#include <sysml/allocations/AllocationUsage.h>
#include <sysml/actions/ActionUsage.h>
#include <sysml/states/StateUsage.h>
#include <sysml/states/TransitionUsage.h>
#include <sysml/calculations/CalculationUsage.h>
#include <sysml/constraints/ConstraintUsage.h>
#include <sysml/requirements/RequirementUsage.h>
#include <sysml/requirements/ConcernUsage.h>
#include <sysml/cases/CaseUsage.h>
#include <sysml/analysiscases/AnalysisCaseUsage.h>
#include <sysml/verificationcases/VerificationCaseUsage.h>
#include <sysml/usecases/UseCaseUsage.h>
#include <sysml/views/ViewUsage.h>
#include <sysml/views/ViewpointUsage.h>
#include <sysml/views/RenderingUsage.h>
#include <sysml/metadata/MetadataUsage.h>
#include "../model/RepresentationSupport.h"
#include <algorithm>
#include <stdexcept>

namespace SysMLv2::Entities {

bool Usage::mayTimeVary() const {
    return mayTimeVary_;
}

void Usage::setMayTimeVary(bool value) {
    mayTimeVary_ = std::move(value);
}

bool Usage::isReference() const {
    return !const_cast<Usage*>(this)->KerML::Entities::Feature::isComposite();
}

std::vector<std::shared_ptr<Usage>> Usage::variant() const {
    std::vector<std::shared_ptr<Usage>> result; for (const auto& membership : variantMembership()) { if (auto value = membership->ownedVariantUsage()) result.push_back(value); } return result;
}

std::vector<std::shared_ptr<VariantMembership>> Usage::variantMembership() const {
    return detail::select<VariantMembership>(KerML::Entities::Namespace::ownedMembership());
}

std::shared_ptr<Definition> Usage::owningDefinition() const {
    auto owner = KerML::Entities::Feature::owningType(); return owner ? std::dynamic_pointer_cast<Definition>(*owner) : nullptr;
}

std::shared_ptr<Usage> Usage::owningUsage() const {
    auto owner = KerML::Entities::Feature::owningType(); return owner ? std::dynamic_pointer_cast<Usage>(*owner) : nullptr;
}

std::vector<std::shared_ptr<KerML::Entities::Classifier>> Usage::definition() const {
    return detail::select<KerML::Entities::Classifier>(KerML::Entities::Feature::type());
}

std::vector<std::shared_ptr<Usage>> Usage::usage() const {
    return detail::select<Usage>(KerML::Entities::Type::features());
}

std::vector<std::shared_ptr<Usage>> Usage::directedUsage() const {
    return detail::select<Usage>(KerML::Entities::Type::directedFeature());
}

std::vector<std::shared_ptr<Usage>> Usage::nestedUsage() const {
    return detail::select<Usage>(KerML::Entities::Type::ownedFeature());
}

std::vector<std::shared_ptr<ReferenceUsage>> Usage::nestedReference() const {
    return detail::select<ReferenceUsage>(KerML::Entities::Type::ownedFeature());
}

std::vector<std::shared_ptr<AttributeUsage>> Usage::nestedAttribute() const {
    return detail::select<AttributeUsage>(KerML::Entities::Type::ownedFeature());
}

std::vector<std::shared_ptr<EnumerationUsage>> Usage::nestedEnumeration() const {
    return detail::select<EnumerationUsage>(KerML::Entities::Type::ownedFeature());
}

std::vector<std::shared_ptr<OccurrenceUsage>> Usage::nestedOccurrence() const {
    return detail::select<OccurrenceUsage>(KerML::Entities::Type::ownedFeature());
}

std::vector<std::shared_ptr<ItemUsage>> Usage::nestedItem() const {
    return detail::select<ItemUsage>(KerML::Entities::Type::ownedFeature());
}

std::vector<std::shared_ptr<PartUsage>> Usage::nestedPart() const {
    return detail::select<PartUsage>(KerML::Entities::Type::ownedFeature());
}

std::vector<std::shared_ptr<PortUsage>> Usage::nestedPort() const {
    return detail::select<PortUsage>(KerML::Entities::Type::ownedFeature());
}

std::vector<std::shared_ptr<ConnectorAsUsage>> Usage::nestedConnection() const {
    return detail::select<ConnectorAsUsage>(KerML::Entities::Type::ownedFeature());
}

std::vector<std::shared_ptr<FlowUsage>> Usage::nestedFlow() const {
    return detail::select<FlowUsage>(KerML::Entities::Type::ownedFeature());
}

std::vector<std::shared_ptr<InterfaceUsage>> Usage::nestedInterface() const {
    return detail::select<InterfaceUsage>(KerML::Entities::Type::ownedFeature());
}

std::vector<std::shared_ptr<AllocationUsage>> Usage::nestedAllocation() const {
    return detail::select<AllocationUsage>(KerML::Entities::Type::ownedFeature());
}

std::vector<std::shared_ptr<ActionUsage>> Usage::nestedAction() const {
    return detail::select<ActionUsage>(KerML::Entities::Type::ownedFeature());
}

std::vector<std::shared_ptr<StateUsage>> Usage::nestedState() const {
    return detail::select<StateUsage>(KerML::Entities::Type::ownedFeature());
}

std::vector<std::shared_ptr<TransitionUsage>> Usage::nestedTransition() const {
    return detail::select<TransitionUsage>(KerML::Entities::Type::ownedFeature());
}

std::vector<std::shared_ptr<CalculationUsage>> Usage::nestedCalculation() const {
    return detail::select<CalculationUsage>(KerML::Entities::Type::ownedFeature());
}

std::vector<std::shared_ptr<ConstraintUsage>> Usage::nestedConstraint() const {
    return detail::select<ConstraintUsage>(KerML::Entities::Type::ownedFeature());
}

std::vector<std::shared_ptr<RequirementUsage>> Usage::nestedRequirement() const {
    return detail::select<RequirementUsage>(KerML::Entities::Type::ownedFeature());
}

std::vector<std::shared_ptr<ConcernUsage>> Usage::nestedConcern() const {
    return detail::select<ConcernUsage>(KerML::Entities::Type::ownedFeature());
}

std::vector<std::shared_ptr<CaseUsage>> Usage::nestedCase() const {
    return detail::select<CaseUsage>(KerML::Entities::Type::ownedFeature());
}

std::vector<std::shared_ptr<AnalysisCaseUsage>> Usage::nestedAnalysisCase() const {
    return detail::select<AnalysisCaseUsage>(KerML::Entities::Type::ownedFeature());
}

std::vector<std::shared_ptr<VerificationCaseUsage>> Usage::nestedVerificationCase() const {
    return detail::select<VerificationCaseUsage>(KerML::Entities::Type::ownedFeature());
}

std::vector<std::shared_ptr<UseCaseUsage>> Usage::nestedUseCase() const {
    return detail::select<UseCaseUsage>(KerML::Entities::Type::ownedFeature());
}

std::vector<std::shared_ptr<ViewUsage>> Usage::nestedView() const {
    return detail::select<ViewUsage>(KerML::Entities::Type::ownedFeature());
}

std::vector<std::shared_ptr<ViewpointUsage>> Usage::nestedViewpoint() const {
    return detail::select<ViewpointUsage>(KerML::Entities::Type::ownedFeature());
}

std::vector<std::shared_ptr<RenderingUsage>> Usage::nestedRendering() const {
    return detail::select<RenderingUsage>(KerML::Entities::Type::ownedFeature());
}

std::vector<std::shared_ptr<MetadataUsage>> Usage::nestedMetadata() const {
    return detail::select<MetadataUsage>(KerML::Entities::Type::ownedFeature());
}

bool Usage::isVariation() const {
    return isVariation_;
}

void Usage::setIsVariation(bool value) {
    isVariation_ = std::move(value);
}

Usage::Usage() {
    _dType = "Usage";
}

Usage::~Usage() = default;

std::string_view Usage::metaclassName() const noexcept {
    return "Usage";
}

std::vector<RepresentationIssue> Usage::validateRepresentation(bool includeDerived) const {
    std::vector<RepresentationIssue> issues; (void)includeDerived;
    return issues;
}

} // namespace SysMLv2::Entities
