// Generated by sysml/tools/generate_abstract_syntax.py.
#include <sysml/usage/VariantMembership.h>
#include <sysml/usage/Usage.h>
#include <algorithm>
#include <stdexcept>

namespace SysMLv2::Entities {

std::shared_ptr<Usage> VariantMembership::ownedVariantUsage() const {
    return ownedVariantUsage_;
}

void VariantMembership::setOwnedVariantUsage(std::shared_ptr<Usage> value) {
    ownedVariantUsage_ = std::move(value);
}

VariantMembership::VariantMembership() {
    _dType = "VariantMembership";
}

VariantMembership::~VariantMembership() = default;

std::string_view VariantMembership::metaclassName() const noexcept {
    return "VariantMembership";
}

std::vector<RepresentationIssue> VariantMembership::validateRepresentation(bool includeDerived) const {
    std::vector<RepresentationIssue> issues; (void)includeDerived;
    if (includeDerived) if (!VariantMembership::ownedVariantUsage()) issues.push_back({"VariantMembership.ownedVariantUsage", "required reference is missing"});
    return issues;
}

} // namespace SysMLv2::Entities
