// Generated by kerml/tools/generate_abstract_syntax.py.
#include <kerml/KerML.h>
#include <utility>
#include <stdexcept>
#include "../../model/RepresentationSupport.h"

namespace KerML::Entities {
std::vector<std::shared_ptr<Type>> Association::relatedType() const {
    return detail::select<Type>(relatedElement());
}

std::shared_ptr<Type> Association::sourceType() const {
    auto values = detail::select<Type>(source()); return values.empty() ? nullptr : values.front();
}

std::vector<std::shared_ptr<Type>> Association::targetType() const {
    return detail::select<Type>(target());
}

std::vector<std::shared_ptr<Feature>> Association::associationEnd() const {
    return endFeature();
}

void Association::setAssociationEnd(std::vector<std::shared_ptr<Feature>> value) {
    detail::checkCollection(value, true, -1);
    setEndFeatures(std::move(value));
}

void Association::appendAssociationEnd(std::shared_ptr<Feature> value) {
    auto values = associationEnd(); values.push_back(std::move(value)); setAssociationEnd(std::move(values));
}

Association::Association() {
    _dType = "Association";
}

Association::~Association() = default;
}
