// Generated by sysml/tools/generate_abstract_syntax.py.
#include <sysml/items/ItemDefinition.h>
#include <algorithm>
#include <stdexcept>

namespace SysMLv2::Entities {

ItemDefinition::ItemDefinition() {
    _dType = "ItemDefinition";
}

ItemDefinition::~ItemDefinition() = default;

std::string_view ItemDefinition::metaclassName() const noexcept {
    return "ItemDefinition";
}

std::vector<RepresentationIssue> ItemDefinition::validateRepresentation(bool includeDerived) const {
    std::vector<RepresentationIssue> issues; (void)includeDerived;
    return issues;
}

} // namespace SysMLv2::Entities
