// Generated by sysml/tools/generate_abstract_syntax.py.
#include <sysml/items/ItemUsage.h>
#include <algorithm>
#include <stdexcept>

namespace SysMLv2::Entities {

std::vector<std::shared_ptr<KerML::Entities::Structure>> ItemUsage::itemDefinition() const {
    return itemDefinition_;
}

void ItemUsage::setItemDefinition(std::vector<std::shared_ptr<KerML::Entities::Structure>> value) {
    if (std::any_of(value.begin(), value.end(), [](const auto& item) { return !item; })) {
        throw std::invalid_argument("ItemUsage.itemDefinition: null entry");
    }
    for (std::size_t i = 0; i < value.size(); ++i) {
        if (std::find(value.begin(), value.begin() + i, value[i]) != value.begin() + i) {
            throw std::invalid_argument("ItemUsage.itemDefinition: duplicate entry");
        }
    }
    itemDefinition_ = std::move(value);
}

void ItemUsage::appendItemDefinition(std::shared_ptr<KerML::Entities::Structure> value) {
    auto values = itemDefinition();
    values.push_back(std::move(value));
    setItemDefinition(std::move(values));
}

ItemUsage::ItemUsage() {
    _dType = "ItemUsage";
}

ItemUsage::~ItemUsage() = default;

std::string_view ItemUsage::metaclassName() const noexcept {
    return "ItemUsage";
}

std::vector<RepresentationIssue> ItemUsage::validateRepresentation(bool includeDerived) const {
    std::vector<RepresentationIssue> issues; (void)includeDerived;
    { auto optional = OccurrenceUsage::portionKind(); if (optional) { auto value = *optional; if (!(value == PortionKind::timeslice || value == PortionKind::snapshot)) issues.push_back({"OccurrenceUsage.portionKind", "invalid enumeration value"}); } }
    return issues;
}

} // namespace SysMLv2::Entities
