// Generated by sysml/tools/generate_abstract_syntax.py.
#include <sysml/calculations/CalculationDefinition.h>
#include <sysml/calculations/CalculationUsage.h>
#include <algorithm>
#include <stdexcept>

namespace SysMLv2::Entities {

std::vector<std::shared_ptr<CalculationUsage>> CalculationDefinition::calculation() const {
    return calculation_;
}

void CalculationDefinition::setCalculation(std::vector<std::shared_ptr<CalculationUsage>> value) {
    if (std::any_of(value.begin(), value.end(), [](const auto& item) { return !item; })) {
        throw std::invalid_argument("CalculationDefinition.calculation: null entry");
    }
    for (std::size_t i = 0; i < value.size(); ++i) {
        if (std::find(value.begin(), value.begin() + i, value[i]) != value.begin() + i) {
            throw std::invalid_argument("CalculationDefinition.calculation: duplicate entry");
        }
    }
    calculation_ = std::move(value);
}

void CalculationDefinition::appendCalculation(std::shared_ptr<CalculationUsage> value) {
    auto values = calculation();
    values.push_back(std::move(value));
    setCalculation(std::move(values));
}

CalculationDefinition::CalculationDefinition() {
    _dType = "CalculationDefinition";
}

CalculationDefinition::~CalculationDefinition() = default;

std::string_view CalculationDefinition::metaclassName() const noexcept {
    return "CalculationDefinition";
}

std::vector<RepresentationIssue> CalculationDefinition::validateRepresentation(bool includeDerived) const {
    std::vector<RepresentationIssue> issues; (void)includeDerived;
    return issues;
}

} // namespace SysMLv2::Entities
