// Generated by sysml/tools/generate_abstract_syntax.py.
#include <sysml/calculations/CalculationUsage.h>
#include <algorithm>
#include <stdexcept>

namespace SysMLv2::Entities {

std::shared_ptr<KerML::Entities::Function> CalculationUsage::calculationDefinition() const {
    return calculationDefinition_;
}

void CalculationUsage::setCalculationDefinition(std::shared_ptr<KerML::Entities::Function> value) {
    calculationDefinition_ = std::move(value);
}

CalculationUsage::CalculationUsage() {
    _dType = "CalculationUsage";
}

CalculationUsage::~CalculationUsage() = default;

std::string_view CalculationUsage::metaclassName() const noexcept {
    return "CalculationUsage";
}

std::vector<RepresentationIssue> CalculationUsage::validateRepresentation(bool includeDerived) const {
    std::vector<RepresentationIssue> issues; (void)includeDerived;
    { auto optional = OccurrenceUsage::portionKind(); if (optional) { auto value = *optional; if (!(value == PortionKind::timeslice || value == PortionKind::snapshot)) issues.push_back({"OccurrenceUsage.portionKind", "invalid enumeration value"}); } }
    return issues;
}

} // namespace SysMLv2::Entities
