// Generated by sysml/tools/generate_abstract_syntax.py.
#include <sysml/flows/FlowUsage.h>
#include <algorithm>
#include <stdexcept>

namespace SysMLv2::Entities {

std::vector<std::shared_ptr<KerML::Entities::Interaction>> FlowUsage::flowDefinition() const {
    return flowDefinition_;
}

void FlowUsage::setFlowDefinition(std::vector<std::shared_ptr<KerML::Entities::Interaction>> value) {
    if (std::any_of(value.begin(), value.end(), [](const auto& item) { return !item; })) {
        throw std::invalid_argument("FlowUsage.flowDefinition: null entry");
    }
    for (std::size_t i = 0; i < value.size(); ++i) {
        if (std::find(value.begin(), value.begin() + i, value[i]) != value.begin() + i) {
            throw std::invalid_argument("FlowUsage.flowDefinition: duplicate entry");
        }
    }
    flowDefinition_ = std::move(value);
}

void FlowUsage::appendFlowDefinition(std::shared_ptr<KerML::Entities::Interaction> value) {
    auto values = flowDefinition();
    values.push_back(std::move(value));
    setFlowDefinition(std::move(values));
}

FlowUsage::FlowUsage() {
    _dType = "FlowUsage";
}

FlowUsage::~FlowUsage() = default;

std::string_view FlowUsage::metaclassName() const noexcept {
    return "FlowUsage";
}

std::vector<RepresentationIssue> FlowUsage::validateRepresentation(bool includeDerived) const {
    std::vector<RepresentationIssue> issues; (void)includeDerived;
    { auto optional = OccurrenceUsage::portionKind(); if (optional) { auto value = *optional; if (!(value == PortionKind::timeslice || value == PortionKind::snapshot)) issues.push_back({"OccurrenceUsage.portionKind", "invalid enumeration value"}); } }
    return issues;
}

} // namespace SysMLv2::Entities
