// Generated by sysml/tools/generate_abstract_syntax.py.
#include <sysml/flows/SuccessionFlowUsage.h>
#include <algorithm>
#include <stdexcept>

namespace SysMLv2::Entities {

SuccessionFlowUsage::SuccessionFlowUsage() {
    _dType = "SuccessionFlowUsage";
}

SuccessionFlowUsage::~SuccessionFlowUsage() = default;

std::string_view SuccessionFlowUsage::metaclassName() const noexcept {
    return "SuccessionFlowUsage";
}

std::vector<RepresentationIssue> SuccessionFlowUsage::validateRepresentation(bool includeDerived) const {
    std::vector<RepresentationIssue> issues; (void)includeDerived;
    { auto optional = OccurrenceUsage::portionKind(); if (optional) { auto value = *optional; if (!(value == PortionKind::timeslice || value == PortionKind::snapshot)) issues.push_back({"OccurrenceUsage.portionKind", "invalid enumeration value"}); } }
    return issues;
}

} // namespace SysMLv2::Entities
