// Generated by sysml/tools/generate_abstract_syntax.py.
#pragma once
#include <sysml/model/Representation.h>
#include <sysml/model/Forward.h>
#include <sysml/model/KerMLTypes.h>
#include <sysml/items/ItemUsage.h>

namespace SysMLv2::Entities {
class SYSML_EXPORT MetadataUsage : public virtual KerML::Entities::MetadataFeature, public virtual ItemUsage, public virtual Representation {
public:
    MetadataUsage();
    ~MetadataUsage() override;
    std::string_view metaclassName() const noexcept override;
    std::vector<RepresentationIssue> validateRepresentation(bool includeDerived = false) const override;
    /// Derived snapshot; populated by a semantic evaluator or importer.
    std::shared_ptr<KerML::Entities::Metaclass> metadataDefinition() const;
    void setMetadataDefinition(std::shared_ptr<KerML::Entities::Metaclass> value);
private:
    std::shared_ptr<KerML::Entities::Metaclass> metadataDefinition_ = {};
};
}
