// Generated by sysml/tools/generate_abstract_syntax.py.
#pragma once
#include <sysml/model/Representation.h>
#include <sysml/model/Forward.h>
#include <sysml/model/KerMLTypes.h>
#include <sysml/occurrences/OccurrenceUsage.h>

namespace SysMLv2::Entities {
class SYSML_EXPORT ItemUsage : public virtual OccurrenceUsage, public virtual Representation {
public:
    ItemUsage();
    ~ItemUsage() override;
    std::string_view metaclassName() const noexcept override;
    std::vector<RepresentationIssue> validateRepresentation(bool includeDerived = false) const override;
    /// Derived snapshot; populated by a semantic evaluator or importer.
    std::vector<std::shared_ptr<KerML::Entities::Structure>> itemDefinition() const;
    void setItemDefinition(std::vector<std::shared_ptr<KerML::Entities::Structure>> value);
    void appendItemDefinition(std::shared_ptr<KerML::Entities::Structure> value);
private:
    std::vector<std::shared_ptr<KerML::Entities::Structure>> itemDefinition_ = {};
};
}
