// Generated by sysml/tools/generate_abstract_syntax.py.
#include <sysml/interfaces/InterfaceDefinition.h>
#include <sysml/ports/PortUsage.h>
#include <algorithm>
#include <stdexcept>

namespace SysMLv2::Entities {

std::vector<std::shared_ptr<PortUsage>> InterfaceDefinition::interfaceEnd() const {
    return interfaceEnd_;
}

void InterfaceDefinition::setInterfaceEnd(std::vector<std::shared_ptr<PortUsage>> value) {
    if (std::any_of(value.begin(), value.end(), [](const auto& item) { return !item; })) {
        throw std::invalid_argument("InterfaceDefinition.interfaceEnd: null entry");
    }
    for (std::size_t i = 0; i < value.size(); ++i) {
        if (std::find(value.begin(), value.begin() + i, value[i]) != value.begin() + i) {
            throw std::invalid_argument("InterfaceDefinition.interfaceEnd: duplicate entry");
        }
    }
    interfaceEnd_ = std::move(value);
}

void InterfaceDefinition::appendInterfaceEnd(std::shared_ptr<PortUsage> value) {
    auto values = interfaceEnd();
    values.push_back(std::move(value));
    setInterfaceEnd(std::move(values));
}

InterfaceDefinition::InterfaceDefinition() {
    _dType = "InterfaceDefinition";
}

InterfaceDefinition::~InterfaceDefinition() = default;

std::string_view InterfaceDefinition::metaclassName() const noexcept {
    return "InterfaceDefinition";
}

std::vector<RepresentationIssue> InterfaceDefinition::validateRepresentation(bool includeDerived) const {
    std::vector<RepresentationIssue> issues; (void)includeDerived;
    return issues;
}

} // namespace SysMLv2::Entities
