// Generated by sysml/tools/generate_abstract_syntax.py.
#include <sysml/interfaces/InterfaceUsage.h>
#include <sysml/interfaces/InterfaceDefinition.h>
#include <algorithm>
#include <stdexcept>

namespace SysMLv2::Entities {

std::vector<std::shared_ptr<InterfaceDefinition>> InterfaceUsage::interfaceDefinition() const {
    return interfaceDefinition_;
}

void InterfaceUsage::setInterfaceDefinition(std::vector<std::shared_ptr<InterfaceDefinition>> value) {
    if (std::any_of(value.begin(), value.end(), [](const auto& item) { return !item; })) {
        throw std::invalid_argument("InterfaceUsage.interfaceDefinition: null entry");
    }
    for (std::size_t i = 0; i < value.size(); ++i) {
        if (std::find(value.begin(), value.begin() + i, value[i]) != value.begin() + i) {
            throw std::invalid_argument("InterfaceUsage.interfaceDefinition: duplicate entry");
        }
    }
    interfaceDefinition_ = std::move(value);
}

void InterfaceUsage::appendInterfaceDefinition(std::shared_ptr<InterfaceDefinition> value) {
    auto values = interfaceDefinition();
    values.push_back(std::move(value));
    setInterfaceDefinition(std::move(values));
}

InterfaceUsage::InterfaceUsage() {
    _dType = "InterfaceUsage";
}

InterfaceUsage::~InterfaceUsage() = default;

std::string_view InterfaceUsage::metaclassName() const noexcept {
    return "InterfaceUsage";
}

std::vector<RepresentationIssue> InterfaceUsage::validateRepresentation(bool includeDerived) const {
    std::vector<RepresentationIssue> issues; (void)includeDerived;
    { auto optional = OccurrenceUsage::portionKind(); if (optional) { auto value = *optional; if (!(value == PortionKind::timeslice || value == PortionKind::snapshot)) issues.push_back({"OccurrenceUsage.portionKind", "invalid enumeration value"}); } }
    return issues;
}

} // namespace SysMLv2::Entities
