// Generated by sysml/tools/generate_abstract_syntax.py.
#include <sysml/metadata/MetadataUsage.h>
#include <algorithm>
#include <stdexcept>

namespace SysMLv2::Entities {

std::shared_ptr<KerML::Entities::Metaclass> MetadataUsage::metadataDefinition() const {
    return metadataDefinition_;
}

void MetadataUsage::setMetadataDefinition(std::shared_ptr<KerML::Entities::Metaclass> value) {
    metadataDefinition_ = std::move(value);
}

MetadataUsage::MetadataUsage() {
    _dType = "MetadataUsage";
}

MetadataUsage::~MetadataUsage() = default;

std::string_view MetadataUsage::metaclassName() const noexcept {
    return "MetadataUsage";
}

std::vector<RepresentationIssue> MetadataUsage::validateRepresentation(bool includeDerived) const {
    std::vector<RepresentationIssue> issues; (void)includeDerived;
    { auto optional = OccurrenceUsage::portionKind(); if (optional) { auto value = *optional; if (!(value == PortionKind::timeslice || value == PortionKind::snapshot)) issues.push_back({"OccurrenceUsage.portionKind", "invalid enumeration value"}); } }
    return issues;
}

} // namespace SysMLv2::Entities
