// Generated by sysml/tools/generate_abstract_syntax.py.
#include <sysml/metadata/MetadataDefinition.h>
#include <algorithm>
#include <stdexcept>

namespace SysMLv2::Entities {

MetadataDefinition::MetadataDefinition() {
    _dType = "MetadataDefinition";
}

MetadataDefinition::~MetadataDefinition() = default;

std::string_view MetadataDefinition::metaclassName() const noexcept {
    return "MetadataDefinition";
}

std::vector<RepresentationIssue> MetadataDefinition::validateRepresentation(bool includeDerived) const {
    std::vector<RepresentationIssue> issues; (void)includeDerived;
    return issues;
}

} // namespace SysMLv2::Entities
