// Generated by sysml/tools/generate_abstract_syntax.py.
#pragma once
#include <sysml/model/Representation.h>
#include <sysml/model/Forward.h>
#include <sysml/model/KerMLTypes.h>
#include <sysml/connections/ConnectorAsUsage.h>

namespace SysMLv2::Entities {
class SYSML_EXPORT BindingConnectorAsUsage : public virtual KerML::Entities::BindingConnector, public virtual ConnectorAsUsage, public virtual Representation {
public:
    BindingConnectorAsUsage();
    ~BindingConnectorAsUsage() override;
    std::string_view metaclassName() const noexcept override;
    std::vector<RepresentationIssue> validateRepresentation(bool includeDerived = false) const override;
private:
};
}
