// Generated by sysml/tools/generate_abstract_syntax.py.
#pragma once
#include <sysml/model/Representation.h>
#include <sysml/model/Forward.h>
#include <sysml/model/KerMLTypes.h>
#include <sysml/parts/PartDefinition.h>

namespace SysMLv2::Entities {
class SYSML_EXPORT ConnectionDefinition : public virtual KerML::Entities::AssociationStructure, public virtual PartDefinition, public virtual Representation {
public:
    ConnectionDefinition();
    ~ConnectionDefinition() override;
    std::string_view metaclassName() const noexcept override;
    std::vector<RepresentationIssue> validateRepresentation(bool includeDerived = false) const override;
    /// Derived snapshot; populated by a semantic evaluator or importer.
    std::vector<std::shared_ptr<Usage>> connectionEnd() const;
    void setConnectionEnd(std::vector<std::shared_ptr<Usage>> value);
    void appendConnectionEnd(std::shared_ptr<Usage> value);
    /// Stored metamodel property.
    bool isSufficient() const;
    void setIsSufficient(bool value);
private:
    std::vector<std::shared_ptr<Usage>> connectionEnd_ = {};
    bool isSufficient_ = true;
};
}
