// Generated by sysml/tools/generate_abstract_syntax.py.
#pragma once
#include <sysml/model/Representation.h>
#include <sysml/model/Forward.h>
#include <sysml/model/KerMLTypes.h>
#include <sysml/parts/PartUsage.h>
#include <sysml/connections/ConnectorAsUsage.h>

namespace SysMLv2::Entities {
class SYSML_EXPORT ConnectionUsage : public virtual PartUsage, public virtual ConnectorAsUsage, public virtual Representation {
public:
    ConnectionUsage();
    ~ConnectionUsage() override;
    std::string_view metaclassName() const noexcept override;
    std::vector<RepresentationIssue> validateRepresentation(bool includeDerived = false) const override;
    /// Derived snapshot; populated by a semantic evaluator or importer.
    std::vector<std::shared_ptr<KerML::Entities::AssociationStructure>> connectionDefinition() const;
    void setConnectionDefinition(std::vector<std::shared_ptr<KerML::Entities::AssociationStructure>> value);
    void appendConnectionDefinition(std::shared_ptr<KerML::Entities::AssociationStructure> value);
private:
    std::vector<std::shared_ptr<KerML::Entities::AssociationStructure>> connectionDefinition_ = {};
};
}
