// Generated by sysml/tools/generate_abstract_syntax.py.
#pragma once
#include <sysml/model/Representation.h>
#include <sysml/model/Forward.h>
#include <sysml/model/KerMLTypes.h>
#include <sysml/usage/Usage.h>

namespace SysMLv2::Entities {
class SYSML_EXPORT ConnectorAsUsage : public virtual Usage, public virtual KerML::Entities::Connector, public virtual Representation {
public:
    ConnectorAsUsage();
    ~ConnectorAsUsage() override;
    std::string_view metaclassName() const noexcept override = 0;
    std::vector<RepresentationIssue> validateRepresentation(bool includeDerived = false) const override;
private:
};
}
