// Generated by sysml/tools/generate_abstract_syntax.py.
#pragma once
#include <sysml/model/Representation.h>
#include <sysml/model/Forward.h>
#include <sysml/model/KerMLTypes.h>
#include <sysml/connections/ConnectorAsUsage.h>

namespace SysMLv2::Entities {
class SYSML_EXPORT SuccessionAsUsage : public virtual ConnectorAsUsage, public virtual KerML::Entities::Succession, public virtual Representation {
public:
    SuccessionAsUsage();
    ~SuccessionAsUsage() override;
    std::string_view metaclassName() const noexcept override;
    std::vector<RepresentationIssue> validateRepresentation(bool includeDerived = false) const override;
private:
};
}
