# WebAssembly module of sysmlv2check (ES module sysmlv2check.js + sysmlv2check.wasm; tested with emsdk 5.0.2 and Node, see the README).
#
# Build: check/cmake/build-wasm.sh (conan install with check/cmake/emscripten.profile, cmake configure, build; emsdk 5.0.2 / clang 23).
# The preset "emscripten-check" (EmscriptenPresets.json) holds the same cache variables, but a CMakePresets.json generated by Conan that includes
# several generator folders can make presets fail ("Duplicate preset"), which is why the script passes the variables itself.
# Static libraries and -fwasm-exceptions everywhere (all dependencies are built with that flag by the profile), -O2 (no LTO: the module
# is 5 % bigger and not faster), no REST / services / online (no curl) / tests; the date library is header-only.
# Output: build/wasm/out/sysmlv2check.js (ES module, MODULARIZE + EXPORT_ES6, ENVIRONMENT=web,worker,node) and sysmlv2check.wasm (next to it).
# The module exports sysml_pruefe, sysml_freigeben, sysml_vorwaermen, sysml_konfigurieren (and malloc/free) and the runtime methods ccall/cwrap/UTF8ToString:
#   import createSysmlCheck from './sysmlv2check.js';
#   const mod = await createSysmlCheck();
#   const pruefe = mod.cwrap('sysml_pruefe', 'number', ['string']);   // returns a pointer to the response
#   const text = mod.UTF8ToString(ptr); mod._sysml_freigeben(ptr);
# The module keeps its standard library context for as long as the instance lives: create one instance per worker and reuse it.
add_executable(sysmlv2check-wasm src/CApi.cpp)
set_target_properties(sysmlv2check-wasm PROPERTIES OUTPUT_NAME sysmlv2check SUFFIX ".js")
target_link_libraries(sysmlv2check-wasm sysmlv2check)
target_compile_options(sysmlv2check-wasm PRIVATE -fwasm-exceptions)
target_link_options(sysmlv2check-wasm PRIVATE
        -fwasm-exceptions
        --no-entry
        -sMODULARIZE=1
        -sEXPORT_NAME=createSysmlCheck
        -sEXPORT_ES6=1
        -sENVIRONMENT=web,worker,node
        "-sEXPORTED_FUNCTIONS=['_sysml_pruefe','_sysml_freigeben','_sysml_vorwaermen','_sysml_konfigurieren','_sysml_speicher','_malloc','_free']"
        "-sEXPORTED_RUNTIME_METHODS=['ccall','cwrap','UTF8ToString']"
        -sALLOW_MEMORY_GROWTH=1
        # STACK_OVERFLOW_CHECK only places a cookie at the end of the stack that is verified at certain points (it detects an overflow afterwards,
        # it does not prevent it); the protection is the input limits (nesting depth, prefix operators, operators per statement).
        -sSTACK_OVERFLOW_CHECK=1
        -sSTACK_SIZE=16777216         # 16 MB shadow stack (there is one stack, no parse thread); the limits keep the recursion far below
        -sINITIAL_MEMORY=67108864     # 64 MB; grows on demand ...
        -sMAXIMUM_MEMORY=1073741824   # ... up to 1 GB, then allocation fails (std::bad_alloc -> error response / worker is replaced)
        -sFILESYSTEM=0)
