// Generated by sysml/tools/generate_abstract_syntax.py.
#pragma once
#include <sysml/model/Representation.h>
#include <sysml/model/Forward.h>
#include <sysml/model/KerMLTypes.h>
#include <sysml/actions/PerformActionUsage.h>
#include <sysml/states/StateUsage.h>

namespace SysMLv2::Entities {
class SYSML_EXPORT ExhibitStateUsage : public virtual PerformActionUsage, public virtual StateUsage, public virtual Representation {
public:
    ExhibitStateUsage();
    ~ExhibitStateUsage() override;
    std::string_view metaclassName() const noexcept override;
    std::vector<RepresentationIssue> validateRepresentation(bool includeDerived = false) const override;
    /// Derived snapshot; populated by a semantic evaluator or importer.
    std::shared_ptr<StateUsage> exhibitedState() const;
    void setExhibitedState(std::shared_ptr<StateUsage> value);
private:
    std::shared_ptr<StateUsage> exhibitedState_ = {};
};
}
