// Generated by sysml/tools/generate_abstract_syntax.py.
#pragma once
#include <sysml/model/Representation.h>
#include <sysml/model/Forward.h>
#include <sysml/model/KerMLTypes.h>
#include <sysml/actions/ActionDefinition.h>

namespace SysMLv2::Entities {
class SYSML_EXPORT StateDefinition : public virtual ActionDefinition, public virtual Representation {
public:
    StateDefinition();
    ~StateDefinition() override;
    std::string_view metaclassName() const noexcept override;
    std::vector<RepresentationIssue> validateRepresentation(bool includeDerived = false) const override;
    /// Derived snapshot; populated by a semantic evaluator or importer.
    std::vector<std::shared_ptr<StateUsage>> state() const;
    void setState(std::vector<std::shared_ptr<StateUsage>> value);
    void appendState(std::shared_ptr<StateUsage> value);
    /// Derived snapshot; populated by a semantic evaluator or importer.
    std::shared_ptr<ActionUsage> entryAction() const;
    void setEntryAction(std::shared_ptr<ActionUsage> value);
    /// Derived snapshot; populated by a semantic evaluator or importer.
    std::shared_ptr<ActionUsage> doAction() const;
    void setDoAction(std::shared_ptr<ActionUsage> value);
    /// Derived snapshot; populated by a semantic evaluator or importer.
    std::shared_ptr<ActionUsage> exitAction() const;
    void setExitAction(std::shared_ptr<ActionUsage> value);
    /// Stored metamodel property.
    bool isParallel() const;
    void setIsParallel(bool value);
private:
    std::vector<std::shared_ptr<StateUsage>> state_ = {};
    std::shared_ptr<ActionUsage> entryAction_ = {};
    std::shared_ptr<ActionUsage> doAction_ = {};
    std::shared_ptr<ActionUsage> exitAction_ = {};
    bool isParallel_ = false;
};
}
