// Generated by sysml/tools/generate_abstract_syntax.py.
#pragma once
#include <sysml/model/Representation.h>
#include <sysml/model/Forward.h>
#include <sysml/model/KerMLTypes.h>
#include <sysml/actions/ActionUsage.h>

namespace SysMLv2::Entities {
class SYSML_EXPORT StateUsage : public virtual ActionUsage, public virtual Representation {
public:
    StateUsage();
    ~StateUsage() override;
    std::string_view metaclassName() const noexcept override;
    std::vector<RepresentationIssue> validateRepresentation(bool includeDerived = false) const override;
    /// Derived snapshot; populated by a semantic evaluator or importer.
    std::vector<std::shared_ptr<KerML::Entities::Behavior>> stateDefinition() const;
    void setStateDefinition(std::vector<std::shared_ptr<KerML::Entities::Behavior>> value);
    void appendStateDefinition(std::shared_ptr<KerML::Entities::Behavior> value);
    /// Derived snapshot; populated by a semantic evaluator or importer.
    std::shared_ptr<ActionUsage> entryAction() const;
    void setEntryAction(std::shared_ptr<ActionUsage> value);
    /// Derived snapshot; populated by a semantic evaluator or importer.
    std::shared_ptr<ActionUsage> doAction() const;
    void setDoAction(std::shared_ptr<ActionUsage> value);
    /// Derived snapshot; populated by a semantic evaluator or importer.
    std::shared_ptr<ActionUsage> exitAction() const;
    void setExitAction(std::shared_ptr<ActionUsage> value);
    /// Stored metamodel property.
    bool isParallel() const;
    void setIsParallel(bool value);
private:
    std::vector<std::shared_ptr<KerML::Entities::Behavior>> stateDefinition_ = {};
    std::shared_ptr<ActionUsage> entryAction_ = {};
    std::shared_ptr<ActionUsage> doAction_ = {};
    std::shared_ptr<ActionUsage> exitAction_ = {};
    bool isParallel_ = false;
};
}
