// Generated by sysml/tools/generate_abstract_syntax.py.
#pragma once
#include <sysml/model/Representation.h>
#include <sysml/model/Forward.h>
#include <sysml/model/KerMLTypes.h>
#include <sysml/states/StateSubactionKind.h>

namespace SysMLv2::Entities {
class SYSML_EXPORT StateSubactionMembership : public virtual KerML::Entities::FeatureMembership, public virtual Representation {
public:
    StateSubactionMembership();
    ~StateSubactionMembership() override;
    std::string_view metaclassName() const noexcept override;
    std::vector<RepresentationIssue> validateRepresentation(bool includeDerived = false) const override;
    /// Stored metamodel property.
    StateSubactionKind kind() const;
    void setKind(StateSubactionKind value);
    /// Derived snapshot; populated by a semantic evaluator or importer.
    std::shared_ptr<ActionUsage> action() const;
    void setAction(std::shared_ptr<ActionUsage> value);
private:
    StateSubactionKind kind_ = {};
    std::shared_ptr<ActionUsage> action_ = {};
};
}
