// Generated by sysml/tools/generate_abstract_syntax.py.
#pragma once
#include <sysml/model/Representation.h>
#include <sysml/model/Forward.h>
#include <sysml/model/KerMLTypes.h>
#include <sysml/actions/ActionUsage.h>

namespace SysMLv2::Entities {
class SYSML_EXPORT TransitionUsage : public virtual ActionUsage, public virtual Representation {
public:
    TransitionUsage();
    ~TransitionUsage() override;
    std::string_view metaclassName() const noexcept override;
    std::vector<RepresentationIssue> validateRepresentation(bool includeDerived = false) const override;
    /// Derived snapshot; populated by a semantic evaluator or importer.
    std::shared_ptr<ActionUsage> source() const;
    void setSource(std::shared_ptr<ActionUsage> value);
    /// Derived snapshot; populated by a semantic evaluator or importer.
    std::shared_ptr<ActionUsage> target() const;
    void setTarget(std::shared_ptr<ActionUsage> value);
    /// Derived snapshot; populated by a semantic evaluator or importer.
    std::vector<std::shared_ptr<AcceptActionUsage>> triggerAction() const;
    void setTriggerAction(std::vector<std::shared_ptr<AcceptActionUsage>> value);
    void appendTriggerAction(std::shared_ptr<AcceptActionUsage> value);
    /// Derived snapshot; populated by a semantic evaluator or importer.
    std::vector<std::shared_ptr<KerML::Entities::Expression>> guardExpression() const;
    void setGuardExpression(std::vector<std::shared_ptr<KerML::Entities::Expression>> value);
    void appendGuardExpression(std::shared_ptr<KerML::Entities::Expression> value);
    /// Derived snapshot; populated by a semantic evaluator or importer.
    std::vector<std::shared_ptr<ActionUsage>> effectAction() const;
    void setEffectAction(std::vector<std::shared_ptr<ActionUsage>> value);
    void appendEffectAction(std::shared_ptr<ActionUsage> value);
    /// Derived snapshot; populated by a semantic evaluator or importer.
    std::shared_ptr<KerML::Entities::Succession> succession() const;
    void setSuccession(std::shared_ptr<KerML::Entities::Succession> value);
private:
    std::shared_ptr<ActionUsage> source_ = {};
    std::shared_ptr<ActionUsage> target_ = {};
    std::vector<std::shared_ptr<AcceptActionUsage>> triggerAction_ = {};
    std::vector<std::shared_ptr<KerML::Entities::Expression>> guardExpression_ = {};
    std::vector<std::shared_ptr<ActionUsage>> effectAction_ = {};
    std::shared_ptr<KerML::Entities::Succession> succession_ = {};
};
}
