// Generated by sysml/tools/generate_abstract_syntax.py.
#pragma once
#include <sysml/model/Representation.h>
#include <sysml/model/Forward.h>
#include <sysml/model/KerMLTypes.h>
#include <sysml/states/TransitionFeatureKind.h>

namespace SysMLv2::Entities {
class SYSML_EXPORT TransitionFeatureMembership : public virtual KerML::Entities::FeatureMembership, public virtual Representation {
public:
    TransitionFeatureMembership();
    ~TransitionFeatureMembership() override;
    std::string_view metaclassName() const noexcept override;
    std::vector<RepresentationIssue> validateRepresentation(bool includeDerived = false) const override;
    /// Stored metamodel property.
    TransitionFeatureKind kind() const;
    void setKind(TransitionFeatureKind value);
    /// Derived snapshot; populated by a semantic evaluator or importer.
    std::shared_ptr<KerML::Entities::Step> transitionFeature() const;
    void setTransitionFeature(std::shared_ptr<KerML::Entities::Step> value);
private:
    TransitionFeatureKind kind_ = {};
    std::shared_ptr<KerML::Entities::Step> transitionFeature_ = {};
};
}
