// Generated by kerml/tools/generate_abstract_syntax.py.
#include <kerml/KerML.h>
#include <utility>
#include <stdexcept>
#include "../../model/RepresentationSupport.h"

namespace KerML::Entities {
BindingConnector::BindingConnector() {
    _dType = "BindingConnector";
}

BindingConnector::~BindingConnector() = default;
}
