// Generated by kerml/tools/generate_abstract_syntax.py.
#include <kerml/KerML.h>
#include <utility>
#include <stdexcept>
#include "../../model/RepresentationSupport.h"

namespace KerML::Entities {
std::vector<std::shared_ptr<Feature>> Connector::relatedFeature() const {
    return detail::select<Feature>(relatedElement());
}

std::vector<std::shared_ptr<Association>> Connector::association() const {
    return detail::select<Association>(Feature::type());
}

std::vector<std::shared_ptr<Feature>> Connector::connectorEnd() const {
    return endFeature();
}

void Connector::setConnectorEnd(std::vector<std::shared_ptr<Feature>> value) {
    detail::checkCollection(value, true, -1);
    setEndFeatures(std::move(value));
}

void Connector::appendConnectorEnd(std::shared_ptr<Feature> value) {
    auto values = connectorEnd(); values.push_back(std::move(value)); setConnectorEnd(std::move(values));
}

std::shared_ptr<Feature> Connector::sourceFeature() const {
    auto values = detail::select<Feature>(source()); return values.empty() ? nullptr : values.front();
}

std::vector<std::shared_ptr<Feature>> Connector::targetFeature() const {
    return detail::select<Feature>(target());
}

std::shared_ptr<Type> Connector::defaultFeaturingType() const {
    return defaultFeaturingType_;
}

void Connector::setDefaultFeaturingType(std::shared_ptr<Type> value) {
    defaultFeaturingType_ = std::move(value);
}

Connector::Connector() {
    _dType = "Connector";
}

Connector::~Connector() = default;
}
