#pragma once
#include <kerml/core/classifiers/Classifier.h>
#include <kerml/core/features/Feature.h>
#include <kerml/core/features/FeatureTyping.h>
#include <kerml/core/types/Conjugation.h>
#include <kerml/core/features/FeatureMembership.h>
#include <kerml/kernel/associations/AssociationStructure.h>
#include <kerml/kernel/behaviors/Behavior.h>
#include <kerml/kernel/functions/ParameterMembership.h>
#include <kerml/kernel/behaviors/Step.h>
#include <kerml/kernel/classes/Class.h>
#include <kerml/kernel/connectors/BindingConnector.h>
#include <kerml/kernel/connectors/Connector.h>
#include <kerml/kernel/connectors/Succession.h>
#include <kerml/kernel/datatypes/DataType.h>
#include <kerml/kernel/expressions/InvocationExpression.h>
#include <kerml/kernel/functions/BooleanExpression.h>
#include <kerml/kernel/functions/Expression.h>
#include <kerml/kernel/functions/Function.h>
#include <kerml/kernel/functions/Invariant.h>
#include <kerml/kernel/functions/Predicate.h>
#include <kerml/kernel/interactions/Flow.h>
#include <kerml/kernel/interactions/Interaction.h>
#include <kerml/kernel/interactions/SuccessionFlow.h>
#include <kerml/kernel/metadata/Metaclass.h>
#include <kerml/kernel/metadata/MetadataFeature.h>
#include <kerml/kernel/structures/Structure.h>
#include <kerml/root/elements/Element.h>
#include <kerml/root/namespaces/Import.h>
#include <kerml/root/namespaces/MembershipImport.h>
#include <kerml/root/namespaces/NamespaceImport.h>
#include <kerml/root/namespaces/OwningMembership.h>
#include <kerml/root/namespaces/VisibilityKind.h>
