// Generated by kerml/tools/generate_abstract_syntax.py.
#include <kerml/KerML.h>
#include <utility>
#include <stdexcept>
#include "../../model/RepresentationSupport.h"

namespace KerML::Entities {
Class::Class() {
    _dType = "Class";
}

Class::~Class() = default;
}
