// Generated by sysml/tools/generate_abstract_syntax.py.
#include <sysml/allocations/AllocationUsage.h>
#include <sysml/allocations/AllocationDefinition.h>
#include <algorithm>
#include <stdexcept>

namespace SysMLv2::Entities {

std::vector<std::shared_ptr<AllocationDefinition>> AllocationUsage::allocationDefinition() const {
    return allocationDefinition_;
}

void AllocationUsage::setAllocationDefinition(std::vector<std::shared_ptr<AllocationDefinition>> value) {
    if (std::any_of(value.begin(), value.end(), [](const auto& item) { return !item; })) {
        throw std::invalid_argument("AllocationUsage.allocationDefinition: null entry");
    }
    for (std::size_t i = 0; i < value.size(); ++i) {
        if (std::find(value.begin(), value.begin() + i, value[i]) != value.begin() + i) {
            throw std::invalid_argument("AllocationUsage.allocationDefinition: duplicate entry");
        }
    }
    allocationDefinition_ = std::move(value);
}

void AllocationUsage::appendAllocationDefinition(std::shared_ptr<AllocationDefinition> value) {
    auto values = allocationDefinition();
    values.push_back(std::move(value));
    setAllocationDefinition(std::move(values));
}

AllocationUsage::AllocationUsage() {
    _dType = "AllocationUsage";
}

AllocationUsage::~AllocationUsage() = default;

std::string_view AllocationUsage::metaclassName() const noexcept {
    return "AllocationUsage";
}

std::vector<RepresentationIssue> AllocationUsage::validateRepresentation(bool includeDerived) const {
    std::vector<RepresentationIssue> issues; (void)includeDerived;
    { auto optional = OccurrenceUsage::portionKind(); if (optional) { auto value = *optional; if (!(value == PortionKind::timeslice || value == PortionKind::snapshot)) issues.push_back({"OccurrenceUsage.portionKind", "invalid enumeration value"}); } }
    return issues;
}

} // namespace SysMLv2::Entities
