// Generated by sysml/tools/generate_abstract_syntax.py.
#include <sysml/allocations/AllocationDefinition.h>
#include <sysml/allocations/AllocationUsage.h>
#include <algorithm>
#include <stdexcept>

namespace SysMLv2::Entities {

std::vector<std::shared_ptr<AllocationUsage>> AllocationDefinition::allocation() const {
    return allocation_;
}

void AllocationDefinition::setAllocation(std::vector<std::shared_ptr<AllocationUsage>> value) {
    if (std::any_of(value.begin(), value.end(), [](const auto& item) { return !item; })) {
        throw std::invalid_argument("AllocationDefinition.allocation: null entry");
    }
    for (std::size_t i = 0; i < value.size(); ++i) {
        if (std::find(value.begin(), value.begin() + i, value[i]) != value.begin() + i) {
            throw std::invalid_argument("AllocationDefinition.allocation: duplicate entry");
        }
    }
    allocation_ = std::move(value);
}

void AllocationDefinition::appendAllocation(std::shared_ptr<AllocationUsage> value) {
    auto values = allocation();
    values.push_back(std::move(value));
    setAllocation(std::move(values));
}

AllocationDefinition::AllocationDefinition() {
    _dType = "AllocationDefinition";
}

AllocationDefinition::~AllocationDefinition() = default;

std::string_view AllocationDefinition::metaclassName() const noexcept {
    return "AllocationDefinition";
}

std::vector<RepresentationIssue> AllocationDefinition::validateRepresentation(bool includeDerived) const {
    std::vector<RepresentationIssue> issues; (void)includeDerived;
    return issues;
}

} // namespace SysMLv2::Entities
