// Generated by sysml/tools/generate_abstract_syntax.py.
#pragma once
#include <sysml/model/Representation.h>
#include <sysml/model/Forward.h>
#include <sysml/model/KerMLTypes.h>
#include <sysml/occurrences/OccurrenceUsage.h>

namespace SysMLv2::Entities {
class SYSML_EXPORT ActionUsage : public virtual KerML::Entities::Step, public virtual OccurrenceUsage, public virtual Representation {
public:
    ActionUsage();
    ~ActionUsage() override;
    std::string_view metaclassName() const noexcept override;
    std::vector<RepresentationIssue> validateRepresentation(bool includeDerived = false) const override;
    /// Derived snapshot; populated by a semantic evaluator or importer.
    std::vector<std::shared_ptr<KerML::Entities::Behavior>> actionDefinition() const;
    void setActionDefinition(std::vector<std::shared_ptr<KerML::Entities::Behavior>> value);
    void appendActionDefinition(std::shared_ptr<KerML::Entities::Behavior> value);
private:
    std::vector<std::shared_ptr<KerML::Entities::Behavior>> actionDefinition_ = {};
};
}
