// Generated by sysml/tools/generate_abstract_syntax.py.
#pragma once
#include <sysml/model/Representation.h>
#include <sysml/model/Forward.h>
#include <sysml/model/KerMLTypes.h>
#include <sysml/occurrences/OccurrenceDefinition.h>

namespace SysMLv2::Entities {
class SYSML_EXPORT ActionDefinition : public virtual OccurrenceDefinition, public virtual KerML::Entities::Behavior, public virtual Representation {
public:
    ActionDefinition();
    ~ActionDefinition() override;
    std::string_view metaclassName() const noexcept override;
    std::vector<RepresentationIssue> validateRepresentation(bool includeDerived = false) const override;
    /// Derived snapshot; populated by a semantic evaluator or importer.
    std::vector<std::shared_ptr<ActionUsage>> action() const;
    void setAction(std::vector<std::shared_ptr<ActionUsage>> value);
    void appendAction(std::shared_ptr<ActionUsage> value);
private:
    std::vector<std::shared_ptr<ActionUsage>> action_ = {};
};
}
