// Generated by sysml/tools/generate_abstract_syntax.py.
#pragma once
#include <sysml/model/Representation.h>
#include <sysml/model/Forward.h>
#include <sysml/model/KerMLTypes.h>
#include <sysml/actions/ActionUsage.h>

namespace SysMLv2::Entities {
class SYSML_EXPORT AssignmentActionUsage : public virtual ActionUsage, public virtual Representation {
public:
    AssignmentActionUsage();
    ~AssignmentActionUsage() override;
    std::string_view metaclassName() const noexcept override;
    std::vector<RepresentationIssue> validateRepresentation(bool includeDerived = false) const override;
    /// Derived snapshot; populated by a semantic evaluator or importer.
    std::shared_ptr<KerML::Entities::Expression> targetArgument() const;
    void setTargetArgument(std::shared_ptr<KerML::Entities::Expression> value);
    /// Derived snapshot; populated by a semantic evaluator or importer.
    std::shared_ptr<KerML::Entities::Expression> valueExpression() const;
    void setValueExpression(std::shared_ptr<KerML::Entities::Expression> value);
    /// Derived snapshot; populated by a semantic evaluator or importer.
    std::shared_ptr<KerML::Entities::Feature> referent() const;
    void setReferent(std::shared_ptr<KerML::Entities::Feature> value);
private:
    std::shared_ptr<KerML::Entities::Expression> targetArgument_ = {};
    std::shared_ptr<KerML::Entities::Expression> valueExpression_ = {};
    std::shared_ptr<KerML::Entities::Feature> referent_ = {};
};
}
