// Generated by sysml/tools/generate_abstract_syntax.py.
#pragma once
#include <sysml/model/Representation.h>
#include <sysml/model/Forward.h>
#include <sysml/model/KerMLTypes.h>
#include <sysml/actions/LoopActionUsage.h>

namespace SysMLv2::Entities {
class SYSML_EXPORT ForLoopActionUsage : public virtual LoopActionUsage, public virtual Representation {
public:
    ForLoopActionUsage();
    ~ForLoopActionUsage() override;
    std::string_view metaclassName() const noexcept override;
    std::vector<RepresentationIssue> validateRepresentation(bool includeDerived = false) const override;
    /// Derived snapshot; populated by a semantic evaluator or importer.
    std::shared_ptr<KerML::Entities::Expression> seqArgument() const;
    void setSeqArgument(std::shared_ptr<KerML::Entities::Expression> value);
    /// Derived snapshot; populated by a semantic evaluator or importer.
    std::shared_ptr<ReferenceUsage> loopVariable() const;
    void setLoopVariable(std::shared_ptr<ReferenceUsage> value);
private:
    std::shared_ptr<KerML::Entities::Expression> seqArgument_ = {};
    std::shared_ptr<ReferenceUsage> loopVariable_ = {};
};
}
