// Generated by sysml/tools/generate_abstract_syntax.py.
#pragma once
#include <sysml/model/Representation.h>
#include <sysml/model/Forward.h>
#include <sysml/model/KerMLTypes.h>
#include <sysml/actions/ActionUsage.h>

namespace SysMLv2::Entities {
class SYSML_EXPORT IfActionUsage : public virtual ActionUsage, public virtual Representation {
public:
    IfActionUsage();
    ~IfActionUsage() override;
    std::string_view metaclassName() const noexcept override;
    std::vector<RepresentationIssue> validateRepresentation(bool includeDerived = false) const override;
    /// Derived snapshot; populated by a semantic evaluator or importer.
    std::shared_ptr<ActionUsage> elseAction() const;
    void setElseAction(std::shared_ptr<ActionUsage> value);
    /// Derived snapshot; populated by a semantic evaluator or importer.
    std::shared_ptr<ActionUsage> thenAction() const;
    void setThenAction(std::shared_ptr<ActionUsage> value);
    /// Derived snapshot; populated by a semantic evaluator or importer.
    std::shared_ptr<KerML::Entities::Expression> ifArgument() const;
    void setIfArgument(std::shared_ptr<KerML::Entities::Expression> value);
private:
    std::shared_ptr<ActionUsage> elseAction_ = {};
    std::shared_ptr<ActionUsage> thenAction_ = {};
    std::shared_ptr<KerML::Entities::Expression> ifArgument_ = {};
};
}
