// Generated by sysml/tools/generate_abstract_syntax.py.
#pragma once
#include <sysml/model/Representation.h>
#include <sysml/model/Forward.h>
#include <sysml/model/KerMLTypes.h>
#include <sysml/actions/TriggerKind.h>

namespace SysMLv2::Entities {
class SYSML_EXPORT TriggerInvocationExpression : public virtual KerML::Entities::InvocationExpression, public virtual Representation {
public:
    TriggerInvocationExpression();
    ~TriggerInvocationExpression() override;
    std::string_view metaclassName() const noexcept override;
    std::vector<RepresentationIssue> validateRepresentation(bool includeDerived = false) const override;
    /// Stored metamodel property.
    TriggerKind kind() const;
    void setKind(TriggerKind value);
private:
    TriggerKind kind_ = {};
};
}
