// Generated by sysml/tools/generate_abstract_syntax.py.
#pragma once
#include <sysml/model/Representation.h>
#include <sysml/model/Forward.h>
#include <sysml/model/KerMLTypes.h>
#include <sysml/actions/LoopActionUsage.h>

namespace SysMLv2::Entities {
class SYSML_EXPORT WhileLoopActionUsage : public virtual LoopActionUsage, public virtual Representation {
public:
    WhileLoopActionUsage();
    ~WhileLoopActionUsage() override;
    std::string_view metaclassName() const noexcept override;
    std::vector<RepresentationIssue> validateRepresentation(bool includeDerived = false) const override;
    /// Derived snapshot; populated by a semantic evaluator or importer.
    std::shared_ptr<KerML::Entities::Expression> whileArgument() const;
    void setWhileArgument(std::shared_ptr<KerML::Entities::Expression> value);
    /// Derived snapshot; populated by a semantic evaluator or importer.
    std::shared_ptr<KerML::Entities::Expression> untilArgument() const;
    void setUntilArgument(std::shared_ptr<KerML::Entities::Expression> value);
private:
    std::shared_ptr<KerML::Entities::Expression> whileArgument_ = {};
    std::shared_ptr<KerML::Entities::Expression> untilArgument_ = {};
};
}
