// Generated by kerml/tools/generate_abstract_syntax.py.
#include <kerml/KerML.h>
#include <utility>
#include <stdexcept>
#include "../../model/RepresentationSupport.h"

namespace KerML::Entities {
std::vector<std::shared_ptr<Step>> Behavior::step() const {
    return detail::select<Step>(features());
}

std::vector<std::shared_ptr<Feature>> Behavior::parameter() const {
    return parameter_;
}

void Behavior::setParameter(std::vector<std::shared_ptr<Feature>> value) {
    detail::checkCollection(value, true, -1);
    parameter_ = std::move(value);
}

void Behavior::appendParameter(std::shared_ptr<Feature> value) {
    auto values = parameter(); values.push_back(std::move(value)); setParameter(std::move(values));
}

Behavior::Behavior() {
    _dType = "Behavior";
}

Behavior::~Behavior() = default;
}
