// Generated by kerml/tools/generate_abstract_syntax.py.
#include <kerml/KerML.h>
#include <utility>
#include <stdexcept>
#include "../../model/RepresentationSupport.h"

namespace KerML::Entities {
std::vector<std::shared_ptr<Behavior>> Step::behavior() const {
    return behavior_;
}

void Step::setBehavior(std::vector<std::shared_ptr<Behavior>> value) {
    detail::checkCollection(value, true, -1);
    behavior_ = std::move(value);
}

void Step::appendBehavior(std::shared_ptr<Behavior> value) {
    auto values = behavior(); values.push_back(std::move(value)); setBehavior(std::move(values));
}

std::vector<std::shared_ptr<Feature>> Step::parameter() const {
    return parameter_;
}

void Step::setParameter(std::vector<std::shared_ptr<Feature>> value) {
    detail::checkCollection(value, true, -1);
    parameter_ = std::move(value);
}

void Step::appendParameter(std::shared_ptr<Feature> value) {
    auto values = parameter(); values.push_back(std::move(value)); setParameter(std::move(values));
}

Step::Step() {
    _dType = "Step";
}

Step::~Step() = default;
}
