// Generated by sysml/tools/generate_abstract_syntax.py.
#include <sysml/ports/ConjugatedPortDefinition.h>
#include <sysml/ports/PortDefinition.h>
#include <sysml/ports/PortConjugation.h>
#include <algorithm>
#include <stdexcept>

namespace SysMLv2::Entities {

std::shared_ptr<PortDefinition> ConjugatedPortDefinition::originalPortDefinition() const {
    return originalPortDefinition_;
}

void ConjugatedPortDefinition::setOriginalPortDefinition(std::shared_ptr<PortDefinition> value) {
    originalPortDefinition_ = std::move(value);
}

std::shared_ptr<PortConjugation> ConjugatedPortDefinition::ownedPortConjugator() const {
    return ownedPortConjugator_;
}

void ConjugatedPortDefinition::setOwnedPortConjugator(std::shared_ptr<PortConjugation> value) {
    ownedPortConjugator_ = std::move(value);
}

ConjugatedPortDefinition::ConjugatedPortDefinition() {
    _dType = "ConjugatedPortDefinition";
}

ConjugatedPortDefinition::~ConjugatedPortDefinition() = default;

std::string_view ConjugatedPortDefinition::metaclassName() const noexcept {
    return "ConjugatedPortDefinition";
}

std::vector<RepresentationIssue> ConjugatedPortDefinition::validateRepresentation(bool includeDerived) const {
    std::vector<RepresentationIssue> issues; (void)includeDerived;
    if (includeDerived) if (!ConjugatedPortDefinition::originalPortDefinition()) issues.push_back({"ConjugatedPortDefinition.originalPortDefinition", "required reference is missing"});
    if (includeDerived) if (!ConjugatedPortDefinition::ownedPortConjugator()) issues.push_back({"ConjugatedPortDefinition.ownedPortConjugator", "required reference is missing"});
    return issues;
}

} // namespace SysMLv2::Entities
