// Generated by sysml/tools/generate_abstract_syntax.py.
#include <sysml/ports/ConjugatedPortTyping.h>
#include <sysml/ports/PortDefinition.h>
#include <sysml/ports/ConjugatedPortDefinition.h>
#include <algorithm>
#include <stdexcept>

namespace SysMLv2::Entities {

std::shared_ptr<PortDefinition> ConjugatedPortTyping::portDefinition() const {
    return portDefinition_;
}

void ConjugatedPortTyping::setPortDefinition(std::shared_ptr<PortDefinition> value) {
    portDefinition_ = std::move(value);
}

std::shared_ptr<ConjugatedPortDefinition> ConjugatedPortTyping::conjugatedPortDefinition() const {
    return conjugatedPortDefinition_;
}

void ConjugatedPortTyping::setConjugatedPortDefinition(std::shared_ptr<ConjugatedPortDefinition> value) {
    conjugatedPortDefinition_ = std::move(value);
}

ConjugatedPortTyping::ConjugatedPortTyping() {
    _dType = "ConjugatedPortTyping";
}

ConjugatedPortTyping::~ConjugatedPortTyping() = default;

std::string_view ConjugatedPortTyping::metaclassName() const noexcept {
    return "ConjugatedPortTyping";
}

std::vector<RepresentationIssue> ConjugatedPortTyping::validateRepresentation(bool includeDerived) const {
    std::vector<RepresentationIssue> issues; (void)includeDerived;
    if (includeDerived) if (!ConjugatedPortTyping::portDefinition()) issues.push_back({"ConjugatedPortTyping.portDefinition", "required reference is missing"});
    if (!ConjugatedPortTyping::conjugatedPortDefinition()) issues.push_back({"ConjugatedPortTyping.conjugatedPortDefinition", "required reference is missing"});
    return issues;
}

} // namespace SysMLv2::Entities
