// Generated by sysml/tools/generate_abstract_syntax.py.
#include <sysml/ports/PortConjugation.h>
#include <sysml/ports/PortDefinition.h>
#include <sysml/ports/ConjugatedPortDefinition.h>
#include <algorithm>
#include <stdexcept>

namespace SysMLv2::Entities {

std::shared_ptr<PortDefinition> PortConjugation::originalPortDefinition() const {
    return originalPortDefinition_;
}

void PortConjugation::setOriginalPortDefinition(std::shared_ptr<PortDefinition> value) {
    originalPortDefinition_ = std::move(value);
}

std::shared_ptr<ConjugatedPortDefinition> PortConjugation::conjugatedPortDefinition() const {
    return conjugatedPortDefinition_;
}

void PortConjugation::setConjugatedPortDefinition(std::shared_ptr<ConjugatedPortDefinition> value) {
    conjugatedPortDefinition_ = std::move(value);
}

PortConjugation::PortConjugation() {
    _dType = "PortConjugation";
}

PortConjugation::~PortConjugation() = default;

std::string_view PortConjugation::metaclassName() const noexcept {
    return "PortConjugation";
}

std::vector<RepresentationIssue> PortConjugation::validateRepresentation(bool includeDerived) const {
    std::vector<RepresentationIssue> issues; (void)includeDerived;
    if (!PortConjugation::originalPortDefinition()) issues.push_back({"PortConjugation.originalPortDefinition", "required reference is missing"});
    if (includeDerived) if (!PortConjugation::conjugatedPortDefinition()) issues.push_back({"PortConjugation.conjugatedPortDefinition", "required reference is missing"});
    return issues;
}

} // namespace SysMLv2::Entities
