// Generated by sysml/tools/generate_abstract_syntax.py.
#include <sysml/ports/PortDefinition.h>
#include <sysml/ports/ConjugatedPortDefinition.h>
#include <algorithm>
#include <stdexcept>

namespace SysMLv2::Entities {

std::shared_ptr<ConjugatedPortDefinition> PortDefinition::conjugatedPortDefinition() const {
    return conjugatedPortDefinition_;
}

void PortDefinition::setConjugatedPortDefinition(std::shared_ptr<ConjugatedPortDefinition> value) {
    conjugatedPortDefinition_ = std::move(value);
}

PortDefinition::PortDefinition() {
    _dType = "PortDefinition";
}

PortDefinition::~PortDefinition() = default;

std::string_view PortDefinition::metaclassName() const noexcept {
    return "PortDefinition";
}

std::vector<RepresentationIssue> PortDefinition::validateRepresentation(bool includeDerived) const {
    std::vector<RepresentationIssue> issues; (void)includeDerived;
    return issues;
}

} // namespace SysMLv2::Entities
