// Generated by sysml/tools/generate_abstract_syntax.py.
#include <sysml/ports/PortUsage.h>
#include <sysml/ports/PortDefinition.h>
#include <algorithm>
#include <stdexcept>

namespace SysMLv2::Entities {

std::vector<std::shared_ptr<PortDefinition>> PortUsage::portDefinition() const {
    return portDefinition_;
}

void PortUsage::setPortDefinition(std::vector<std::shared_ptr<PortDefinition>> value) {
    if (std::any_of(value.begin(), value.end(), [](const auto& item) { return !item; })) {
        throw std::invalid_argument("PortUsage.portDefinition: null entry");
    }
    for (std::size_t i = 0; i < value.size(); ++i) {
        if (std::find(value.begin(), value.begin() + i, value[i]) != value.begin() + i) {
            throw std::invalid_argument("PortUsage.portDefinition: duplicate entry");
        }
    }
    portDefinition_ = std::move(value);
}

void PortUsage::appendPortDefinition(std::shared_ptr<PortDefinition> value) {
    auto values = portDefinition();
    values.push_back(std::move(value));
    setPortDefinition(std::move(values));
}

PortUsage::PortUsage() {
    _dType = "PortUsage";
}

PortUsage::~PortUsage() = default;

std::string_view PortUsage::metaclassName() const noexcept {
    return "PortUsage";
}

std::vector<RepresentationIssue> PortUsage::validateRepresentation(bool includeDerived) const {
    std::vector<RepresentationIssue> issues; (void)includeDerived;
    { auto optional = OccurrenceUsage::portionKind(); if (optional) { auto value = *optional; if (!(value == PortionKind::timeslice || value == PortionKind::snapshot)) issues.push_back({"OccurrenceUsage.portionKind", "invalid enumeration value"}); } }
    return issues;
}

} // namespace SysMLv2::Entities
