// Generated by kerml/tools/generate_abstract_syntax.py.
#pragma once
#include <kerml/root/namespaces/OwningMembership.h>
#include <kerml/model/Forward.h>
#include <kerml/kerml_global.h>
#include <cstdint>
#include <memory>
#include <string>
#include <vector>

namespace KerML::Entities {
class KERML_EXPORT ElementFilterMembership : public virtual OwningMembership {
public:
    ElementFilterMembership();
    ~ElementFilterMembership() override;
    /// Computed from the underlying representation.
    std::shared_ptr<Expression> condition() const;
    void setCondition(std::shared_ptr<Expression> value);
private:
};
}
