// Generated by kerml/tools/generate_abstract_syntax.py.
#pragma once
#include <kerml/kernel/packages/Package.h>
#include <kerml/model/Forward.h>
#include <kerml/kerml_global.h>
#include <cstdint>
#include <memory>
#include <string>
#include <vector>

namespace KerML::Entities {
class KERML_EXPORT LibraryPackage : public virtual Package {
public:
    LibraryPackage();
    ~LibraryPackage() override;
    /// Stored metamodel property.
    bool isStandard() const;
    void setIsStandard(bool value);
private:
    bool isStandard_ = false;
};
}
