// Generated by kerml/tools/generate_abstract_syntax.py.
#pragma once
#include <kerml/root/namespaces/Namespace.h>
#include <kerml/model/Forward.h>
#include <kerml/kerml_global.h>
#include <cstdint>
#include <memory>
#include <string>
#include <vector>

namespace KerML::Entities {
class KERML_EXPORT Package : public virtual Namespace {
public:
    Package();
    ~Package() override;
    /// Computed from the underlying representation.
    std::vector<std::shared_ptr<Expression>> filterCondition() const;
private:
};
}
