// Generated by sysml/tools/generate_abstract_syntax.py.
#pragma once
#include <sysml/model/Representation.h>
#include <sysml/model/Forward.h>
#include <sysml/model/KerMLTypes.h>
#include <sysml/calculations/CalculationUsage.h>

namespace SysMLv2::Entities {
class SYSML_EXPORT CaseUsage : public virtual CalculationUsage, public virtual Representation {
public:
    CaseUsage();
    ~CaseUsage() override;
    std::string_view metaclassName() const noexcept override;
    std::vector<RepresentationIssue> validateRepresentation(bool includeDerived = false) const override;
    /// Derived snapshot; populated by a semantic evaluator or importer.
    std::shared_ptr<RequirementUsage> objectiveRequirement() const;
    void setObjectiveRequirement(std::shared_ptr<RequirementUsage> value);
    /// Derived snapshot; populated by a semantic evaluator or importer.
    std::shared_ptr<CaseDefinition> caseDefinition() const;
    void setCaseDefinition(std::shared_ptr<CaseDefinition> value);
    /// Derived snapshot; populated by a semantic evaluator or importer.
    std::shared_ptr<Usage> subjectParameter() const;
    void setSubjectParameter(std::shared_ptr<Usage> value);
    /// Derived snapshot; populated by a semantic evaluator or importer.
    std::vector<std::shared_ptr<PartUsage>> actorParameter() const;
    void setActorParameter(std::vector<std::shared_ptr<PartUsage>> value);
    void appendActorParameter(std::shared_ptr<PartUsage> value);
private:
    std::shared_ptr<RequirementUsage> objectiveRequirement_ = {};
    std::shared_ptr<CaseDefinition> caseDefinition_ = {};
    std::shared_ptr<Usage> subjectParameter_ = {};
    std::vector<std::shared_ptr<PartUsage>> actorParameter_ = {};
};
}
