// Generated by sysml/tools/generate_abstract_syntax.py.
#pragma once
#include <sysml/model/Representation.h>
#include <sysml/model/Forward.h>
#include <sysml/model/KerMLTypes.h>

namespace SysMLv2::Entities {
class SYSML_EXPORT ObjectiveMembership : public virtual KerML::Entities::FeatureMembership, public virtual Representation {
public:
    ObjectiveMembership();
    ~ObjectiveMembership() override;
    std::string_view metaclassName() const noexcept override;
    std::vector<RepresentationIssue> validateRepresentation(bool includeDerived = false) const override;
    /// Derived snapshot; populated by a semantic evaluator or importer.
    std::shared_ptr<RequirementUsage> ownedObjectiveRequirement() const;
    void setOwnedObjectiveRequirement(std::shared_ptr<RequirementUsage> value);
private:
    std::shared_ptr<RequirementUsage> ownedObjectiveRequirement_ = {};
};
}
