// Generated by kerml/tools/generate_abstract_syntax.py.
#pragma once
#include <kerml/kerml_global.h>
#include <string>
#include <string_view>
#include <vector>
namespace KerML::Entities {
class Element;
struct MetaclassDescriptor { std::string_view name; bool isAbstract; std::size_t declaredPropertyCount; };
struct RepresentationIssue { std::string property; std::string message; };
KERML_EXPORT const std::vector<MetaclassDescriptor>& metaclasses();
// Checks property multiplicities and uniqueness; does not evaluate OCL.
KERML_EXPORT std::vector<RepresentationIssue> validateRepresentation(Element& element, bool includeDerived = false);
}
