// Generated by kerml/tools/generate_abstract_syntax.py.
#pragma once
#include <kerml/kernel/functions/Expression.h>
#include <kerml/model/Forward.h>
#include <kerml/kerml_global.h>
#include <cstdint>
#include <memory>
#include <string>
#include <vector>

namespace KerML::Entities {
class KERML_EXPORT BooleanExpression : public virtual Expression {
public:
    BooleanExpression();
    ~BooleanExpression() override;
    /// Computed from the underlying representation.
    std::shared_ptr<Predicate> predicate() const;
    void setPredicate(std::shared_ptr<Predicate> value);
private:
};
}
