// Generated by kerml/tools/generate_abstract_syntax.py.
#pragma once
#include <kerml/kernel/behaviors/Step.h>
#include <kerml/model/Forward.h>
#include <kerml/kerml_global.h>
#include <cstdint>
#include <memory>
#include <string>
#include <vector>

namespace KerML::Entities {
class KERML_EXPORT Expression : public virtual Step {
public:
    Expression();
    ~Expression() override;
    /// Derived snapshot populated by an importer or semantic evaluator.
    std::shared_ptr<Function> function() const;
    void setFunction(std::shared_ptr<Function> value);
    /// Derived snapshot populated by an importer or semantic evaluator.
    std::shared_ptr<Feature> result() const;
    void setResult(std::shared_ptr<Feature> value);
    /// Derived snapshot populated by an importer or semantic evaluator.
    bool isModelLevelEvaluable() const;
    void setIsModelLevelEvaluable(bool value);
private:
    std::shared_ptr<Function> function_ = {};
    std::shared_ptr<Feature> result_ = {};
    bool isModelLevelEvaluable_ = {};
};
}
