// Generated by kerml/tools/generate_abstract_syntax.py.
#pragma once
#include <kerml/kernel/behaviors/Behavior.h>
#include <kerml/model/Forward.h>
#include <kerml/kerml_global.h>
#include <cstdint>
#include <memory>
#include <string>
#include <vector>

namespace KerML::Entities {
class KERML_EXPORT Function : public virtual Behavior {
public:
    Function();
    ~Function() override;
    /// Computed from the underlying representation.
    std::vector<std::shared_ptr<Expression>> expression() const;
    /// Derived snapshot populated by an importer or semantic evaluator.
    std::shared_ptr<Feature> result() const;
    void setResult(std::shared_ptr<Feature> value);
    /// Derived snapshot populated by an importer or semantic evaluator.
    bool isModelLevelEvaluable() const;
    void setIsModelLevelEvaluable(bool value);
private:
    std::shared_ptr<Feature> result_ = {};
    bool isModelLevelEvaluable_ = {};
};
}
