// Generated by kerml/tools/generate_abstract_syntax.py.
#pragma once
#include <kerml/kernel/functions/BooleanExpression.h>
#include <kerml/model/Forward.h>
#include <kerml/kerml_global.h>
#include <cstdint>
#include <memory>
#include <string>
#include <vector>

namespace KerML::Entities {
class KERML_EXPORT Invariant : public virtual BooleanExpression {
public:
    Invariant();
    ~Invariant() override;
    /// Stored metamodel property.
    bool isNegated() const;
    void setIsNegated(bool value);
private:
    bool isNegated_ = false;
};
}
