// Generated by kerml/tools/generate_abstract_syntax.py.
#pragma once
#include <kerml/core/features/FeatureMembership.h>
#include <kerml/model/Forward.h>
#include <kerml/kerml_global.h>
#include <cstdint>
#include <memory>
#include <string>
#include <vector>

namespace KerML::Entities {
class KERML_EXPORT ParameterMembership : public virtual FeatureMembership {
public:
    ParameterMembership();
    ~ParameterMembership() override;
    /// Computed from the underlying representation.
    std::shared_ptr<Feature> ownedMemberParameter() const;
    void setOwnedMemberParameter(std::shared_ptr<Feature> value);
private:
};
}
