// Generated by kerml/tools/generate_abstract_syntax.py.
#pragma once
#include <kerml/core/features/FeatureMembership.h>
#include <kerml/model/Forward.h>
#include <kerml/kerml_global.h>
#include <cstdint>
#include <memory>
#include <string>
#include <vector>

namespace KerML::Entities {
class KERML_EXPORT ResultExpressionMembership : public virtual FeatureMembership {
public:
    ResultExpressionMembership();
    ~ResultExpressionMembership() override;
    ResultExpressionMembership(std::shared_ptr<Expression> expression, std::shared_ptr<Type> owner);
    void setOwningType(std::shared_ptr<Type> owner);
    /// Computed from the underlying representation.
    std::shared_ptr<Expression> ownedResultExpression() const;
    void setOwnedResultExpression(std::shared_ptr<Expression> value);
private:
};
}
