// Generated by sysml/tools/generate_abstract_syntax.py.
#pragma once
#include <sysml/model/Representation.h>
#include <sysml/model/Forward.h>
#include <sysml/model/KerMLTypes.h>
#include <sysml/attributes/AttributeDefinition.h>

namespace SysMLv2::Entities {
class SYSML_EXPORT EnumerationDefinition : public virtual AttributeDefinition, public virtual Representation {
public:
    EnumerationDefinition();
    ~EnumerationDefinition() override;
    std::string_view metaclassName() const noexcept override;
    std::vector<RepresentationIssue> validateRepresentation(bool includeDerived = false) const override;
    /// Derived snapshot; populated by a semantic evaluator or importer.
    std::vector<std::shared_ptr<EnumerationUsage>> enumeratedValue() const;
    void setEnumeratedValue(std::vector<std::shared_ptr<EnumerationUsage>> value);
    void appendEnumeratedValue(std::shared_ptr<EnumerationUsage> value);
    /// Stored metamodel property.
    bool isVariation() const;
    void setIsVariation(bool value);
private:
    std::vector<std::shared_ptr<EnumerationUsage>> enumeratedValue_ = {};
    bool isVariation_ = true;
};
}
