// Generated by sysml/tools/generate_abstract_syntax.py.
#pragma once
#include <sysml/model/Representation.h>
#include <sysml/model/Forward.h>
#include <sysml/model/KerMLTypes.h>
#include <sysml/attributes/AttributeUsage.h>

namespace SysMLv2::Entities {
class SYSML_EXPORT EnumerationUsage : public virtual AttributeUsage, public virtual Representation {
public:
    EnumerationUsage();
    ~EnumerationUsage() override;
    std::string_view metaclassName() const noexcept override;
    std::vector<RepresentationIssue> validateRepresentation(bool includeDerived = false) const override;
    /// Derived snapshot; populated by a semantic evaluator or importer.
    std::shared_ptr<EnumerationDefinition> enumerationDefinition() const;
    void setEnumerationDefinition(std::shared_ptr<EnumerationDefinition> value);
private:
    std::shared_ptr<EnumerationDefinition> enumerationDefinition_ = {};
};
}
