// Generated by sysml/tools/generate_abstract_syntax.py.
#include <sysml/attributes/AttributeUsage.h>
#include <algorithm>
#include <stdexcept>

namespace SysMLv2::Entities {

std::vector<std::shared_ptr<KerML::Entities::DataType>> AttributeUsage::attributeDefinition() const {
    return attributeDefinition_;
}

void AttributeUsage::setAttributeDefinition(std::vector<std::shared_ptr<KerML::Entities::DataType>> value) {
    if (std::any_of(value.begin(), value.end(), [](const auto& item) { return !item; })) {
        throw std::invalid_argument("AttributeUsage.attributeDefinition: null entry");
    }
    for (std::size_t i = 0; i < value.size(); ++i) {
        if (std::find(value.begin(), value.begin() + i, value[i]) != value.begin() + i) {
            throw std::invalid_argument("AttributeUsage.attributeDefinition: duplicate entry");
        }
    }
    attributeDefinition_ = std::move(value);
}

void AttributeUsage::appendAttributeDefinition(std::shared_ptr<KerML::Entities::DataType> value) {
    auto values = attributeDefinition();
    values.push_back(std::move(value));
    setAttributeDefinition(std::move(values));
}

bool AttributeUsage::isReference() const {
    return isReference_;
}

void AttributeUsage::setIsReference(bool value) {
    isReference_ = std::move(value);
}

AttributeUsage::AttributeUsage() {
    _dType = "AttributeUsage";
}

AttributeUsage::~AttributeUsage() = default;

std::string_view AttributeUsage::metaclassName() const noexcept {
    return "AttributeUsage";
}

std::vector<RepresentationIssue> AttributeUsage::validateRepresentation(bool includeDerived) const {
    std::vector<RepresentationIssue> issues; (void)includeDerived;
    return issues;
}

} // namespace SysMLv2::Entities
