// Generated by sysml/tools/generate_abstract_syntax.py.
#include <sysml/attributes/AttributeDefinition.h>
#include <algorithm>
#include <stdexcept>

namespace SysMLv2::Entities {

AttributeDefinition::AttributeDefinition() {
    _dType = "AttributeDefinition";
}

AttributeDefinition::~AttributeDefinition() = default;

std::string_view AttributeDefinition::metaclassName() const noexcept {
    return "AttributeDefinition";
}

std::vector<RepresentationIssue> AttributeDefinition::validateRepresentation(bool includeDerived) const {
    std::vector<RepresentationIssue> issues; (void)includeDerived;
    return issues;
}

} // namespace SysMLv2::Entities
