// Generated by kerml/tools/generate_abstract_syntax.py.
#pragma once
#include <kerml/root/annotations/AnnotatingElement.h>
#include <kerml/core/features/Feature.h>
#include <kerml/model/Forward.h>
#include <kerml/kerml_global.h>
#include <cstdint>
#include <memory>
#include <string>
#include <vector>

namespace KerML::Entities {
class KERML_EXPORT MetadataFeature : public virtual AnnotatingElement, public virtual Feature {
public:
    MetadataFeature();
    ~MetadataFeature() override;
    /// Computed from the underlying representation.
    std::shared_ptr<Metaclass> metaclass() const;
private:
};
}
