// Generated by kerml/tools/generate_abstract_syntax.py.
#pragma once
#include <kerml/kernel/functions/Expression.h>
#include <kerml/model/Forward.h>
#include <kerml/kerml_global.h>
#include <cstdint>
#include <memory>
#include <string>
#include <vector>

namespace KerML::Entities {
class KERML_EXPORT InstantiationExpression : public virtual Expression {
public:
    InstantiationExpression();
    ~InstantiationExpression() override;
    /// Derived snapshot populated by an importer or semantic evaluator.
    std::vector<std::shared_ptr<Expression>> argument() const;
    void setArgument(std::vector<std::shared_ptr<Expression>> value);
    void appendArgument(std::shared_ptr<Expression> value);
    /// Derived snapshot populated by an importer or semantic evaluator.
    std::shared_ptr<Type> instantiatedType() const;
    void setInstantiatedType(std::shared_ptr<Type> value);
private:
    std::vector<std::shared_ptr<Expression>> argument_ = {};
    std::shared_ptr<Type> instantiatedType_ = {};
};
}
