// Generated by kerml/tools/generate_abstract_syntax.py.
#pragma once
#include <kerml/kernel/expressions/LiteralExpression.h>
#include <kerml/model/Forward.h>
#include <kerml/kerml_global.h>
#include <cstdint>
#include <memory>
#include <string>
#include <vector>

namespace KerML::Entities {
class KERML_EXPORT LiteralRational : public virtual LiteralExpression {
public:
    LiteralRational();
    ~LiteralRational() override;
    /// Stored metamodel property.
    double value() const;
    void setValue(double value);
private:
    double value_ = {};
};
}
