// Generated by kerml/tools/generate_abstract_syntax.py.
#pragma once
#include <kerml/kernel/expressions/LiteralExpression.h>
#include <kerml/model/Forward.h>
#include <kerml/kerml_global.h>
#include <cstdint>
#include <memory>
#include <string>
#include <vector>

namespace KerML::Entities {
class KERML_EXPORT LiteralBoolean : public virtual LiteralExpression {
public:
    LiteralBoolean();
    ~LiteralBoolean() override;
    /// Stored metamodel property.
    bool value() const;
    void setValue(bool value);
private:
    bool value_ = {};
};
}
