// Generated by kerml/tools/generate_abstract_syntax.py.
#pragma once
#include <kerml/kernel/expressions/LiteralExpression.h>
#include <kerml/model/Forward.h>
#include <kerml/kerml_global.h>
#include <cstdint>
#include <memory>
#include <string>
#include <vector>

namespace KerML::Entities {
class KERML_EXPORT LiteralInteger : public virtual LiteralExpression {
public:
    LiteralInteger();
    ~LiteralInteger() override;
    /// Stored metamodel property.
    std::int64_t value() const;
    void setValue(std::int64_t value);
private:
    std::int64_t value_ = {};
};
}
