// Generated by kerml/tools/generate_abstract_syntax.py.
#pragma once
#include <kerml/kernel/expressions/LiteralExpression.h>
#include <kerml/model/Forward.h>
#include <kerml/kerml_global.h>
#include <cstdint>
#include <memory>
#include <string>
#include <vector>

namespace KerML::Entities {
class KERML_EXPORT LiteralString : public virtual LiteralExpression {
public:
    LiteralString();
    ~LiteralString() override;
    /// Stored metamodel property.
    std::string value() const;
    void setValue(std::string value);
private:
    std::string value_ = {};
};
}
