// Generated by kerml/tools/generate_abstract_syntax.py.
#pragma once
#include <kerml/kernel/functions/Expression.h>
#include <kerml/model/Forward.h>
#include <kerml/kerml_global.h>
#include <cstdint>
#include <memory>
#include <string>
#include <vector>

namespace KerML::Entities {
class KERML_EXPORT MetadataAccessExpression : public virtual Expression {
public:
    MetadataAccessExpression();
    ~MetadataAccessExpression() override;
    /// Derived snapshot populated by an importer or semantic evaluator.
    std::shared_ptr<Element> referencedElement() const;
    void setReferencedElement(std::shared_ptr<Element> value);
private:
    std::shared_ptr<Element> referencedElement_ = {};
};
}
