// Generated by kerml/tools/generate_abstract_syntax.py.
#pragma once
#include <kerml/kernel/expressions/InvocationExpression.h>
#include <kerml/model/Forward.h>
#include <kerml/kerml_global.h>
#include <cstdint>
#include <memory>
#include <string>
#include <vector>

namespace KerML::Entities {
class KERML_EXPORT OperatorExpression : public virtual InvocationExpression {
public:
    OperatorExpression();
    ~OperatorExpression() override;
    /// Stored metamodel property.
    const std::string& operatorName() const;
    virtual void setOperatorName(const std::string& value);
private:
    std::string operatorName_ = {};
};
}
