// Generated by kerml/tools/generate_abstract_syntax.py.
#pragma once
#include <kerml/kernel/expressions/OperatorExpression.h>
#include <kerml/model/Forward.h>
#include <kerml/kerml_global.h>
#include <cstdint>
#include <memory>
#include <string>
#include <vector>

namespace KerML::Entities {
class KERML_EXPORT SelectExpression : public virtual OperatorExpression {
public:
    SelectExpression();
    ~SelectExpression() override;
    void setOperatorName(const std::string& name) override;
private:
};
}
