// Generated by kerml/tools/generate_abstract_syntax.py.
#pragma once
#include <algorithm>
#include <memory>
#include <stdexcept>
#include <vector>
namespace KerML::Entities::detail {
template<class T, class U> std::vector<std::shared_ptr<T>> select(const std::vector<std::shared_ptr<U>>& values) {
    std::vector<std::shared_ptr<T>> result;
    for (const auto& value : values) if (auto typed = std::dynamic_pointer_cast<T>(value)) result.push_back(typed);
    return result;
}
template<class T> void checkCollection(const std::vector<std::shared_ptr<T>>& values, bool unique, int upper) {
    if (upper >= 0 && values.size() > static_cast<std::size_t>(upper)) throw std::invalid_argument("Upper multiplicity exceeded");
    for (std::size_t i = 0; i < values.size(); ++i) {
        if (!values[i]) throw std::invalid_argument("Null collection entry");
        if (unique && std::find(values.begin(), values.begin() + i, values[i]) != values.begin() + i) throw std::invalid_argument("Duplicate collection entry");
    }
}
}
