// Generated by kerml/tools/generate_abstract_syntax.py.
#include <kerml/KerML.h>
#include <algorithm>
#include <optional>

namespace KerML::Entities {
const std::vector<MetaclassDescriptor>& metaclasses() {
    static const std::vector<MetaclassDescriptor> result = {
        {"Behavior", false, 2},
        {"ParameterMembership", false, 1},
        {"Step", false, 2},
        {"FeatureChainExpression", false, 2},
        {"LiteralString", false, 1},
        {"LiteralInteger", false, 1},
        {"InstantiationExpression", true, 2},
        {"MetadataAccessExpression", false, 1},
        {"InvocationExpression", false, 0},
        {"LiteralExpression", false, 0},
        {"OperatorExpression", false, 1},
        {"ConstructorExpression", false, 0},
        {"LiteralRational", false, 1},
        {"LiteralBoolean", false, 1},
        {"LiteralInfinity", false, 0},
        {"NullExpression", false, 0},
        {"SelectExpression", false, 1},
        {"FeatureReferenceExpression", false, 1},
        {"CollectExpression", false, 1},
        {"IndexExpression", false, 1},
        {"ReturnParameterMembership", false, 0},
        {"Predicate", false, 0},
        {"Expression", false, 3},
        {"ResultExpressionMembership", false, 1},
        {"BooleanExpression", false, 1},
        {"Invariant", false, 1},
        {"Function", false, 3},
        {"Flow", false, 6},
        {"SuccessionFlow", false, 0},
        {"PayloadFeature", false, 0},
        {"FlowEnd", false, 0},
        {"Interaction", false, 0},
        {"FeatureValue", false, 4},
        {"ElementFilterMembership", false, 1},
        {"LibraryPackage", false, 1},
        {"Package", false, 1},
        {"MultiplicityRange", false, 3},
        {"Succession", false, 0},
        {"Connector", false, 6},
        {"BindingConnector", false, 0},
        {"Class", false, 0},
        {"Metaclass", false, 0},
        {"MetadataFeature", false, 1},
        {"Structure", false, 0},
        {"Association", false, 4},
        {"AssociationStructure", false, 0},
        {"DataType", false, 0},
        {"Disjoining", false, 3},
        {"Type", false, 24},
        {"Multiplicity", false, 0},
        {"Differencing", false, 2},
        {"Intersecting", false, 2},
        {"Unioning", false, 2},
        {"FeatureMembership", false, 2},
        {"Conjugation", false, 3},
        {"Specialization", false, 3},
        {"Subclassification", false, 3},
        {"Classifier", false, 1},
        {"FeatureInverting", false, 3},
        {"FeatureChaining", false, 2},
        {"Redefinition", false, 2},
        {"ReferenceSubsetting", false, 2},
        {"Feature", false, 25},
        {"TypeFeaturing", false, 3},
        {"Subsetting", false, 3},
        {"FeatureTyping", false, 3},
        {"EndFeatureMembership", false, 1},
        {"CrossSubsetting", false, 2},
        {"Dependency", false, 2},
        {"TextualRepresentation", false, 3},
        {"Documentation", false, 1},
        {"Comment", false, 2},
        {"Annotation", false, 5},
        {"AnnotatingElement", false, 4},
        {"NamespaceImport", false, 1},
        {"MembershipImport", false, 1},
        {"OwningMembership", false, 4},
        {"Import", true, 5},
        {"Namespace", false, 6},
        {"Membership", false, 6},
        {"Relationship", true, 6},
        {"Element", true, 18},
    }; return result;
}
namespace {
//template<class T> bool present(const std::shared_ptr<T>& value) { return bool(value); }
//template<class T> bool present(const std::optional<T>& value) { return value && present(*value); }
//template<class T> bool present(const T&) { return true; }
//template<class T> void check(std::vector<RepresentationIssue>& issues, const T& value, const char* path, int lower, int, bool) {
//    if (lower > 0 && !present(value)) issues.push_back({path, "Required property is missing"});
//}
//template<class T> void check(std::vector<RepresentationIssue>& issues, const std::vector<T>& value, const char* path, int lower, int upper, bool unique) {
//    if (value.size() < static_cast<std::size_t>(lower) || (upper >= 0 && value.size() > static_cast<std::size_t>(upper))) issues.push_back({path, "Invalid multiplicity"});
//    for (std::size_t i=0; i<value.size(); ++i) {
//        if (!present(value[i])) issues.push_back({path, "Null entry"});
//        if (unique && std::find(value.begin(), value.begin()+i, value[i]) != value.begin()+i) issues.push_back({path, "Duplicate entry"});
//    }
//}
}
//std::vector<RepresentationIssue> validateRepresentation(Element& element, bool includeDerived) {
//    std::vector<RepresentationIssue> issues;
//    if (auto* value = dynamic_cast<Behavior*>(&element)) {
//        if (includeDerived) check(issues, value->Behavior::step(), "Behavior.step", 0, -1, true);
//        if (includeDerived) check(issues, value->Behavior::parameter(), "Behavior.parameter", 0, -1, true);
//    }
//    if (auto* value = dynamic_cast<ParameterMembership*>(&element)) {
//        if (includeDerived) check(issues, value->ParameterMembership::ownedMemberParameter(), "ParameterMembership.ownedMemberParameter", 1, 1, true);
//    }
//    if (auto* value = dynamic_cast<Step*>(&element)) {
//        if (includeDerived) check(issues, value->Step::behavior(), "Step.behavior", 0, -1, true);
//        if (includeDerived) check(issues, value->Step::parameter(), "Step.parameter", 0, -1, true);
//    }
//    if (auto* value = dynamic_cast<FeatureChainExpression*>(&element)) {
//        check(issues, value->FeatureChainExpression::operatorName(), "FeatureChainExpression.operator", 1, 1, true);
//        if (includeDerived) check(issues, value->FeatureChainExpression::targetFeature(), "FeatureChainExpression.targetFeature", 1, 1, true);
//    }
//    if (auto* value = dynamic_cast<LiteralString*>(&element)) {
//        check(issues, value->LiteralString::value(), "LiteralString.value", 1, 1, true);
//    }
//    if (auto* value = dynamic_cast<LiteralInteger*>(&element)) {
//        check(issues, value->LiteralInteger::value(), "LiteralInteger.value", 1, 1, true);
//    }
//    if (auto* value = dynamic_cast<InstantiationExpression*>(&element)) {
//        if (includeDerived) check(issues, value->InstantiationExpression::argument(), "InstantiationExpression.argument", 0, -1, true);
//        if (includeDerived) check(issues, value->InstantiationExpression::instantiatedType(), "InstantiationExpression.instantiatedType", 1, 1, true);
//    }
//    if (auto* value = dynamic_cast<MetadataAccessExpression*>(&element)) {
//        if (includeDerived) check(issues, value->MetadataAccessExpression::referencedElement(), "MetadataAccessExpression.referencedElement", 1, 1, true);
//    }
//    if (auto* value = dynamic_cast<OperatorExpression*>(&element)) {
//        check(issues, value->OperatorExpression::operatorName(), "OperatorExpression.operator", 1, 1, true);
//    }
//    if (auto* value = dynamic_cast<LiteralRational*>(&element)) {
//        check(issues, value->LiteralRational::value(), "LiteralRational.value", 1, 1, true);
//    }
//    if (auto* value = dynamic_cast<LiteralBoolean*>(&element)) {
//        check(issues, value->LiteralBoolean::value(), "LiteralBoolean.value", 1, 1, true);
//    }
//    if (auto* value = dynamic_cast<SelectExpression*>(&element)) {
//        check(issues, value->SelectExpression::operatorName(), "SelectExpression.operator", 1, 1, true);
//    }
//    if (auto* value = dynamic_cast<FeatureReferenceExpression*>(&element)) {
//        if (includeDerived) check(issues, value->FeatureReferenceExpression::referent(), "FeatureReferenceExpression.referent", 1, 1, true);
//    }
//    if (auto* value = dynamic_cast<CollectExpression*>(&element)) {
//        check(issues, value->CollectExpression::operatorName(), "CollectExpression.operator", 1, 1, true);
//    }
//    if (auto* value = dynamic_cast<IndexExpression*>(&element)) {
//        check(issues, value->IndexExpression::operatorName(), "IndexExpression.operator", 1, 1, true);
//    }
//    if (auto* value = dynamic_cast<Expression*>(&element)) {
//        if (includeDerived) check(issues, value->Expression::function(), "Expression.function", 0, 1, true);
//        if (includeDerived) check(issues, value->Expression::result(), "Expression.result", 1, 1, true);
//        if (includeDerived) check(issues, value->Expression::isModelLevelEvaluable(), "Expression.isModelLevelEvaluable", 1, 1, true);
//    }
//    if (auto* value = dynamic_cast<ResultExpressionMembership*>(&element)) {
//        if (includeDerived) check(issues, value->ResultExpressionMembership::ownedResultExpression(), "ResultExpressionMembership.ownedResultExpression", 1, 1, true);
//    }
//    if (auto* value = dynamic_cast<BooleanExpression*>(&element)) {
//        if (includeDerived) check(issues, value->BooleanExpression::predicate(), "BooleanExpression.predicate", 0, 1, true);
//    }
//    if (auto* value = dynamic_cast<Invariant*>(&element)) {
//        check(issues, value->Invariant::isNegated(), "Invariant.isNegated", 1, 1, true);
//    }
//    if (auto* value = dynamic_cast<Function*>(&element)) {
//        if (includeDerived) check(issues, value->Function::expression(), "Function.expression", 0, -1, true);
//        if (includeDerived) check(issues, value->Function::result(), "Function.result", 1, 1, true);
//        if (includeDerived) check(issues, value->Function::isModelLevelEvaluable(), "Function.isModelLevelEvaluable", 1, 1, true);
//    }
//    if (auto* value = dynamic_cast<Flow*>(&element)) {
//        if (includeDerived) check(issues, value->Flow::payloadType(), "Flow.payloadType", 0, -1, false);
//        if (includeDerived) check(issues, value->Flow::targetInputFeature(), "Flow.targetInputFeature", 0, 1, false);
//        if (includeDerived) check(issues, value->Flow::sourceOutputFeature(), "Flow.sourceOutputFeature", 0, 1, false);
//        if (includeDerived) check(issues, value->Flow::flowEnd(), "Flow.flowEnd", 0, 2, true);
//        if (includeDerived) check(issues, value->Flow::payloadFeature(), "Flow.payloadFeature", 0, 1, true);
//        if (includeDerived) check(issues, value->Flow::interaction(), "Flow.interaction", 0, -1, true);
//    }
//    if (auto* value = dynamic_cast<FeatureValue*>(&element)) {
//        if (includeDerived) check(issues, value->FeatureValue::featureWithValue(), "FeatureValue.featureWithValue", 1, 1, true);
//        if (includeDerived) check(issues, value->FeatureValue::value(), "FeatureValue.value", 1, 1, true);
//        check(issues, value->FeatureValue::isInitial(), "FeatureValue.isInitial", 1, 1, true);
//        check(issues, value->FeatureValue::isDefault(), "FeatureValue.isDefault", 1, 1, true);
//    }
//    if (auto* value = dynamic_cast<ElementFilterMembership*>(&element)) {
//        if (includeDerived) check(issues, value->ElementFilterMembership::condition(), "ElementFilterMembership.condition", 1, 1, true);
//    }
//    if (auto* value = dynamic_cast<LibraryPackage*>(&element)) {
//        check(issues, value->LibraryPackage::isStandard(), "LibraryPackage.isStandard", 1, 1, true);
//    }
//    if (auto* value = dynamic_cast<Package*>(&element)) {
//        if (includeDerived) check(issues, value->Package::filterCondition(), "Package.filterCondition", 0, -1, true);
//    }
//    if (auto* value = dynamic_cast<MultiplicityRange*>(&element)) {
//        if (includeDerived) check(issues, value->MultiplicityRange::lowerBound(), "MultiplicityRange.lowerBound", 0, 1, true);
//        if (includeDerived) check(issues, value->MultiplicityRange::upperBound(), "MultiplicityRange.upperBound", 1, 1, true);
//        if (includeDerived) check(issues, value->MultiplicityRange::bound(), "MultiplicityRange.bound", 1, 2, true);
//    }
//    if (auto* value = dynamic_cast<Connector*>(&element)) {
//        if (includeDerived) check(issues, value->Connector::relatedFeature(), "Connector.relatedFeature", 0, -1, false);
//        if (includeDerived) check(issues, value->Connector::association(), "Connector.association", 0, -1, true);
//        if (includeDerived) check(issues, value->Connector::connectorEnd(), "Connector.connectorEnd", 0, -1, true);
//        if (includeDerived) check(issues, value->Connector::sourceFeature(), "Connector.sourceFeature", 0, 1, true);
//        if (includeDerived) check(issues, value->Connector::targetFeature(), "Connector.targetFeature", 0, -1, true);
//        if (includeDerived) check(issues, value->Connector::defaultFeaturingType(), "Connector.defaultFeaturingType", 0, 1, true);
//    }
//    if (auto* value = dynamic_cast<MetadataFeature*>(&element)) {
//        if (includeDerived) check(issues, value->MetadataFeature::metaclass(), "MetadataFeature.metaclass", 0, 1, true);
//    }
//    if (auto* value = dynamic_cast<Association*>(&element)) {
//        if (includeDerived) check(issues, value->Association::relatedType(), "Association.relatedType", 0, -1, false);
//        if (includeDerived) check(issues, value->Association::sourceType(), "Association.sourceType", 0, 1, true);
//        if (includeDerived) check(issues, value->Association::targetType(), "Association.targetType", 0, -1, true);
//        if (includeDerived) check(issues, value->Association::associationEnd(), "Association.associationEnd", 0, -1, true);
//    }
//    if (auto* value = dynamic_cast<Disjoining*>(&element)) {
//        check(issues, value->Disjoining::typeDisjoined(), "Disjoining.typeDisjoined", 1, 1, true);
//        check(issues, value->Disjoining::disjoiningType(), "Disjoining.disjoiningType", 1, 1, true);
//        if (includeDerived) check(issues, value->Disjoining::owningType(), "Disjoining.owningType", 0, 1, true);
//    }
//    if (auto* value = dynamic_cast<Type*>(&element)) {
//        if (includeDerived) check(issues, value->Type::ownedSpecialization(), "Type.ownedSpecialization", 0, -1, true);
//        if (includeDerived) check(issues, value->Type::ownedFeatureMembership(), "Type.ownedFeatureMembership", 0, -1, true);
//        if (includeDerived) check(issues, value->Type::features(), "Type.feature", 0, -1, true);
//        if (includeDerived) check(issues, value->Type::ownedFeature(), "Type.ownedFeature", 0, -1, true);
//        if (includeDerived) check(issues, value->Type::input(), "Type.input", 0, -1, true);
//        if (includeDerived) check(issues, value->Type::output(), "Type.output", 0, -1, true);
//        check(issues, value->Type::isAbstract(), "Type.isAbstract", 1, 1, true);
//        if (includeDerived) check(issues, value->Type::inheritedMemberships(), "Type.inheritedMembership", 0, -1, true);
//        if (includeDerived) check(issues, value->Type::endFeature(), "Type.endFeature", 0, -1, true);
//        if (includeDerived) check(issues, value->Type::ownedEndFeature(), "Type.ownedEndFeature", 0, -1, true);
//        check(issues, value->Type::isSufficient(), "Type.isSufficient", 1, 1, true);
//        if (includeDerived) check(issues, value->Type::conjugation(), "Type.ownedConjugator", 0, 1, true);
//        if (includeDerived) check(issues, value->Type::isConjugated(), "Type.isConjugated", 1, 1, true);
//        if (includeDerived) check(issues, value->Type::inheritedFeature(), "Type.inheritedFeature", 0, -1, true);
//        if (includeDerived) check(issues, value->Type::multiplicity(), "Type.multiplicity", 0, 1, true);
//        if (includeDerived) check(issues, value->Type::unioningType(), "Type.unioningType", 0, -1, true);
//        if (includeDerived) check(issues, value->Type::ownedIntersecting(), "Type.ownedIntersecting", 0, -1, true);
//        if (includeDerived) check(issues, value->Type::intersectingType(), "Type.intersectingType", 0, -1, true);
//        if (includeDerived) check(issues, value->Type::ownedUnioning(), "Type.ownedUnioning", 0, -1, true);
//        if (includeDerived) check(issues, value->Type::ownedDisjoining(), "Type.ownedDisjoining", 0, -1, true);
//        if (includeDerived) check(issues, value->Type::featureMemberships(), "Type.featureMembership", 0, -1, true);
//        if (includeDerived) check(issues, value->Type::differencingType(), "Type.differencingType", 0, -1, true);
//        if (includeDerived) check(issues, value->Type::ownedDifferencing(), "Type.ownedDifferencing", 0, -1, true);
//        if (includeDerived) check(issues, value->Type::directedFeature(), "Type.directedFeature", 0, -1, true);
//    }
//    if (auto* value = dynamic_cast<Differencing*>(&element)) {
//        if (includeDerived) check(issues, value->Differencing::typeDifferenced(), "Differencing.typeDifferenced", 1, 1, true);
//        check(issues, value->Differencing::differencingType(), "Differencing.differencingType", 1, 1, true);
//    }
//    if (auto* value = dynamic_cast<Intersecting*>(&element)) {
//        if (includeDerived) check(issues, value->Intersecting::typeIntersecting(), "Intersecting.typeIntersected", 1, 1, true);
//        check(issues, value->Intersecting::intersectingType(), "Intersecting.intersectingType", 1, 1, true);
//    }
//    if (auto* value = dynamic_cast<Unioning*>(&element)) {
//        if (includeDerived) check(issues, value->Unioning::typeUnioned(), "Unioning.typeUnioned", 1, 1, true);
//        check(issues, value->Unioning::unioningType(), "Unioning.unioningType", 1, 1, true);
//    }
//    if (auto* value = dynamic_cast<FeatureMembership*>(&element)) {
//        if (includeDerived) check(issues, value->FeatureMembership::owningType(), "FeatureMembership.owningType", 1, 1, true);
//        if (includeDerived) check(issues, value->FeatureMembership::ownedMemberFeature(), "FeatureMembership.ownedMemberFeature", 1, 1, true);
//    }
//    if (auto* value = dynamic_cast<Conjugation*>(&element)) {
//        check(issues, value->Conjugation::originalType(), "Conjugation.originalType", 1, 1, true);
//        check(issues, value->Conjugation::conjungatedType(), "Conjugation.conjugatedType", 1, 1, true);
//        if (includeDerived) check(issues, value->Conjugation::owningType(), "Conjugation.owningType", 0, 1, true);
//    }
//    if (auto* value = dynamic_cast<Specialization*>(&element)) {
//        if (includeDerived) check(issues, value->Specialization::owningType(), "Specialization.owningType", 0, 1, true);
//        check(issues, value->Specialization::general(), "Specialization.general", 1, 1, true);
//        check(issues, value->Specialization::specific(), "Specialization.specific", 1, 1, true);
//    }
//    if (auto* value = dynamic_cast<Subclassification*>(&element)) {
//        check(issues, value->Subclassification::superclassifier(), "Subclassification.superclassifier", 1, 1, true);
//        check(issues, value->Subclassification::subclassifier(), "Subclassification.subclassifier", 1, 1, true);
//        if (includeDerived) check(issues, value->Subclassification::owningClassifier(), "Subclassification.owningClassifier", 0, 1, true);
//    }
//    if (auto* value = dynamic_cast<Classifier*>(&element)) {
//        if (includeDerived) check(issues, value->Classifier::ownedSubclassification(), "Classifier.ownedSubclassification", 0, -1, true);
//    }
//    if (auto* value = dynamic_cast<FeatureInverting*>(&element)) {
//        check(issues, value->FeatureInverting::featureInverted(), "FeatureInverting.featureInverted", 1, 1, true);
//        check(issues, value->FeatureInverting::invertingFeature(), "FeatureInverting.invertingFeature", 1, 1, true);
//        if (includeDerived) check(issues, value->FeatureInverting::owningFeature(), "FeatureInverting.owningFeature", 0, 1, true);
//    }
//    if (auto* value = dynamic_cast<FeatureChaining*>(&element)) {
//        check(issues, value->FeatureChaining::chainingFeature(), "FeatureChaining.chainingFeature", 1, 1, true);
//        if (includeDerived) check(issues, value->FeatureChaining::featureChained(), "FeatureChaining.featureChained", 1, 1, true);
//    }
//    if (auto* value = dynamic_cast<Redefinition*>(&element)) {
//        check(issues, value->Redefinition::redefiningFeature(), "Redefinition.redefiningFeature", 1, 1, true);
//        check(issues, value->Redefinition::redefinedFeature(), "Redefinition.redefinedFeature", 1, 1, true);
//    }
//    if (auto* value = dynamic_cast<ReferenceSubsetting*>(&element)) {
//        check(issues, value->ReferenceSubsetting::referencedFeature(), "ReferenceSubsetting.referencedFeature", 1, 1, true);
//        if (includeDerived) check(issues, value->ReferenceSubsetting::referencingFeature(), "ReferenceSubsetting.referencingFeature", 1, 1, true);
//    }
//    if (auto* value = dynamic_cast<Feature*>(&element)) {
//        if (includeDerived) check(issues, value->Feature::owningType(), "Feature.owningType", 0, 1, true);
//        check(issues, value->Feature::isUnique(), "Feature.isUnique", 1, 1, true);
//        check(issues, value->Feature::isOrdered(), "Feature.isOrdered", 1, 1, true);
//        if (includeDerived) check(issues, value->Feature::type(), "Feature.type", 0, -1, true);
//        if (includeDerived) check(issues, value->Feature::ownedRedefinition(), "Feature.ownedRedefinition", 0, -1, true);
//        if (includeDerived) check(issues, value->Feature::ownedSubsetting(), "Feature.ownedSubsetting", 0, -1, true);
//        if (includeDerived) check(issues, value->Feature::owningFeatureMembership(), "Feature.owningFeatureMembership", 0, 1, true);
//        check(issues, value->Feature::isComposite(), "Feature.isComposite", 1, 1, true);
//        check(issues, value->Feature::isEnd(), "Feature.isEnd", 1, 1, true);
//        if (includeDerived) check(issues, value->Feature::endOwningType(), "Feature.endOwningType", 0, 1, true);
//        if (includeDerived) check(issues, value->Feature::ownedTyping(), "Feature.ownedTyping", 0, -1, true);
//        if (includeDerived) check(issues, value->Feature::featuringType(), "Feature.featuringType", 0, -1, true);
//        if (includeDerived) check(issues, value->Feature::ownedTypeFeaturing(), "Feature.ownedTypeFeaturing", 0, -1, true);
//        check(issues, value->Feature::isDerived(), "Feature.isDerived", 1, 1, true);
//        if (includeDerived) check(issues, value->Feature::chainingFeature(), "Feature.chainingFeature", 0, -1, false);
//        if (includeDerived) check(issues, value->Feature::ownedFeatureInverting(), "Feature.ownedFeatureInverting", 0, -1, true);
//        if (includeDerived) check(issues, value->Feature::ownedFeatureChaining(), "Feature.ownedFeatureChaining", 0, -1, true);
//        check(issues, value->Feature::isPortion(), "Feature.isPortion", 1, 1, true);
//        check(issues, value->Feature::isVariable(), "Feature.isVariable", 1, 1, true);
//        check(issues, value->Feature::isConstant(), "Feature.isConstant", 1, 1, true);
//        if (includeDerived) check(issues, value->Feature::ownedReferenceSubsetting(), "Feature.ownedReferenceSubsetting", 0, 1, true);
//        if (includeDerived) check(issues, value->Feature::featureTarget(), "Feature.featureTarget", 1, 1, true);
//        if (includeDerived) check(issues, value->Feature::crossFeature(), "Feature.crossFeature", 0, 1, true);
//        check(issues, value->Feature::direction(), "Feature.direction", 0, 1, true);
//        if (includeDerived) check(issues, value->Feature::ownedCrossSubsetting(), "Feature.ownedCrossSubsetting", 0, 1, true);
//    }
//    if (auto* value = dynamic_cast<TypeFeaturing*>(&element)) {
//        check(issues, value->TypeFeaturing::featureOfType(), "TypeFeaturing.featureOfType", 1, 1, true);
//        check(issues, value->TypeFeaturing::featuringType(), "TypeFeaturing.featuringType", 1, 1, true);
//        if (includeDerived) check(issues, value->TypeFeaturing::owningFeatureOfType(), "TypeFeaturing.owningFeatureOfType", 0, 1, true);
//    }
//    if (auto* value = dynamic_cast<Subsetting*>(&element)) {
//        check(issues, value->Subsetting::subsettedFeature(), "Subsetting.subsettedFeature", 1, 1, true);
//        check(issues, value->Subsetting::subsettingFeature(), "Subsetting.subsettingFeature", 1, 1, true);
//        if (includeDerived) check(issues, value->Subsetting::owningFeature(), "Subsetting.owningFeature", 0, 1, true);
//    }
//    if (auto* value = dynamic_cast<FeatureTyping*>(&element)) {
//        check(issues, value->FeatureTyping::typedFeature(), "FeatureTyping.typedFeature", 1, 1, true);
//        check(issues, value->FeatureTyping::type(), "FeatureTyping.type", 1, 1, true);
//        if (includeDerived) check(issues, value->FeatureTyping::owningFeature(), "FeatureTyping.owningFeature", 0, 1, true);
//    }
//    if (auto* value = dynamic_cast<EndFeatureMembership*>(&element)) {
//        if (includeDerived) check(issues, value->EndFeatureMembership::ownedMemberFeature(), "EndFeatureMembership.ownedMemberFeature", 1, 1, true);
//    }
//    if (auto* value = dynamic_cast<CrossSubsetting*>(&element)) {
//        check(issues, value->CrossSubsetting::crossedFeature(), "CrossSubsetting.crossedFeature", 1, 1, true);
//        if (includeDerived) check(issues, value->CrossSubsetting::crossingFeature(), "CrossSubsetting.crossingFeature", 1, 1, true);
//    }
//    if (auto* value = dynamic_cast<Dependency*>(&element)) {
//        check(issues, value->Dependency::client(), "Dependency.client", 1, -1, true);
//        check(issues, value->Dependency::supplier(), "Dependency.supplier", 1, -1, true);
//    }
//    if (auto* value = dynamic_cast<TextualRepresentation*>(&element)) {
//        check(issues, value->TextualRepresentation::language(), "TextualRepresentation.language", 1, 1, true);
//        if (includeDerived) check(issues, value->TextualRepresentation::representedElement(), "TextualRepresentation.representedElement", 1, 1, true);
//        check(issues, value->TextualRepresentation::body(), "TextualRepresentation.body", 1, 1, true);
//    }
//    if (auto* value = dynamic_cast<Documentation*>(&element)) {
//        if (includeDerived) check(issues, value->Documentation::documentedElement(), "Documentation.documentedElement", 1, 1, true);
//    }
//    if (auto* value = dynamic_cast<Comment*>(&element)) {
//        check(issues, value->Comment::locale(), "Comment.locale", 0, 1, true);
//        check(issues, value->Comment::body(), "Comment.body", 1, 1, true);
//    }
//    if (auto* value = dynamic_cast<Annotation*>(&element)) {
//        if (includeDerived) check(issues, value->Annotation::annotatingElement(), "Annotation.annotatingElement", 1, 1, true);
//        check(issues, value->Annotation::annotatedElement(), "Annotation.annotatedElement", 1, 1, true);
//        if (includeDerived) check(issues, value->Annotation::owningAnnotatedElement(), "Annotation.owningAnnotatedElement", 0, 1, true);
//        if (includeDerived) check(issues, value->Annotation::owningAnnotatingElement(), "Annotation.owningAnnotatingElement", 0, 1, true);
//        if (includeDerived) check(issues, value->Annotation::ownedAnnotatingElement(), "Annotation.ownedAnnotatingElement", 0, 1, true);
//    }
//    if (auto* value = dynamic_cast<AnnotatingElement*>(&element)) {
//        if (includeDerived) check(issues, value->AnnotatingElement::annotatedElements(), "AnnotatingElement.annotatedElement", 1, -1, true);
//        if (includeDerived) check(issues, value->AnnotatingElement::ownedAnnotatingRelationships(), "AnnotatingElement.ownedAnnotatingRelationship", 0, -1, true);
//        if (includeDerived) check(issues, value->AnnotatingElement::owningAnnotatingRelationship(), "AnnotatingElement.owningAnnotatingRelationship", 0, 1, true);
//        if (includeDerived) check(issues, value->AnnotatingElement::annotations(), "AnnotatingElement.annotation", 0, -1, true);
//    }
//    if (auto* value = dynamic_cast<NamespaceImport*>(&element)) {
//        check(issues, value->NamespaceImport::importedNamespace(), "NamespaceImport.importedNamespace", 1, 1, true);
//    }
//    if (auto* value = dynamic_cast<MembershipImport*>(&element)) {
//        check(issues, value->MembershipImport::importedMembership(), "MembershipImport.importedMembership", 1, 1, true);
//    }
//    if (auto* value = dynamic_cast<OwningMembership*>(&element)) {
//        if (includeDerived) check(issues, value->OwningMembership::ownedMemberElement(), "OwningMembership.ownedMemberElement", 1, 1, true);
//        if (includeDerived) check(issues, value->OwningMembership::ownedMemberElementId(), "OwningMembership.ownedMemberElementId", 1, 1, true);
//        if (includeDerived) check(issues, value->OwningMembership::ownedMemberShortName(), "OwningMembership.ownedMemberShortName", 0, 1, true);
//        if (includeDerived) check(issues, value->OwningMembership::ownedMemberName(), "OwningMembership.ownedMemberName", 0, 1, true);
//    }
//    if (auto* value = dynamic_cast<Import*>(&element)) {
//        if (includeDerived) check(issues, value->Import::importOwningNamespace(), "Import.importOwningNamespace", 1, 1, true);
//        check(issues, value->Import::visibility(), "Import.visibility", 1, 1, true);
//        check(issues, value->Import::isRecursive(), "Import.isRecursive", 1, 1, true);
//        check(issues, value->Import::isImportAll(), "Import.isImportAll", 1, 1, true);
//        if (includeDerived) check(issues, value->Import::importedElement(), "Import.importedElement", 1, 1, true);
//    }
//    if (auto* value = dynamic_cast<Namespace*>(&element)) {
//        if (includeDerived) check(issues, value->Namespace::memberships(), "Namespace.membership", 0, -1, true);
//        if (includeDerived) check(issues, value->Namespace::ownedImport(), "Namespace.ownedImport", 0, -1, true);
//        if (includeDerived) check(issues, value->Namespace::member(), "Namespace.member", 0, -1, true);
//        if (includeDerived) check(issues, value->Namespace::ownedMember(), "Namespace.ownedMember", 0, -1, true);
//        if (includeDerived) check(issues, value->Namespace::ownedMembership(), "Namespace.ownedMembership", 0, -1, true);
//        if (includeDerived) check(issues, value->Namespace::importedMemberships(), "Namespace.importedMembership", 0, -1, true);
//    }
//    if (auto* value = dynamic_cast<Membership*>(&element)) {
//        if (includeDerived) check(issues, value->Membership::memberElementId(), "Membership.memberElementId", 1, 1, true);
//        if (includeDerived) check(issues, value->Membership::membershipOwningNamespace(), "Membership.membershipOwningNamespace", 1, 1, true);
//        check(issues, value->Membership::memberShortName(), "Membership.memberShortName", 0, 1, true);
//        check(issues, value->Membership::memberElement(), "Membership.memberElement", 1, 1, true);
//        check(issues, value->Membership::memberName(), "Membership.memberName", 0, 1, true);
//        check(issues, value->Membership::visibility(), "Membership.visibility", 1, 1, true);
//    }
//    if (auto* value = dynamic_cast<Relationship*>(&element)) {
//        if (includeDerived) check(issues, value->Relationship::relatedElement(), "Relationship.relatedElement", 0, -1, false);
//        check(issues, value->Relationship::target(), "Relationship.target", 0, -1, true);
//        check(issues, value->Relationship::source(), "Relationship.source", 0, -1, true);
//        check(issues, value->Relationship::owningRelatedElement(), "Relationship.owningRelatedElement", 0, 1, true);
//        check(issues, value->Relationship::ownedRelatedElement(), "Relationship.ownedRelatedElement", 0, -1, true);
//        check(issues, value->Relationship::isImplied(), "Relationship.isImplied", 1, 1, true);
//    }
//    if (auto* value = dynamic_cast<Element*>(&element)) {
//        if (includeDerived) check(issues, value->Element::owningMembership(), "Element.owningMembership", 0, 1, true);
//        check(issues, value->Element::owningRelationship(), "Element.owningRelationship", 0, 1, true);
//        if (includeDerived) check(issues, value->Element::owningNamespace(), "Element.owningNamespace", 0, 1, true);
//        check(issues, value->Element::elementId(), "Element.elementId", 1, 1, true);
//        check(issues, value->Element::ownedRelationship(), "Element.ownedRelationship", 0, -1, true);
//        if (includeDerived) check(issues, value->Element::owner(), "Element.owner", 0, 1, true);
//        if (includeDerived) check(issues, value->Element::ownedElement(), "Element.ownedElement", 0, -1, true);
//        if (includeDerived) check(issues, value->Element::documentation(), "Element.documentation", 0, -1, true);
//        if (includeDerived) check(issues, value->Element::ownedAnnotation(), "Element.ownedAnnotation", 0, -1, true);
//        if (includeDerived) check(issues, value->Element::textualRepresentation(), "Element.textualRepresentation", 0, -1, true);
//        check(issues, value->Element::aliasIds(), "Element.aliasIds", 0, -1, true);
//        check(issues, value->Element::declaredShortName(), "Element.declaredShortName", 0, 1, true);
//        check(issues, value->Element::declaredName(), "Element.declaredName", 0, 1, true);
//        if (includeDerived) check(issues, value->Element::shortName(), "Element.shortName", 0, 1, true);
//        if (includeDerived) check(issues, value->Element::name(), "Element.name", 0, 1, true);
//        if (includeDerived) check(issues, value->Element::qualifiedName(), "Element.qualifiedName", 0, 1, true);
//        check(issues, value->Element::isImpliedIncluded(), "Element.isImpliedIncluded", 1, 1, true);
//        if (includeDerived) check(issues, value->Element::isLibraryElement(), "Element.isLibraryElement", 1, 1, true);
//    }
//    return issues;
//}
}
