// Generated by sysml/tools/generate_abstract_syntax.py.
#pragma once
#include <sysml/model/Representation.h>
#include <sysml/model/Forward.h>
#include <sysml/model/KerMLTypes.h>
#include <sysml/connections/ConnectionDefinition.h>

namespace SysMLv2::Entities {
class SYSML_EXPORT AllocationDefinition : public virtual ConnectionDefinition, public virtual Representation {
public:
    AllocationDefinition();
    ~AllocationDefinition() override;
    std::string_view metaclassName() const noexcept override;
    std::vector<RepresentationIssue> validateRepresentation(bool includeDerived = false) const override;
    /// Derived snapshot; populated by a semantic evaluator or importer.
    std::vector<std::shared_ptr<AllocationUsage>> allocation() const;
    void setAllocation(std::vector<std::shared_ptr<AllocationUsage>> value);
    void appendAllocation(std::shared_ptr<AllocationUsage> value);
private:
    std::vector<std::shared_ptr<AllocationUsage>> allocation_ = {};
};
}
