// Generated by sysml/tools/generate_abstract_syntax.py.
#pragma once
#include <sysml/model/Representation.h>
#include <sysml/model/Forward.h>
#include <sysml/model/KerMLTypes.h>
#include <sysml/requirements/RequirementConstraintMembership.h>
#include <sysml/requirements/RequirementConstraintKind.h>

namespace SysMLv2::Entities {
class SYSML_EXPORT RequirementVerificationMembership : public virtual RequirementConstraintMembership, public virtual Representation {
public:
    RequirementVerificationMembership();
    ~RequirementVerificationMembership() override;
    std::string_view metaclassName() const noexcept override;
    std::vector<RepresentationIssue> validateRepresentation(bool includeDerived = false) const override;
    /// Derived snapshot; populated by a semantic evaluator or importer.
    std::shared_ptr<RequirementUsage> ownedRequirement() const;
    void setOwnedRequirement(std::shared_ptr<RequirementUsage> value);
    /// Stored metamodel property.
    RequirementConstraintKind kind() const;
    void setKind(RequirementConstraintKind value);
    /// Derived snapshot; populated by a semantic evaluator or importer.
    std::shared_ptr<RequirementUsage> verifiedRequirement() const;
    void setVerifiedRequirement(std::shared_ptr<RequirementUsage> value);
private:
    std::shared_ptr<RequirementUsage> ownedRequirement_ = {};
    RequirementConstraintKind kind_ = RequirementConstraintKind::requirement;
    std::shared_ptr<RequirementUsage> verifiedRequirement_ = {};
};
}
