// Generated by sysml/tools/generate_abstract_syntax.py.
#pragma once
#include <sysml/model/Representation.h>
#include <sysml/model/Forward.h>
#include <sysml/model/KerMLTypes.h>
#include <sysml/cases/CaseUsage.h>

namespace SysMLv2::Entities {
class SYSML_EXPORT VerificationCaseUsage : public virtual CaseUsage, public virtual Representation {
public:
    VerificationCaseUsage();
    ~VerificationCaseUsage() override;
    std::string_view metaclassName() const noexcept override;
    std::vector<RepresentationIssue> validateRepresentation(bool includeDerived = false) const override;
    /// Derived snapshot; populated by a semantic evaluator or importer.
    std::shared_ptr<VerificationCaseDefinition> verificationCaseDefinition() const;
    void setVerificationCaseDefinition(std::shared_ptr<VerificationCaseDefinition> value);
    /// Derived snapshot; populated by a semantic evaluator or importer.
    std::vector<std::shared_ptr<RequirementUsage>> verifiedRequirement() const;
    void setVerifiedRequirement(std::vector<std::shared_ptr<RequirementUsage>> value);
    void appendVerifiedRequirement(std::shared_ptr<RequirementUsage> value);
private:
    std::shared_ptr<VerificationCaseDefinition> verificationCaseDefinition_ = {};
    std::vector<std::shared_ptr<RequirementUsage>> verifiedRequirement_ = {};
};
}
