// Generated by sysml/tools/generate_abstract_syntax.py.
#pragma once
#include <sysml/model/Representation.h>
#include <sysml/model/Forward.h>
#include <sysml/model/KerMLTypes.h>
#include <sysml/items/ItemDefinition.h>

namespace SysMLv2::Entities {
class SYSML_EXPORT PartDefinition : public virtual ItemDefinition, public virtual Representation {
public:
    PartDefinition();
    ~PartDefinition() override;
    std::string_view metaclassName() const noexcept override;
    std::vector<RepresentationIssue> validateRepresentation(bool includeDerived = false) const override;
private:
};
}
