// Generated by sysml/tools/generate_abstract_syntax.py.
#pragma once
#include <sysml/model/Representation.h>
#include <sysml/model/Forward.h>
#include <sysml/model/KerMLTypes.h>
#include <sysml/items/ItemUsage.h>

namespace SysMLv2::Entities {
class SYSML_EXPORT PartUsage : public virtual ItemUsage, public virtual Representation {
public:
    PartUsage();
    ~PartUsage() override;
    std::string_view metaclassName() const noexcept override;
    std::vector<RepresentationIssue> validateRepresentation(bool includeDerived = false) const override;
    /// Derived snapshot; populated by a semantic evaluator or importer.
    std::vector<std::shared_ptr<PartDefinition>> partDefinition() const;
    void setPartDefinition(std::vector<std::shared_ptr<PartDefinition>> value);
    void appendPartDefinition(std::shared_ptr<PartDefinition> value);
private:
    std::vector<std::shared_ptr<PartDefinition>> partDefinition_ = {};
};
}
