// Generated by sysml/tools/generate_abstract_syntax.py.
#include <sysml/usecases/IncludeUseCaseUsage.h>
#include <sysml/usecases/UseCaseUsage.h>
#include <algorithm>
#include <stdexcept>

namespace SysMLv2::Entities {

std::shared_ptr<UseCaseUsage> IncludeUseCaseUsage::useCaseIncluded() const {
    return useCaseIncluded_;
}

void IncludeUseCaseUsage::setUseCaseIncluded(std::shared_ptr<UseCaseUsage> value) {
    useCaseIncluded_ = std::move(value);
}

IncludeUseCaseUsage::IncludeUseCaseUsage() {
    _dType = "IncludeUseCaseUsage";
}

IncludeUseCaseUsage::~IncludeUseCaseUsage() = default;

std::string_view IncludeUseCaseUsage::metaclassName() const noexcept {
    return "IncludeUseCaseUsage";
}

std::vector<RepresentationIssue> IncludeUseCaseUsage::validateRepresentation(bool includeDerived) const {
    std::vector<RepresentationIssue> issues; (void)includeDerived;
    { auto optional = OccurrenceUsage::portionKind(); if (optional) { auto value = *optional; if (!(value == PortionKind::timeslice || value == PortionKind::snapshot)) issues.push_back({"OccurrenceUsage.portionKind", "invalid enumeration value"}); } }
    if (includeDerived) if (!CaseUsage::subjectParameter()) issues.push_back({"CaseUsage.subjectParameter", "required reference is missing"});
    if (includeDerived) if (!EventOccurrenceUsage::eventOccurrence()) issues.push_back({"EventOccurrenceUsage.eventOccurrence", "required reference is missing"});
    if (includeDerived) if (!PerformActionUsage::performedAction()) issues.push_back({"PerformActionUsage.performedAction", "required reference is missing"});
    if (includeDerived) if (!IncludeUseCaseUsage::useCaseIncluded()) issues.push_back({"IncludeUseCaseUsage.useCaseIncluded", "required reference is missing"});
    return issues;
}

} // namespace SysMLv2::Entities
