// Generated by sysml/tools/generate_abstract_syntax.py.
#include <sysml/usecases/UseCaseDefinition.h>
#include <sysml/usecases/UseCaseUsage.h>
#include <algorithm>
#include <stdexcept>

namespace SysMLv2::Entities {

std::vector<std::shared_ptr<UseCaseUsage>> UseCaseDefinition::includedUseCase() const {
    return includedUseCase_;
}

void UseCaseDefinition::setIncludedUseCase(std::vector<std::shared_ptr<UseCaseUsage>> value) {
    if (std::any_of(value.begin(), value.end(), [](const auto& item) { return !item; })) {
        throw std::invalid_argument("UseCaseDefinition.includedUseCase: null entry");
    }
    for (std::size_t i = 0; i < value.size(); ++i) {
        if (std::find(value.begin(), value.begin() + i, value[i]) != value.begin() + i) {
            throw std::invalid_argument("UseCaseDefinition.includedUseCase: duplicate entry");
        }
    }
    includedUseCase_ = std::move(value);
}

void UseCaseDefinition::appendIncludedUseCase(std::shared_ptr<UseCaseUsage> value) {
    auto values = includedUseCase();
    values.push_back(std::move(value));
    setIncludedUseCase(std::move(values));
}

UseCaseDefinition::UseCaseDefinition() {
    _dType = "UseCaseDefinition";
}

UseCaseDefinition::~UseCaseDefinition() = default;

std::string_view UseCaseDefinition::metaclassName() const noexcept {
    return "UseCaseDefinition";
}

std::vector<RepresentationIssue> UseCaseDefinition::validateRepresentation(bool includeDerived) const {
    std::vector<RepresentationIssue> issues; (void)includeDerived;
    if (includeDerived) if (!CaseDefinition::subjectParameter()) issues.push_back({"CaseDefinition.subjectParameter", "required reference is missing"});
    return issues;
}

} // namespace SysMLv2::Entities
