// Generated by sysml/tools/generate_abstract_syntax.py.
#include <sysml/usecases/UseCaseUsage.h>
#include <sysml/usecases/UseCaseDefinition.h>
#include <algorithm>
#include <stdexcept>

namespace SysMLv2::Entities {

std::shared_ptr<UseCaseDefinition> UseCaseUsage::useCaseDefinition() const {
    return useCaseDefinition_;
}

void UseCaseUsage::setUseCaseDefinition(std::shared_ptr<UseCaseDefinition> value) {
    useCaseDefinition_ = std::move(value);
}

std::vector<std::shared_ptr<UseCaseUsage>> UseCaseUsage::includedUseCase() const {
    return includedUseCase_;
}

void UseCaseUsage::setIncludedUseCase(std::vector<std::shared_ptr<UseCaseUsage>> value) {
    if (std::any_of(value.begin(), value.end(), [](const auto& item) { return !item; })) {
        throw std::invalid_argument("UseCaseUsage.includedUseCase: null entry");
    }
    for (std::size_t i = 0; i < value.size(); ++i) {
        if (std::find(value.begin(), value.begin() + i, value[i]) != value.begin() + i) {
            throw std::invalid_argument("UseCaseUsage.includedUseCase: duplicate entry");
        }
    }
    includedUseCase_ = std::move(value);
}

void UseCaseUsage::appendIncludedUseCase(std::shared_ptr<UseCaseUsage> value) {
    auto values = includedUseCase();
    values.push_back(std::move(value));
    setIncludedUseCase(std::move(values));
}

UseCaseUsage::UseCaseUsage() {
    _dType = "UseCaseUsage";
}

UseCaseUsage::~UseCaseUsage() = default;

std::string_view UseCaseUsage::metaclassName() const noexcept {
    return "UseCaseUsage";
}

std::vector<RepresentationIssue> UseCaseUsage::validateRepresentation(bool includeDerived) const {
    std::vector<RepresentationIssue> issues; (void)includeDerived;
    { auto optional = OccurrenceUsage::portionKind(); if (optional) { auto value = *optional; if (!(value == PortionKind::timeslice || value == PortionKind::snapshot)) issues.push_back({"OccurrenceUsage.portionKind", "invalid enumeration value"}); } }
    if (includeDerived) if (!CaseUsage::subjectParameter()) issues.push_back({"CaseUsage.subjectParameter", "required reference is missing"});
    return issues;
}

} // namespace SysMLv2::Entities
