// Generated by sysml/tools/generate_abstract_syntax.py.
#pragma once
#include <sysml/model/Representation.h>
#include <sysml/model/Forward.h>
#include <sysml/model/KerMLTypes.h>
#include <sysml/cases/CaseUsage.h>

namespace SysMLv2::Entities {
class SYSML_EXPORT AnalysisCaseUsage : public virtual CaseUsage, public virtual Representation {
public:
    AnalysisCaseUsage();
    ~AnalysisCaseUsage() override;
    std::string_view metaclassName() const noexcept override;
    std::vector<RepresentationIssue> validateRepresentation(bool includeDerived = false) const override;
    /// Derived snapshot; populated by a semantic evaluator or importer.
    std::shared_ptr<AnalysisCaseDefinition> analysisCaseDefinition() const;
    void setAnalysisCaseDefinition(std::shared_ptr<AnalysisCaseDefinition> value);
    /// Derived snapshot; populated by a semantic evaluator or importer.
    std::shared_ptr<KerML::Entities::Expression> resultExpression() const;
    void setResultExpression(std::shared_ptr<KerML::Entities::Expression> value);
private:
    std::shared_ptr<AnalysisCaseDefinition> analysisCaseDefinition_ = {};
    std::shared_ptr<KerML::Entities::Expression> resultExpression_ = {};
};
}
