// Generated by sysml/tools/generate_abstract_syntax.py.
#pragma once
#include <sysml/model/Representation.h>
#include <sysml/model/Forward.h>
#include <sysml/model/KerMLTypes.h>
#include <sysml/cases/CaseDefinition.h>

namespace SysMLv2::Entities {
class SYSML_EXPORT AnalysisCaseDefinition : public virtual CaseDefinition, public virtual Representation {
public:
    AnalysisCaseDefinition();
    ~AnalysisCaseDefinition() override;
    std::string_view metaclassName() const noexcept override;
    std::vector<RepresentationIssue> validateRepresentation(bool includeDerived = false) const override;
    /// Derived snapshot; populated by a semantic evaluator or importer.
    std::shared_ptr<KerML::Entities::Expression> resultExpression() const;
    void setResultExpression(std::shared_ptr<KerML::Entities::Expression> value);
private:
    std::shared_ptr<KerML::Entities::Expression> resultExpression_ = {};
};
}
