// Generated by sysml/tools/generate_abstract_syntax.py.
#include <sysml/verificationcases/RequirementVerificationMembership.h>
#include <sysml/requirements/RequirementUsage.h>
#include <sysml/requirements/RequirementConstraintKind.h>
#include <algorithm>
#include <stdexcept>

namespace SysMLv2::Entities {

std::shared_ptr<RequirementUsage> RequirementVerificationMembership::ownedRequirement() const {
    return ownedRequirement_;
}

void RequirementVerificationMembership::setOwnedRequirement(std::shared_ptr<RequirementUsage> value) {
    ownedRequirement_ = std::move(value);
}

RequirementConstraintKind RequirementVerificationMembership::kind() const {
    return kind_;
}

void RequirementVerificationMembership::setKind(RequirementConstraintKind value) {
    kind_ = std::move(value);
}

std::shared_ptr<RequirementUsage> RequirementVerificationMembership::verifiedRequirement() const {
    return verifiedRequirement_;
}

void RequirementVerificationMembership::setVerifiedRequirement(std::shared_ptr<RequirementUsage> value) {
    verifiedRequirement_ = std::move(value);
}

RequirementVerificationMembership::RequirementVerificationMembership() {
    _dType = "RequirementVerificationMembership";
}

RequirementVerificationMembership::~RequirementVerificationMembership() = default;

std::string_view RequirementVerificationMembership::metaclassName() const noexcept {
    return "RequirementVerificationMembership";
}

std::vector<RepresentationIssue> RequirementVerificationMembership::validateRepresentation(bool includeDerived) const {
    std::vector<RepresentationIssue> issues; (void)includeDerived;
    { auto value = RequirementConstraintMembership::kind(); if (!(value == RequirementConstraintKind::assumption || value == RequirementConstraintKind::requirement)) issues.push_back({"RequirementConstraintMembership.kind", "invalid enumeration value"}); }
    if (includeDerived) if (!RequirementConstraintMembership::ownedConstraint()) issues.push_back({"RequirementConstraintMembership.ownedConstraint", "required reference is missing"});
    if (includeDerived) if (!RequirementConstraintMembership::referencedConstraint()) issues.push_back({"RequirementConstraintMembership.referencedConstraint", "required reference is missing"});
    if (includeDerived) if (!RequirementVerificationMembership::ownedRequirement()) issues.push_back({"RequirementVerificationMembership.ownedRequirement", "required reference is missing"});
    { auto value = RequirementVerificationMembership::kind(); if (!(value == RequirementConstraintKind::assumption || value == RequirementConstraintKind::requirement)) issues.push_back({"RequirementVerificationMembership.kind", "invalid enumeration value"}); }
    if (includeDerived) if (!RequirementVerificationMembership::verifiedRequirement()) issues.push_back({"RequirementVerificationMembership.verifiedRequirement", "required reference is missing"});
    return issues;
}

} // namespace SysMLv2::Entities
