// Generated by sysml/tools/generate_abstract_syntax.py.
#include <sysml/verificationcases/VerificationCaseDefinition.h>
#include <sysml/requirements/RequirementUsage.h>
#include <algorithm>
#include <stdexcept>

namespace SysMLv2::Entities {

std::vector<std::shared_ptr<RequirementUsage>> VerificationCaseDefinition::verifiedRequirement() const {
    return verifiedRequirement_;
}

void VerificationCaseDefinition::setVerifiedRequirement(std::vector<std::shared_ptr<RequirementUsage>> value) {
    if (std::any_of(value.begin(), value.end(), [](const auto& item) { return !item; })) {
        throw std::invalid_argument("VerificationCaseDefinition.verifiedRequirement: null entry");
    }
    for (std::size_t i = 0; i < value.size(); ++i) {
        if (std::find(value.begin(), value.begin() + i, value[i]) != value.begin() + i) {
            throw std::invalid_argument("VerificationCaseDefinition.verifiedRequirement: duplicate entry");
        }
    }
    verifiedRequirement_ = std::move(value);
}

void VerificationCaseDefinition::appendVerifiedRequirement(std::shared_ptr<RequirementUsage> value) {
    auto values = verifiedRequirement();
    values.push_back(std::move(value));
    setVerifiedRequirement(std::move(values));
}

VerificationCaseDefinition::VerificationCaseDefinition() {
    _dType = "VerificationCaseDefinition";
}

VerificationCaseDefinition::~VerificationCaseDefinition() = default;

std::string_view VerificationCaseDefinition::metaclassName() const noexcept {
    return "VerificationCaseDefinition";
}

std::vector<RepresentationIssue> VerificationCaseDefinition::validateRepresentation(bool includeDerived) const {
    std::vector<RepresentationIssue> issues; (void)includeDerived;
    if (includeDerived) if (!CaseDefinition::subjectParameter()) issues.push_back({"CaseDefinition.subjectParameter", "required reference is missing"});
    return issues;
}

} // namespace SysMLv2::Entities
