// Generated by sysml/tools/generate_abstract_syntax.py.
#include <sysml/verificationcases/VerificationCaseUsage.h>
#include <sysml/verificationcases/VerificationCaseDefinition.h>
#include <sysml/requirements/RequirementUsage.h>
#include <algorithm>
#include <stdexcept>

namespace SysMLv2::Entities {

std::shared_ptr<VerificationCaseDefinition> VerificationCaseUsage::verificationCaseDefinition() const {
    return verificationCaseDefinition_;
}

void VerificationCaseUsage::setVerificationCaseDefinition(std::shared_ptr<VerificationCaseDefinition> value) {
    verificationCaseDefinition_ = std::move(value);
}

std::vector<std::shared_ptr<RequirementUsage>> VerificationCaseUsage::verifiedRequirement() const {
    return verifiedRequirement_;
}

void VerificationCaseUsage::setVerifiedRequirement(std::vector<std::shared_ptr<RequirementUsage>> value) {
    if (std::any_of(value.begin(), value.end(), [](const auto& item) { return !item; })) {
        throw std::invalid_argument("VerificationCaseUsage.verifiedRequirement: null entry");
    }
    for (std::size_t i = 0; i < value.size(); ++i) {
        if (std::find(value.begin(), value.begin() + i, value[i]) != value.begin() + i) {
            throw std::invalid_argument("VerificationCaseUsage.verifiedRequirement: duplicate entry");
        }
    }
    verifiedRequirement_ = std::move(value);
}

void VerificationCaseUsage::appendVerifiedRequirement(std::shared_ptr<RequirementUsage> value) {
    auto values = verifiedRequirement();
    values.push_back(std::move(value));
    setVerifiedRequirement(std::move(values));
}

VerificationCaseUsage::VerificationCaseUsage() {
    _dType = "VerificationCaseUsage";
}

VerificationCaseUsage::~VerificationCaseUsage() = default;

std::string_view VerificationCaseUsage::metaclassName() const noexcept {
    return "VerificationCaseUsage";
}

std::vector<RepresentationIssue> VerificationCaseUsage::validateRepresentation(bool includeDerived) const {
    std::vector<RepresentationIssue> issues; (void)includeDerived;
    { auto optional = OccurrenceUsage::portionKind(); if (optional) { auto value = *optional; if (!(value == PortionKind::timeslice || value == PortionKind::snapshot)) issues.push_back({"OccurrenceUsage.portionKind", "invalid enumeration value"}); } }
    if (includeDerived) if (!CaseUsage::subjectParameter()) issues.push_back({"CaseUsage.subjectParameter", "required reference is missing"});
    return issues;
}

} // namespace SysMLv2::Entities
