"""Generate KerML kernel properties and structural inventory from the pinned OMG manifest.

Root/core implementations are preserved; their API is audited by Inventory.cpp.
Derived kernel views are computed where a canonical relationship exists, otherwise
explicitly stored snapshots for population by an importer/semantic evaluator.
"""
import argparse,json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2]
MODEL=json.loads((ROOT/'kerml/model/abstract_syntax.json').read_text())
TYPES={n['name']:n for n in MODEL['types']}
CLASSES=[n for n in TYPES.values() if n['kind']=='Class']
KERNEL=[n for n in CLASSES if n['package'].startswith('kernel')]
OUT={}
def emit(p,s): OUT[ROOT/p]=s
BANNER='// Generated by kerml/tools/generate_abstract_syntax.py.\n'
def method(sig,body):return sig+' {\n'+''.join('    '+l+'\n' for l in body.splitlines())+'}\n\n'
def pn(p):return 'operatorName' if p['name']=='operator' else p['name']
def vt(p):
 return {'Boolean':'bool','String':'std::string','Integer':'std::int64_t','Real':'double'}.get(p['type'],'std::shared_ptr<'+p['type']+'>')
def pt(p):return 'std::vector<'+vt(p)+'>' if p['upper']!=1 else vt(p)
def isref(p):return p['type'] not in ('Boolean','String','Integer','Real')
def first(t,expr): return 'auto values = '+expr+'; return values.empty() ? nullptr : values.front();'
def select(t,expr):return 'detail::select<'+t+'>('+expr+')'
# Getters and setters sharing canonical base properties, rather than duplicate fields.
def computed(n,p):
 c=n['name']; a=p['name']; t=p['type']
 table={
 ('Behavior','step'):('return '+select(t,'features()')+';',None),
 ('Function','expression'):('return '+select(t,'step()')+';',None),
 ('BooleanExpression','predicate'):('return std::dynamic_pointer_cast<Predicate>(function());','setFunction(std::move(value));'),
 ('ResultExpressionMembership','ownedResultExpression'):('return std::dynamic_pointer_cast<Expression>(FeatureMembership::ownedMemberFeature());','FeatureMembership::setOwnedMemberFeature(std::move(value));'),
 ('ParameterMembership','ownedMemberParameter'):('return FeatureMembership::ownedMemberFeature();','FeatureMembership::setOwnedMemberFeature(std::move(value));'),
 ('FeatureValue','value'):('return std::dynamic_pointer_cast<Expression>(ownedMemberElement());','setOwnedMemberElement(std::move(value));'),
 ('FeatureValue','featureWithValue'):('return std::dynamic_pointer_cast<Feature>(membershipOwningNamespace());','setMembershipOwningNamespace(std::move(value));'),
 ('ElementFilterMembership','condition'):('return std::dynamic_pointer_cast<Expression>(ownedMemberElement());','setOwnedMemberElement(std::move(value));'),
 ('Flow','flowEnd'):('return '+select(t,'connectorEnd()')+';',None),
 ('Flow','payloadFeature'):(first(t,select(t,'ownedFeature()')),None),
 ('Flow','payloadType'):('auto payload = payloadFeature(); return payload ? '+select(t,'payload->type()')+' : std::vector<std::shared_ptr<Classifier>>{};',None),
 ('Flow','sourceOutputFeature'):('auto ends = connectorEnd(); if (ends.empty() || !ends.front()) return nullptr; '+first(t,'ends.front()->ownedFeature()'),None),
 ('Flow','targetInputFeature'):('auto ends = connectorEnd(); if (ends.size() < 2 || !ends[1]) return nullptr; '+first(t,'ends[1]->ownedFeature()'),None),
 ('Flow','interaction'):('return '+select(t,'Feature::type()')+';',None),
 ('Connector','association'):('return '+select(t,'Feature::type()')+';',None),
 ('Connector','connectorEnd'):('return endFeature();','setEndFeatures(std::move(value));'),
 ('Connector','relatedFeature'):('return '+select(t,'relatedElement()')+';',None),
 ('Connector','sourceFeature'):(first(t,select(t,'source()')),None),
 ('Connector','targetFeature'):('return '+select(t,'target()')+';',None),
 ('Association','relatedType'):('return '+select(t,'relatedElement()')+';',None),
 ('Association','sourceType'):(first(t,select(t,'source()')),None),
 ('Association','targetType'):('return '+select(t,'target()')+';',None),
 ('Association','associationEnd'):('return endFeature();','setEndFeatures(std::move(value));'),
 ('MetadataFeature','metaclass'):(first(t,select(t,'Feature::type()')),None),
 ('MultiplicityRange','lowerBound'):('auto values = bound(); return values.size() == 2 ? values.front() : nullptr;',None),
 ('MultiplicityRange','upperBound'):('auto values = bound(); return values.empty() ? nullptr : values.back();',None),
 ('Package','filterCondition'):('std::vector<std::shared_ptr<Expression>> result; for (const auto& m : ownedMembership()) { if (auto filter = std::dynamic_pointer_cast<ElementFilterMembership>(m)) { if (auto condition = filter->condition()) result.push_back(condition); } } return result;',None),
 }
 return table.get((c,a))
fixed={'IndexExpression':'#','CollectExpression':'collect','SelectExpression':'select','FeatureChainExpression':'.'}
emit('kerml/include/kerml/model/Forward.h',BANNER+'#pragma once\nnamespace KerML::Entities {\n'+''.join('class '+n['name']+';\n' for n in CLASSES)+'}\n')
emit('kerml/include/kerml/KerML.h',BANNER+'#pragma once\n'+''.join('#include <'+n['header']+'>\n' for n in TYPES.values())+'#include <kerml/model/Representation.h>\n')
emit('kerml/src/kerml/model/RepresentationSupport.h',BANNER+'''#pragma once
#include <algorithm>
#include <memory>
#include <stdexcept>
#include <vector>
namespace KerML::Entities::detail {
template<class T, class U> std::vector<std::shared_ptr<T>> select(const std::vector<std::shared_ptr<U>>& values) {
    std::vector<std::shared_ptr<T>> result;
    for (const auto& value : values) if (auto typed = std::dynamic_pointer_cast<T>(value)) result.push_back(typed);
    return result;
}
template<class T> void checkCollection(const std::vector<std::shared_ptr<T>>& values, bool unique, int upper) {
    if (upper >= 0 && values.size() > static_cast<std::size_t>(upper)) throw std::invalid_argument("Upper multiplicity exceeded");
    for (std::size_t i = 0; i < values.size(); ++i) {
        if (!values[i]) throw std::invalid_argument("Null collection entry");
        if (unique && std::find(values.begin(), values.begin() + i, values[i]) != values.begin() + i) throw std::invalid_argument("Duplicate collection entry");
    }
}
}
''')
sources=[]
for n in KERNEL:
 name=n['name']; header=n['header']; src='kerml/src/'+header[:-2]+'.cpp'; sources.append(src)
 includes=[TYPES[b]['header'] for b in n['bases']]+['kerml/model/Forward.h','kerml/kerml_global.h']
 lines=[BANNER+'#pragma once\n']+['#include <'+h+'>\n' for h in dict.fromkeys(includes)]+['#include <cstdint>\n#include <memory>\n#include <string>\n#include <vector>\n\nnamespace KerML::Entities {\n']
 # Virtual bases preserve one Element for SysML multiple inheritance.
 lines+=['class KERML_EXPORT '+name+' : '+', '.join('public virtual '+b for b in n['bases'])+' {\n    friend struct ElementDisposer;\npublic:\n    '+name+'();\n    ~'+name+'() override;\n']
 source=[BANNER+'#include <kerml/KerML.h>\n#include <utility>\n#include <stdexcept>\n#include "../../model/RepresentationSupport.h"\n\nnamespace KerML::Entities {\n']
 # Relative path from any kernel category is ../../model.
 ctor=['_dType = "'+name+'";']
 if name in fixed:ctor+=['OperatorExpression::setOperatorName("'+fixed[name]+'");']
 if name=='FlowEnd':ctor+=['setIsEnd(true);']
 fields=[]
 if name=='ResultExpressionMembership':
  lines+=['    ResultExpressionMembership(std::shared_ptr<Expression> expression, std::shared_ptr<Type> owner);\n    void setOwningType(std::shared_ptr<Type> owner);\n']
  source+=[method(name+'::'+name+'(std::shared_ptr<Expression> expression, std::shared_ptr<Type> owner) : '+name+'()', 'setOwnedResultExpression(std::move(expression));\nsetOwningType(std::move(owner));')]
  source+=[method('void '+name+'::setOwningType(std::shared_ptr<Type> owner)','if (!std::dynamic_pointer_cast<Function>(owner) && !std::dynamic_pointer_cast<Expression>(owner)) throw std::invalid_argument("Result expression owner must be a Function or Expression");\nFeatureMembership::setOwningType(std::move(owner));')]
 for p in n['properties']:
  prop=pn(p); typ=pt(p); cap=prop[0].upper()+prop[1:]; comp=computed(n,p)
  if name in fixed and p['name']=='operator':
   lines+=['    void setOperatorName(const std::string& name) override;\n']
   source+=[method('void '+name+'::setOperatorName(const std::string& name)','if (name != "'+fixed[name]+'") throw std::invalid_argument("Invalid fixed operator for '+name+'");\nOperatorExpression::setOperatorName(name);')];continue
  lines+=['    /// '+('Computed from the underlying representation.' if comp else 'Derived snapshot populated by an importer or semantic evaluator.' if p['derived'] else 'Stored metamodel property.')+'\n']
  ret='const std::string&' if prop=='operatorName' else typ
  lines+=['    '+ret+' '+prop+'() const;\n']
  source+=[method(ret+' '+name+'::'+prop+'() const',comp[0] if comp else 'return '+prop+'_;')]
  if comp and comp[1] is None:continue
  param='const std::string&' if prop=='operatorName' else typ
  lines+=['    '+('virtual ' if prop=='operatorName' else '')+'void set'+cap+'('+param+' value);\n']
  body=''
  if p['upper']!=1 and isref(p):body+='detail::checkCollection(value, '+str(p['unique']).lower()+', '+str(p['upper'])+');\n'
  if name=='ResultExpressionMembership':body+='if (!value) throw std::invalid_argument("Result expression is required");\n'
  body+=comp[1] if comp else prop+'_ = std::move(value);'
  source+=[method('void '+name+'::set'+cap+'('+param+' value)',body)]
  if not comp:
   default=p.get('default','{}')
   if p['type']=='String':default=json.dumps(p['default']) if 'default' in p else '{}'
   fields+=['    '+typ+' '+prop+'_ = '+default+';\n']
  if p['upper']!=1:
   lines+=['    void append'+cap+'('+vt(p)+' value);\n']
   source+=[method('void '+name+'::append'+cap+'('+vt(p)+' value)','auto values = '+prop+'(); values.push_back(std::move(value)); set'+cap+'(std::move(values));')]
 lines+=['private:\n']+fields+['};\n}\n']
 source += [method(name+'::'+name+'()', '\n'.join(ctor)),name+'::~'+name+'() = default;\n}\n']
 emit('kerml/include/'+header,''.join(lines));emit(src,''.join(source))
emit('kerml/KernelSources.cmake',BANNER.replace('//','#')+'target_sources(kerml PRIVATE\n'+''.join('    '+s.removeprefix('kerml/')+'\n' for s in sources)+')\n')
# Representation metadata is also useful to importers and coverage tests.
emit('kerml/include/kerml/model/Representation.h',BANNER+'''#pragma once
#include <kerml/kerml_global.h>
#include <string>
#include <string_view>
#include <vector>
namespace KerML::Entities {
class Element;
struct MetaclassDescriptor { std::string_view name; bool isAbstract; std::size_t declaredPropertyCount; };
struct RepresentationIssue { std::string property; std::string message; };
KERML_EXPORT const std::vector<MetaclassDescriptor>& metaclasses();
// Checks property multiplicities and uniqueness; does not evaluate OCL.
KERML_EXPORT std::vector<RepresentationIssue> validateRepresentation(Element& element, bool includeDerived = false);
}
''')
# Validation calls class-qualified getters, so redefinitions don't hide base APIs.
# Root getter aliases with different historical spelling.
alias={'Type':{'feature':'features','featureMembership':'featureMemberships','inheritedMembership':'inheritedMemberships','ownedConjugator':'conjugation'},'Conjugation':{'conjugatedType':'conjungatedType'},'Intersecting':{'typeIntersected':'typeIntersecting'},'Namespace':{'membership':'memberships','importedMembership':'importedMemberships'},'AnnotatingElement':{'annotatedElement':'annotatedElements','annotation':'annotations','ownedAnnotatingRelationship':'ownedAnnotatingRelationships'}}
validators=[BANNER+'#include <kerml/KerML.h>\n#include <algorithm>\n#include <optional>\n\nnamespace KerML::Entities {\n']
validators += ['const std::vector<MetaclassDescriptor>& metaclasses() {\n    static const std::vector<MetaclassDescriptor> result = {\n'+''.join('        {"'+n['name']+'", '+str(n['abstract']).lower()+', '+str(len(n['properties']))+'},\n' for n in CLASSES)+'    }; return result;\n}\n']
validators+=['''namespace {
template<class T> bool present(const T&) { return true; }
template<class T> bool present(const std::shared_ptr<T>& value) { return bool(value); }
template<class T> bool present(const std::optional<T>& value);
template<class T> bool present(const std::optional<T>& value) { return value && present(*value); }
template<class T> void check(std::vector<RepresentationIssue>& issues, const T& value, const char* path, int lower, int, bool) {
    if (lower > 0 && !present(value)) issues.push_back({path, "Required property is missing"});
}
template<class T> void check(std::vector<RepresentationIssue>& issues, const std::vector<T>& value, const char* path, int lower, int upper, bool unique) {
    if (value.size() < static_cast<std::size_t>(lower) || (upper >= 0 && value.size() > static_cast<std::size_t>(upper))) issues.push_back({path, "Invalid multiplicity"});
    for (std::size_t i=0; i<value.size(); ++i) {
        if (!present(value[i])) issues.push_back({path, "Null entry"});
        if (unique && std::find(value.begin(), value.begin()+i, value[i]) != value.begin()+i) issues.push_back({path, "Duplicate entry"});
    }
}
}
std::vector<RepresentationIssue> validateRepresentation(Element& element, bool includeDerived) {
    std::vector<RepresentationIssue> issues;
''']
inventory=[BANNER+'#include <kerml/KerML.h>\n#include <type_traits>\nusing namespace KerML::Entities;\n']
for n in CLASSES:
 name=n['name']
 inventory+=['static_assert(std::is_convertible_v<'+name+'*, Element*>);\n']
 for b in n['bases']:inventory+=['static_assert(std::is_convertible_v<'+name+'*, '+b+'*>);\n']
 if not n['properties']:continue
 validators+=['    if (auto* value = dynamic_cast<'+name+'*>(&element)) {\n']
 for p in n['properties']:
  prop=alias.get(name,{}).get(p['name'],pn(p))
  inventory+=['static_assert(requires('+name+'& value) { value.'+name+'::'+prop+'(); });\n']
  validators+=['        '+('if (includeDerived) ' if p['derived'] else '')+'check(issues, value->'+name+'::'+prop+'(), "'+name+'.'+p['name']+'", '+str(p['lower'])+', '+str(p['upper'])+', '+str(p['unique']).lower()+');\n']
 validators+=['    }\n']
validators+=['    return issues;\n}\n}\n']
emit('kerml/src/kerml/model/Representation.cpp',''.join(validators))
emit('kerml/tests/Inventory.cpp',''.join(inventory))
args=argparse.ArgumentParser();args.add_argument('--check',action='store_true');a=args.parse_args()
errors=[]
for p,s in OUT.items():
 if a.check:
  if not p.exists() or p.read_text()!=s:errors.append(str(p.relative_to(ROOT)))
 else:p.parent.mkdir(parents=True,exist_ok=True);p.write_text(s)
if errors:raise SystemExit('Stale generated files: '+', '.join(errors))
print(len(CLASSES),'classes,',sum(len(n['properties']) for n in CLASSES),'properties;',len(OUT),'generated files')
