#!/usr/bin/env python3
"""Generates kerml/src/kerml/model/ElementDisposer.cpp and adds `friend struct ElementDisposer;` to the classes of kerml/include
that own other elements through std::shared_ptr members.

The model holds owners, owned elements, relationships and types through shared_ptr in both directions, so every parsed model
is a graph of reference cycles that is never freed by itself. KerML::Entities::disposeLinks(Element&) clears these members of one
element; calling it for all elements of a model breaks the cycles. The script is idempotent: run it again after adding members.
"""
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
INCLUDE = ROOT / "include"
OUT = ROOT / "src/kerml/model/ElementDisposer.cpp"
FRIEND = "        friend struct ::KerML::Entities::ElementDisposer;"
MEMBER = re.compile(r"^\s+(std::vector<std::shared_ptr<[\w:]+>>|std::shared_ptr<[\w:]+>)\s+(\w+)\s*(=\s*[^;(]*)?;\s*(//.*)?$")
CLASS = re.compile(r"^\s*class\s+(?:\w+_EXPORT\s+)?(\w+)\b[^;]*$")


def main():
    entries = []   # (header, qualified class, [(member, isVector)])
    for header in sorted(INCLUDE.rglob("*.h")):
        text = header.read_text()
        generated = text.startswith("// Generated by")   # by generate_abstract_syntax.py, which writes the friend line itself
        lines = text.split("\n")
        namespace = "KerML::Entities"
        out = []
        i = 0
        changed = False
        while i < len(lines):
            line = lines[i]
            m = re.match(r"^\s*namespace\s+([\w:]+)\s*\{", line)
            if m:
                namespace = m.group(1)
            out.append(line)
            c = CLASS.match(line)
            if c and not line.rstrip().endswith(";"):
                # find the opening brace, then the matching closing one
                j = i
                depth = 0
                started = False
                body = []
                while j < len(lines):
                    for ch in lines[j]:
                        if ch == "{":
                            depth += 1
                            started = True
                        elif ch == "}":
                            depth -= 1
                    if j > i:
                        out.append(lines[j])
                    body.append(lines[j])
                    if started and depth == 0:
                        break
                    j += 1
                members = []
                # members at class depth 1 only
                d = 0
                for text in body:
                    if d == 1:
                        mm = MEMBER.match(text)
                        if mm:
                            members.append((mm.group(2), mm.group(1).startswith("std::vector")))
                    d += text.count("{") - text.count("}")
                if members:
                    entries.append((header, namespace + "::" + c.group(1), members))
                if members or generated:
                    # friend declaration: after the line with the opening brace of the class
                    k = len(out) - len(body)
                    while "{" not in out[k]:
                        k += 1
                    friend = "    friend struct ElementDisposer;" if generated else FRIEND
                    if friend not in out[k + 1:k + 3]:
                        out.insert(k + 1, friend)
                        changed = True
                i = j + 1
                continue
            i += 1
        if changed:
            header.write_text("\n".join(out))
    lines = ["// Generated by kerml/tools/generate_dispose.py. Do not edit.", "#include <kerml/KerML.h>", "",
             "namespace KerML::Entities {", "", "struct ElementDisposer {", "    static void dispose(Element& element) {"]
    for header, cls, members in entries:
        lines.append("        if (auto* o = dynamic_cast<%s*>(&element)) {" % cls)
        for name, vec in members:
            lines.append("            o->%s%s;" % (name, ".clear()" if vec else ".reset()"))
        lines.append("        }")
    lines += ["    }", "};", "", "void disposeLinks(Element& element) {", "    ElementDisposer::dispose(element);", "}", "", "}", ""]
    OUT.write_text("\n".join(lines))
    print(len(entries), "classes")


main()
