// Generated by sysml/tools/generate_abstract_syntax.py.
#pragma once
#include <sysml/model/Representation.h>
#include <sysml/model/Forward.h>
#include <sysml/model/KerMLTypes.h>
#include <sysml/actions/ActionDefinition.h>

namespace SysMLv2::Entities {
class SYSML_EXPORT CalculationDefinition : public virtual ActionDefinition, public virtual KerML::Entities::Function, public virtual Representation {
public:
    CalculationDefinition();
    ~CalculationDefinition() override;
    std::string_view metaclassName() const noexcept override;
    std::vector<RepresentationIssue> validateRepresentation(bool includeDerived = false) const override;
    /// Derived snapshot; populated by a semantic evaluator or importer.
    std::vector<std::shared_ptr<CalculationUsage>> calculation() const;
    void setCalculation(std::vector<std::shared_ptr<CalculationUsage>> value);
    void appendCalculation(std::shared_ptr<CalculationUsage> value);
private:
    std::vector<std::shared_ptr<CalculationUsage>> calculation_ = {};
};
}
