// Generated by sysml/tools/generate_abstract_syntax.py.
#pragma once
#include <sysml/model/Representation.h>
#include <sysml/model/Forward.h>
#include <sysml/model/KerMLTypes.h>
#include <sysml/actions/ActionUsage.h>

namespace SysMLv2::Entities {
class SYSML_EXPORT CalculationUsage : public virtual KerML::Entities::Expression, public virtual ActionUsage, public virtual Representation {
public:
    CalculationUsage();
    ~CalculationUsage() override;
    std::string_view metaclassName() const noexcept override;
    std::vector<RepresentationIssue> validateRepresentation(bool includeDerived = false) const override;
    /// Derived snapshot; populated by a semantic evaluator or importer.
    std::shared_ptr<KerML::Entities::Function> calculationDefinition() const;
    void setCalculationDefinition(std::shared_ptr<KerML::Entities::Function> value);
private:
    std::shared_ptr<KerML::Entities::Function> calculationDefinition_ = {};
};
}
