// Generated by sysml/tools/generate_abstract_syntax.py.
#pragma once
#include <sysml/model/Representation.h>
#include <sysml/model/Forward.h>
#include <sysml/model/KerMLTypes.h>
#include <sysml/occurrences/OccurrenceUsage.h>

namespace SysMLv2::Entities {
class SYSML_EXPORT EventOccurrenceUsage : public virtual OccurrenceUsage, public virtual Representation {
public:
    EventOccurrenceUsage();
    ~EventOccurrenceUsage() override;
    std::string_view metaclassName() const noexcept override;
    std::vector<RepresentationIssue> validateRepresentation(bool includeDerived = false) const override;
    /// Derived snapshot; populated by a semantic evaluator or importer.
    std::shared_ptr<OccurrenceUsage> eventOccurrence() const;
    void setEventOccurrence(std::shared_ptr<OccurrenceUsage> value);
    /// Derived snapshot; populated by a semantic evaluator or importer.
    bool isReference() const;
    void setIsReference(bool value);
private:
    std::shared_ptr<OccurrenceUsage> eventOccurrence_ = {};
    bool isReference_ = true;
};
}
