// Generated by sysml/tools/generate_abstract_syntax.py.
#pragma once
#include <sysml/model/Representation.h>
#include <sysml/model/Forward.h>
#include <sysml/model/KerMLTypes.h>
#include <sysml/usage/Usage.h>
#include <sysml/occurrences/PortionKind.h>

namespace SysMLv2::Entities {
class SYSML_EXPORT OccurrenceUsage : public virtual Usage, public virtual Representation {
public:
    OccurrenceUsage();
    ~OccurrenceUsage() override;
    std::string_view metaclassName() const noexcept override;
    std::vector<RepresentationIssue> validateRepresentation(bool includeDerived = false) const override;
    /// Derived snapshot; populated by a semantic evaluator or importer.
    std::vector<std::shared_ptr<KerML::Entities::Class>> occurrenceDefinition() const;
    void setOccurrenceDefinition(std::vector<std::shared_ptr<KerML::Entities::Class>> value);
    void appendOccurrenceDefinition(std::shared_ptr<KerML::Entities::Class> value);
    /// Derived snapshot; populated by a semantic evaluator or importer.
    std::shared_ptr<OccurrenceDefinition> individualDefinition() const;
    void setIndividualDefinition(std::shared_ptr<OccurrenceDefinition> value);
    /// Stored metamodel property.
    bool isIndividual() const;
    void setIsIndividual(bool value);
    /// Stored metamodel property.
    std::optional<PortionKind> portionKind() const;
    void setPortionKind(std::optional<PortionKind> value);
private:
    std::vector<std::shared_ptr<KerML::Entities::Class>> occurrenceDefinition_ = {};
    std::shared_ptr<OccurrenceDefinition> individualDefinition_ = {};
    bool isIndividual_ = false;
    std::optional<PortionKind> portionKind_ = {};
};
}
