// Generated by sysml/tools/generate_abstract_syntax.py.
#pragma once
#include <sysml/model/Representation.h>
#include <sysml/model/Forward.h>
#include <sysml/model/KerMLTypes.h>
#include <sysml/usage/Definition.h>

namespace SysMLv2::Entities {
class SYSML_EXPORT OccurrenceDefinition : public virtual Definition, public virtual KerML::Entities::Class, public virtual Representation {
public:
    OccurrenceDefinition();
    ~OccurrenceDefinition() override;
    std::string_view metaclassName() const noexcept override;
    std::vector<RepresentationIssue> validateRepresentation(bool includeDerived = false) const override;
    /// Stored metamodel property.
    bool isIndividual() const;
    void setIsIndividual(bool value);
private:
    bool isIndividual_ = false;
};
}
