// Generated by sysml/tools/generate_abstract_syntax.py.
#pragma once
#include <sysml/model/Representation.h>
#include <sysml/model/Forward.h>
#include <sysml/model/KerMLTypes.h>
#include <sysml/ports/PortDefinition.h>

namespace SysMLv2::Entities {
class SYSML_EXPORT ConjugatedPortDefinition : public virtual PortDefinition, public virtual Representation {
public:
    ConjugatedPortDefinition();
    ~ConjugatedPortDefinition() override;
    std::string_view metaclassName() const noexcept override;
    std::vector<RepresentationIssue> validateRepresentation(bool includeDerived = false) const override;
    /// Derived snapshot; populated by a semantic evaluator or importer.
    std::shared_ptr<PortDefinition> originalPortDefinition() const;
    void setOriginalPortDefinition(std::shared_ptr<PortDefinition> value);
    /// Derived snapshot; populated by a semantic evaluator or importer.
    std::shared_ptr<PortConjugation> ownedPortConjugator() const;
    void setOwnedPortConjugator(std::shared_ptr<PortConjugation> value);
private:
    std::shared_ptr<PortDefinition> originalPortDefinition_ = {};
    std::shared_ptr<PortConjugation> ownedPortConjugator_ = {};
};
}
