// Generated by sysml/tools/generate_abstract_syntax.py.
#pragma once
#include <sysml/model/Representation.h>
#include <sysml/model/Forward.h>
#include <sysml/model/KerMLTypes.h>

namespace SysMLv2::Entities {
class SYSML_EXPORT PortConjugation : public virtual KerML::Entities::Conjugation, public virtual Representation {
public:
    PortConjugation();
    ~PortConjugation() override;
    std::string_view metaclassName() const noexcept override;
    std::vector<RepresentationIssue> validateRepresentation(bool includeDerived = false) const override;
    /// Stored metamodel property.
    std::shared_ptr<PortDefinition> originalPortDefinition() const;
    void setOriginalPortDefinition(std::shared_ptr<PortDefinition> value);
    /// Derived snapshot; populated by a semantic evaluator or importer.
    std::shared_ptr<ConjugatedPortDefinition> conjugatedPortDefinition() const;
    void setConjugatedPortDefinition(std::shared_ptr<ConjugatedPortDefinition> value);
private:
    std::shared_ptr<PortDefinition> originalPortDefinition_ = {};
    std::shared_ptr<ConjugatedPortDefinition> conjugatedPortDefinition_ = {};
};
}
