// Generated by sysml/tools/generate_abstract_syntax.py.
#pragma once
#include <sysml/model/Representation.h>
#include <sysml/model/Forward.h>
#include <sysml/model/KerMLTypes.h>
#include <sysml/occurrences/OccurrenceDefinition.h>

namespace SysMLv2::Entities {
class SYSML_EXPORT PortDefinition : public virtual KerML::Entities::Structure, public virtual OccurrenceDefinition, public virtual Representation {
public:
    PortDefinition();
    ~PortDefinition() override;
    std::string_view metaclassName() const noexcept override;
    std::vector<RepresentationIssue> validateRepresentation(bool includeDerived = false) const override;
    /// Derived snapshot; populated by a semantic evaluator or importer.
    std::shared_ptr<ConjugatedPortDefinition> conjugatedPortDefinition() const;
    void setConjugatedPortDefinition(std::shared_ptr<ConjugatedPortDefinition> value);
private:
    std::shared_ptr<ConjugatedPortDefinition> conjugatedPortDefinition_ = {};
};
}
