// Generated by kerml/tools/generate_abstract_syntax.py.
#pragma once
#include <kerml/kernel/connectors/Connector.h>
#include <kerml/kernel/behaviors/Step.h>
#include <kerml/model/Forward.h>
#include <kerml/kerml_global.h>
#include <cstdint>
#include <memory>
#include <string>
#include <vector>

namespace KerML::Entities {
class KERML_EXPORT Flow : public virtual Connector, public virtual Step {
public:
    Flow();
    ~Flow() override;
    /// Computed from the underlying representation.
    std::vector<std::shared_ptr<Classifier>> payloadType() const;
    /// Computed from the underlying representation.
    std::shared_ptr<Feature> targetInputFeature() const;
    /// Computed from the underlying representation.
    std::shared_ptr<Feature> sourceOutputFeature() const;
    /// Computed from the underlying representation.
    std::vector<std::shared_ptr<FlowEnd>> flowEnd() const;
    /// Computed from the underlying representation.
    std::shared_ptr<PayloadFeature> payloadFeature() const;
    /// Computed from the underlying representation.
    std::vector<std::shared_ptr<Interaction>> interaction() const;
private:
};
}
