// Generated by kerml/tools/generate_abstract_syntax.py.
#pragma once
#include <kerml/core/features/Feature.h>
#include <kerml/model/Forward.h>
#include <kerml/kerml_global.h>
#include <cstdint>
#include <memory>
#include <string>
#include <vector>

namespace KerML::Entities {
class KERML_EXPORT FlowEnd : public virtual Feature {
public:
    FlowEnd();
    ~FlowEnd() override;
private:
};
}
