// Generated by kerml/tools/generate_abstract_syntax.py.
#pragma once
#include <kerml/kernel/assiciations/Association.h>
#include <kerml/kernel/behaviors/Behavior.h>
#include <kerml/model/Forward.h>
#include <kerml/kerml_global.h>
#include <cstdint>
#include <memory>
#include <string>
#include <vector>

namespace KerML::Entities {
class KERML_EXPORT Interaction : public virtual Association, public virtual Behavior {
public:
    Interaction();
    ~Interaction() override;
private:
};
}
