// Generated by kerml/tools/generate_abstract_syntax.py.
#pragma once
#include <kerml/kernel/connectors/Succession.h>
#include <kerml/kernel/interactions/Flow.h>
#include <kerml/model/Forward.h>
#include <kerml/kerml_global.h>
#include <cstdint>
#include <memory>
#include <string>
#include <vector>

namespace KerML::Entities {
class KERML_EXPORT SuccessionFlow : public virtual Succession, public virtual Flow {
public:
    SuccessionFlow();
    ~SuccessionFlow() override;
private:
};
}
