#!/usr/bin/env python3
"""Generates conformance-test/src/abstractsyntax/TestMetaclassNames.cpp from the model headers.

For every concrete class exported by kerml/include and sysml/include, every public constructor is called with value-initialised
arguments and getType() must return the exact metaclass name (the class name). SysML classes must additionally agree with metaclassName().
Usage: generate_metaclass_name_test.py <repository root> > TestMetaclassNames.cpp
"""
import glob
import os
import re
import sys

root = sys.argv[1] if len(sys.argv) > 1 else '.'
SKIP_TYPES = ('std::function', '&&')


def split_params(text):
    parts, depth, cur = [], 0, ''
    for ch in text:
        if ch in '<([{': depth += 1
        if ch in '>)]}': depth -= 1
        if ch == ',' and depth == 0:
            parts.append(cur); cur = ''
        else:
            cur += ch
    if cur.strip(): parts.append(cur)
    return [p.strip() for p in parts]


def param_type(p):
    p = re.sub(r'=.*$', '', p, flags=re.S).strip()
    p = re.sub(r'\bconst\b', '', p).replace('&', ' ').strip()
    m = re.match(r'^(.*?[>\*\w])\s+(\w+)$', p, flags=re.S)
    builtin = {'bool', 'int', 'long', 'short', 'double', 'float', 'char', 'unsigned', 'size_t', 'signed'}
    if m and not (m.group(2) in builtin):
        # "unsigned int" has no name, "std::string name" does
        head = m.group(1).strip()
        if head.split()[-1] in builtin and m.group(2) in ('int', 'long', 'short', 'char'):
            return p.strip()
        return head
    return p.strip()


def classes_of(path, macro):
    text = open(path, encoding='utf-8-sig', errors='replace').read()
    text = re.sub(r'//[^\n]*', '', text)
    text = re.sub(r'/\*.*?\*/', '', text, flags=re.S)
    found = []
    for m in re.finditer(r'\bclass\s+' + macro + r'\s+(\w+)\s*(?:final\s*)?(?::[^{;]*)?\{', text):
        name = m.group(1)
        i, depth = m.end(), 1
        body_start = i
        while depth and i < len(text):
            if text[i] == '{': depth += 1
            elif text[i] == '}': depth -= 1
            i += 1
        body = text[body_start:i - 1]
        # top level of the class body only
        top, depth = '', 0
        for ch in body:
            if ch == '{':
                depth += 1
                if depth == 1: top += '{'
            elif ch == '}':
                depth -= 1
                if depth == 0: top += '}'
            elif depth == 0:
                top += ch
        access, ctors, abstract = 'private', [], False
        for stmt in re.split(r'(?<=[;}])', top):
            s = stmt.strip()
            am = re.match(r'^((?:public|private|protected)\s*:)', s)
            while am:
                access = am.group(1).split(':')[0].strip()
                s = s[am.end():].strip()
                am = re.match(r'^((?:public|private|protected)\s*:)', s)
            if re.search(r'=\s*0\s*;', s): abstract = True
            cm = re.match(r'^(?:explicit\s+)?' + name + r'\s*\((.*?)\)\s*(?:noexcept\s*)?(?::.*)?(\{\}|\{|;|=\s*default;|=\s*delete;)?$', s, flags=re.S)
            if cm and access == 'public' and '~' not in s[:1] and 'delete' not in (cm.group(2) or ''):
                params = split_params(cm.group(1))
                if not any(any(k in p for k in SKIP_TYPES) for p in params) and not re.match(r'^' + name + r'\s*\(\s*(const\s+)?' + name + r'\s*&', s):
                    ctors.append([param_type(p) for p in params])
        found.append((name, ctors, abstract))
    return found


def header_include(path, base):
    return os.path.relpath(path, base).replace(os.sep, '/')


groups = []
for label, base, macro, ns in (('kerml', 'kerml/include', 'KERML_EXPORT', 'KerML::Entities'), ('sysml', 'sysml/include', 'SYSML_EXPORT', 'SysMLv2::Entities')):
    entries = []
    inc = os.path.join(root, base)
    for h in sorted(glob.glob(inc + '/**/*.h', recursive=True)):
        for name, ctors, abstract in classes_of(h, macro):
            entries.append((header_include(h, inc), name, ctors, abstract))
    groups.append((label, ns, entries))

out = []
out.append('// Generated by conformance-test/tools/generate_metaclass_name_test.py from the model headers. Do not edit by hand.')
out.append('// Every concrete class is instantiated with each of its public constructors; getType() must be the exact metaclass name.')
out.append('#include <gtest/gtest.h>')
out.append('#include <iostream>')
out.append('#include <exception>')
out.append('#include <memory>')
out.append('#include <vector>')
out.append('#include <string>')
out.append('#include <type_traits>')
out.append('#include <boost/uuid/uuid.hpp>')
seen = set()
for label, ns, entries in groups:
    for inc, name, ctors, abstract in entries:
        if inc not in seen:
            seen.add(inc)
            out.append('#include <%s>' % inc)
out.append('')
out.append('namespace {')
out.append('struct Failure { std::string cls; std::string what; };')
out.append('template <class A, bool Sample> struct Arg { static A make() { return A{}; } };')
out.append('template <class U> struct Arg<std::shared_ptr<U>, true> {')
out.append('    static std::shared_ptr<U> make() { if constexpr (std::is_default_constructible_v<U> && !std::is_abstract_v<U>) return std::make_shared<U>(); else return nullptr; }')
out.append('};')
out.append('template <bool Sample> struct Arg<std::string, Sample> { static std::string make() { return Sample ? "00000000-0000-0000-0000-000000000001" : std::string(); } };')
out.append('template <class T, bool Sample, class... Args>')
out.append('void attempt(std::vector<Failure>& failures, const char* expected, unsigned& instantiated, const char* signature) {')
out.append('    T object{Arg<Args, Sample>::make()...};')
out.append('    ++instantiated;')
out.append('    const std::string actual = object.getType();')
out.append('    if (actual != expected) failures.push_back({expected, std::string(signature) + " reports getType() == \\"" + actual + "\\""});')
out.append('    if constexpr (requires { object.metaclassName(); }) {')
out.append('        if (std::string(object.metaclassName()) != expected) failures.push_back({expected, std::string(signature) + " reports metaclassName() == \\"" + std::string(object.metaclassName()) + "\\""});')
out.append('    }')
out.append('}')
out.append('template <class T, class... Args>')
out.append('void check(std::vector<Failure>& failures, const char* expected, unsigned& instantiated, const char* signature, std::vector<std::string>& skipped) {')
out.append('    if constexpr (std::is_abstract_v<T> || !std::is_constructible_v<T, Args...>) { (void)failures; (void)expected; (void)instantiated; (void)signature; (void)skipped; }')
out.append('    else {')
out.append('        try { attempt<T, false, Args...>(failures, expected, instantiated, signature); return; } catch (const std::exception&) {}')
out.append('        try { attempt<T, true, Args...>(failures, expected, instantiated, signature); }')
out.append('        catch (const std::exception& e) { skipped.push_back(std::string(expected) + ": " + signature + " rejects the sample arguments (" + e.what() + ")"); }')
out.append('    }')
out.append('}')
out.append('')
total = 0
for label, ns, entries in groups:
    out.append('void check_%s(std::vector<Failure>& failures, unsigned& instantiated, unsigned& classes, std::vector<std::string>& skipped) {' % label)
    out.append('    using namespace %s;' % ns)
    for inc, name, ctors, abstract in entries:
        if abstract: continue
        out.append('    if constexpr (!std::is_abstract_v<%s>) { ++classes;' % name)
        cs = ctors if ctors else [[]]
        for c in cs:
            args = ''.join(', ' + a for a in c)
            sig = '%s(%s)' % (name, ', '.join(c))
            sig = sig.replace('\\', '\\\\').replace('"', '\\"')
            out.append('        check<%s%s>(failures, "%s", instantiated, "%s", skipped);' % (name, args, name, sig))
            total += 1
        out.append('    }')
    out.append('}')
    out.append('')
out.append('}  // namespace')
out.append('')
out.append('TEST(MetaclassNames, EveryConcreteClassReportsItsExactMetaclassName) {')
out.append('    std::vector<Failure> failures;')
out.append('    unsigned instantiated = 0, classes = 0;')
out.append('    std::vector<std::string> skipped;')
out.append('    check_kerml(failures, instantiated, classes, skipped);')
out.append('    check_sysml(failures, instantiated, classes, skipped);')
out.append('    for (const auto& failure : failures) ADD_FAILURE() << failure.cls << ": " << failure.what;')
out.append('    std::cout << "[  NAMES  ] " << classes << " concrete classes, " << instantiated << " constructors instantiated" << std::endl;')
out.append('    for (const auto& line : skipped) std::cout << "[  NAMES  ] skipped: " << line << std::endl;')
out.append('    EXPECT_GT(classes, 150u);')
out.append('}')
sys.stdout.write('\n'.join(out) + '\n')
