// Generated by kerml/tools/generate_abstract_syntax.py.
#include <kerml/KerML.h>
#include <utility>
#include <stdexcept>
#include "../../model/RepresentationSupport.h"

namespace KerML::Entities {
std::shared_ptr<Feature> FeatureValue::featureWithValue() const {
    return std::dynamic_pointer_cast<Feature>(membershipOwningNamespace());
}

void FeatureValue::setFeatureWithValue(std::shared_ptr<Feature> value) {
    setMembershipOwningNamespace(std::move(value));
}

std::shared_ptr<Expression> FeatureValue::value() const {
    return std::dynamic_pointer_cast<Expression>(ownedMemberElement());
}

void FeatureValue::setValue(std::shared_ptr<Expression> value) {
    setOwnedMemberElement(std::move(value));
}

bool FeatureValue::isInitial() const {
    return isInitial_;
}

void FeatureValue::setIsInitial(bool value) {
    isInitial_ = std::move(value);
}

bool FeatureValue::isDefault() const {
    return isDefault_;
}

void FeatureValue::setIsDefault(bool value) {
    isDefault_ = std::move(value);
}

FeatureValue::FeatureValue() {
    _dType = "FeatureValue";
}

FeatureValue::~FeatureValue() = default;
}
