// Generated by kerml/tools/generate_abstract_syntax.py.
#pragma once
#include <kerml/kernel/connectors/Connector.h>
#include <kerml/model/Forward.h>
#include <kerml/kerml_global.h>
#include <cstdint>
#include <memory>
#include <string>
#include <vector>

namespace KerML::Entities {
class KERML_EXPORT BindingConnector : public virtual Connector {
public:
    BindingConnector();
    ~BindingConnector() override;
private:
};
}
