// Generated by kerml/tools/generate_abstract_syntax.py.
#pragma once
#include <kerml/core/features/Feature.h>
#include <kerml/root/elements/Relationship.h>
#include <kerml/model/Forward.h>
#include <kerml/kerml_global.h>
#include <cstdint>
#include <memory>
#include <string>
#include <vector>

namespace KerML::Entities {
class KERML_EXPORT Connector : public virtual Feature, public virtual Relationship {
public:
    Connector();
    ~Connector() override;
    /// Computed from the underlying representation.
    std::vector<std::shared_ptr<Feature>> relatedFeature() const;
    /// Computed from the underlying representation.
    std::vector<std::shared_ptr<Association>> association() const;
    /// Computed from the underlying representation.
    std::vector<std::shared_ptr<Feature>> connectorEnd() const;
    void setConnectorEnd(std::vector<std::shared_ptr<Feature>> value);
    void appendConnectorEnd(std::shared_ptr<Feature> value);
    /// Computed from the underlying representation.
    std::shared_ptr<Feature> sourceFeature() const;
    /// Computed from the underlying representation.
    std::vector<std::shared_ptr<Feature>> targetFeature() const;
    /// Derived snapshot populated by an importer or semantic evaluator.
    std::shared_ptr<Type> defaultFeaturingType() const;
    void setDefaultFeaturingType(std::shared_ptr<Type> value);
private:
    std::shared_ptr<Type> defaultFeaturingType_ = {};
};
}
