// Generated by kerml/tools/generate_abstract_syntax.py.
#pragma once
#include <kerml/core/classifiers/Classifier.h>
#include <kerml/root/elements/Relationship.h>
#include <kerml/model/Forward.h>
#include <kerml/kerml_global.h>
#include <cstdint>
#include <memory>
#include <string>
#include <vector>

namespace KerML::Entities {
class KERML_EXPORT Association : public virtual Classifier, public virtual Relationship {
public:
    Association();
    ~Association() override;
    /// Computed from the underlying representation.
    std::vector<std::shared_ptr<Type>> relatedType() const;
    /// Computed from the underlying representation.
    std::shared_ptr<Type> sourceType() const;
    /// Computed from the underlying representation.
    std::vector<std::shared_ptr<Type>> targetType() const;
    /// Computed from the underlying representation.
    std::vector<std::shared_ptr<Feature>> associationEnd() const;
    void setAssociationEnd(std::vector<std::shared_ptr<Feature>> value);
    void appendAssociationEnd(std::shared_ptr<Feature> value);
private:
};
}
