// Generated by sysml/tools/generate_abstract_syntax.py.
#include <sysml/parts/PartUsage.h>
#include <sysml/parts/PartDefinition.h>
#include <algorithm>
#include <stdexcept>

namespace SysMLv2::Entities {

std::vector<std::shared_ptr<PartDefinition>> PartUsage::partDefinition() const {
    return partDefinition_;
}

void PartUsage::setPartDefinition(std::vector<std::shared_ptr<PartDefinition>> value) {
    if (std::any_of(value.begin(), value.end(), [](const auto& item) { return !item; })) {
        throw std::invalid_argument("PartUsage.partDefinition: null entry");
    }
    for (std::size_t i = 0; i < value.size(); ++i) {
        if (std::find(value.begin(), value.begin() + i, value[i]) != value.begin() + i) {
            throw std::invalid_argument("PartUsage.partDefinition: duplicate entry");
        }
    }
    partDefinition_ = std::move(value);
}

void PartUsage::appendPartDefinition(std::shared_ptr<PartDefinition> value) {
    auto values = partDefinition();
    values.push_back(std::move(value));
    setPartDefinition(std::move(values));
}

PartUsage::PartUsage() {
    _dType = "PartUsage";
}

PartUsage::~PartUsage() = default;

std::string_view PartUsage::metaclassName() const noexcept {
    return "PartUsage";
}

std::vector<RepresentationIssue> PartUsage::validateRepresentation(bool includeDerived) const {
    std::vector<RepresentationIssue> issues; (void)includeDerived;
    { auto optional = OccurrenceUsage::portionKind(); if (optional) { auto value = *optional; if (!(value == PortionKind::timeslice || value == PortionKind::snapshot)) issues.push_back({"OccurrenceUsage.portionKind", "invalid enumeration value"}); } }
    return issues;
}

} // namespace SysMLv2::Entities
