// Generated by sysml/tools/generate_abstract_syntax.py.
#include <sysml/parts/PartDefinition.h>
#include <algorithm>
#include <stdexcept>

namespace SysMLv2::Entities {

PartDefinition::PartDefinition() {
    _dType = "PartDefinition";
}

PartDefinition::~PartDefinition() = default;

std::string_view PartDefinition::metaclassName() const noexcept {
    return "PartDefinition";
}

std::vector<RepresentationIssue> PartDefinition::validateRepresentation(bool includeDerived) const {
    std::vector<RepresentationIssue> issues; (void)includeDerived;
    return issues;
}

} // namespace SysMLv2::Entities
