// Generated by kerml/tools/generate_abstract_syntax.py.
#include <kerml/KerML.h>
#include <utility>
#include <stdexcept>
#include "../../model/RepresentationSupport.h"

namespace KerML::Entities {
std::shared_ptr<Expression> MultiplicityRange::lowerBound() const {
    auto values = bound(); return values.size() == 2 ? values.front() : nullptr;
}

std::shared_ptr<Expression> MultiplicityRange::upperBound() const {
    auto values = bound(); return values.empty() ? nullptr : values.back();
}

std::vector<std::shared_ptr<Expression>> MultiplicityRange::bound() const {
    return bound_;
}

void MultiplicityRange::setBound(std::vector<std::shared_ptr<Expression>> value) {
    detail::checkCollection(value, true, 2);
    bound_ = std::move(value);
}

void MultiplicityRange::appendBound(std::shared_ptr<Expression> value) {
    auto values = bound(); values.push_back(std::move(value)); setBound(std::move(values));
}

MultiplicityRange::MultiplicityRange() {
    _dType = "MultiplicityRange";
}

MultiplicityRange::~MultiplicityRange() = default;
}
