// Generated by sysml/tools/generate_abstract_syntax.py.
#pragma once
#include <sysml/model/Representation.h>
#include <sysml/model/Forward.h>
#include <sysml/model/KerMLTypes.h>
#include <sysml/connections/ConnectorAsUsage.h>
#include <sysml/actions/ActionUsage.h>

namespace SysMLv2::Entities {
class SYSML_EXPORT FlowUsage : public virtual ConnectorAsUsage, public virtual KerML::Entities::Flow, public virtual ActionUsage, public virtual Representation {
public:
    FlowUsage();
    ~FlowUsage() override;
    std::string_view metaclassName() const noexcept override;
    std::vector<RepresentationIssue> validateRepresentation(bool includeDerived = false) const override;
    /// Derived snapshot; populated by a semantic evaluator or importer.
    std::vector<std::shared_ptr<KerML::Entities::Interaction>> flowDefinition() const;
    void setFlowDefinition(std::vector<std::shared_ptr<KerML::Entities::Interaction>> value);
    void appendFlowDefinition(std::shared_ptr<KerML::Entities::Interaction> value);
private:
    std::vector<std::shared_ptr<KerML::Entities::Interaction>> flowDefinition_ = {};
};
}
