// Generated by sysml/tools/generate_abstract_syntax.py.
#pragma once
#include <sysml/model/Representation.h>
#include <sysml/model/Forward.h>
#include <sysml/model/KerMLTypes.h>
#include <sysml/actions/ActionDefinition.h>

namespace SysMLv2::Entities {
class SYSML_EXPORT FlowDefinition : public virtual ActionDefinition, public virtual KerML::Entities::Interaction, public virtual Representation {
public:
    FlowDefinition();
    ~FlowDefinition() override;
    std::string_view metaclassName() const noexcept override;
    std::vector<RepresentationIssue> validateRepresentation(bool includeDerived = false) const override;
    /// Derived snapshot; populated by a semantic evaluator or importer.
    std::vector<std::shared_ptr<Usage>> flowEnd() const;
    void setFlowEnd(std::vector<std::shared_ptr<Usage>> value);
    void appendFlowEnd(std::shared_ptr<Usage> value);
private:
    std::vector<std::shared_ptr<Usage>> flowEnd_ = {};
};
}
