// Generated by sysml/tools/generate_abstract_syntax.py.
#pragma once
#include <sysml/model/Representation.h>
#include <sysml/model/Forward.h>
#include <sysml/model/KerMLTypes.h>
#include <sysml/flows/FlowUsage.h>

namespace SysMLv2::Entities {
class SYSML_EXPORT SuccessionFlowUsage : public virtual KerML::Entities::SuccessionFlow, public virtual FlowUsage, public virtual Representation {
public:
    SuccessionFlowUsage();
    ~SuccessionFlowUsage() override;
    std::string_view metaclassName() const noexcept override;
    std::vector<RepresentationIssue> validateRepresentation(bool includeDerived = false) const override;
private:
};
}
