
    #include <sysmlv2/sysmlv2file_global.h>


    #include <sysmlv2/sysmlv2file_global.h>


// Generated from filehandling/resources/grammars/SysMLv2.g4 by ANTLR 4.13.2

#pragma once


#include "antlr4-runtime.h"




class SYSMLV2FILE_EXPORT SysMLv2Lexer : public antlr4::Lexer {
public:
  enum {
    KEYWORD_ACCEPT = 1, KEYWORD_ACTION = 2, KEYWORD_ACTOR = 3, KEYWORD_AFTER = 4, 
    KEYWORD_ALIAS = 5, KEYWORD_ALLOCATE = 6, KEYWORD_ALLOCATION = 7, KEYWORD_ANALYSIS = 8, 
    KEYWORD_ASSIGN = 9, KEYWORD_ASSERT = 10, KEYWORD_ASSUME = 11, KEYWORD_AT = 12, 
    KEYWORD_ATTRIBUTE = 13, KEYWORD_BIND = 14, KEYWORD_CALC = 15, KEYWORD_CASE = 16, 
    KEYWORD_CONCERN = 17, KEYWORD_CONNECT = 18, KEYWORD_CONNECTION = 19, 
    KEYWORD_CONSTRAINT = 20, KEYWORD_DECIDE = 21, KEYWORD_DEF = 22, KEYWORD_DEFINED = 23, 
    KEYWORD_DERIVED = 24, KEYWORD_DO = 25, KEYWORD_ENTRY = 26, KEYWORD_ENUM = 27, 
    KEYWORD_EVENT = 28, KEYWORD_EXHIBIT = 29, KEYWORD_EXIT = 30, KEYWORD_EXPOSE = 31, 
    KEYWORD_FORK = 32, KEYWORD_FRAME = 33, KEYWORD_INCLUDE = 34, KEYWORD_INDIVIDUAL = 35, 
    KEYWORD_INTERFACE = 36, KEYWORD_ITEM = 37, KEYWORD_JOIN = 38, KEYWORD_LOOP = 39, 
    KEYWORD_MERGE = 40, KEYWORD_MESSAGE = 41, KEYWORD_NONUNIQUE = 42, KEYWORD_OBJECTIVE = 43, 
    KEYWORD_OCCURRENCE = 44, KEYWORD_PARALLEL = 45, KEYWORD_PART = 46, KEYWORD_PERFORM = 47, 
    KEYWORD_PORT = 48, KEYWORD_REF = 49, KEYWORD_REFERENCES = 50, KEYWORD_RENDER = 51, 
    KEYWORD_RENDERING = 52, KEYWORD_REQUIRE = 53, KEYWORD_REQUIREMENT = 54, 
    KEYWORD_SATISFY = 55, KEYWORD_SEND = 56, KEYWORD_SNAPSHOT = 57, KEYWORD_STAKEHOLDER = 58, 
    KEYWORD_STATE = 59, KEYWORD_SUBJECT = 60, KEYWORD_TERMINATE = 61, KEYWORD_TIMESLICE = 62, 
    KEYWORD_TRANSITION = 63, KEYWORD_UNTIL = 64, KEYWORD_USE = 65, KEYWORD_VARIANT = 66, 
    KEYWORD_VARIATION = 67, KEYWORD_VERIFICATION = 68, KEYWORD_VERIFY = 69, 
    KEYWORD_VIA = 70, KEYWORD_VIEW = 71, KEYWORD_VIEWPOINT = 72, KEYWORD_WHEN = 73, 
    KEYWORD_WHILE = 74, KEYWORD_ABOUT = 75, KEYWORD_ABSTRACT = 76, KEYWORD_ALL = 77, 
    KEYWORD_AND = 78, KEYWORD_AS = 79, KEYWORD_ASSOC = 80, KEYWORD_BEHAVIOR = 81, 
    KEYWORD_BINDING = 82, KEYWORD_BOOL = 83, KEYWORD_BY = 84, KEYWORD_CHAINS = 85, 
    KEYWORD_CLASS = 86, KEYWORD_CLASSIFIER = 87, KEYWORD_COMMENT = 88, KEYWORD_COMPOSITE = 89, 
    KEYWORD_CONJUGATE = 90, KEYWORD_CONJUGATES = 91, KEYWORD_CONJUGATION = 92, 
    KEYWORD_CONNECTOR = 93, KEYWORD_DATATYPE = 94, KEYWORD_DEFAULT = 95, 
    KEYWORD_DEPENDENCY = 96, KEYWORD_DIFFERENCES = 97, KEYWORD_DISJOINING = 98, 
    KEYWORD_DISJOINT = 99, KEYWORD_DOC = 100, KEYWORD_ELSE = 101, KEYWORD_END = 102, 
    KEYWORD_EXPR = 103, KEYWORD_FALSE = 104, KEYWORD_FEATURE = 105, KEYWORD_FEATURED = 106, 
    KEYWORD_FEATURING = 107, KEYWORD_FILTER = 108, KEYWORD_FIRST = 109, 
    KEYWORD_FLOW = 110, KEYWORD_FOR = 111, KEYWORD_FROM = 112, KEYWORD_FUNCTION = 113, 
    KEYWORD_HASTYPE = 114, KEYWORD_IF = 115, KEYWORD_INTERSECTS = 116, KEYWORD_IMPLIES = 117, 
    KEYWORD_IMPORT = 118, KEYWORD_IN = 119, KEYWORD_INOUT = 120, KEYWORD_INTERACTION = 121, 
    KEYWORD_INV = 122, KEYWORD_INVERSE = 123, KEYWORD_INVERTING = 124, KEYWORD_ISTYPE = 125, 
    KEYWORD_LANGUAGE = 126, KEYWORD_MEMBER = 127, KEYWORD_METACLASS = 128, 
    KEYWORD_METADATA = 129, KEYWORD_MULTIPLICITY = 130, KEYWORD_NAMESPACE = 131, 
    KEYWORD_NOT = 132, KEYWORD_NULL = 133, KEYWORD_OF = 134, KEYWORD_OR = 135, 
    KEYWORD_ORDERED = 136, KEYWORD_OUT = 137, KEYWORD_PACKAGE = 138, KEYWORD_PORTION = 139, 
    KEYWORD_PREDICATE = 140, KEYWORD_PRIVATE = 141, KEYWORD_PROTECTED = 142, 
    KEYWORD_PUBLIC = 143, KEYWORD_READONLY = 144, KEYWORD_REDEFINES = 145, 
    KEYWORD_REDEFINITION = 146, KEYWORD_REP = 147, KEYWORD_RETURN = 148, 
    KEYWORD_SPECIALIZATION = 149, KEYWORD_SPECIALIZES = 150, KEYWORD_STEP = 151, 
    KEYWORD_STRUCT = 152, KEYWORD_SUBCLASSIFIER = 153, KEYWORD_SUBSET = 154, 
    KEYWORD_SUBSETS = 155, KEYWORD_SUBTYPE = 156, KEYWORD_SUCCESSION = 157, 
    KEYWORD_THEN = 158, KEYWORD_TO = 159, KEYWORD_TRUE = 160, KEYWORD_TYPE = 161, 
    KEYWORD_TYPED = 162, KEYWORD_TYPING = 163, KEYWORD_UNIONS = 164, KEYWORD_XOR = 165, 
    KEYWORD_VAR = 166, KEYWORD_LOCALE = 167, KEYWORD_STANDARD = 168, KEYWORD_LIBRARY = 169, 
    KEYWORD_CONSTANT = 170, KEYWORD_CROSSES = 171, KEYWORD_META = 172, KEYWORD_NEW = 173, 
    SINGLE_LINE_NOTE = 174, MULTI_LINE_NOTE = 175, REGULAR_COMMENT = 176, 
    SYMBOL_COMMENT_BLOCK_START = 177, SYMBOL_NOTE_BLOCK_START = 178, SYMBOL_COMMENT_BLOCK_END = 179, 
    SYMBOL_STATEMENT_DELIMITER = 180, SYMBOL_STAR = 181, SYMBOL_NAMESPACE_SUBSET = 182, 
    SYMBOL_TYPED_BY = 183, SYMBOL_SPECIALIZES = 184, SYMBOL_REFERENCES = 185, 
    SYMBOL_REDEFINES = 186, SYMBOL_CONJUGATES = 187, SYMBOL_CROSSES = 188, 
    SYMBOL_ROUND_BRACKET_OPEN = 189, SYMBOL_ROUND_BRACKET_CLOSE = 190, SYMBOL_CURLY_BRACKET_OPEN = 191, 
    SYMBOL_CURLY_BRACKET_CLOSE = 192, SYMBOL_SQUARE_BRACKET_OPEN = 193, 
    SYMBOL_SQUARE_BRACKET_CLOSE = 194, SYMBOL_COMMA = 195, SYMBOL_AT = 196, 
    SYMBOL_HASHTAG = 197, SYMBOL_MOD = 198, SYMBOL_AND = 199, SYMBOL_UPPER = 200, 
    SYMBOL_VERTICAL_LINE = 201, SYMBOL_DOUBLE_STAR = 202, SYMBOL_PLUS = 203, 
    SYMBOL_MINUS = 204, SYMBOL_SLASH = 205, SYMBOL_ARROW = 206, SYMBOL_DOT = 207, 
    SYMBOL_DDOT = 208, SYMBOL_SMALLER = 209, SYMBOL_SMALLER_EQUAL = 210, 
    SYMBOL_ASSIGN = 211, SYMBOL_DEF_ASSIGN = 212, SYMBOL_EQUALS = 213, SYMBOL_IFF_EQUALS = 214, 
    SYMBOL_NOT_EQUALS = 215, SYMBOL_IFF_NOT_EQUALS = 216, SYMBOL_GREATER = 217, 
    SYMBOL_GREATER_EQUALS = 218, SYMBOL_QUESTION = 219, SYMBOL_DQUESTION = 220, 
    SYMBOL_DOT_QUESTION = 221, SYMBOL_ATAT = 222, NAME = 223, BASIC_NAME = 224, 
    UNRESTRICTED_NAME = 225, DECIMAL_VALUE = 226, EXPONENTIAL_VALUE = 227, 
    STRING_VALUE = 228, WS = 229
  };

  explicit SysMLv2Lexer(antlr4::CharStream *input);

  ~SysMLv2Lexer() override;


  std::string getGrammarFileName() const override;

  const std::vector<std::string>& getRuleNames() const override;

  const std::vector<std::string>& getChannelNames() const override;

  const std::vector<std::string>& getModeNames() const override;

  const antlr4::dfa::Vocabulary& getVocabulary() const override;

  antlr4::atn::SerializedATNView getSerializedATN() const override;

  const antlr4::atn::ATN& getATN() const override;

  // By default the static state used to implement the lexer is lazily initialized during the first
  // call to the constructor. You can call this function if you wish to initialize the static state
  // ahead of time.
  static void initialize();

private:

  // Individual action functions triggered by action() above.

  // Individual semantic predicate functions triggered by sempred() above.

};

