// Generated by sysml/tools/generate_abstract_syntax.py.
#include <sysml/constraints/AssertConstraintUsage.h>
#include <sysml/constraints/ConstraintUsage.h>
#include <algorithm>
#include <stdexcept>

namespace SysMLv2::Entities {

std::shared_ptr<ConstraintUsage> AssertConstraintUsage::assertedConstraint() const {
    return assertedConstraint_;
}

void AssertConstraintUsage::setAssertedConstraint(std::shared_ptr<ConstraintUsage> value) {
    assertedConstraint_ = std::move(value);
}

AssertConstraintUsage::AssertConstraintUsage() {
    _dType = "AssertConstraintUsage";
}

AssertConstraintUsage::~AssertConstraintUsage() = default;

std::string_view AssertConstraintUsage::metaclassName() const noexcept {
    return "AssertConstraintUsage";
}

std::vector<RepresentationIssue> AssertConstraintUsage::validateRepresentation(bool includeDerived) const {
    std::vector<RepresentationIssue> issues; (void)includeDerived;
    { auto optional = OccurrenceUsage::portionKind(); if (optional) { auto value = *optional; if (!(value == PortionKind::timeslice || value == PortionKind::snapshot)) issues.push_back({"OccurrenceUsage.portionKind", "invalid enumeration value"}); } }
    if (includeDerived) if (!AssertConstraintUsage::assertedConstraint()) issues.push_back({"AssertConstraintUsage.assertedConstraint", "required reference is missing"});
    return issues;
}

} // namespace SysMLv2::Entities
