// Generated by sysml/tools/generate_abstract_syntax.py.
#include <sysml/constraints/ConstraintUsage.h>
#include <algorithm>
#include <stdexcept>

namespace SysMLv2::Entities {

std::shared_ptr<KerML::Entities::Predicate> ConstraintUsage::constraintDefinition() const {
    return constraintDefinition_;
}

void ConstraintUsage::setConstraintDefinition(std::shared_ptr<KerML::Entities::Predicate> value) {
    constraintDefinition_ = std::move(value);
}

ConstraintUsage::ConstraintUsage() {
    _dType = "ConstraintUsage";
}

ConstraintUsage::~ConstraintUsage() = default;

std::string_view ConstraintUsage::metaclassName() const noexcept {
    return "ConstraintUsage";
}

std::vector<RepresentationIssue> ConstraintUsage::validateRepresentation(bool includeDerived) const {
    std::vector<RepresentationIssue> issues; (void)includeDerived;
    { auto optional = OccurrenceUsage::portionKind(); if (optional) { auto value = *optional; if (!(value == PortionKind::timeslice || value == PortionKind::snapshot)) issues.push_back({"OccurrenceUsage.portionKind", "invalid enumeration value"}); } }
    return issues;
}

} // namespace SysMLv2::Entities
