// Generated by sysml/tools/generate_abstract_syntax.py.
#include <sysml/constraints/ConstraintDefinition.h>
#include <algorithm>
#include <stdexcept>

namespace SysMLv2::Entities {

ConstraintDefinition::ConstraintDefinition() {
    _dType = "ConstraintDefinition";
}

ConstraintDefinition::~ConstraintDefinition() = default;

std::string_view ConstraintDefinition::metaclassName() const noexcept {
    return "ConstraintDefinition";
}

std::vector<RepresentationIssue> ConstraintDefinition::validateRepresentation(bool includeDerived) const {
    std::vector<RepresentationIssue> issues; (void)includeDerived;
    return issues;
}

} // namespace SysMLv2::Entities
