// Generated by sysml/tools/generate_abstract_syntax.py.
#include <sysml/views/Expose.h>
#include <algorithm>
#include <stdexcept>

namespace SysMLv2::Entities {

KerML::Entities::VisibilityKind Expose::visibility() const {
    return const_cast<Expose*>(this)->KerML::Entities::Import::visibility();
}

void Expose::setVisibility(KerML::Entities::VisibilityKind value) {
    KerML::Entities::Import::setVisibility(value);
}

bool Expose::isImportAll() const {
    return const_cast<Expose*>(this)->KerML::Entities::Import::isImportAll();
}

void Expose::setIsImportAll(bool value) {
    KerML::Entities::Import::setIsImportAll(value);
}

Expose::Expose() {
    KerML::Entities::Import::setVisibility(KerML::Entities::VisibilityKind::PROTECTED);
    KerML::Entities::Import::setIsImportAll(true);
    _dType = "Expose";
}

Expose::~Expose() = default;

std::vector<RepresentationIssue> Expose::validateRepresentation(bool includeDerived) const {
    std::vector<RepresentationIssue> issues; (void)includeDerived;
    { auto value = Expose::visibility(); if (!(value == KerML::Entities::VisibilityKind::PRIVATE || value == KerML::Entities::VisibilityKind::PROTECTED || value == KerML::Entities::VisibilityKind::PUBLIC)) issues.push_back({"Expose.visibility", "invalid enumeration value"}); }
    return issues;
}

} // namespace SysMLv2::Entities
