// Generated by sysml/tools/generate_abstract_syntax.py.
#include <sysml/views/MembershipExpose.h>
#include <algorithm>
#include <stdexcept>

namespace SysMLv2::Entities {

MembershipExpose::MembershipExpose() {
    _dType = "MembershipExpose";
}

MembershipExpose::~MembershipExpose() = default;

std::string_view MembershipExpose::metaclassName() const noexcept {
    return "MembershipExpose";
}

std::vector<RepresentationIssue> MembershipExpose::validateRepresentation(bool includeDerived) const {
    std::vector<RepresentationIssue> issues; (void)includeDerived;
    { auto value = Expose::visibility(); if (!(value == KerML::Entities::VisibilityKind::PRIVATE || value == KerML::Entities::VisibilityKind::PROTECTED || value == KerML::Entities::VisibilityKind::PUBLIC)) issues.push_back({"Expose.visibility", "invalid enumeration value"}); }
    return issues;
}

} // namespace SysMLv2::Entities
