// Generated by sysml/tools/generate_abstract_syntax.py.
#include <sysml/views/NamespaceExpose.h>
#include <algorithm>
#include <stdexcept>

namespace SysMLv2::Entities {

NamespaceExpose::NamespaceExpose() {
    _dType = "NamespaceExpose";
}

NamespaceExpose::~NamespaceExpose() = default;

std::string_view NamespaceExpose::metaclassName() const noexcept {
    return "NamespaceExpose";
}

std::vector<RepresentationIssue> NamespaceExpose::validateRepresentation(bool includeDerived) const {
    std::vector<RepresentationIssue> issues; (void)includeDerived;
    { auto value = Expose::visibility(); if (!(value == KerML::Entities::VisibilityKind::PRIVATE || value == KerML::Entities::VisibilityKind::PROTECTED || value == KerML::Entities::VisibilityKind::PUBLIC)) issues.push_back({"Expose.visibility", "invalid enumeration value"}); }
    return issues;
}

} // namespace SysMLv2::Entities
