// Generated by sysml/tools/generate_abstract_syntax.py.
#include <sysml/views/RenderingUsage.h>
#include <sysml/views/RenderingDefinition.h>
#include <algorithm>
#include <stdexcept>

namespace SysMLv2::Entities {

std::shared_ptr<RenderingDefinition> RenderingUsage::renderingDefinition() const {
    return renderingDefinition_;
}

void RenderingUsage::setRenderingDefinition(std::shared_ptr<RenderingDefinition> value) {
    renderingDefinition_ = std::move(value);
}

RenderingUsage::RenderingUsage() {
    _dType = "RenderingUsage";
}

RenderingUsage::~RenderingUsage() = default;

std::string_view RenderingUsage::metaclassName() const noexcept {
    return "RenderingUsage";
}

std::vector<RepresentationIssue> RenderingUsage::validateRepresentation(bool includeDerived) const {
    std::vector<RepresentationIssue> issues; (void)includeDerived;
    { auto optional = OccurrenceUsage::portionKind(); if (optional) { auto value = *optional; if (!(value == PortionKind::timeslice || value == PortionKind::snapshot)) issues.push_back({"OccurrenceUsage.portionKind", "invalid enumeration value"}); } }
    return issues;
}

} // namespace SysMLv2::Entities
