// Generated by sysml/tools/generate_abstract_syntax.py.
#include <sysml/views/RenderingDefinition.h>
#include <sysml/views/RenderingUsage.h>
#include <algorithm>
#include <stdexcept>

namespace SysMLv2::Entities {

std::vector<std::shared_ptr<RenderingUsage>> RenderingDefinition::rendering() const {
    return rendering_;
}

void RenderingDefinition::setRendering(std::vector<std::shared_ptr<RenderingUsage>> value) {
    if (std::any_of(value.begin(), value.end(), [](const auto& item) { return !item; })) {
        throw std::invalid_argument("RenderingDefinition.rendering: null entry");
    }
    for (std::size_t i = 0; i < value.size(); ++i) {
        if (std::find(value.begin(), value.begin() + i, value[i]) != value.begin() + i) {
            throw std::invalid_argument("RenderingDefinition.rendering: duplicate entry");
        }
    }
    rendering_ = std::move(value);
}

void RenderingDefinition::appendRendering(std::shared_ptr<RenderingUsage> value) {
    auto values = rendering();
    values.push_back(std::move(value));
    setRendering(std::move(values));
}

RenderingDefinition::RenderingDefinition() {
    _dType = "RenderingDefinition";
}

RenderingDefinition::~RenderingDefinition() = default;

std::string_view RenderingDefinition::metaclassName() const noexcept {
    return "RenderingDefinition";
}

std::vector<RepresentationIssue> RenderingDefinition::validateRepresentation(bool includeDerived) const {
    std::vector<RepresentationIssue> issues; (void)includeDerived;
    return issues;
}

} // namespace SysMLv2::Entities
