// Generated by sysml/tools/generate_abstract_syntax.py.
#include <sysml/views/ViewpointUsage.h>
#include <sysml/views/ViewpointDefinition.h>
#include <sysml/parts/PartUsage.h>
#include <algorithm>
#include <stdexcept>

namespace SysMLv2::Entities {

std::shared_ptr<ViewpointDefinition> ViewpointUsage::viewpointDefinition() const {
    return viewpointDefinition_;
}

void ViewpointUsage::setViewpointDefinition(std::shared_ptr<ViewpointDefinition> value) {
    viewpointDefinition_ = std::move(value);
}

std::vector<std::shared_ptr<PartUsage>> ViewpointUsage::viewpointStakeholder() const {
    return viewpointStakeholder_;
}

void ViewpointUsage::setViewpointStakeholder(std::vector<std::shared_ptr<PartUsage>> value) {
    if (std::any_of(value.begin(), value.end(), [](const auto& item) { return !item; })) {
        throw std::invalid_argument("ViewpointUsage.viewpointStakeholder: null entry");
    }
    for (std::size_t i = 0; i < value.size(); ++i) {
        if (std::find(value.begin(), value.begin() + i, value[i]) != value.begin() + i) {
            throw std::invalid_argument("ViewpointUsage.viewpointStakeholder: duplicate entry");
        }
    }
    viewpointStakeholder_ = std::move(value);
}

void ViewpointUsage::appendViewpointStakeholder(std::shared_ptr<PartUsage> value) {
    auto values = viewpointStakeholder();
    values.push_back(std::move(value));
    setViewpointStakeholder(std::move(values));
}

ViewpointUsage::ViewpointUsage() {
    _dType = "ViewpointUsage";
}

ViewpointUsage::~ViewpointUsage() = default;

std::string_view ViewpointUsage::metaclassName() const noexcept {
    return "ViewpointUsage";
}

std::vector<RepresentationIssue> ViewpointUsage::validateRepresentation(bool includeDerived) const {
    std::vector<RepresentationIssue> issues; (void)includeDerived;
    { auto optional = OccurrenceUsage::portionKind(); if (optional) { auto value = *optional; if (!(value == PortionKind::timeslice || value == PortionKind::snapshot)) issues.push_back({"OccurrenceUsage.portionKind", "invalid enumeration value"}); } }
    if (includeDerived) if (!RequirementUsage::subjectParameter()) issues.push_back({"RequirementUsage.subjectParameter", "required reference is missing"});
    return issues;
}

} // namespace SysMLv2::Entities
