// Generated by sysml/tools/generate_abstract_syntax.py.
#include <sysml/views/ViewDefinition.h>
#include <sysml/views/ViewUsage.h>
#include <sysml/views/ViewpointUsage.h>
#include <sysml/views/RenderingUsage.h>
#include <algorithm>
#include <stdexcept>

namespace SysMLv2::Entities {

std::vector<std::shared_ptr<ViewUsage>> ViewDefinition::view() const {
    return view_;
}

void ViewDefinition::setView(std::vector<std::shared_ptr<ViewUsage>> value) {
    if (std::any_of(value.begin(), value.end(), [](const auto& item) { return !item; })) {
        throw std::invalid_argument("ViewDefinition.view: null entry");
    }
    for (std::size_t i = 0; i < value.size(); ++i) {
        if (std::find(value.begin(), value.begin() + i, value[i]) != value.begin() + i) {
            throw std::invalid_argument("ViewDefinition.view: duplicate entry");
        }
    }
    view_ = std::move(value);
}

void ViewDefinition::appendView(std::shared_ptr<ViewUsage> value) {
    auto values = view();
    values.push_back(std::move(value));
    setView(std::move(values));
}

std::vector<std::shared_ptr<ViewpointUsage>> ViewDefinition::satisfiedViewpoint() const {
    return satisfiedViewpoint_;
}

void ViewDefinition::setSatisfiedViewpoint(std::vector<std::shared_ptr<ViewpointUsage>> value) {
    if (std::any_of(value.begin(), value.end(), [](const auto& item) { return !item; })) {
        throw std::invalid_argument("ViewDefinition.satisfiedViewpoint: null entry");
    }
    for (std::size_t i = 0; i < value.size(); ++i) {
        if (std::find(value.begin(), value.begin() + i, value[i]) != value.begin() + i) {
            throw std::invalid_argument("ViewDefinition.satisfiedViewpoint: duplicate entry");
        }
    }
    satisfiedViewpoint_ = std::move(value);
}

void ViewDefinition::appendSatisfiedViewpoint(std::shared_ptr<ViewpointUsage> value) {
    auto values = satisfiedViewpoint();
    values.push_back(std::move(value));
    setSatisfiedViewpoint(std::move(values));
}

std::shared_ptr<RenderingUsage> ViewDefinition::viewRendering() const {
    return viewRendering_;
}

void ViewDefinition::setViewRendering(std::shared_ptr<RenderingUsage> value) {
    viewRendering_ = std::move(value);
}

std::vector<std::shared_ptr<KerML::Entities::Expression>> ViewDefinition::viewCondition() const {
    return viewCondition_;
}

void ViewDefinition::setViewCondition(std::vector<std::shared_ptr<KerML::Entities::Expression>> value) {
    if (std::any_of(value.begin(), value.end(), [](const auto& item) { return !item; })) {
        throw std::invalid_argument("ViewDefinition.viewCondition: null entry");
    }
    for (std::size_t i = 0; i < value.size(); ++i) {
        if (std::find(value.begin(), value.begin() + i, value[i]) != value.begin() + i) {
            throw std::invalid_argument("ViewDefinition.viewCondition: duplicate entry");
        }
    }
    viewCondition_ = std::move(value);
}

void ViewDefinition::appendViewCondition(std::shared_ptr<KerML::Entities::Expression> value) {
    auto values = viewCondition();
    values.push_back(std::move(value));
    setViewCondition(std::move(values));
}

ViewDefinition::ViewDefinition() {
    _dType = "ViewDefinition";
}

ViewDefinition::~ViewDefinition() = default;

std::string_view ViewDefinition::metaclassName() const noexcept {
    return "ViewDefinition";
}

std::vector<RepresentationIssue> ViewDefinition::validateRepresentation(bool includeDerived) const {
    std::vector<RepresentationIssue> issues; (void)includeDerived;
    return issues;
}

} // namespace SysMLv2::Entities
