// Generated by sysml/tools/generate_abstract_syntax.py.
#include <sysml/views/ViewRenderingMembership.h>
#include <sysml/views/RenderingUsage.h>
#include <algorithm>
#include <stdexcept>

namespace SysMLv2::Entities {

std::shared_ptr<RenderingUsage> ViewRenderingMembership::ownedRendering() const {
    return ownedRendering_;
}

void ViewRenderingMembership::setOwnedRendering(std::shared_ptr<RenderingUsage> value) {
    ownedRendering_ = std::move(value);
}

std::shared_ptr<RenderingUsage> ViewRenderingMembership::referencedRendering() const {
    return referencedRendering_;
}

void ViewRenderingMembership::setReferencedRendering(std::shared_ptr<RenderingUsage> value) {
    referencedRendering_ = std::move(value);
}

ViewRenderingMembership::ViewRenderingMembership() {
    _dType = "ViewRenderingMembership";
}

ViewRenderingMembership::~ViewRenderingMembership() = default;

std::string_view ViewRenderingMembership::metaclassName() const noexcept {
    return "ViewRenderingMembership";
}

std::vector<RepresentationIssue> ViewRenderingMembership::validateRepresentation(bool includeDerived) const {
    std::vector<RepresentationIssue> issues; (void)includeDerived;
    if (includeDerived) if (!ViewRenderingMembership::ownedRendering()) issues.push_back({"ViewRenderingMembership.ownedRendering", "required reference is missing"});
    if (includeDerived) if (!ViewRenderingMembership::referencedRendering()) issues.push_back({"ViewRenderingMembership.referencedRendering", "required reference is missing"});
    return issues;
}

} // namespace SysMLv2::Entities
