// Generated by sysml/tools/generate_abstract_syntax.py.
#include <sysml/views/ViewpointDefinition.h>
#include <sysml/parts/PartUsage.h>
#include <algorithm>
#include <stdexcept>

namespace SysMLv2::Entities {

std::vector<std::shared_ptr<PartUsage>> ViewpointDefinition::viewpointStakeholder() const {
    return viewpointStakeholder_;
}

void ViewpointDefinition::setViewpointStakeholder(std::vector<std::shared_ptr<PartUsage>> value) {
    if (std::any_of(value.begin(), value.end(), [](const auto& item) { return !item; })) {
        throw std::invalid_argument("ViewpointDefinition.viewpointStakeholder: null entry");
    }
    for (std::size_t i = 0; i < value.size(); ++i) {
        if (std::find(value.begin(), value.begin() + i, value[i]) != value.begin() + i) {
            throw std::invalid_argument("ViewpointDefinition.viewpointStakeholder: duplicate entry");
        }
    }
    viewpointStakeholder_ = std::move(value);
}

void ViewpointDefinition::appendViewpointStakeholder(std::shared_ptr<PartUsage> value) {
    auto values = viewpointStakeholder();
    values.push_back(std::move(value));
    setViewpointStakeholder(std::move(values));
}

ViewpointDefinition::ViewpointDefinition() {
    _dType = "ViewpointDefinition";
}

ViewpointDefinition::~ViewpointDefinition() = default;

std::string_view ViewpointDefinition::metaclassName() const noexcept {
    return "ViewpointDefinition";
}

std::vector<RepresentationIssue> ViewpointDefinition::validateRepresentation(bool includeDerived) const {
    std::vector<RepresentationIssue> issues; (void)includeDerived;
    if (includeDerived) if (!RequirementDefinition::subjectParameter()) issues.push_back({"RequirementDefinition.subjectParameter", "required reference is missing"});
    return issues;
}

} // namespace SysMLv2::Entities
