// Generated by sysml/tools/generate_abstract_syntax.py.
#include <sysml/views/ViewUsage.h>
#include <sysml/views/ViewDefinition.h>
#include <sysml/views/ViewpointUsage.h>
#include <sysml/views/RenderingUsage.h>
#include <algorithm>
#include <stdexcept>

namespace SysMLv2::Entities {

std::shared_ptr<ViewDefinition> ViewUsage::viewDefinition() const {
    return viewDefinition_;
}

void ViewUsage::setViewDefinition(std::shared_ptr<ViewDefinition> value) {
    viewDefinition_ = std::move(value);
}

std::vector<std::shared_ptr<ViewpointUsage>> ViewUsage::satisfiedViewpoint() const {
    return satisfiedViewpoint_;
}

void ViewUsage::setSatisfiedViewpoint(std::vector<std::shared_ptr<ViewpointUsage>> value) {
    if (std::any_of(value.begin(), value.end(), [](const auto& item) { return !item; })) {
        throw std::invalid_argument("ViewUsage.satisfiedViewpoint: null entry");
    }
    for (std::size_t i = 0; i < value.size(); ++i) {
        if (std::find(value.begin(), value.begin() + i, value[i]) != value.begin() + i) {
            throw std::invalid_argument("ViewUsage.satisfiedViewpoint: duplicate entry");
        }
    }
    satisfiedViewpoint_ = std::move(value);
}

void ViewUsage::appendSatisfiedViewpoint(std::shared_ptr<ViewpointUsage> value) {
    auto values = satisfiedViewpoint();
    values.push_back(std::move(value));
    setSatisfiedViewpoint(std::move(values));
}

std::vector<std::shared_ptr<KerML::Entities::Element>> ViewUsage::exposedElement() const {
    return exposedElement_;
}

void ViewUsage::setExposedElement(std::vector<std::shared_ptr<KerML::Entities::Element>> value) {
    if (std::any_of(value.begin(), value.end(), [](const auto& item) { return !item; })) {
        throw std::invalid_argument("ViewUsage.exposedElement: null entry");
    }
    for (std::size_t i = 0; i < value.size(); ++i) {
        if (std::find(value.begin(), value.begin() + i, value[i]) != value.begin() + i) {
            throw std::invalid_argument("ViewUsage.exposedElement: duplicate entry");
        }
    }
    exposedElement_ = std::move(value);
}

void ViewUsage::appendExposedElement(std::shared_ptr<KerML::Entities::Element> value) {
    auto values = exposedElement();
    values.push_back(std::move(value));
    setExposedElement(std::move(values));
}

std::shared_ptr<RenderingUsage> ViewUsage::viewRendering() const {
    return viewRendering_;
}

void ViewUsage::setViewRendering(std::shared_ptr<RenderingUsage> value) {
    viewRendering_ = std::move(value);
}

std::vector<std::shared_ptr<KerML::Entities::Expression>> ViewUsage::viewCondition() const {
    return viewCondition_;
}

void ViewUsage::setViewCondition(std::vector<std::shared_ptr<KerML::Entities::Expression>> value) {
    if (std::any_of(value.begin(), value.end(), [](const auto& item) { return !item; })) {
        throw std::invalid_argument("ViewUsage.viewCondition: null entry");
    }
    for (std::size_t i = 0; i < value.size(); ++i) {
        if (std::find(value.begin(), value.begin() + i, value[i]) != value.begin() + i) {
            throw std::invalid_argument("ViewUsage.viewCondition: duplicate entry");
        }
    }
    viewCondition_ = std::move(value);
}

void ViewUsage::appendViewCondition(std::shared_ptr<KerML::Entities::Expression> value) {
    auto values = viewCondition();
    values.push_back(std::move(value));
    setViewCondition(std::move(values));
}

ViewUsage::ViewUsage() {
    _dType = "ViewUsage";
}

ViewUsage::~ViewUsage() = default;

std::string_view ViewUsage::metaclassName() const noexcept {
    return "ViewUsage";
}

std::vector<RepresentationIssue> ViewUsage::validateRepresentation(bool includeDerived) const {
    std::vector<RepresentationIssue> issues; (void)includeDerived;
    { auto optional = OccurrenceUsage::portionKind(); if (optional) { auto value = *optional; if (!(value == PortionKind::timeslice || value == PortionKind::snapshot)) issues.push_back({"OccurrenceUsage.portionKind", "invalid enumeration value"}); } }
    return issues;
}

} // namespace SysMLv2::Entities
