#!/usr/bin/env python3
"""Generate the C++ representation from the checked-in OMG type manifest.

No network access is needed. Run from any directory; --check verifies freshness.
Derived properties are explicit snapshots unless handled by computed() below.
Each class is implemented in its own source file, mirroring the header tree.
"""
import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
MODEL = json.loads((ROOT / 'sysml/model/abstract_syntax.json').read_text())
TYPES = {n['id']: n for n in MODEL['types']}
CLASSES = [n for n in TYPES.values() if n['kind'] == 'Class']
ENUMS = [n for n in TYPES.values() if n['kind'] == 'Enumeration']
OUTPUTS = {}

def emit(path, text):
    OUTPUTS[ROOT / path] = text

def literal(value):
    return value + '_' if value in ('do', 'if', 'else', 'while', 'for', 'return') else value

def header(n):
    return 'sysml/' + n['package'] + '/' + n['name'] + '.h'

def external_path(ref):
    name = ref.split('-')[-1]
    matches = sorted((ROOT / 'kerml/include').rglob(name + '.h'))
    canonical = ROOT / 'kerml/include' / ('/'.join(s.lower() for s in ref.split('-')[:-1])) / (name + '.h')
    path = canonical if canonical.exists() else matches[-1]
    return path.relative_to(ROOT / 'kerml/include').as_posix()

def cpp(ref):
    if ref == 'Boolean': return 'bool'
    if ref == 'String': return 'std::string'
    if ref == 'Integer': return 'std::int64_t'
    return ('' if ref in TYPES else 'KerML::Entities::') + ref.split('-')[-1]

def is_enum(p):
    return p['type'] in TYPES and TYPES[p['type']]['kind'] == 'Enumeration' or p['type'].endswith('VisibilityKind')

def is_ref(p):
    return p['type'] not in ('Boolean', 'Integer', 'String') and not is_enum(p)

def value_type(p):
    t = cpp(p['type'])
    if is_ref(p): t = 'std::shared_ptr<' + t + '>'
    return t

def property_type(p):
    t = value_type(p)
    if p['upper'] != 1: return 'std::vector<' + t + '>'
    if p['lower'] == 0 and not is_ref(p): return 'std::optional<' + t + '>'
    return t

def default(p):
    if p.get('default'):
        d=p['default']
        if p['type']=='Boolean': return d
        if is_enum(p): return cpp(p['type']) + '::' + (d.upper() if p['type'].endswith('VisibilityKind') else d)
    return '{}'

def ancestors(n):
    result=[]
    for b in n['bases']:
        if b in TYPES:
            for a in ancestors(TYPES[b]) + [TYPES[b]]:
                if a not in result: result.append(a)
    return result

# Canonical derivations backed by the existing KerML graph, not duplicate storage.
def computed(n, p):
    name=n['name']; prop=p['name']
    if name in ('Usage','ReferenceUsage') and prop=='isReference':
        return 'return !const_cast<' + name + '*>(this)->KerML::Entities::Feature::isComposite();'
    if name in ('Definition','Usage') and (prop.startswith('owned') or prop.startswith('nested')) and is_ref(p):
        return 'return detail::select<' + cpp(p['type']) + '>(KerML::Entities::Type::ownedFeature());'
    if name in ('Definition','Usage') and prop in ('usage', 'directedUsage'):
        method = 'features' if prop == 'usage' else 'directedFeature'
        return 'return detail::select<Usage>(KerML::Entities::Type::' + method + '());'
    if name=='Usage' and prop in ('owningDefinition', 'owningUsage'):
        return 'auto owner = KerML::Entities::Feature::owningType(); return owner ? std::dynamic_pointer_cast<' + cpp(p['type']) + '>(*owner) : nullptr;'
    if name=='Usage' and prop=='definition':
        return 'return detail::select<KerML::Entities::Classifier>(KerML::Entities::Feature::type());'
    if name in ('Definition','Usage') and prop=='variantMembership':
        return 'return detail::select<VariantMembership>(KerML::Entities::Namespace::ownedMembership());'
    if name in ('Definition','Usage') and prop=='variant':
        return 'std::vector<std::shared_ptr<Usage>> result; for (const auto& membership : variantMembership()) { if (auto value = membership->ownedVariantUsage()) result.push_back(value); } return result;'
    if name=='Expose':
        return 'return const_cast<Expose*>(this)->KerML::Entities::Import::' + prop + '();'
    return None

external = sorted({r for n in CLASSES for r in n['bases'] + [p['type'] for p in n['properties']] if r not in TYPES and r not in ('Boolean','String','Integer')})
emit('sysml/include/sysml/model/KerMLTypes.h', '#pragma once\n' + ''.join('#include <'+external_path(r)+'>\n' for r in external))
emit('sysml/include/sysml/model/Forward.h', '#pragma once\nnamespace SysMLv2::Entities {\n' + ''.join('class '+n['name']+';\n' for n in CLASSES) + '}\n')
for n in ENUMS:
    emit('sysml/include/'+header(n), '#pragma once\n\nnamespace SysMLv2::Entities {\nenum class '+n['name']+' { '+', '.join(literal(v) for v in n['literals'])+' };\n}\n')

BANNER = '// Generated by sysml/tools/generate_abstract_syntax.py.\n'

def method(signature, body):
    return signature + ' {\n' + ''.join('    ' + line + '\n' for line in body.splitlines()) + '}\n\n'

emit('sysml/src/sysml/model/RepresentationSupport.h', BANNER + """#pragma once

#include <memory>
#include <utility>
#include <vector>

namespace SysMLv2::Entities::detail {
template<class T, class U>
std::vector<std::shared_ptr<T>> select(const std::vector<std::shared_ptr<U>>& values) {
    std::vector<std::shared_ptr<T>> result;
    for (const auto& value : values) {
        if (auto typed = std::dynamic_pointer_cast<T>(value)) {
            result.push_back(std::move(typed));
        }
    }
    return result;
}
} // namespace SysMLv2::Entities::detail
""")
source_paths = ['src/sysml/AbstractSyntax.cpp']
for n in CLASSES:
    name=n['name']
    source_includes = [header(n)]
    # Dynamic casts and reference operations need complete related class types.
    source_includes += [header(TYPES[p['type']]) for p in n['properties'] if p['type'] in TYPES]
    source = [BANNER]
    source += ['#include <'+i+'>\n' for i in dict.fromkeys(source_includes)]
    if any('detail::select<' in (computed(n, p) or '') for p in n['properties']):
        source += ['#include "../model/RepresentationSupport.h"\n']
    source += ['#include <algorithm>\n#include <stdexcept>\n\nnamespace SysMLv2::Entities {\n\n']
    bases=[cpp(b) for b in n['bases']]
    includes=['sysml/model/Representation.h','sysml/model/Forward.h','sysml/model/KerMLTypes.h']
    includes += [header(TYPES[b]) for b in n['bases'] if b in TYPES]
    includes += [header(TYPES[p['type']]) for p in n['properties'] if p['type'] in TYPES and is_enum(p)]
    lines=['// Generated by sysml/tools/generate_abstract_syntax.py.\n#pragma once\n']
    lines += ['#include <'+i+'>\n' for i in dict.fromkeys(includes)]
    lines += ['\nnamespace SysMLv2::Entities {\nclass SYSML_EXPORT '+name+' : '+', '.join('public virtual '+b for b in bases+['Representation'])+' {\npublic:\n', '    '+name+'();\n    ~'+name+'() override;\n']
    lines += ['    std::string_view metaclassName() const noexcept override'+(' = 0;\n' if n['abstract'] else ';\n')]
    lines += ['    std::vector<RepresentationIssue> validateRepresentation(bool includeDerived = false) const override;\n']
    members=[]
    ctor=[]
    for p in n['properties']:
        prop=p['name']; t=property_type(p); cap=prop[0].upper()+prop[1:]; body=computed(n,p)
        lines += ['    /// '+('Derived view.' if body and n['name']!='Expose' else 'Derived snapshot; populated by a semantic evaluator or importer.' if p['derived'] else 'Stored metamodel property.')+'\n', '    '+t+' '+prop+'() const;\n']
        source += [method(t+' '+name+'::'+prop+'() const', body or 'return '+prop+'_;')]
        if not body or name=='Expose':
            lines += ['    void set'+cap+'('+t+' value);\n']
            setter=''
            if name=='Expose':
                setter='KerML::Entities::Import::set'+cap+'(value);'
                ctor+=['KerML::Entities::Import::set'+cap+'('+default(p)+');']
            else:
                if p['upper'] != 1:
                    if is_ref(p):
                        setter += ('if (std::any_of(value.begin(), value.end(), [](const auto& item) { return !item; })) {\n'
                                   '    throw std::invalid_argument("'+name+'.'+prop+': null entry");\n'
                                   '}\n')
                    if p['unique']:
                        setter += ('for (std::size_t i = 0; i < value.size(); ++i) {\n'
                                   '    if (std::find(value.begin(), value.begin() + i, value[i]) != value.begin() + i) {\n'
                                   '        throw std::invalid_argument("'+name+'.'+prop+': duplicate entry");\n'
                                   '    }\n'
                                   '}\n')
                setter+=prop+'_ = std::move(value);'
                members+=['    '+t+' '+prop+'_ = '+default(p)+';\n']
            source += [method('void '+name+'::set'+cap+'('+t+' value)', setter)]
            if p['upper'] != 1:
                lines+=['    void append'+cap+'('+value_type(p)+' value);\n']
                source += [method('void '+name+'::append'+cap+'('+value_type(p)+' value)', 'auto values = '+prop+'();\nvalues.push_back(std::move(value));\nset'+cap+'(std::move(values));')]
    lines+=['private:\n']+members+['};\n}\n']
    emit('sysml/include/'+header(n), ''.join(lines))
    ctor += ['_dType = "'+name+'";']
    source += [method(name+'::'+name+'()', '\n'.join(ctor)), name+'::~'+name+'() = default;\n\n']
    if not n['abstract']:
        source += [method('std::string_view '+name+'::metaclassName() const noexcept', 'return "'+name+'";')]
    checks=['std::vector<RepresentationIssue> issues; (void)includeDerived;']
    for a in ancestors(n)+[n]:
        for p in a['properties']:
            access=a['name']+'::'+p['name']+'()'; label=a['name']+'.'+p['name']
            prefix='if (includeDerived) ' if p['derived'] else ''
            if is_ref(p) and p['upper']==1 and p['lower']>0:
                checks+=[prefix+'if (!'+access+') issues.push_back({"'+label+'", "required reference is missing"});']
            if p['upper']!=1:
                if p['lower']>0:checks+=[prefix+'if ('+access+'.size() < '+str(p['lower'])+') issues.push_back({"'+label+'", "lower multiplicity violated"});']
                if p['upper']>=0:checks+=[prefix+'if ('+access+'.size() > '+str(p['upper'])+') issues.push_back({"'+label+'", "upper multiplicity violated"});']
            if is_enum(p):
                vals=TYPES[p['type']]['literals'] if p['type'] in TYPES else ['PRIVATE','PROTECTED','PUBLIC']
                comparisons=['value == '+cpp(p['type'])+'::'+literal(v) for v in vals]
                check='auto value = '+access+'; '
                if p['lower']==0:check='auto optional = '+access+'; if (optional) { auto value = *optional; '
                check+='if (!('+' || '.join(comparisons)+')) issues.push_back({"'+label+'", "invalid enumeration value"});'
                if p['lower']==0:check+=' }'
                checks+=[prefix+'{ '+check+' }']
    source+=['std::vector<RepresentationIssue> '+name+'::validateRepresentation(bool includeDerived) const {\n    '+'\n    '.join(checks)+'\n    return issues;\n}\n']
    source += ['\n} // namespace SysMLv2::Entities\n']
    source_path = 'src/sysml/' + n['package'] + '/' + name + '.cpp'
    source_paths.append(source_path)
    emit('sysml/' + source_path, ''.join(source))

source = [BANNER, '#include <sysml/SysML.h>\n#include <stdexcept>\n\nnamespace SysMLv2::Entities {\n\n']
source += ['std::shared_ptr<Representation> createRepresentation(std::string_view name) {\n']
for n in CLASSES:
    if not n['abstract']:
        source += ['    if (name == "'+n['name']+'") return std::make_shared<'+n['name']+'>();\n']
source += ['    throw std::invalid_argument("Unknown or abstract SysML metaclass: " + std::string(name));\n}\n']
source += ['std::span<const MetaclassDescriptor> metaclasses() noexcept {\n    static const MetaclassDescriptor values[] = {\n']
for n in CLASSES:
    source += ['        {"'+n['name']+'", "'+n['package']+'", '+str(n['abstract']).lower()+', '+str(len(n['properties']))+'},\n']
source += ['    };\n    return values;\n}\n']
source+=['}\n']
emit('sysml/src/sysml/AbstractSyntax.cpp',''.join(source))
emit('sysml/SysMLSources.cmake', '# Generated by sysml/tools/generate_abstract_syntax.py.\nset(SYSML_SOURCES\n' + ''.join('    '+path+'\n' for path in source_paths) + ')\n')
emit('sysml/include/sysml/SysML.h','#pragma once\n'+''.join('#include <'+header(n)+'>\n' for n in TYPES.values()))
for name in ('AttributeDefinition','AttributeUsage'):
    emit('sysml/include/sysml/attibutes/'+name+'.h','#pragma once\n// Compatibility with the original misspelled include directory.\n#include <sysml/attributes/'+name+'.h>\n')
# A compile test for every concrete class and every declared generalization.
checks=['// Generated; exercises the complete class inventory.\n#include <sysml/SysML.h>\n#include <type_traits>\n#include <stdexcept>\nusing namespace SysMLv2::Entities;\nvoid checkInventory() {\n']
for n in CLASSES:
    name=n['name']
    checks+=['static_assert(std::is_abstract_v<'+name+'> == '+str(n['abstract']).lower()+');\n']
    for b in n['bases']:
        checks+=['static_assert(std::is_convertible_v<'+name+'*, '+cpp(b)+'*>);\n']
    checks+=['static_assert(std::is_convertible_v<'+name+'*, KerML::Entities::Element*>);\n']
    if not n['abstract']:
        checks+=['{ '+name+' value; if (value.metaclassName() != "'+name+'") throw std::runtime_error("incorrect metaclass identity"); }\n']
checks+=['}\n']
emit('sysml/tests/Inventory.cpp',''.join(checks))

if __name__ == '__main__':
    parser=argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check',action='store_true')
    args=parser.parse_args()
    stale=[]
    for path,text in OUTPUTS.items():
        if args.check:
            if not path.exists() or path.read_text()!=text: stale.append(str(path.relative_to(ROOT)))
        else:
            path.parent.mkdir(parents=True,exist_ok=True)
            path.write_text(text)
    if stale: raise SystemExit('Generated files are stale:\n'+'\n'.join(stale))
    print(f'{len(CLASSES)} classes, {len(ENUMS)} enumerations; {len(OUTPUTS)} files '+('verified' if args.check else 'generated'))
