//
// Created by Moritz Herzog on 31.03.25.
//

#ifndef SYSMLV2_FEATUREREFERENCEEXPRESSION_H
#define SYSMLV2_FEATUREREFERENCEEXPRESSION_H


class FeatureReferenceExpression {

};


#endif //SYSMLV2_FEATUREREFERENCEEXPRESSION_H
